# -*- coding: utf-8 -*-
"""Datensatz Abgeordnetenhauswahl Berlin 2026. Alle Aussagen aus den PDFs."""

WAHL = {
    "id": "agh-be-2026",
    "name": "Abgeordnetenhauswahl Berlin",
    "region": "Berlin",
    "wahltag": "2026-09-20",
    "kuerzel": "be",
}

PROGRAMME = {
    "cdu": ("Der Anfang ist gemacht. Regierungsprogramm 2026–2031",
            "https://berlin-wird.de/image/uploads/data/regierungsprogramm2026_2031.pdf"),
    "spd": ("Wahlprogramm zur Abgeordnetenhauswahl 2026",
            "https://spd.berlin/media/2026/08/SPD_Berlin_Wahlprogramm_20260521-v4-1.pdf"),
    "gruene": ("Politik ändern. Berlin bleiben. Wahlprogramm zur Abgeordnetenhauswahl 2026",
               "https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf"),
    "fdp": ("Berlin geht besser. Wahlprogramm zur Abgeordnetenhauswahl 2026",
            "https://www.fdp-berlin.de/sites/default/files/2026-07/Wahlprogramm_FDP%20Berlin_Abgeordnetenhauswahl%202026_FINAL.pdf"),
    "afd": ("Berlin. Stark. Machen. Programm für die Wahlen am 20. September 2026",
            "https://lichtenberg.afd.berlin/wp-content/uploads/2026/07/AfD-WK-Berlin-Wahlprogramm-Webversion.pdf"),
    "linke": ("Berlin machen bezahlbar. Wahlprogramm zur Abgeordnetenhauswahl 2026",
              "https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf"),
    "bsw": ("Berlin – Mit uns endlich vernünftig und gerecht. Wahlprogramm zur AGH-Wahl 2026",
            "https://bsw.berlin/wp-content/uploads/Wahlprogramm-BSW-Berlin-AGH-Wahl-2026.pdf"),
}

# (themaId, Titel, Beschreibung, [(Fragetext, [Aussagen])])
# Aussage: (parteiId, seite, kurz, original, markierung)
# Regeln: 3-4 Aussagen je Frage, jede Partei je Thema genau einmal,
# alle Aussagen einer Frage beantworten dieselbe Unterfrage.
THEMEN = [
 ('wohnen', 'Wohnen und Mieten',
  'Mietregulierung, Neubau, landeseigene Wohnungsunternehmen.', [
  ('Wie stark soll der Staat in den Mietmarkt eingreifen?', [
   ('cdu', 30,
    'Forderungen nach Enteignungen oder einem Mietendeckel wird eine klare Absage erteilt. Solche Eingriffe seien keine Lösung, sondern verschärften die Lage am Wohnungsmarkt. Stattdessen sollen Mieterinnen und Mieter ihre Rechte einfacher geltend machen können.',
    'Populistischen Forderungen nach Enteignungen oder der Einführung eines Mietendeckels erteilen wir eine klare Absage. Solche Eingriffe sind keine Lösung für den angespannten Wohnungsmarkt, sondern verschärfen die Situation.',
    'Populistischen Forderungen nach Enteignungen oder der Einführung eines Mietendeckels erteilen wir eine klare Absage',
   ),
   ('linke', 7,
    'Für die kommunalen Wohnungen soll ein Mietendeckel durchgesetzt werden. Ein Landesamt für Mieterschutz soll Verstöße ahnden und Recht durchsetzen. Die landeseigenen Wohnungen müssen bezahlbar bleiben.',
    'Unsere kommunalen Wohnungen müssen bezahlbar bleiben. Deshalb werden wir dort einen Mietendeckel durchsetzen. Mit unserem Landesamt für Mieterschutz schaffen wir eine handlungsfähige Behörde, die Verstöße ahndet und Recht durchsetzt.',
    'Deshalb werden wir dort einen Mietendeckel durchsetzen',
   ),
   ('bsw', 2,
    'Die bestehenden Instrumente der Mietenregulierung sollen geschärft und konsequent durchgesetzt werden. Über eine Bundesratsinitiative soll zusätzlich ein Mietendeckel eingeführt werden. Berlin brauche mehr Wohnungen in öffentlicher Hand und gemeinnütziger Bewirtschaftung.',
    'Wir wollen die bestehenden Instrumente der Mietenregulierung schärfen und endlich konsequent durchsetzen und zusätzlich über eine Bundesratsinitiative einen Mietendeckel einführen. Berlin braucht mehr Wohnungen in öffentlicher Hand und in gemeinnütziger Bewirtschaftung.',
    'zusätzlich über eine Bundesratsinitiative einen Mietendeckel einführen',
   ),
  ]),
  ('Wie soll mit Milieuschutz- und Sanierungsgebieten umgegangen werden?', [
   ('spd', 20,
    'Bei An- und Ummeldungen soll über Mietpreisbremse und Mietwucher informiert und auf kostenlose Beratung verwiesen werden. Die Schutzregeln in Milieuschutzgebieten sollen erklärt werden. Milieuschutzgebiete sollen ausgeweitet werden.',
    'Bei An- und Ummeldungen informieren wir über Mietpreisbremse und Mietwucher, verweisen auf kostenlose Beratung in den Bezirken und erklären Schutzregeln in Milieuschutzgebieten. Wir setzen uns für die Ausweitung von Milieuschutzgebieten ein.',
    'Wir setzen uns für die Ausweitung von Milieuschutzgebieten ein',
   ),
   ('gruene', 16,
    'Das Land soll insbesondere in Milieuschutzgebieten ambitionierte Sanierungen fördern und Eigentümer beraten. Mieterinnen und Mieter in unsanierten Häusern dürfen den Kostensteigerungen fossiler Brennstoffe nicht ungeschützt ausgesetzt sein. In allen Bezirken soll eine starke unabhängige Beratung entstehen.',
    'Mieter*innen in unsanierten Häusern dürfen den Kostensteigerungen fossiler Brennstoffe nicht ungeschützt ausgesetzt werden. Das Land Berlin soll insbesondere in Milieuschutzgebieten ambitionierte Sanierungen fördern und Gebäudeeigentümer entsprechend beraten.',
    'Das Land Berlin soll insbesondere in Milieuschutzgebieten ambitionierte Sanierun gen fördern',
   ),
   ('fdp', 38,
    'Das öffentliche Vorkaufsrecht soll in Sanierungs- und Milieuschutzgebieten außer für öffentliche Infrastruktur nicht mehr ausgeübt werden. Die landeseigenen Wohnungsbaugesellschaften sollen Wohnraum für von Wohnungslosigkeit bedrohte Menschen bereitstellen. Reine Mieter-Neubauquartiere am Stadtrand werden abgelehnt.',
    'Die landeseigenen WBG sollen aus ihren Beständen auch Wohnraum für von Wohnungslosigkeit bedrohte Menschen zur Verfügung stellen. In Sanierungs- und Milieuschutzgebieten soll das öffentliche Vorkaufsrecht, außer für öffentliche Infrastruktur, nicht mehr ausgeübt werden.',
    'In Sanierungs- und Milieuschutzgebieten soll das öffentliche Vorkaufsrecht, außer für öffentliche Infrastruktur, nicht mehr ausgeübt werden',
   ),
   ('afd', 6,
    'Die Fehlbelegungsabgabe soll wieder eingeführt und die Untervermietung von Sozialwohnungen generell verboten werden. Die Ausweisung von Milieuschutzgebieten soll begrenzt werden. Ziel ist es, Missbrauch zu verhindern.',
    '[Wir wollen] die Fehlbelegungsabgabe wieder einführen. Um den Missbrauch zu verhindern, setzen wir uns für ein generelles Verbot der Untervermietung von Sozialwohnungen ein. Milieuschutz begrenzen: Die Ausweisung von Wohnvierteln als Milieuschutzgebiete (§ 172 BauGB) […].',
    'wir uns für ein generelles Verbot der Untervermietung von Sozialwohnungen ein',
   ),
  ]),
 ]),
 ('sicherheit', 'Innere Sicherheit',
  'Polizei, Videoüberwachung, Verbotszonen und Kontrolle.', [
  ('Wo und wie soll Videoüberwachung eingesetzt werden?', [
   ('cdu', 6,
    'An bekannten Kriminalitätsschwerpunkten sollen verstärkt Videoüberwachung sowie Waffen- und Messerverbotszonen eingesetzt werden. Als Beleg wird auf die Wache am Kottbusser Tor verwiesen. Die Polizei soll zudem mit Tasern ausgestattet werden.',
    'Genau hinschauen, was passiert, um Kriminelle dingfest zu machen: An bekannten Kriminalitätsschwerpunkten kommen nun verstärkt Videoüberwachung und Waffen- und Messerverbotszonen zum Einsatz. Mit messbarem Erfolg […].',
    'An bekannten Kriminalitätsschwerpunkten kommen nun verstärkt Videoüberwachung und Waffen- und Messerverbotszonen zum Einsatz',
   ),
   ('fdp', 67,
    'An Risikoorten wie Bahnhöfen soll neben temporärer Videoüberwachung mit baulichen Maßnahmen gearbeitet werden. Dazu zählen gute Beleuchtung, offene Sichtachsen und die Vermeidung dunkler Ecken. Security by Design soll berlinweit umgesetzt werden.',
    'Wir möchten Security by Design berlinweit implementieren. An Berliner Risikoorten wie Bahnhöfen oder Drogenumschlagplätzen wollen wir – neben der temporären Videoüberwachung – mit baulichen Maßnahmen wie guter Beleuchtung, offenen Sichtachsen, Verhinderung dunkler Ecken die Sicherheit […] [erhöhen].',
    'neben der temporären Videoüberwachung – mit baulichen Maßnahmen wie guter Beleuchtung',
   ),
   ('afd', 13,
    'Gefordert wird eine vollständige Videoüberwachung in allen Brennpunktbereichen. Mobile Polizeiwachen in Problemvierteln und ein dichteres Netz stationärer Wachen sollen eingeführt werden. Das Landesantidiskriminierungsgesetz soll sofort aufgehoben werden.',
    'Die AfD fordert: → Die sofortige Aufhebung des Landesantidiskriminierungsgesetzes und die Überarbeitung anderer sicherheitsrelevanter Gesetze. → Eine vollständige Videoüberwachung in allen Brennpunktbereichen. → Die Einführung mobiler Polizeiwachen in Problemvierteln.',
    'Eine vollständige Videoüberwachung in allen Brennpunktbereichen',
   ),
   ('bsw', 41,
    'Videoüberwachung soll an nachweislich besonders kriminalitätsbelasteten Orten eingesetzt werden. Nötig seien dafür eine parlamentarische Genehmigung und eine Echtzeit-Auswertung durch ausreichend Personal. Kriminalität und Gewalt müsse wirksam entgegengetreten werden.',
    'Kriminalität und Gewalt muss wirksam entgegengetreten werden, damit sich alle Bürger unserer Stadt sicher fühlen können. Dazu setzen wir Videoüberwachung an nachweislich besonders kriminalitätsbelasteten Orten ein – mit parlamentarischer Genehmigung und Echtzeit-Auswertung durch ausreichend Personal.',
    'Videoüberwachung an nachweislich besonders kriminalitätsbelasteten Orten ein – mit parlamentarischer Genehmigung',
   ),
  ]),
  ('Wie sollen Polizeibefugnisse und Kriminalitätsorte kontrolliert werden?', [
   ('spd', 31,
    'Die Einstufung kriminalitätsbelasteter Orte soll einer regelmäßigen parlamentarischen Kontrolle unterliegen. Software intransparenter Hersteller wie Palantir wird für Berlin abgelehnt. Die Polizei soll respektvoll handeln und die Vielfalt der Stadt widerspiegeln.',
    '[Wir unterziehen] die Einstufung kriminalitätsbelasteter Orte einer regelmäßigen parlamentarischen Kontrolle. […] Den Einsatz von Software intransparente und datenschutzrechtlich bedenklicher Hersteller wie Palantir lehnen wir für Berlin entschieden [ab].',
    'die Einstufung kriminalitätsbelasteter Orte einer regelmäßigen parlamentarischen Kontrolle',
   ),
   ('gruene', 228,
    'Die bestehenden kriminalitätsbelasteten Orte sowie Messer- und Waffenverbotszonen sollen auf ihre Sinnhaftigkeit überprüft und wo nötig wieder abgeschafft werden. Die Ergebnisse der Bodycam-Studie sollen umgesetzt werden. Ziel sind Transparenz und Nachvollziehbarkeit polizeilichen Handelns.',
    'Wir werden die bestehenden kriminalitätsbelasteten Orte und Messer- und Waffenverbotszonen auf ihre Sinnhaftigkeit überprüfen und werden sie, wo erforderlich, wieder abschaffen. Die Ergebnisse der Bodycam-Studie wollen wir umsetzen.',
    'Messer- und Waffenverbotszonen auf ihre Sinnhaftigkeit überprüfen und werden sie, wo erforderlich, wieder abschaffen',
   ),
   ('linke', 288,
    'Die Aufrüstung der Polizei soll gestoppt und die Mittel umverteilt werden. Einsätze bei Demonstrationen, anlasslose Kontrollen und Waffenverbotszonen gelten als personalintensiv und oft nicht zielführend. Geprüft werden soll, den Personalbestand auf das Niveau anderer Städte zu bringen.',
    'Aufrüstung der Polizei wollen wir stoppen und die Mittel umverteilen. Polizeieinsätze z. B. bei Demos, anlasslosen Kontrollen an KBOs und Waffenverbotszonen oder Fußballspielen sind personalintensiv und oft nicht zielführend.',
    'Aufrüstung der Polizei wollen wir stoppen und die Mittel umverteilen',
   ),
  ]),
 ]),
 ('verkehr', 'Verkehr und Mobilität',
  'Rad, Auto, Bus und Bahn im Stadtverkehr.', [
  ('Welcher Verkehrsart soll in der Stadt Vorrang eingeräumt werden?', [
   ('gruene', 80,
    'Mobilität dürfe keine Frage von Einkommen, Wohnort oder Alter sein. Derzeit kämen Busse zu spät, U-Bahnen fielen aus und Radwege endeten im Nichts. Zu viele Straßen seien für Kinder, Seniorinnen und Menschen mit Behinderungen gefährlich.',
    'Sie darf keine Frage des Einkommens, des Wohnorts oder des Alters sein. Doch die Realität sieht derzeit anders aus: Busse kommen zu spät, U-Bahnen fallen aus, Radwege enden im Nichts und zu viele Straßen sind gerade für Kinder, Senior*innen und Menschen mit Behinderungen gefährlich.',
    'Busse kommen zu spät, U-Bahnen fallen aus, Radwege enden im Nichts',
   ),
   ('afd', 42,
    'Der motorisierte Individualverkehr bleibt aus Sicht der Partei unverzichtbarer Bestandteil urbaner Mobilität. Gefordert werden Zugangsbeschränkungen für Personen ohne Fahrschein im Nahverkehr. Der Regionalverkehr soll besser in das Gesamtnetz eingebunden werden.',
    '→ Zugangsbeschränkungen für Personen ohne Fahrschein. → Eine bessere Einbindung des Regionalverkehrs in das Gesamtnetz. Für diskriminierungsfreien Autoverkehr: Der motorisierte Individualverkehr bleibt für uns auch in Zukunft ein unverzichtbarer Bestandteil urbaner Mobilität.',
    'Der motorisierte Individualverkehr bleibt für uns auch in Zukunft ein unverzichtbarer Bestandteil urbaner Mobilität',
   ),
   ('linke', 55,
    'Priorität hat ein überzeugendes Angebot im öffentlichen Nahverkehr. Hinzu kommen der Ausbau eines umfassenden Radwegenetzes und barrierefreier Gehwege. So soll allen eine kostengünstige Mobilität ermöglicht werden.',
    'Unsere Priorität liegt daher auf einem überzeugenden Angebot im öffentlichen Personennahverkehr (ÖPNV) sowie dem Ausbau eines umfassenden Radwegenetzes und von barrierefreien Gehwegen. So ermöglichen wir allen eine kostengünstige Mobilität.',
    'Unsere Priorität liegt daher auf einem überzeugenden Angebot im öffentlichen Personennahverkehr',
   ),
   ('bsw', 48,
    'Gefordert wird kein Gegeneinander von Auto, Fahrrad und Nahverkehr, sondern ein vernünftiges Miteinander. Sichere Fußwege, ein starker Nahverkehr, ein verlässliches Radwegenetz und gute Bedingungen für den Autoverkehr gehören zusammen. Besonders benannt werden Außenbezirke, Schichtarbeit und Handwerk.',
    '[Wir wollen kein Gegeneinander] zwischen Auto, Fahrrad und öffentlichem Nahverkehr, sondern ein vernünftiges Miteinander. Sichere Wege für Fußgänger, ein starker Nahverkehr, ein verlässliches Radwegenetz und gute Bedingungen für den motorisierten Individualverkehr gehören zusammen.',
    'ein verlässliches Radwegenetz und gute Bedingungen für den motorisierten Individualverkehr gehören zusammen',
   ),
  ]),
  ('Worin soll beim Verkehr zuerst investiert werden?', [
   ('cdu', 71,
    'Das Radwegenetz soll gezielt verbessert und bedarfsgerecht ausgebaut werden. Vorrang haben Sanierung und Ertüchtigung bestehender Wege. Sharing-Fahrzeuge sollen nur noch an fest definierten Abstellanlagen abgestellt werden dürfen.',
    'Mit dem Rad durch die Stadt: Das Berliner Radwegenetz werden wir gezielt verbessern und bedarfsgerecht ausbauen. Vorrang hat für uns die Sanierung und Ertüchtigung bestehender Wege.',
    'Das Berliner Radwegenetz werden wir gezielt verbessern und bedarfsgerecht ausbauen. Vorrang hat für uns die Sanierung',
   ),
   ('spd', 24,
    'Der Ausbau der Straßenbahn soll in allen Bezirken vorangetrieben werden. Die Elektrifizierung des Busverkehrs wird fortgesetzt und senkt zugleich den Lärm. Laufende Projekte sollen weiter finanziert werden.',
    'Die Elektrifizierung des Busverkehrs setzen wir fort und senken damit zugleich den Lärm in der Stadt. Wir treiben den Ausbau der Straßenbahn in allen Bezirken voran, finanzieren laufende Projekte […].',
    'Wir treiben den Ausbau der Straßenbahn in allen Bezirken voran',
   ),
   ('fdp', 55,
    'Bestehende Radwege sollen repariert werden, auch wenn sie nicht der Normbreite entsprechen. Man solle nicht zehn Jahre auf ein Verkehrskonzept und dessen Umsetzung warten. Eine bessere Anbindung von Außenbezirken und Umland soll den Wohnungsmarkt entlasten.',
    'Bestehende Radwege müssen repariert werden, auch wenn sie nicht der „Normbreite“ entsprechen, anstatt zehn Jahre auf ein „Verkehrskonzept“ und dessen Umsetzung zu warten.',
    'Bestehende Radwege müssen repariert werden, auch wenn sie nicht der „Normbreite“ entsprechen',
   ),
  ]),
 ]),
 ('verwaltung', 'Verwaltung und Digitalisierung',
  'Bürgerämter, Verwaltungsreform und digitale Verfahren.', [
  ('Wie weit soll die Verwaltung digitalisiert werden?', [
   ('spd', 11,
    'Der digitale Wirtschaftsservice der Berliner Verwaltung soll umgesetzt und mehr Leistungen digital angeboten werden. Digitalisierungsprojekte sollen schneller in die Umsetzung kommen. Mit digitalen Werkzeugen soll ein modernes Vergaberecht umgesetzt werden.',
    'Wir setzen den DIWI – den digitalen Wirtschaftsservice der Berliner Verwaltung – um und bieten noch mehr Leistungen digital an. Außerdem setzen wir mit digitalen Tools ein modernes Vergaberecht um.',
    'den digitalen Wirtschaftsservice der Berliner Verwaltung – um und bieten noch mehr Leistungen digital an',
   ),
   ('gruene', 71,
    'Die internen Prozesse in den Verwaltungen sollen vollständig digitalisiert werden. Dafür soll übergreifend in allen Verwaltungen die E-Akte eingeführt werden. Zudem soll die Datenkommunikation zwischen den Behörden abgesichert werden.',
    'Um das Angebot unserer Behörden verbessern zu können, müssen wir die internen Prozesse in den Verwaltungen vollständig digitalisieren. Dafür führen wir übergreifend in allen Verwaltungen die E-Akte ein.',
    'Dafür führen wir übergreifend in allen Verwaltungen die E-Akte ein',
   ),
   ('fdp', 21,
    'Bei neuen Gesetzen und Verordnungen sollen alle Verwaltungsvorgänge digitaltauglich umgesetzt werden können. Gelten sollen die Grundsätze „digital only“ und „digital once“. Daten sollen also nur noch einmal an die Verwaltung übermittelt werden.',
    'Bei neuen Gesetzen und Verordnungen oder auch bei Änderungen sorgen wir dafür, dass alle damit verbundenen Verwaltungsvorgänge digitaltauglich umgesetzt werden können. Die Grundsätze „digital only“ und „digital once“ (Übermittlung von Daten nur noch einmal an die Berliner [Verwaltung]) […].',
    'dass alle damit verbundenen Verwaltungsvorgänge digitaltauglich umgesetzt werden können',
   ),
   ('bsw', 62,
    'Verwaltung bedeute auch Dienstleistung und müsse beschleunigt werden. Dafür brauche es eine konsequentere Digitalisierung, Papierakten sollen abgelöst werden. Beförderungen für kontinuierliche Leistung sollen zum Regelfall werden.',
    'Verwaltung modernisieren: Verwaltung bedeutet auch Dienstleistung. Damit diese beschleunigt wird, braucht es eine konsequentere Digitalisierung: Papierakten soll[en] […] [abgelöst werden].',
    'Damit diese beschleunigt wird, braucht es eine konsequentere Digitalisierung',
   ),
  ]),
  ('Wo steht die Verwaltungsreform und was fehlt ihr?', [
   ('cdu', 87,
    'Die Verwaltungsreform gilt als beschlossen und das Behörden-Pingpong als beendet. Monatelanges Warten auf einen Bürgeramtstermin sei früher Alltag gewesen. Heute gebe es oft schon am nächsten Tag einen Termin.',
    'Berlin wird funktionieren. Verwaltungsreform beschlossen. Behörden-Pingpong beendet. Monatelanges Warten auf einen Bürgeramtstermin war in Berlin Alltag. […] Heute gibt’s oft schon am nächsten Tag einen Termin.',
    'Verwaltungsreform beschlossen. Behörden-Pingpong beendet',
   ),
   ('afd', 96,
    'Investitionen seien insbesondere in Verwaltungsmodernisierung und die Digitalisierung kritischer Systeme erforderlich. Genannt werden zudem Infrastruktur, Sicherheits- und Rettungsdienste sowie der Substanzerhalt öffentlicher Gebäude. Der Investitionsstau der öffentlichen Hand liege bei weit über 100 Milliarden Euro.',
    'Der Investitionsstau der öffentlichen Hand beläuft sich inzwischen auf weit über 100 Mrd. Euro. Investitionen sind erforderlich, insbesondere in: Die Infrastruktur; die Verwaltungsmodernisierung; die Digitalisierung kritischer Systeme; Sicherheits- und Rettungsdienste; Substanzerhalt öffentlicher Gebäude.',
    'die Verwaltungsmodernisierung; die Digitalisierung kritischer Systeme',
   ),
   ('linke', 11,
    'Die Verwaltung soll digitaler und effizienter werden und die Verwaltungsreform mit Leben gefüllt werden. Die Ausgaben für Überwachungskameras sollen reduziert werden. Stattdessen soll in soziale Angebote investiert werden.',
    'Wir reduzieren die Ausgaben für Überwachungskameras und investieren stattdessen in soziale Angebote. Wir müssen unsere Verwaltung digitaler und effizienter machen und die Verwaltungsreform mit Leben füllen.',
    'Wir müssen unsere Verwaltung digitaler und effizienter machen und die Verwaltungsreform mit Leben füllen',
   ),
  ]),
 ]),
 ('schule', 'Schule und Bildung',
  'Schulplätze, Personal, Schulformen und Inklusion.', [
  ('Wie soll die Schule organisiert und gesteuert werden?', [
   ('cdu', 54,
    'Im Rahmen der Schulbauoffensive sind rund 62.000 neue Schulplätze, 41 neue Schulen und 76 Sporthallen entstanden. In den Schulbau soll massiv weiter investiert werden. Ein neues 11. Pflichtschuljahr soll Jugendlichen ohne Ausbildungsplatz eine Perspektive geben.',
    'Das neue 11. Pflichtschuljahr gibt Jugendlichen ohne Ausbildungsplatz eine klare Perspektive. Wir investieren massiv in Berlins Schulbau: Im Rahmen der Schulbauoffensive wurden so rund 62.000 neue Schulplätze, 41 neue Schulen, 119 Ergänzungsbauten und 76 neue Sporthallen entstanden.',
    'Wir investieren massiv in Berlins Schulbau',
   ),
   ('spd', 42,
    'Die Schulbauoffensive soll fortgesetzt werden, nachdem bereits über 50.000 Schulplätze geschaffen wurden. Die Lehrkräftebildung soll über die Schools of Education gestärkt werden. Betont wird eine praxisorientierte Professionalisierung.',
    'In diesem Sinne stärken wir die Schools of Education als zentrale Struktur der Lehrkräftebildung. Die Schulbauoffensive fortsetzen: Seit Beginn der Schulbauoffensive haben wir durch Erweiterungen und Neubauten deutlich über 50.000 Schulplätze geschaffen.',
    'Die Schulbauoffensive fortsetzen',
   ),
   ('fdp', 8,
    'Schulen sollen ihr Personal selbst auswählen und ihre Selbstverwaltung ausbauen können. Lehrkräfte und Schulleitungen sollen von Verwaltungsaufgaben entlastet werden. Schulen sollen schulspezifisch multiprofessionelle Teams bilden dürfen.',
    'Wir wollen die personelle Situation der Schulen bei der Selbstverwaltung weiter verbessern, um Lehrkräfte und die pädagogische Schulleitung von Verwaltungsaufgaben zu entlasten. Im Rahmen ihrer Personalautonomie wollen wir es Schulen außerdem ermöglichen, schulspezifisch multiprofessionelle Teams […] zu bilden.',
    'um Lehrkräfte und die pädagogische Schulleitung von Verwaltungsaufgaben zu entlasten',
   ),
   ('afd', 28,
    'Die Vergabe von 30 Prozent der Schulplätze über das Losverfahren soll abgeschafft werden. Die Aufnahme an weiterführenden Schulen soll sich an Noten, Wohnortnähe und einer Geschwisterkindregelung orientieren. An freiwilligen Aufnahmetests zum Gymnasium wird festgehalten.',
    '[Die Aufnahme an] weiterführenden Schulen muss sich konsequent an den Noten und der Wohnortnähe orientieren sowie eine Geschwisterkindregelung umfassen. Die Vergabe von 30 % der Schulplätze über das Losverfahren werden wir abschaffen.',
    'Die Vergabe von 30 % der Schulplätze über das Losverfahren werden wir abschaffen',
   ),
  ]),
  ('Worauf soll Bildung inhaltlich zielen?', [
   ('gruene', 154,
    'Exkludierende Systeme sollen vollständig abgebaut und Inklusion in allen Schulen ermöglicht werden. Multiprofessionelle Teams und Schulassistenz sollen gleiche Bildungschancen sichern. Hinzu kommen ergänzende Förderung und Betreuung in Grundschulen.',
    'Exkludierende Systeme müssen vollständig abgebaut und Inklusion in allen Schulen möglich gemacht werden. Multiprofessionelle Teams, Schulassistenz sowie ergänzende Förderung und Betreuung in Grundschulen sichern gleiche Bildungschancen.',
    'Exkludierende Systeme müssen vollständig abgebaut und Inklusion in allen Schulen möglich gemacht werden',
   ),
   ('linke', 152,
    'Schülerinnen und Schüler sollen ihren Schulalltag zunehmend selbstbestimmt mitgestalten können. Bildung soll befähigen, Gesellschaft kritisch zu verstehen. Lehrkräfte sollen bestärkt werden, emanzipatorische und partizipative Konzepte anzuwenden.',
    '[…] ihren Schulalltag zunehmend selbstbestimmt mitgestalten können. Bildung soll sie befähigen, Gesellschaft kritisch zu verstehen und solidarisch zu verändern. Lehrkräfte wollen wir bestärken, emanzipatorische und partizipative pädagogische Konzepte anzuwenden.',
    'Lehrkräfte wollen wir bestärken, emanzipatorische und partizipative pädagogische Konzepte anzuwenden',
   ),
   ('bsw', 14,
    'Das Bildungssystem verliere zunehmend an Bildungsqualität, Chancengerechtigkeit und kultureller Tiefe. Diese Entwicklung soll umgekehrt werden. Ziel ist eine Bildungswende hin zu mündigen, selbstständig denkenden Kindern.',
    'Das deutsche Bildungssystem verliert zunehmend an Bildungsqualität, Chancengerechtigkeit und kultureller Tiefe. Das BSW will diese Entwicklung umkehren. Unser Ziel ist eine Bildungswende, die die Erziehung unserer Kinder zu mündigen, selbstständig denkenden und verantwortungsbewussten [Menschen fördert].',
    'Unser Ziel ist eine Bildungswende',
   ),
  ]),
 ]),
 ('zuwanderung', 'Zuwanderung und Integration',
  'Aufnahme, Rückführung, Einbürgerung und Arbeitsmarkt.', [
  ('Wie konsequent soll Zuwanderung begrenzt werden?', [
   ('cdu', 18,
    'Die Zahl der Abschiebungen, insbesondere aus dem Strafvollzug, sei deutlich gestiegen. Die Migrationswende sei damit vollzogen. Neue Containerunterkünfte in Berlins Kiezen soll es nicht mehr geben.',
    'Die Migrationswende ist da: Die Zahl der Abschiebungen, insbesondere aus dem Strafvollzug, ist jetzt deutlich höher. Und deshalb gilt jetzt auch: Keine neuen Containerunterkünfte in Berlins Kiezen.',
    'Keine neuen Containerunterkünfte in Berlins Kiezen',
   ),
   ('fdp', 95,
    'Irreguläre Migration soll unterbunden werden, wer legal komme, erhalte echte Chancen. Sprach- und Integrationskurse soll es vom ersten Tag an geben. Vermittelt werden sollen die freiheitlich-demokratische Grundordnung und der Respekt vor Gleichberechtigung.',
    'Irreguläre Migration muss unterbunden werden, wer legal kommt, erhält echte Chancen. Integration fordert alle Beteiligten: Sprach- und Integrationskurse vom ersten Tag an, die Vermittlung unserer freiheitlich-demokratischen Grundordnung, den Respekt vor Gleichberechtigung.',
    'Irreguläre Migration muss unterbunden werden, wer legal kommt, erhält echte Chancen',
   ),
   ('afd', 14,
    'Bei der Ausländerbehörde soll eine Sondereinheit eingerichtet werden. Diese soll die Ausweisung und Abschiebung ausländischer Krimineller betreiben. Die Maßnahmen richten sich zudem gegen Strukturen der organisierten Kriminalität.',
    'Die AfD fordert: → Die Einrichtung einer Sondereinheit bei der Ausländerbehörde, die die Ausweisung und Abschiebung ausländischer Krimineller [betreibt].',
    'Die Einrichtung einer Sondereinheit bei der Ausländerbehörde',
   ),
   ('bsw', 34,
    'Wer keinen Anspruch auf Asyl habe, dürfe gar nicht erst in die EU einreisen. Dann komme es auch nicht mehr zu Schwierigkeiten bei einer Abschiebung. Die notwendigen Regelungen sollen in Deutschland zügig umgesetzt werden, damit Zuwanderung regelbasiert stattfindet.',
    'Wer keinen Anspruch auf Asyl hat, darf gar nicht erst in die Europäische Union einreisen und es kann somit auch nicht mehr zu Schwierigkeiten bei einer Abschiebung kommen. Wir fordern, dass die notwendigen Regelungen in Deutschland nun zügig umzusetzen sind, damit Zuwanderung künftig regelbasiert stattfindet.',
    'Wer keinen Anspruch auf Asyl hat, darf gar nicht erst in die Europäische Union einreisen',
   ),
  ]),
  ('Wie soll die Integration derer gelingen, die hier sind?', [
   ('spd', 52,
    'Die Anstrengungen zur Integration in den Arbeitsmarkt sollen weiter gestärkt werden, damit Menschen schnell selbst ihren Lebensunterhalt verdienen. Über Einbürgerung soll Teilhabe ermöglicht werden. Alle Berlinerinnen und Berliner sollen demokratisch mitbestimmen können.',
    '[…] schnell selbst ihren Lebensunterhalt verdienen können. Deshalb stärken wir Berlins Anstrengungen zur Integration in den Arbeitsmarkt weiter. Teilhabe durch Einbürgerung: Wir wollen, dass alle Berlinerinnen und Berliner demokratisch mitbestimmen.',
    'Deshalb stärken wir Berlins Anstrengungen zur Integration in den Arbeitsmarkt weiter',
   ),
   ('gruene', 112,
    'Betroffene sollen durch Rechtsberatung und aufenthaltsrechtliche Absicherung unterstützt werden, ihre Rechte ohne Angst vor Abschiebung wahrzunehmen. Dafür brauche es ausreichend Personal. Die Kernarbeitsnormen der Internationalen Arbeitsorganisation sollen beachtet werden.',
    '[Mit] Rechtsberatung und aufenthaltsrechtlicher Absicherung unterstützen wir Betroffene dabei, ihre Rechte wahrzunehmen und Rechtsverfahren durchzustehen – ohne Angst vor Abschiebung. Dazu gehört auch eine ausreichende Zahl an Mitarbeiter*innen.',
    'ihre Rechte wahrzunehmen und Rechtsverfahren durchzustehen – ohne Angst vor Abschiebung',
   ),
   ('linke', 105,
    'Berufsbegleitende Sprachkurse und Projekte zur Arbeitsmarktintegration von Migrantinnen und Migranten sollen gestärkt werden. Der Zugang für Geflüchtete zum Arbeitsmarkt soll erleichtert werden. Behörden mit Kontakt zu migrantischen Beschäftigten sollen geschult werden.',
    'Berufsbegleitende Sprachkurse und Projekte für eine bessere Arbeitsmarktintegration von Migrant*innen müssen gestärkt werden. Der Zugang für Geflüchtete zum Arbeitsmarkt muss erleichtert werden.',
    'Der Zugang für Geflüchtete zum Arbeitsmarkt muss erleichtert werden',
   ),
  ]),
 ]),
 ('gesundheit', 'Gesundheit und Krankenhäuser',
  'Versorgung in den Bezirken, Kliniken und Pflege.', [
  ('Wie sollen die Krankenhäuser finanziert und getragen werden?', [
   ('spd', 33,
    'Angestrebt wird eine gerechte und flächendeckende Gesundheitsversorgung. Ambulante, stationäre und psychosoziale Angebote sollen enger zusammenarbeiten. Für die Krankenhäuser wird eine auskömmliche Finanzierung gefordert.',
    'Gesundheit ist ein Menschenrecht. Deshalb wollen wir eine gerechte und flächendeckende Gesundheitsversorgung. Ambulante, stationäre und psychosoziale Angebote müssen enger zusammenarbeiten. […] Die SPD Berlin setzt sich vor diesem Hintergrund für eine auskömmliche Finanzierung ein.',
    'Deshalb wollen wir eine gerechte und flächendeckende Gesundheitsversorgung',
   ),
   ('fdp', 114,
    'Wer eine Krankenhausbehandlung benötigt, soll rund um die Uhr die beste medizinische Versorgung erhalten. Angestrebt wird eine Neuordnung der Krankenhausfinanzierung am tatsächlichen Patientenbedarf. Die Trennung zwischen ambulant und stationär soll überwunden werden.',
    'Wer eine Behandlung im Krankenhaus benötigt, muss rund um die Uhr an sieben Tagen in der Woche und 365 Tagen im Jahr die beste medizinische Versorgung erhalten können. […] Wir werden uns daher für eine Neuordnung der Krankenhausfinanzierung einsetzen, die sich am tatsächlichen medizinischen Patientenbedarf orientiert.',
    'eine Neuordnung der Krankenhausfinanzierung einsetzen, die sich am tatsächlichen medizinischen Patientenbedarf orientiert',
   ),
   ('linke', 8,
    'Die Krankenhäuser sollen in kommunaler Hand bleiben. Wo private Konzerne sich aus der Verantwortung ziehen, soll rekommunalisiert werden. Gesundheit dürfe nicht dem Profitstreben von Krankenhauskonzernen zum Opfer fallen.',
    'Unser Wohlbefinden, unsere Gesundheit darf nicht dem Profitstreben von Krankenhauskonzernen zum Opfer fallen. Wir wollen, dass unsere Krankenhäuser in kommunaler Hand bleiben und dort rekommunalisiert werden, wo sich private Konzerne aus der Verantwortung ziehen.',
    'dass unsere Krankenhäuser in kommunaler Hand bleiben und dort rekommunalisiert werden',
   ),
   ('bsw', 21,
    'Das solidarische Gesundheitswesen soll gestärkt statt kaputtgespart werden. Die Zwei-Klassen-Medizin soll beendet werden. Angestrebt wird eine Bürgerversicherung als einheitliches Krankenversicherungssystem.',
    'Wir wollen das solidarische Gesundheitswesen stärken, statt es weiter kaputtzusparen. Die Zwei-Klassen-Medizin muss beendet werden. […] Deshalb strebt das BSW eine Bürgerversicherung als einheitliches Krankenversicherungssystem [an].',
    'Deshalb strebt das BSW eine Bürgerversicherung als einheitliches Krankenversicherungssystem',
   ),
  ]),
  ('Wie soll die Versorgung im Alltag erreichbar bleiben?', [
   ('cdu', 99,
    'Dokumentations- und Meldeprozesse in Pflege und Verwaltung sollen deutlich vereinfacht werden. Gute Versorgung brauche gute Ausbildung in allen Bereichen. Angehende Pflegefachkräfte sollen ausreichend Praxisplätze finden.',
    '[Wir wollen Entlastungen] in der Pflege und der Verwaltung schaffen, um Dokumentations- und Meldeprozesse deutlich zu vereinfachen. Gute Versorgung braucht gute Ausbildung in allen Bereichen der Gesundheitsversorgung. Wir setzen uns insbesondere dafür ein, dass angehende Pflegefachkräfte ausreichend Praxisplätze finden.',
    'dass angehende Pflegefachkräfte ausreichend Praxisplätze finden',
   ),
   ('gruene', 201,
    'Die Gesundheitschancen unterscheiden sich in Berlin je nach Bezirk und sozioökonomischem Status stark. Haus-, Fach- und Kinderärztinnen fehlten besonders in Stadtrandlagen. Angestrebt wird eine gleichmäßige Verteilung der Vertragsarztsitze.',
    'Noch immer unterscheiden sich die Gesundheitschancen in Berlin stark: Je nach Bezirk, Wohnviertel, Geschlecht und sozioökonomischem Status weichen Lebenserwartung und Krankheitshäufigkeiten voneinander ab. […] Wir setzen uns dafür ein, dass es eine gleichmäßige Verteilung von Vertragsärzt*innensitzen gibt.',
    'dass es eine gleichmäßige Verteilung von Vertragsärzt*innensitzen gibt',
   ),
   ('afd', 69,
    'Eine leistungsfähige und wohnortnahe Gesundheitsversorgung sowie fürsorgliche Pflege haben herausragende Bedeutung. Grundlage sind Eigenverantwortung, Prävention sowie private und staatliche Angebote der Daseinsvorsorge. Moderne Krankenhäuser sollen gesichert werden.',
    'Eine leistungsfähige und wohnortnahe Gesundheitsversorgung sowie eine fürsorgliche Pflege sind für die AfD von herausragender Bedeutung. Eigenverantwortung, Prävention, private und staatliche Angebote der Daseinsvorsorge sind die Basis für ein gesundes, langes und selbstbestimmtes Leben.',
    'Eine leistungsfähige und wohnortnahe Gesundheitsversorgung sowie eine fürsorgliche Pflege',
   ),
  ]),
 ]),
 ('wirtschaft', 'Wirtschaft und Gewerbe',
  'Gewerbeflächen, Ansiedlung und Rahmenbedingungen.', [
  ('Wodurch soll Berlin als Wirtschaftsstandort wachsen?', [
   ('spd', 6,
    'In Wirtschaftsförderung und Infrastruktur soll investiert werden. Angestrebt werden attraktive Arbeitsbedingungen mit Tarifbindung statt Lohndumping. Wachstum soll dem Wohl aller dienen.',
    'Wir investieren in Wirtschaftsförderung und Infrastruktur und wollen attraktive Arbeitsbedingungen mit Tarifbindungen statt Lohndumping.',
    'Wir investieren in Wirtschaftsförderung und Infrastruktur und wollen attraktive Arbeitsbedingungen mit Tarifbindungen statt Lohndumping',
   ),
   ('gruene', 98,
    'Technologie, Industrie, Forschung und Ausbildung sollen an einer gemeinsamen Schnittstelle zusammenwirken. Berlin soll als Standort für angewandte Innovation und klimaneutrale Industrie gestärkt werden. Geprüft wird die Einrichtung einer landeseigenen Innovationsagentur.',
    '[…] damit Technologie, Industrie, Forschung und Ausbildung an dieser wichtigen Schnittstelle zusammenwirken und Berlin als Standort für angewandte Innovation und klimaneutrale Industrie gestärkt wird. […] prüfen wir die Einrichtung einer landeseigenen Innovationsagentur.',
    'Berlin als Standort für angewandte Innovation und klimaneutrale Industrie gestärkt wird',
   ),
   ('afd', 47,
    'Berlin soll wieder industrieller Kernstandort werden. Gezielt gefördert wird die Ansiedlung in Luft- und Raumfahrt, Gesundheitswirtschaft, Halbleiter und KI. Ein öffentliches Gewerbeflächenkataster soll Flächen transparent verfügbar machen.',
    '[Der] Energiestandort Berlin muss wieder industrieller Kernstandort werden. Wir fördern gezielt die Ansiedlung von Unternehmen in den Bereichen: + Luft- und Raumfahrt; + Gesundheitswirtschaft; + Halbleiter, KI […]. Flächen für Gewerbe und Industrie – transparent und verfügbar: Ein öffentliches Gewerbeflächenkataster […].',
    'Wir fördern gezielt die Ansiedlung von Unternehmen in den Bereichen',
   ),
  ]),
  ('Wem soll die Wirtschaftspolitik vor allem dienen?', [
   ('cdu', 37,
    'Für mehr Transparenz auf dem Gewerbemarkt soll ein systematisches Leerstandsmonitoring von Büro- und Gewerbeflächen eingeführt werden. Das Leerstandsmanagement landeseigener Immobilien soll weiterentwickelt werden. Flächen sollen gezielt für Start-ups und Unternehmen genutzt werden.',
    'Für mehr Transparenz über die Entwicklungen auf dem Gewerbemarkt setzen wir uns für die Einführung eines systematischen Leerstandsmonitorings von Büro- und Gewerbeflächen ein. Wir werden das Leerstandsmanagement landeseigener Immobilien weiterentwickeln und gezielt für die Nutzung durch Start-ups und Unternehmen [öffnen].',
    'die Einführung eines systematischen Leerstandsmonitorings von Büro- und Gewerbeflächen',
   ),
   ('fdp', 18,
    'Berlin sei trotz Universitäten und lebendiger Start-up-Szene größter Nettoempfänger im Länderfinanzausgleich. Als Grund werden Bürokratie und endlose Genehmigungsverfahren genannt. Investoren würden abgeschreckt statt empfangen.',
    'Trotzdem sind wir nach Jahrzehnten als Hauptstadt immer noch der größte Nettoempfänger im Länderfinanzausgleich. Der Grund ist klar: Während andere Städte Investorinnen und Investoren freundlich empfangen, schrecken wir sie mit Bürokratie-Wahnsinn, endlosen Genehmigungsverfahren […] [ab].',
    'schrecken wir sie mit Bürokratie-Wahnsinn, endlosen Genehmigungsverfahren',
   ),
   ('linke', 15,
    'Bei der Vergabe von Gewerbeflächen sollen Anwohnerinnen und Anwohner eng eingebunden werden. Eigene Bestände sollen wo möglich für Nahversorgung und soziale Angebote genutzt werden. Zwangsräumungen wegen Mietschulden werden abgelehnt.',
    'Wo immer möglich, sollen eigene Bestände für eine gute Nahversorgung für den täglichen Bedarf und soziale Angebote genutzt werden. Bei der Vergabe von Gewerbeflächen sollen Anwohner*innen und deren Vertretungen eng eingebunden werden.',
    'Bei der Vergabe von Gewerbeflächen sollen Anwohner*innen und deren Vertretungen eng eingebunden werden',
   ),
   ('bsw', 42,
    'Die Wirtschaftspolitik rückt Familienbetriebe, Selbständige und Freiberufler in den Mittelpunkt. Schwerpunkte sind der Abbau von Überregulierung, der Ausbau digitaler Verwaltungsleistungen und die Ausbildungsförderung. Zusätzlich wird ein Mutterschutz für Selbständige gefordert.',
    'Die Wirtschaftspolitik des Berliner BSW rückt Familienbetriebe, Selbständige und Freiberufler […] in den Mittelpunkt. Wir konzentrieren uns auf den Abbau von Überregulierung, den Ausbau digitaler Verwaltungsleistungen und die Ausbildungsförderung. Außerdem setzen wir uns für einen Mutterschutz für Selbständige ein.',
    'Wir konzentrieren uns auf den Abbau von Überregulierung, den Ausbau digitaler Verwaltungsleistungen',
   ),
  ]),
 ]),
 ('klima', 'Klima, Energie und Wärme',
  'Klimaziele, Wärmeversorgung und Energiekosten.', [
  ('Wie soll die Wärmeversorgung bezahlbar und klimafreundlich werden?', [
   ('fdp', 87,
    'Gesetzt wird auf einen massiven Ausbau der Geothermie, um die Wärmeversorgung klimaneutral zu gestalten. Die CO2-Emissionen der Fernwärme sollen weitgehend reduziert und die Netze ausgeweitet werden. Bevorzugt werden Technologieoffenheit und private Investitionen.',
    'Zudem setzen wir auf den massiven Ausbau der Geothermie in Berlin, um die Wärmeversorgung klimaneutral zu gestalten. Wir wollen die CO2-Emissionen der Fernwärme weitgehend reduzieren und die Fern- und Nahwärmenetze im Stadtgebiet ausweiten.',
    'den massiven Ausbau der Geothermie in Berlin, um die Wärmeversorgung klimaneutral zu gestalten',
   ),
   ('afd', 7,
    'Die stark gestiegenen Preise für Strom, Gas und Heizöl wirkten sich auf die Kosten der Fernwärmeversorgung aus. Für Mieter landeseigener Wohnungsgesellschaften habe das zu drastischen Nachzahlungen geführt. Als Ursache wird die gescheiterte Energiewende benannt.',
    'Die infolge der gescheiterten „Energiewende“ und steuerlicher Belastungen stark gestiegenen Preise für Strom, Gas und Heizöl wirken sich auch auf die Kosten der Fernwärmeversorgung aus. Dies hat nicht nur für Mieter der landeseigenen Wohnungsgesellschaften zu teilweise drastischen Nachzahlungen geführt.',
    'stark gestiegenen Preise für Strom, Gas und Heizöl wirken sich auch auf die Kosten der Fernwärmeversorgung aus',
   ),
   ('bsw', 43,
    'Mit hoher Priorität soll für eine stabile, bezahlbare und krisenfeste Versorgung mit Strom, Wasser und Fernwärme gesorgt werden. Die Infrastruktur soll verlässlich finanziert werden. Betont wird die Bedeutung eines starken Wissenschafts- und Technologiestandorts.',
    'Gleichzeitig ist mit hoher Priorität für eine stabile, bezahlbare und krisenfeste Versorgung mit Strom, Wasser und Fernwärme zu sorgen.',
    'für eine stabile, bezahlbare und krisenfeste Versorgung mit Strom, Wasser und Fernwärme zu sorgen',
   ),
  ]),
  ('Wie verbindlich sollen die Berliner Klimaziele sein?', [
   ('cdu', 31,
    'Der Wettbewerb verschiedener Energieträger wie Gas, Fernwärme und Wärmepumpen soll erhalten bleiben. Nur so blieben Heizkosten dauerhaft bezahlbar. Einseitige staatliche Vorgaben werden abgelehnt.',
    'Den Wettbewerb verschiedener Energieträger wie Gas, Fernwärme und Wärmepumpen wollen wir erhalten, denn nur so bleiben Heizkosten dauerhaft bezahlbar. Einseitige staatliche Vorgaben lehnen wir ab.',
    'Den Wettbewerb verschiedener Energieträger wie Gas, Fernwärme und Wärmepumpen wollen wir erhalten',
   ),
   ('spd', 59,
    'Die Partei steht zu den Klimaschutzzielen und kämpft für Klimaneutralität vor dem Jahr 2045. Das Berliner Energiewendegesetz soll umgesetzt werden. Mieterinnen und Mieter sollen durch Klimaschutzmaßnahmen nicht zusätzlich belastet werden.',
    'Wir stehen zu den Klimaschutzzielen, kämpfen für Klimaneutralität vor dem Jahr 2045 und stehen zur Umsetzung des Berliner Energiewendegesetzes.',
    'kämpfen für Klimaneutralität vor dem Jahr 2045 und stehen zur Umsetzung des Berliner Energiewendegesetzes',
   ),
   ('gruene', 11,
    'Durch die Haushaltspolitik und falsche Prioritäten seien die Klimaziele 2030 nicht mehr zu halten. Damit sei auch das Ziel gefährdet, Berlin 2045 klimaneutral zu machen. Das gehe gegen die Interessen der Bevölkerung.',
    '[…] mit ihrer Haushaltspolitik und falschen Prioritätensetzung dafür sorgt, dass die Klimaziele 2030 nicht mehr zu halten sind, und so faktisch das Ziel, Berlin 2045 klimaneutral zu machen, stark gefährdet. Das geht gegen die Interessen der Bevölkerung.',
    'dass die Klimaziele 2030 nicht mehr zu halten sind',
   ),
   ('linke', 71,
    'Der Luftverkehrssektor müsse klimaneutral werden. Dafür sollen die erforderlichen Voraussetzungen geschaffen werden. Gefordert wird ein Verbot von Kurzstreckenflügen, wenn es Alternativen gibt.',
    'Klimaschutz im Luftverkehr: Der Luftverkehrssektor muss klimaneutral werden. Dafür unterstützen wir die Schaffung der erforderlichen Voraussetzungen. Wir setzen uns für ein Verbot von Kurzstreckenflügen ein.',
    'Wir setzen uns für ein Verbot von Kurzstreckenflügen ein',
   ),
  ]),
 ]),
]
