# -*- coding: utf-8 -*-
"""Datensatz Abgeordnetenhauswahl Berlin 2026. Alle Aussagen aus den PDFs."""

WAHL = {
    "id": "agh-be-2026",
    "name": "Abgeordnetenhauswahl Berlin",
    "region": "Berlin",
    "wahltag": "2026-09-20",
    "kuerzel": "be",
}

PROGRAMME = {
    "cdu": ("Der Anfang ist gemacht. Regierungsprogramm 2026–2031",
            "https://berlin-wird.de/image/uploads/data/regierungsprogramm2026_2031.pdf"),
    "spd": ("Wahlprogramm zur Abgeordnetenhauswahl 2026",
            "https://spd.berlin/media/2026/08/SPD_Berlin_Wahlprogramm_20260521-v4-1.pdf"),
    "gruene": ("Politik ändern. Berlin bleiben. Wahlprogramm zur Abgeordnetenhauswahl 2026",
               "https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf"),
    "fdp": ("Berlin geht besser. Wahlprogramm zur Abgeordnetenhauswahl 2026",
            "https://www.fdp-berlin.de/sites/default/files/2026-07/Wahlprogramm_FDP%20Berlin_Abgeordnetenhauswahl%202026_FINAL.pdf"),
    "afd": ("Berlin. Stark. Machen. Programm für die Wahlen am 20. September 2026",
            "https://lichtenberg.afd.berlin/wp-content/uploads/2026/07/AfD-WK-Berlin-Wahlprogramm-Webversion.pdf"),
    "linke": ("Berlin machen bezahlbar. Wahlprogramm zur Abgeordnetenhauswahl 2026",
              "https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf"),
    "bsw": ("Berlin – Mit uns endlich vernünftig und gerecht. Wahlprogramm zur AGH-Wahl 2026",
            "https://bsw.berlin/wp-content/uploads/Wahlprogramm-BSW-Berlin-AGH-Wahl-2026.pdf"),
}

# (themaId, Titel, Beschreibung, [(Fragetext, [Aussagen])])
# Aussage: (parteiId, seite, kurz, original, markierung)
# Regeln: 3-4 Aussagen je Frage, jede Partei je Thema genau einmal,
# alle Aussagen einer Frage beantworten dieselbe Unterfrage.
THEMEN = [
 ('wohnen', 'Wohnen und Mieten',
  'Mietregulierung, Neubau, landeseigene Wohnungsunternehmen.', [
  ('Wie stark soll der Staat in den Mietmarkt eingreifen?', [
   ('cdu', 30,
    'Enteignungen und einem Mietendeckel wird eine Absage erteilt; Mieter sollen ihre Rechte leichter durchsetzen.',
    'Populistischen Forderungen nach Enteignungen oder der Einführung eines Mietendeckels erteilen wir eine klare Absage. Solche Eingriffe sind keine Lösung für den angespannten Wohnungsmarkt, sondern verschärfen die Situation.',
    'Populistischen Forderungen nach Enteignungen oder der Einführung eines Mietendeckels erteilen wir eine klare Absage',
   ),
   ('linke', 7,
    'Für die kommunalen Wohnungen soll ein Mietendeckel gelten; ein Landesamt für Mieterschutz ahndet Verstöße.',
    'Unsere kommunalen Wohnungen müssen bezahlbar bleiben. Deshalb werden wir dort einen Mietendeckel durchsetzen. Mit unserem Landesamt für Mieterschutz schaffen wir eine handlungsfähige Behörde, die Verstöße ahndet und Recht durchsetzt.',
    'Deshalb werden wir dort einen Mietendeckel durchsetzen',
   ),
   ('bsw', 2,
    'Die Mietenregulierung soll geschärft werden; über den Bundesrat soll zusätzlich ein Mietendeckel kommen.',
    'Wir wollen die bestehenden Instrumente der Mietenregulierung schärfen und endlich konsequent durchsetzen und zusätzlich über eine Bundesratsinitiative einen Mietendeckel einführen. Berlin braucht mehr Wohnungen in öffentlicher Hand und in gemeinnütziger Bewirtschaftung.',
    'zusätzlich über eine Bundesratsinitiative einen Mietendeckel einführen',
   ),
  ]),
  ('Wie soll mit Milieuschutz- und Sanierungsgebieten umgegangen werden?', [
   ('spd', 20,
    'Bei An- und Ummeldung soll über Mietpreisbremse und Beratung informiert werden; Milieuschutzgebiete wachsen.',
    'Bei An- und Ummeldungen informieren wir über Mietpreisbremse und Mietwucher, verweisen auf kostenlose Beratung in den Bezirken und erklären Schutzregeln in Milieuschutzgebieten. Wir setzen uns für die Ausweitung von Milieuschutzgebieten ein.',
    'Wir setzen uns für die Ausweitung von Milieuschutzgebieten ein',
   ),
   ('gruene', 16,
    'Sanierungen in Milieuschutzgebieten sollen gefördert werden, damit Mieter den Energiekosten nicht ausgeliefert sind.',
    'Mieter*innen in unsanierten Häusern dürfen den Kostensteigerungen fossiler Brennstoffe nicht ungeschützt ausgesetzt werden. Das Land Berlin soll insbesondere in Milieuschutzgebieten ambitionierte Sanierungen fördern und Gebäudeeigentümer entsprechend beraten.',
    'Das Land Berlin soll insbesondere in Milieuschutzgebieten ambitionierte Sanierun gen fördern',
   ),
   ('fdp', 38,
    'Das öffentliche Vorkaufsrecht soll in Milieuschutzgebieten nur noch für öffentliche Infrastruktur gelten.',
    'Die landeseigenen WBG sollen aus ihren Beständen auch Wohnraum für von Wohnungslosigkeit bedrohte Menschen zur Verfügung stellen. In Sanierungs- und Milieuschutzgebieten soll das öffentliche Vorkaufsrecht, außer für öffentliche Infrastruktur, nicht mehr ausgeübt werden.',
    'In Sanierungs- und Milieuschutzgebieten soll das öffentliche Vorkaufsrecht, außer für öffentliche Infrastruktur, nicht mehr ausgeübt werden',
   ),
   ('afd', 6,
    'Die Fehlbelegungsabgabe soll zurückkommen, Untervermietung von Sozialwohnungen verboten, Milieuschutz begrenzt.',
    '[Wir wollen] die Fehlbelegungsabgabe wieder einführen. Um den Missbrauch zu verhindern, setzen wir uns für ein generelles Verbot der Untervermietung von Sozialwohnungen ein. Milieuschutz begrenzen: Die Ausweisung von Wohnvierteln als Milieuschutzgebiete (§ 172 BauGB) […].',
    'wir uns für ein generelles Verbot der Untervermietung von Sozialwohnungen ein',
   ),
  ]),
 ]),
 ('sicherheit', 'Innere Sicherheit',
  'Polizei, Videoüberwachung, Verbotszonen und Kontrolle.', [
  ('Wo und wie soll Videoüberwachung eingesetzt werden?', [
   ('cdu', 6,
    'An Kriminalitätsschwerpunkten soll es mehr Videoüberwachung und Messerverbotszonen geben, dazu Taser.',
    'Genau hinschauen, was passiert, um Kriminelle dingfest zu machen: An bekannten Kriminalitätsschwerpunkten kommen nun verstärkt Videoüberwachung und Waffen- und Messerverbotszonen zum Einsatz. Mit messbarem Erfolg […].',
    'An bekannten Kriminalitätsschwerpunkten kommen nun verstärkt Videoüberwachung und Waffen- und Messerverbotszonen zum Einsatz',
   ),
   ('fdp', 67,
    'An Risikoorten soll neben zeitweiliger Videoüberwachung mit Beleuchtung und offenen Sichtachsen gearbeitet werden.',
    'Wir möchten Security by Design berlinweit implementieren. An Berliner Risikoorten wie Bahnhöfen oder Drogenumschlagplätzen wollen wir – neben der temporären Videoüberwachung – mit baulichen Maßnahmen wie guter Beleuchtung, offenen Sichtachsen, Verhinderung dunkler Ecken die Sicherheit […] [erhöhen].',
    'neben der temporären Videoüberwachung – mit baulichen Maßnahmen wie guter Beleuchtung',
   ),
   ('afd', 13,
    'Gefordert wird eine vollständige Videoüberwachung aller Brennpunkte, dazu mobile Wachen in Problemvierteln.',
    'Die AfD fordert: → Die sofortige Aufhebung des Landesantidiskriminierungsgesetzes und die Überarbeitung anderer sicherheitsrelevanter Gesetze. → Eine vollständige Videoüberwachung in allen Brennpunktbereichen. → Die Einführung mobiler Polizeiwachen in Problemvierteln.',
    'Eine vollständige Videoüberwachung in allen Brennpunktbereichen',
   ),
   ('bsw', 41,
    'Videoüberwachung soll nur an belasteten Orten stehen, mit parlamentarischer Genehmigung und Auswertung in Echtzeit.',
    'Kriminalität und Gewalt muss wirksam entgegengetreten werden, damit sich alle Bürger unserer Stadt sicher fühlen können. Dazu setzen wir Videoüberwachung an nachweislich besonders kriminalitätsbelasteten Orten ein – mit parlamentarischer Genehmigung und Echtzeit-Auswertung durch ausreichend Personal.',
    'Videoüberwachung an nachweislich besonders kriminalitätsbelasteten Orten ein – mit parlamentarischer Genehmigung',
   ),
  ]),
  ('Wie sollen Polizeibefugnisse und Kriminalitätsorte kontrolliert werden?', [
   ('spd', 31,
    'Kriminalitätsbelastete Orte sollen regelmäßig parlamentarisch kontrolliert werden; Palantir wird abgelehnt.',
    '[Wir unterziehen] die Einstufung kriminalitätsbelasteter Orte einer regelmäßigen parlamentarischen Kontrolle. […] Den Einsatz von Software intransparente und datenschutzrechtlich bedenklicher Hersteller wie Palantir lehnen wir für Berlin entschieden [ab].',
    'die Einstufung kriminalitätsbelasteter Orte einer regelmäßigen parlamentarischen Kontrolle',
   ),
   ('gruene', 228,
    'Kriminalitätsbelastete Orte und Waffenverbotszonen sollen überprüft und wo nötig wieder abgeschafft werden.',
    'Wir werden die bestehenden kriminalitätsbelasteten Orte und Messer- und Waffenverbotszonen auf ihre Sinnhaftigkeit überprüfen und werden sie, wo erforderlich, wieder abschaffen. Die Ergebnisse der Bodycam-Studie wollen wir umsetzen.',
    'Messer- und Waffenverbotszonen auf ihre Sinnhaftigkeit überprüfen und werden sie, wo erforderlich, wieder abschaffen',
   ),
   ('linke', 288,
    'Die Aufrüstung der Polizei soll enden; anlasslose Kontrollen und Verbotszonen gelten als wenig zielführend.',
    'Aufrüstung der Polizei wollen wir stoppen und die Mittel umverteilen. Polizeieinsätze z. B. bei Demos, anlasslosen Kontrollen an KBOs und Waffenverbotszonen oder Fußballspielen sind personalintensiv und oft nicht zielführend.',
    'Aufrüstung der Polizei wollen wir stoppen und die Mittel umverteilen',
   ),
  ]),
 ]),
 ('verkehr', 'Verkehr und Mobilität',
  'Rad, Auto, Bus und Bahn im Stadtverkehr.', [
  ('Welcher Verkehrsart soll in der Stadt Vorrang eingeräumt werden?', [
   ('gruene', 81,
    'Niemand soll ein Auto besitzen müssen; für Handwerk und Lieferverkehr gibt es mehr reservierte Flächen.',
    '[Wir schaffen] Schulzonen und sichere Schulwege von der Haustür bis zum Schuleingang und gestalten lebenswerte Kieze, in denen man entspannt zu Fuß gehen kann. […] Man muss kein Auto mehr besitzen, um mobil zu sein – alle können sich frei und unabhängig bewegen. Und für die, die auf ein Auto angewiesen sind – beispielsweise Handwerker*innen, Lieferverkehr oder Menschen mit Mobilitätseinschränkungen –, gibt es mehr reservierte Parkplätze wie Lieferbereiche und Behindertenparkplätze.',
    'Man muss kein Auto mehr besitzen, um mobil zu sein',
   ),
   ('afd', 42,
    'Das Auto bleibt unverzichtbarer Teil städtischer Mobilität; im Nahverkehr soll es Zugangskontrollen geben.',
    '→ Zugangsbeschränkungen für Personen ohne Fahrschein. → Eine bessere Einbindung des Regionalverkehrs in das Gesamtnetz. Für diskriminierungsfreien Autoverkehr: Der motorisierte Individualverkehr bleibt für uns auch in Zukunft ein unverzichtbarer Bestandteil urbaner Mobilität.',
    'Der motorisierte Individualverkehr bleibt für uns auch in Zukunft ein unverzichtbarer Bestandteil urbaner Mobilität',
   ),
   ('linke', 55,
    'Vorrang hat ein überzeugendes Nahverkehrsangebot, dazu ein dichtes Radwegenetz und barrierefreie Gehwege.',
    'Unsere Priorität liegt daher auf einem überzeugenden Angebot im öffentlichen Personennahverkehr (ÖPNV) sowie dem Ausbau eines umfassenden Radwegenetzes und von barrierefreien Gehwegen. So ermöglichen wir allen eine kostengünstige Mobilität.',
    'Unsere Priorität liegt daher auf einem überzeugenden Angebot im öffentlichen Personennahverkehr',
   ),
   ('bsw', 48,
    'Statt eines Gegeneinanders sollen Auto, Rad und Nahverkehr nebeneinander funktionieren, auch in den Außenbezirken.',
    '[Wir wollen kein Gegeneinander] zwischen Auto, Fahrrad und öffentlichem Nahverkehr, sondern ein vernünftiges Miteinander. Sichere Wege für Fußgänger, ein starker Nahverkehr, ein verlässliches Radwegenetz und gute Bedingungen für den motorisierten Individualverkehr gehören zusammen.',
    'ein verlässliches Radwegenetz und gute Bedingungen für den motorisierten Individualverkehr gehören zusammen',
   ),
  ]),
  ('Worin soll beim Verkehr zuerst investiert werden?', [
   ('cdu', 71,
    'Das Radwegenetz soll bedarfsgerecht wachsen, vorrangig durch Sanierung der vorhandenen Wege.',
    'Mit dem Rad durch die Stadt: Das Berliner Radwegenetz werden wir gezielt verbessern und bedarfsgerecht ausbauen. Vorrang hat für uns die Sanierung und Ertüchtigung bestehender Wege.',
    'Das Berliner Radwegenetz werden wir gezielt verbessern und bedarfsgerecht ausbauen. Vorrang hat für uns die Sanierung',
   ),
   ('spd', 24,
    'Der Ausbau der Straßenbahn soll in allen Bezirken vorangehen, die Busflotte wird weiter elektrifiziert.',
    'Die Elektrifizierung des Busverkehrs setzen wir fort und senken damit zugleich den Lärm in der Stadt. Wir treiben den Ausbau der Straßenbahn in allen Bezirken voran, finanzieren laufende Projekte […].',
    'Wir treiben den Ausbau der Straßenbahn in allen Bezirken voran',
   ),
   ('fdp', 55,
    'Vorhandene Radwege sollen repariert werden, auch unterhalb der Normbreite, statt auf Konzepte zu warten.',
    'Bestehende Radwege müssen repariert werden, auch wenn sie nicht der „Normbreite“ entsprechen, anstatt zehn Jahre auf ein „Verkehrskonzept“ und dessen Umsetzung zu warten.',
    'Bestehende Radwege müssen repariert werden, auch wenn sie nicht der „Normbreite“ entsprechen',
   ),
  ]),
 ]),
 ('verwaltung', 'Verwaltung und Digitalisierung',
  'Bürgerämter, Verwaltungsreform und digitale Verfahren.', [
  ('Wie weit soll die Verwaltung digitalisiert werden?', [
   ('spd', 11,
    'Der digitale Wirtschaftsservice soll kommen und mehr Leistungen sollen digital angeboten werden.',
    'Wir setzen den DIWI – den digitalen Wirtschaftsservice der Berliner Verwaltung – um und bieten noch mehr Leistungen digital an. Außerdem setzen wir mit digitalen Tools ein modernes Vergaberecht um.',
    'den digitalen Wirtschaftsservice der Berliner Verwaltung – um und bieten noch mehr Leistungen digital an',
   ),
   ('gruene', 71,
    'Die internen Abläufe sollen vollständig digitalisiert und die E-Akte überall eingeführt werden.',
    'Um das Angebot unserer Behörden verbessern zu können, müssen wir die internen Prozesse in den Verwaltungen vollständig digitalisieren. Dafür führen wir übergreifend in allen Verwaltungen die E-Akte ein.',
    'Dafür führen wir übergreifend in allen Verwaltungen die E-Akte ein',
   ),
   ('fdp', 21,
    'Für neue Gesetze sollen die Grundsätze digital only und digital once gelten: Daten nur einmal übermitteln.',
    'Bei neuen Gesetzen und Verordnungen oder auch bei Änderungen sorgen wir dafür, dass alle damit verbundenen Verwaltungsvorgänge digitaltauglich umgesetzt werden können. Die Grundsätze „digital only“ und „digital once“ (Übermittlung von Daten nur noch einmal an die Berliner [Verwaltung]) […].',
    'dass alle damit verbundenen Verwaltungsvorgänge digitaltauglich umgesetzt werden können',
   ),
   ('bsw', 62,
    'Verwaltung sei Dienstleistung und müsse schneller werden; Papierakten sollen abgelöst werden.',
    'Verwaltung modernisieren: Verwaltung bedeutet auch Dienstleistung. Damit diese beschleunigt wird, braucht es eine konsequentere Digitalisierung: Papierakten soll[en] […] [abgelöst werden].',
    'Damit diese beschleunigt wird, braucht es eine konsequentere Digitalisierung',
   ),
  ]),
  ('Worauf soll es bei der Verwaltungsreform jetzt ankommen?', [
   ('cdu', 87,
    'Die Reform soll klare Verantwortung und starke Bezirke bringen und das Behörden-Pingpong beenden.',
    'Mit der großen Verwaltungsreform setzen wir um, woran Vorgängersenate 25 Jahre gescheitert sind: klare Verantwortung, starke Bezirke, kein Behörden-Pingpong mehr. Wir bringen Berlin nach und nach wieder zum Funktionieren – für eine Verwaltung, die zuallererst den Bürgern dient.',
    'klare Verantwortung, starke Bezirke, kein Behörden-Pingpong mehr',
   ),
   ('afd', 96,
    'Investiert werden müsse in Verwaltungsmodernisierung und kritische Systeme; der Stau liege über 100 Milliarden.',
    'Der Investitionsstau der öffentlichen Hand beläuft sich inzwischen auf weit über 100 Mrd. Euro. Investitionen sind erforderlich, insbesondere in: Die Infrastruktur; die Verwaltungsmodernisierung; die Digitalisierung kritischer Systeme; Sicherheits- und Rettungsdienste; Substanzerhalt öffentlicher Gebäude.',
    'die Verwaltungsmodernisierung; die Digitalisierung kritischer Systeme',
   ),
   ('linke', 11,
    'Die Verwaltung soll digitaler und effizienter werden; Geld für Überwachungskameras fließt ins Soziale.',
    'Wir reduzieren die Ausgaben für Überwachungskameras und investieren stattdessen in soziale Angebote. Wir müssen unsere Verwaltung digitaler und effizienter machen und die Verwaltungsreform mit Leben füllen.',
    'Wir müssen unsere Verwaltung digitaler und effizienter machen und die Verwaltungsreform mit Leben füllen',
   ),
  ]),
 ]),
 ('schule', 'Schule und Bildung',
  'Schulplätze, Personal, Schulformen und Inklusion.', [
  ('Wie soll die Schule organisiert und gesteuert werden?', [
   ('cdu', 54,
    'Nach 62.000 neuen Schulplätzen soll weiter massiv in Schulbau investiert werden, dazu ein 11. Pflichtschuljahr.',
    'Das neue 11. Pflichtschuljahr gibt Jugendlichen ohne Ausbildungsplatz eine klare Perspektive. Wir investieren massiv in Berlins Schulbau: Im Rahmen der Schulbauoffensive wurden so rund 62.000 neue Schulplätze, 41 neue Schulen, 119 Ergänzungsbauten und 76 neue Sporthallen entstanden.',
    'Wir investieren massiv in Berlins Schulbau',
   ),
   ('spd', 42,
    'Die Schulbauoffensive soll fortgesetzt und die Lehrkräftebildung über die Schools of Education gestärkt werden.',
    'In diesem Sinne stärken wir die Schools of Education als zentrale Struktur der Lehrkräftebildung. Die Schulbauoffensive fortsetzen: Seit Beginn der Schulbauoffensive haben wir durch Erweiterungen und Neubauten deutlich über 50.000 Schulplätze geschaffen.',
    'Die Schulbauoffensive fortsetzen',
   ),
   ('fdp', 8,
    'Schulen sollen ihr Personal selbst auswählen, ihre Selbstverwaltung ausbauen und eigene Teams bilden dürfen.',
    'Wir wollen die personelle Situation der Schulen bei der Selbstverwaltung weiter verbessern, um Lehrkräfte und die pädagogische Schulleitung von Verwaltungsaufgaben zu entlasten. Im Rahmen ihrer Personalautonomie wollen wir es Schulen außerdem ermöglichen, schulspezifisch multiprofessionelle Teams […] zu bilden.',
    'um Lehrkräfte und die pädagogische Schulleitung von Verwaltungsaufgaben zu entlasten',
   ),
   ('afd', 28,
    'Das Losverfahren für 30 Prozent der Schulplätze soll weg; es zählen Noten, Wohnortnähe und Geschwisterkinder.',
    '[Die Aufnahme an] weiterführenden Schulen muss sich konsequent an den Noten und der Wohnortnähe orientieren sowie eine Geschwisterkindregelung umfassen. Die Vergabe von 30 % der Schulplätze über das Losverfahren werden wir abschaffen.',
    'Die Vergabe von 30 % der Schulplätze über das Losverfahren werden wir abschaffen',
   ),
  ]),
  ('Worauf soll Bildung inhaltlich zielen?', [
   ('gruene', 154,
    'Exkludierende Systeme sollen abgebaut und Inklusion an allen Schulen mit multiprofessionellen Teams möglich werden.',
    'Exkludierende Systeme müssen vollständig abgebaut und Inklusion in allen Schulen möglich gemacht werden. Multiprofessionelle Teams, Schulassistenz sowie ergänzende Förderung und Betreuung in Grundschulen sichern gleiche Bildungschancen.',
    'Exkludierende Systeme müssen vollständig abgebaut und Inklusion in allen Schulen möglich gemacht werden',
   ),
   ('linke', 152,
    'Schüler sollen ihren Schulalltag selbstbestimmt mitgestalten; Bildung soll Gesellschaft kritisch verstehen lehren.',
    '[…] ihren Schulalltag zunehmend selbstbestimmt mitgestalten können. Bildung soll sie befähigen, Gesellschaft kritisch zu verstehen und solidarisch zu verändern. Lehrkräfte wollen wir bestärken, emanzipatorische und partizipative pädagogische Konzepte anzuwenden.',
    'Lehrkräfte wollen wir bestärken, emanzipatorische und partizipative pädagogische Konzepte anzuwenden',
   ),
   ('bsw', 14,
    'Angestrebt wird eine Rückbesinnung auf verbindliche Inhalte, klare Standards und überprüfbare Ergebnisse.',
    'Wir wollen eine Rückbesinnung auf verbindliche Inhalte, klare Leistungsstandards und überprüfbare Ergebnisse. Schülerinnen und Schüler sollen wissen, was sie können – und was von ihnen erwartet wird. Bildung bedeutet für uns, Leistung zu fordern und zu fördern, soziales Verhalten zu stärken und junge Menschen auf ein selbstbestimmtes, beruflich tragfähiges Leben vorzubereiten.',
    'eine Rückbesinnung auf verbindliche Inhalte, klare Leistungsstandards',
   ),
  ]),
 ]),
 ('zuwanderung', 'Zuwanderung und Integration',
  'Aufnahme, Rückführung, Einbürgerung und Arbeitsmarkt.', [
  ('Wie konsequent soll Zuwanderung begrenzt werden?', [
   ('cdu', 25,
    'Rückführungen sollen ganzjährig stattfinden; Ausreisegewahrsam und Abschiebungshaft werden ausgeweitet.',
    '[Wir wollen Rückführungen] ganzjährig durchzuführen, auch in den Wintermonaten. Um Rückführungen wirksam durchzusetzen, sind die bestehenden Instrumente des Ausreisegewahrsams und der Abschiebungshaft stärker zu nutzen. Dazu wollen wir die Kapazitäten des Ausreisegewahrsams deutlich erweitern.',
    'die Kapazitäten des Ausreisegewahrsams deutlich erweitern',
   ),
   ('fdp', 95,
    'Irreguläre Migration soll unterbunden werden; wer legal kommt, bekommt Sprachkurse ab dem ersten Tag.',
    'Irreguläre Migration muss unterbunden werden, wer legal kommt, erhält echte Chancen. Integration fordert alle Beteiligten: Sprach- und Integrationskurse vom ersten Tag an, die Vermittlung unserer freiheitlich-demokratischen Grundordnung, den Respekt vor Gleichberechtigung.',
    'Irreguläre Migration muss unterbunden werden, wer legal kommt, erhält echte Chancen',
   ),
   ('afd', 14,
    'Eine Sondereinheit der Ausländerbehörde soll Ausweisung und Abschiebung krimineller Ausländer betreiben.',
    'Die AfD fordert: → Die Einrichtung einer Sondereinheit bei der Ausländerbehörde, die die Ausweisung und Abschiebung ausländischer Krimineller [betreibt].',
    'Die Einrichtung einer Sondereinheit bei der Ausländerbehörde',
   ),
   ('bsw', 34,
    'Wer keinen Anspruch auf Asyl hat, soll gar nicht erst einreisen; dann stelle sich die Abschiebefrage nicht.',
    'Wer keinen Anspruch auf Asyl hat, darf gar nicht erst in die Europäische Union einreisen und es kann somit auch nicht mehr zu Schwierigkeiten bei einer Abschiebung kommen. Wir fordern, dass die notwendigen Regelungen in Deutschland nun zügig umzusetzen sind, damit Zuwanderung künftig regelbasiert stattfindet.',
    'Wer keinen Anspruch auf Asyl hat, darf gar nicht erst in die Europäische Union einreisen',
   ),
  ]),
  ('Wie soll die Integration derer gelingen, die hier sind?', [
   ('spd', 52,
    'Die Integration in den Arbeitsmarkt soll gestärkt und Teilhabe über die Einbürgerung ermöglicht werden.',
    '[…] schnell selbst ihren Lebensunterhalt verdienen können. Deshalb stärken wir Berlins Anstrengungen zur Integration in den Arbeitsmarkt weiter. Teilhabe durch Einbürgerung: Wir wollen, dass alle Berlinerinnen und Berliner demokratisch mitbestimmen.',
    'Deshalb stärken wir Berlins Anstrengungen zur Integration in den Arbeitsmarkt weiter',
   ),
   ('gruene', 112,
    'Rechtsberatung und aufenthaltsrechtliche Absicherung sollen helfen, Rechte ohne Angst wahrzunehmen.',
    '[Mit] Rechtsberatung und aufenthaltsrechtlicher Absicherung unterstützen wir Betroffene dabei, ihre Rechte wahrzunehmen und Rechtsverfahren durchzustehen – ohne Angst vor Abschiebung. Dazu gehört auch eine ausreichende Zahl an Mitarbeiter*innen.',
    'ihre Rechte wahrzunehmen und Rechtsverfahren durchzustehen – ohne Angst vor Abschiebung',
   ),
   ('linke', 105,
    'Berufsbegleitende Sprachkurse sollen gestärkt und der Zugang zum Arbeitsmarkt erleichtert werden.',
    'Berufsbegleitende Sprachkurse und Projekte für eine bessere Arbeitsmarktintegration von Migrant*innen müssen gestärkt werden. Der Zugang für Geflüchtete zum Arbeitsmarkt muss erleichtert werden.',
    'Der Zugang für Geflüchtete zum Arbeitsmarkt muss erleichtert werden',
   ),
  ]),
 ]),
 ('gesundheit', 'Gesundheit und Krankenhäuser',
  'Versorgung in den Bezirken, Kliniken und Pflege.', [
  ('Wie sollen die Krankenhäuser finanziert und getragen werden?', [
   ('spd', 33,
    'Ambulante, stationäre und psychosoziale Angebote sollen enger zusammenarbeiten, die Kliniken auskömmlich finanziert.',
    'Gesundheit ist ein Menschenrecht. Deshalb wollen wir eine gerechte und flächendeckende Gesundheitsversorgung. Ambulante, stationäre und psychosoziale Angebote müssen enger zusammenarbeiten. […] Die SPD Berlin setzt sich vor diesem Hintergrund für eine auskömmliche Finanzierung ein.',
    'Deshalb wollen wir eine gerechte und flächendeckende Gesundheitsversorgung',
   ),
   ('fdp', 114,
    'Die Krankenhausfinanzierung soll sich am tatsächlichen Bedarf ausrichten, die Trennung ambulant/stationär fallen.',
    'Wer eine Behandlung im Krankenhaus benötigt, muss rund um die Uhr an sieben Tagen in der Woche und 365 Tagen im Jahr die beste medizinische Versorgung erhalten können. […] Wir werden uns daher für eine Neuordnung der Krankenhausfinanzierung einsetzen, die sich am tatsächlichen medizinischen Patientenbedarf orientiert.',
    'eine Neuordnung der Krankenhausfinanzierung einsetzen, die sich am tatsächlichen medizinischen Patientenbedarf orientiert',
   ),
   ('linke', 8,
    'Die Krankenhäuser sollen in kommunaler Hand bleiben; wo private Träger aussteigen, wird rekommunalisiert.',
    'Unser Wohlbefinden, unsere Gesundheit darf nicht dem Profitstreben von Krankenhauskonzernen zum Opfer fallen. Wir wollen, dass unsere Krankenhäuser in kommunaler Hand bleiben und dort rekommunalisiert werden, wo sich private Konzerne aus der Verantwortung ziehen.',
    'dass unsere Krankenhäuser in kommunaler Hand bleiben und dort rekommunalisiert werden',
   ),
   ('bsw', 21,
    'Das solidarische Gesundheitswesen soll gestärkt und die Zwei-Klassen-Medizin durch eine Bürgerversicherung beendet.',
    'Wir wollen das solidarische Gesundheitswesen stärken, statt es weiter kaputtzusparen. Die Zwei-Klassen-Medizin muss beendet werden. […] Deshalb strebt das BSW eine Bürgerversicherung als einheitliches Krankenversicherungssystem [an].',
    'Deshalb strebt das BSW eine Bürgerversicherung als einheitliches Krankenversicherungssystem',
   ),
  ]),
  ('Wie soll die Versorgung im Alltag erreichbar bleiben?', [
   ('cdu', 99,
    'Dokumentations- und Meldepflichten in der Pflege sollen vereinfacht und Praxisplätze gesichert werden.',
    '[Wir wollen Entlastungen] in der Pflege und der Verwaltung schaffen, um Dokumentations- und Meldeprozesse deutlich zu vereinfachen. Gute Versorgung braucht gute Ausbildung in allen Bereichen der Gesundheitsversorgung. Wir setzen uns insbesondere dafür ein, dass angehende Pflegefachkräfte ausreichend Praxisplätze finden.',
    'dass angehende Pflegefachkräfte ausreichend Praxisplätze finden',
   ),
   ('gruene', 201,
    'Die Gesundheitschancen unterscheiden sich je nach Bezirk; Arztsitze sollen gleichmäßiger verteilt werden.',
    'Noch immer unterscheiden sich die Gesundheitschancen in Berlin stark: Je nach Bezirk, Wohnviertel, Geschlecht und sozioökonomischem Status weichen Lebenserwartung und Krankheitshäufigkeiten voneinander ab. […] Wir setzen uns dafür ein, dass es eine gleichmäßige Verteilung von Vertragsärzt*innensitzen gibt.',
    'dass es eine gleichmäßige Verteilung von Vertragsärzt*innensitzen gibt',
   ),
   ('afd', 69,
    'Wohnortnahe Versorgung und Pflege sollen auf Eigenverantwortung, Prävention und moderne Kliniken bauen.',
    'Eine leistungsfähige und wohnortnahe Gesundheitsversorgung sowie eine fürsorgliche Pflege sind für die AfD von herausragender Bedeutung. Eigenverantwortung, Prävention, private und staatliche Angebote der Daseinsvorsorge sind die Basis für ein gesundes, langes und selbstbestimmtes Leben.',
    'Eine leistungsfähige und wohnortnahe Gesundheitsversorgung sowie eine fürsorgliche Pflege',
   ),
  ]),
 ]),
 ('wirtschaft', 'Wirtschaft und Gewerbe',
  'Gewerbeflächen, Ansiedlung und Rahmenbedingungen.', [
  ('Wodurch soll Berlin als Wirtschaftsstandort wachsen?', [
   ('spd', 6,
    'In Wirtschaftsförderung und Infrastruktur soll investiert werden, mit Tarifbindung statt Lohndumping.',
    'Wir investieren in Wirtschaftsförderung und Infrastruktur und wollen attraktive Arbeitsbedingungen mit Tarifbindungen statt Lohndumping.',
    'Wir investieren in Wirtschaftsförderung und Infrastruktur und wollen attraktive Arbeitsbedingungen mit Tarifbindungen statt Lohndumping',
   ),
   ('gruene', 98,
    'Technologie, Industrie und Forschung sollen zusammenwirken; geprüft wird eine landeseigene Innovationsagentur.',
    '[…] damit Technologie, Industrie, Forschung und Ausbildung an dieser wichtigen Schnittstelle zusammenwirken und Berlin als Standort für angewandte Innovation und klimaneutrale Industrie gestärkt wird. […] prüfen wir die Einrichtung einer landeseigenen Innovationsagentur.',
    'Berlin als Standort für angewandte Innovation und klimaneutrale Industrie gestärkt wird',
   ),
   ('afd', 47,
    'Berlin soll wieder Industriestandort werden, mit Förderung von Luftfahrt, Halbleitern und Gesundheitswirtschaft.',
    '[Der] Energiestandort Berlin muss wieder industrieller Kernstandort werden. Wir fördern gezielt die Ansiedlung von Unternehmen in den Bereichen: + Luft- und Raumfahrt; + Gesundheitswirtschaft; + Halbleiter, KI […]. Flächen für Gewerbe und Industrie – transparent und verfügbar: Ein öffentliches Gewerbeflächenkataster […].',
    'Wir fördern gezielt die Ansiedlung von Unternehmen in den Bereichen',
   ),
  ]),
  ('Wem soll die Wirtschaftspolitik vor allem dienen?', [
   ('cdu', 37,
    'Ein Leerstandsmonitoring für Büro- und Gewerbeflächen soll Flächen für Start-ups und Betriebe verfügbar machen.',
    'Für mehr Transparenz über die Entwicklungen auf dem Gewerbemarkt setzen wir uns für die Einführung eines systematischen Leerstandsmonitorings von Büro- und Gewerbeflächen ein. Wir werden das Leerstandsmanagement landeseigener Immobilien weiterentwickeln und gezielt für die Nutzung durch Start-ups und Unternehmen [öffnen].',
    'die Einführung eines systematischen Leerstandsmonitorings von Büro- und Gewerbeflächen',
   ),
   ('fdp', 18,
    'Berlin soll einer der freiesten Wirtschaftsstandorte Europas und vom Empfänger- zum Geberland werden.',
    'Wir [wollen] Berlin zu einem der freiesten Wirtschaftsstandorte Europas machen. Unser Ziel ist eine Verwaltung, die sich auf ihre Kernaufgaben beschränkt, Verfahren beschleunigt, Rechtssicherheit gewährleistet und unternehmerische Tätigkeit nicht behindert, sondern ermöglicht. Berlin muss vom Empfänger- zum Geberland werden!',
    'eine Verwaltung, die sich auf ihre Kernaufgaben beschränkt',
   ),
   ('linke', 15,
    'Bei der Vergabe von Gewerbeflächen sollen Anwohner eingebunden, Bestände für Nahversorgung genutzt werden.',
    'Wo immer möglich, sollen eigene Bestände für eine gute Nahversorgung für den täglichen Bedarf und soziale Angebote genutzt werden. Bei der Vergabe von Gewerbeflächen sollen Anwohner*innen und deren Vertretungen eng eingebunden werden.',
    'Bei der Vergabe von Gewerbeflächen sollen Anwohner*innen und deren Vertretungen eng eingebunden werden',
   ),
   ('bsw', 42,
    'Im Mittelpunkt stehen Familienbetriebe und Selbständige: weniger Überregulierung, mehr Ausbildungsförderung.',
    'Die Wirtschaftspolitik des Berliner BSW rückt Familienbetriebe, Selbständige und Freiberufler […] in den Mittelpunkt. Wir konzentrieren uns auf den Abbau von Überregulierung, den Ausbau digitaler Verwaltungsleistungen und die Ausbildungsförderung. Außerdem setzen wir uns für einen Mutterschutz für Selbständige ein.',
    'Wir konzentrieren uns auf den Abbau von Überregulierung, den Ausbau digitaler Verwaltungsleistungen',
   ),
  ]),
 ]),
 ('klima', 'Klima, Energie und Wärme',
  'Klimaziele, Wärmeversorgung und Energiekosten.', [
  ('Wie soll die Wärmeversorgung bezahlbar und klimafreundlich werden?', [
   ('fdp', 87,
    'Gesetzt wird auf massiven Ausbau der Geothermie und größere Fernwärmenetze, getragen von privaten Investitionen.',
    'Zudem setzen wir auf den massiven Ausbau der Geothermie in Berlin, um die Wärmeversorgung klimaneutral zu gestalten. Wir wollen die CO2-Emissionen der Fernwärme weitgehend reduzieren und die Fern- und Nahwärmenetze im Stadtgebiet ausweiten.',
    'den massiven Ausbau der Geothermie in Berlin, um die Wärmeversorgung klimaneutral zu gestalten',
   ),
   ('afd', 97,
    'Fernwärme und Nahverkehr sollen bezahlbar bleiben; dauerhaft steigende Kosten dürfe die öffentliche Hand nicht abwälzen.',
    '[Erforderlich ist eine Politik], die ideologische Kostensteigerungen zulasten der Berliner verhindert. Investitionen müssen in ein tragfähiges Finanzierungskonzept eingebettet sein. Fernwärme und ÖPNV solide und bezahlbar halten: Die öffentliche Hand darf Bürger und Wirtschaft nicht über dauerhaft steigende Kosten belasten.',
    'Fernwärme und ÖPNV solide und bezahlbar halten',
   ),
   ('bsw', 43,
    'Vorrang hat eine stabile und bezahlbare Versorgung mit Strom, Wasser und Fernwärme, verlässlich finanziert.',
    'Gleichzeitig ist mit hoher Priorität für eine stabile, bezahlbare und krisenfeste Versorgung mit Strom, Wasser und Fernwärme zu sorgen.',
    'für eine stabile, bezahlbare und krisenfeste Versorgung mit Strom, Wasser und Fernwärme zu sorgen',
   ),
  ]),
  ('Wie verbindlich sollen die Berliner Klimaziele sein?', [
   ('cdu', 31,
    'Gas, Fernwärme und Wärmepumpe sollen im Wettbewerb bleiben; einseitige staatliche Vorgaben werden abgelehnt.',
    'Den Wettbewerb verschiedener Energieträger wie Gas, Fernwärme und Wärmepumpen wollen wir erhalten, denn nur so bleiben Heizkosten dauerhaft bezahlbar. Einseitige staatliche Vorgaben lehnen wir ab.',
    'Den Wettbewerb verschiedener Energieträger wie Gas, Fernwärme und Wärmepumpen wollen wir erhalten',
   ),
   ('spd', 59,
    'Berlin soll vor 2045 klimaneutral werden; Mieter dürfen durch den Klimaschutz nicht zusätzlich belastet werden.',
    'Wir stehen zu den Klimaschutzzielen, kämpfen für Klimaneutralität vor dem Jahr 2045 und stehen zur Umsetzung des Berliner Energiewendegesetzes.',
    'kämpfen für Klimaneutralität vor dem Jahr 2045 und stehen zur Umsetzung des Berliner Energiewendegesetzes',
   ),
   ('gruene', 11,
    'Berlin soll sich an Hamburg orientieren und bereits 2040 klimaneutral sein, mit klaren Prioritäten im Fahrplan.',
    'Berlin muss sich ein Vorbild an Hamburg nehmen, das nun schon 2040 klimaneutral sein will. In Regierungsverantwortung werden wir den Fahrplan zur Klimaneutralität und -anpassung auf solide Beine stellen und Prioritäten setzen, um die Ziele schnellstmöglich zu erreichen.',
    'Berlin muss sich ein Vorbild an Hamburg nehmen',
   ),
   ('linke', 71,
    'Auch der Luftverkehr müsse klimaneutral werden; Kurzstreckenflüge sollen bei Alternativen verboten sein.',
    'Klimaschutz im Luftverkehr: Der Luftverkehrssektor muss klimaneutral werden. Dafür unterstützen wir die Schaffung der erforderlichen Voraussetzungen. Wir setzen uns für ein Verbot von Kurzstreckenflügen ein.',
    'Wir setzen uns für ein Verbot von Kurzstreckenflügen ein',
   ),
  ]),
 ]),
]


# ---------------------------------------------------------------------------
# Dritte Frage je Thema (13. September 2026). Getrennt notiert, damit die
# ersten beiden Fragen unangetastet bleiben; angehaengt wird am Dateiende.
# Eine Partei kommt je Thema hoechstens einmal oefter vor als eine andere -
# dieselbe Ausgewogenheitsregel, die baue_datensatz.py prueft.
DRITTE = {
 'wohnen': ('Soll der Rand des Tempelhofer Feldes bebaut werden?', [
   ('cdu', 36,
    'Am Rand des Tempelhofer Feldes sollen mehr als 20.000 Wohnungen entstehen, das übrige Feld bleibt Erholungsort.',
    'Wir bekennen uns klar zur Randbebauung des Tempelhofer Feldes. Auf den Randflächen des Feldes sollen mehr als 20.000 neue Wohnungen für etwa 50.000 Menschen entstehen. Darüber hinaus soll das Tempelhofer Feld als Ort für Sport, Freizeit, Kultur und Erholung erhalten und zugleich gezielt weiterentwickelt werden.',
    'Auf den Randflächen des Feldes sollen mehr als 20.000 neue Wohnungen',
   ),
   ('spd', 19,
    'Das Tempelhofer Feld soll bleiben, wie es ist; Wohnungen am Rand kommen nicht infrage, solange Flächen brachliegen.',
    'Das Tempelhofer Feld ist ein besonderer Ort für Klima, Bewegung und soziales Miteinander. Wir erhalten es in seiner heutigen Funktion und entwickeln es behutsam weiter. […] Wohnungen am Feldrand kommen nicht in Frage, solang die bisherigen Flächen in Berlin ungenutzt sind […]',
    'Wohnungen am Feldrand kommen nicht in Frage',
   ),
   ('gruene', 22,
    'Das Tempelhofer Feld soll geschützt bleiben: als Kaltluftquelle, Lebensraum für Tiere und Pflanzen und Erholungsort.',
    'Das Tempelhofer Feld, mit seiner herausragenden Bedeutung für das Stadtklima und seiner Funktion als wichtige Kaltluftquelle, Lebensraum zahlreicher Pflanzen- und Tierarten sowie einzigartiger Erholungsort, soll weiterhin geschützt bleiben.',
    'soll weiterhin geschützt bleiben',
   ),
   ('bsw', 32,
    'Über eine Randbebauung soll erneut die Bevölkerung entscheiden; Volksentscheide bleiben dem Parlament entzogen.',
    'Gesetze, die durch einen Volksentscheid zustande gekommen sind, können nicht durch das Abgeordnetenhaus allein geändert werden, sondern müssen der Bevölkerung erneut zur Abstimmung gestellt werden (Bsp. Randbebauung Tempelhofer Feld).',
    'müssen der Bevölkerung erneut zur Abstimmung gestellt werden',
   ),
 ]),
 'verkehr': ('Soll die A 100 weitergebaut werden?', [
   ('cdu', 69,
    'Der Weiterbau der A 100 und die Tangentialverbindung Ost sollen entschlossen vorangetrieben werden.',
    'Übergeordnete Projekte wie den Weiterbau der A 100 oder die Tangentialverbindung Ost (TVO) werden wir entschlossen vorantreiben, um Wohngebiete von Durchgangsverkehr zu entlasten und insbesondere Stadtteile im Berliner Osten besser anzubinden.',
    'werden wir entschlossen vorantreiben, um Wohngebiete von Durchgangsverkehr zu entlasten',
   ),
   ('fdp', 62,
    'Die A 100 soll zügig bis zur Storkower Straße weitergebaut werden, dazu neue Verbindungen im Nordosten.',
    'Vor allem der Berliner Osten ist noch nicht in ausreichendem Umfang an das Hauptstraßennetz angeschlossen. Der zügige Weiterbau der A 100 durch den 17. Bauabschnitt bis Storkower Straße und der Fertigbau der Tangentialverbindung Ost (TVO) sowie neuer Straßenverbindungen, vor allem im Nordosten und Süden der Stadt, haben für uns daher weiterhin Priorität.',
    'Der zügige Weiterbau der A 100 durch den 17. Bauabschnitt bis Storkower Straße',
   ),
   ('linke', 69,
    'Neue Autobahnen werden abgelehnt: Die A 100 soll am Treptower Park enden, vorhandene brauchen Lärmschutz.',
    'Neue Autobahnen in Berlin lehnen wir ab. An bestehenden Autobahnen müssen Lärmschutzlösungen ermöglicht werden. Wir fordern, dass die A100 qualifiziert am Treptower Park beendet und nicht weiter ausgebaut wird.',
    'Neue Autobahnen in Berlin lehnen wir ab',
   ),
   ('spd', 26,
    'Statt des Weiterbaus sollen Straßen und Brücken saniert und nachhaltige Mobilität gefördert werden.',
    'Statt die A100 weiterzubauen, setzen wir auf den Erhalt unserer Straßen und Brücken sowie auf nachhaltige Mobilität. Wir setzen uns beim Bund dafür ein, dass Investitionsmittel stärker als bisher für die Sanierung von Straßen und Brücken […] eingesetzt werden.',
    'Statt die A100 weiterzubauen, setzen wir auf den Erhalt unserer Straßen und Brücken',
   ),
 ]),
 'schule': ('Sollen Smartphones an Schulen verboten werden?', [
   ('afd', 30,
    'Die Grundschule soll bildschirmfrei bleiben; auch an weiterführenden Schulen wird das Mitführen streng geregelt.',
    'Die AfD will die Grundschule bildschirmfrei halten, dazu gehört auch ein Verbot der Verwendung von Smartphones. Auch an den weiterführenden Schulen werden wir das Mitführen von Smartphones restriktiver handhaben, damit die Aufmerksamkeit im Unterricht und die sozial-emotionale Entwicklung der Schüler nicht beeinträchtigt werden.',
    'Auch an den weiterführenden Schulen werden wir das Mitführen von Smartphones restriktiver handhaben',
   ),
   ('bsw', 2,
    'Smartphones und Tablets sollen aus den Grundschulklassen verschwinden; Lesen und Rechnen stehen im Vordergrund.',
    '[…] dass […] in den Grundschulen wieder das Erlernen der Kernkompetenzen Lesen, Schreiben und Rechnen im Vordergrund steht. Smartphones und Tablets, die den Wissenserwerb nachweislich erschweren, wollen wir aus den Klassenzimmern der Grundschulen verbannen.',
    'wollen wir aus den Klassenzimmern der Grundschulen verbannen',
   ),
   ('fdp', 17,
    'Generelle Verbote durch Land oder Bezirk werden abgelehnt; jede Schule soll eigene Regeln festlegen.',
    'Generelle Verbote der Nutzung von Smartphones in Schulen auf Landes- oder Bezirksebene lehnen wir ab. Im Rahmen der Schulautonomie sollen schulindividuelle Regeln für den Smartphone-Gebrauch möglich bleiben.',
    'Generelle Verbote der Nutzung von Smartphones in Schulen auf Landes- oder Bezirksebene lehnen wir ab',
   ),
   ('gruene', 190,
    'Die private Handynutzung soll dort eingeschränkt werden, wo die Schule selbst das für die beste Lösung hält.',
    'Wir teilen die Sorgen über den steigenden Medienkonsum von Kindern und Jugendlichen. Deshalb unterstützen wir Einschränkungen der privaten Handynutzung, wo diese von der jeweiligen Schule für die beste Lösung gehalten werden.',
    'Deshalb unterstützen wir Einschränkungen der privaten Handynutzung',
   ),
 ]),
 'zuwanderung': ('Soll Berlin die Bezahlkarte für Geflüchtete nutzen?', [
   ('cdu', 25,
    'Die Bezahlkarte soll dauerhaft kommen; Asylbewerber sollen bis zur Entscheidung zentral untergebracht werden.',
    'Asylbewerber und illegal Eingereiste sollen deshalb vom ersten Tag bis zur Entscheidung über ihren Asylantrag in zentralen Einrichtungen untergebracht werden. Wir stehen zur Einführung der Bezahlkarte und wollen diese dauerhaft etablieren.',
    'Wir stehen zur Einführung der Bezahlkarte und wollen diese dauerhaft etablieren',
   ),
   ('fdp', 96,
    'Die Bezahlkarte soll unverzüglich eingeführt werden, für neu Ankommende wie für bereits hier Lebende.',
    'Berlin führt – als letztes Bundesland – unverzüglich die Bezahlkarte für Geflüchtete ein. Diese gilt sowohl für neu ankommende Geflüchtete als auch für Bestandsfälle.',
    'Diese gilt sowohl für neu ankommende Geflüchtete als auch für Bestandsfälle',
   ),
   ('linke', 278,
    'Die Bezahlkarte soll nicht kommen oder wieder verschwinden; EU-Bürger sollen Zugang zur Sozialhilfe haben.',
    'Nicht-erwerbstätige Unionsbürger*innen brauchen Zugang zur Sozialhilfe. Außerdem werden wir die diskriminierende Bezahlkarte nicht einführen bzw. wieder abschaffen.',
    'Außerdem werden wir die diskriminierende Bezahlkarte nicht einführen',
   ),
   ('spd', 53,
    'Die Bezahlkarte wird abgelehnt, weil sie Teilhabe einschränkt; stattdessen soll eine Stadtkarte kommen.',
    'Eine Bezahlkarte für Geflüchtete lehnen wir ab. Sie schränkt Teilhabe am öffentlichen Leben stark ein. Stattdessen setzen wir uns im Bund für die Voraussetzungen einer Berliner Stadtkarte (CityID).',
    'Eine Bezahlkarte für Geflüchtete lehnen wir ab',
   ),
 ]),
 'wirtschaft': ('Soll Berlin ein eigenes Vergabegesetz behalten?', [
   ('afd', 47,
    'Das Berliner Vergabegesetz soll aufgehoben und entbehrliche Vorschriften sollen gestrichen werden.',
    'Mit einem Sonderausschuss „Bürokratieabbau“ ist eine effektive Systematik zum Abbau des Bürokratiedschungels zu entwickeln und zu begleiten. Die Verwaltung ist aufgefordert, entbehrliche Gesetze und Verordnungen zur Streichung anzumelden. Der Berliner Sonderweg eines eigenen Vergabegesetzes ist aufzugeben.',
    'Der Berliner Sonderweg eines eigenen Vergabegesetzes ist aufzugeben',
   ),
   ('fdp', 20,
    'Das Berliner Vergabegesetz soll abgeschafft werden; es gilt nur noch das Vergaberecht von Bund und EU.',
    'Das Berliner Vergabegesetz werden wir abschaffen und nur noch das Vergaberecht des Bundes (bzw. der EU) anwenden. Die unternehmerischen Berichtspflichten wollen wir reduzieren.',
    'Das Berliner Vergabegesetz werden wir abschaffen',
   ),
   ('gruene', 96,
    'Das Vergaberecht soll einfacher werden, Tariftreue und soziale Standards aber uneingeschränkt bleiben.',
    'Deshalb wollen wir das Vergaberecht reformieren – unter Beibehaltung sozialer und ökologischer Standards sowie deren wirksamer Umsetzung und Kontrolle […]. Vereinfachte Verfahren, eine Flexibilisierung der Wertgrenzen bei uneingeschränkter Tariftreue und Mindestlohnregelung, eine Innovationsklausel und vereinfachte Eignungsprüfungen sowie eine stärkere Aufteilung von Losen erleichtern dabei insbesondere KMU und Start-ups den Zugang […]',
    'Deshalb wollen wir das Vergaberecht reformieren',
   ),
   ('spd', 9,
    'Tariftreue und Vergabemindestlohn sollen strenger durchgesetzt werden, um Lohndumping zu verhindern.',
    'Berlin setzt mit dem Vergabe- und Landesmindestlohn schon jetzt Maßstäbe für faire Bezahlung im öffentlichen Auftragswesen. Wir verschärfen die Durchsetzung von Tariftreue und Vergabemindestlohn, um Lohndumping zu verhindern und öffentliche Gelder konsequent an soziale Standards zu binden. Auch Förderungen des Landes Berlin werden wir an Tarifbindung und Mitbestimmung koppeln.',
    'Wir verschärfen die Durchsetzung von Tariftreue und Vergabemindestlohn',
   ),
 ]),
}

DRITTE.update({
 'sicherheit': ('Sollen Waffen- und Messerverbotszonen bestehen bleiben?', [
   ('afd', 15,
    'Messerverbotszonen gelten als Symbolpolitik; stattdessen härtere Strafen und mehr anlasslose Kontrollen.',
    'Die Verschärfung des Strafrahmens der gefährlichen Körperverletzung bei Angriffen mit Messern, Schnellverfahren bei Messerdelikten, zügige Abschiebung ausländischer Messerstraftäter sowie die Ausweitung anlassloser Kontrollen an kriminalitätsbelasteten Orten. Messerverbotszonen lehnen wir als reine Symbolpolitik ab.',
    'Messerverbotszonen lehnen wir als reine Symbolpolitik ab',
   ),
   ('gruene', 228,
    'Kriminalitätsbelastete Orte und Verbotszonen sollen überprüft und wo nötig wieder abgeschafft werden.',
    'Wir werden die bestehenden kriminalitätsbelasteten Orte und Messer- und Waffenverbotszonen auf ihre Sinnhaftigkeit überprüfen und werden sie, wo erforderlich, wieder abschaffen.',
    'Messer- und Waffenverbotszonen auf ihre Sinnhaftigkeit überprüfen',
   ),
   ('spd', 30,
    'Verbotszonen sollen die Ausnahme bleiben; verdachtsunabhängige Kontrollen werden aufs Nötige beschränkt.',
    'Verdachtsunabhängige Kontrollen wollen wir räumlich und in ihrem Anwendungsbereich auf das notwendige Minimum beschränken. Waffen- und Messerverbotszonen sollen die Ausnahme bleiben.',
    'Waffen- und Messerverbotszonen sollen die Ausnahme bleiben',
   ),
   ('linke', 288,
    'Anlasslose Kontrollen an belasteten Orten gelten als personalintensiv und oft nicht zielführend.',
    '[…] Aufrüstung der Polizei wollen wir stoppen und die Mittel umverteilen. Polizeieinsätze z. B. bei Demos, anlasslosen Kontrollen an KBOs und Waffenverbotszonen oder Fußballspielen sind personalintensiv und oft nicht zielführend.',
    'anlasslosen Kontrollen an KBOs und Waffenverbotszonen',
   ),
 ]),
 'verwaltung': ('Wie offen sollen Daten und Unterlagen der Verwaltung sein?', [
   ('linke', 257,
    'Ein Transparenzgesetz soll Veröffentlichungspflichten mit Fristen bringen, maschinenlesbar statt als Scan.',
    'Transparenz ist Voraussetzung demokratischer Kontrolle, sie entsteht jedoch nicht allein durch politische Absichtserklärungen. Ein Transparenzgesetz für Berlin muss konkrete Veröffentlichungspflichten, verbindliche Fristen und maschinenlesbare Formate vorsehen. Informationen dürfen nicht nur als gescannte Dokumente bereitgestellt werden, sondern müssen strukturiert, durchsuchbar und technisch weiterverarbeitbar sein.',
    'Ein Transparenzgesetz für Berlin muss konkrete Veröffentlichungspflichten',
   ),
   ('spd', 62,
    'Alle nicht sensiblen Verwaltungsdaten sollen öffentlich und über ein zentrales Portal in Echtzeit abrufbar sein.',
    'Deshalb gilt für Daten das Prinzip „Open by default“. Alle nichtsensiblen Verwaltungsdaten sollen grundsätzlich öffentlich sein. Daten zur kritischen Infrastruktur bedürfen eines besonderen Schutzes. Wir streben ein umfassendes Transparenzgesetz und ein zentrales Transparenzportal an. In einem übersichtlichen Dashboard sollen Daten in Echtzeit abrufbar sein.',
    'Wir streben ein umfassendes Transparenzgesetz und ein zentrales Transparenzportal an',
   ),
   ('cdu', 14,
    'Offenlegungspflichten sollen überprüft werden, damit Transparenzregeln keine Baupläne für Sabotage liefern.',
    'Informationsfreiheits-, Transparenz- und Open-Data-Regelungen dürfen keine Baupläne für Sabotage liefern. Sensible Informationen über Lage, Aufbau oder Schwachstellen kritischer Infrastruktur müssen wirksam geschützt werden. Offenlegungspflichten werden wir dort überprüfen und anpassen […]',
    'dürfen keine Baupläne für Sabotage liefern',
   ),
 ]),
 'gesundheit': ('Wie soll Berlin mit Drogen und Drogenkonsum umgehen?', [
   ('cdu', 11,
    'Drogenkriminalität soll mit aller Härte bekämpft werden; ein anonymes Hinweisgebersystem soll Meldungen erleichtern.',
    'Drogenkriminalität werden wir in unserer Stadt mit aller Härte bekämpfen. Clanstrukturen und Drogennetzwerke müssen konsequent zerschlagen werden. Dafür braucht die Polizei noch bessere Möglichkeiten zur Informationsgewinnung. Deshalb wollen wir ein anonymes elektronisches Hinweisgebersystem bei der Polizei Berlin einführen, über das Hinweise zu Drogenhandel und Organisierter Kriminalität sicher und vertraulich gemeldet werden können.',
    'Drogenkriminalität werden wir in unserer Stadt mit aller Härte bekämpfen',
   ),
   ('spd', 51,
    'Drogenkonsumräume sollen ausgebaut werden; Abhängige sollen nicht vertrieben, Parks aber drogenfrei werden.',
    'Wir vertreiben drogenabhängige Menschen nicht von Ort zu Ort. Wir helfen dort, wo sie sind. Gleichzeitig holen wir Drogen aus dem öffentlichen Raum. Parks und Spielplätze müssen geschützt bleiben. Drogenkonsumräume bauen wir aus. Wir erleichtern ihre Einrichtung, erweitern Öffnungszeiten und stellen Landesgebäude bereit.',
    'Drogenkonsumräume bauen wir aus',
   ),
   ('bsw', 12,
    'Die Prävention soll ausgeweitet werden, dazu geschützte Konsumräume und mehr Substitutionstherapien.',
    'Wir setzen uns dafür ein, Maßnahmen zur Drogenprävention auszuweiten. Aufgrund der steigenden Zahl von Drogenkranken sollten Hilfsangebote wie geschützte Drogenkonsumräume, medizinische Betreuungseinrichtungen oder die Unterstützung bei Substitutionstherapien ausgeweitet werden.',
    'Maßnahmen zur Drogenprävention auszuweiten',
   ),
   ('fdp', 118,
    'Drug-Checking soll deutlich ausgebaut werden, auch mobil und mit einem berlinweiten Frühwarnsystem.',
    'Drug-Checking ist eine zentrale Maßnahme zur Schadensminderung, die den sicheren Konsum fördert und potenzielle Gesundheitsrisiken reduziert. […] Wir wollen, dass das Berliner Drug-Checking-Projekt deutlich ausgebaut, auch mobil verfügbar und mit einem berlinweiten Frühwarnsystem für gefährliche Wirkstoffe verbunden wird.',
    'Drug-Checking-Projekt deutlich ausgebaut',
   ),
 ]),
 'klima': ('Wie sollen Böden und Regenwasser in Berlin geschützt werden?', [
   ('linke', 202,
    'Bis 2030 soll unter dem Strich keine Fläche mehr versiegelt werden; für Neubau wird anderswo entsiegelt.',
    'Boden ist ein Gemeingut. Wir treten für eine Netto-Null-Versiegelung bis 2030 ein. Wo versiegelt wird, muss innerhalb Berlins in gleicher Größe entsiegelt werden. Das Entsiegelungsprogramm wird in der nächsten Wahlperiode konsequent umgesetzt.',
    'Wir treten für eine Netto-Null-Versiegelung bis 2030 ein',
   ),
   ('afd', 80,
    'Der Flächenverbrauch soll sinken: ungenutzte Flächen bebauen, andere entsiegeln, damit Regen versickert.',
    'Wir wollen den Flächenverbrauch konsequent reduzieren und naturnahe Flächen bewahren. Sowohl ungenutzte Naturflächen als auch teilweise versiegelte Flächen müssen gezielt erfasst werden. Manche Flächen können sinnvoll bebaut werden, andere sollen durch Entsiegelung wieder naturnah hergestellt werden, damit Regenwasser versickern kann und städtische Lebensräume ökologisch aufgewertet werden.',
    'Manche Flächen können sinnvoll bebaut werden',
   ),
   ('fdp', 87,
    'Berlin soll als Schwammstadt Regenwasser nutzen, erreicht mit privatem Kapital und Anreizen statt Verboten.',
    'Wir wollen eine Stadt, die Regenwasser als Ressource nutzt, deren Gewässer Badequalität haben, die als Schwammstadt Starkregen bewältigt. Aber all das erreichen wir nicht durch Verbote, sondern durch die Mobilisierung privaten Kapitals und durch marktwirtschaftliche Anreize.',
    'nicht durch Verbote, sondern durch die Mobilisierung privaten Kapitals',
   ),
 ]),
})

for _t in THEMEN:
    if _t[0] in DRITTE:
        _t[3].append(DRITTE[_t[0]])


# Vierte Fragen (gezielt, September 2026): nur Parteien, die im Thema bisher
# einmal auftreten - haelt die Ausgewogenheit und hebt seltene Paarungen.
VIERTE = {
 'klima': ('Wie soll Berlin vor Hitze geschützt werden?', [
   ('cdu', 80,
    'Der Bestand an Straßenbäumen soll bis 2040 auf eine Million wachsen, mit gesicherter Finanzierung.',
    'Wir wollen den Bestand an Straßenbäumen deutlich erhöhen und bis zum Jahr 2040 auf eine Million Bäume steigern, um Berlin widerstandsfähiger gegen Hitze und Extremwetter zu machen. Dabei setzen wir auf realistische Ziele für Baumbepflanzungen, eine Einbindung der Bezirke sowie verlässliche Finanzierungsmöglichkeiten für die Klimaanpassung.',
    'bis zum Jahr 2040 auf eine Million Bäume steigern',
   ),
   ('gruene', 21,
    'In belasteten Vierteln sollen Klimainseln mit Schatten und Wasser entstehen, dazu mehr Trinkbrunnen.',
    '[…] durch deutlich mehr Trinkwasserbrunnen […]. In besonders belasteten Quartieren schaffen wir Klimainseln, die mit Schatten, Wasser und Sitzgelegenheiten für sofortige Abkühlung sorgen. […] Wir wollen den Berliner Hitzeaktionsplan jährlich evaluieren und weiterentwickeln.',
    'Hitzeaktionsplan jährlich evaluieren und weiterentwickeln',
   ),
   ('bsw', 56,
    'Neubauten sollen verbindlich begrünte Dächer und Höfe bekommen, dazu eine finanzierte Baumoffensive.',
    'Verbindliche Begrünungspflichten für Neubauten: begrünte Dächer, Fassaden und Innenhöfe sollen die Regel sein. […] Wir wollen, dass aus diesen Beschlüssen echte Baumoffensiven werden. Dazu gehören eine verlässliche Finanzierung im Haushalt und klare Priorität für Neupflanzungen und Pflege.',
    'Verbindliche Begrünungspflichten für Neubauten',
   ),
 ]),
}

for _t in THEMEN:
    if _t[0] in VIERTE:
        _t[3].append(VIERTE[_t[0]])
