# -*- coding: utf-8 -*-
"""Datensatz Abgeordnetenhauswahl Berlin 2026. Alle Aussagen aus den PDFs."""

WAHL = {
    "id": "agh-be-2026",
    "name": "Abgeordnetenhauswahl Berlin",
    "region": "Berlin",
    "wahltag": "2026-09-20",
    "kuerzel": "be",
}

PROGRAMME = {
    "cdu": ("Der Anfang ist gemacht. Regierungsprogramm 2026–2031",
            "https://berlin-wird.de/image/uploads/data/regierungsprogramm2026_2031.pdf"),
    "spd": ("Wahlprogramm zur Abgeordnetenhauswahl 2026",
            "https://spd.berlin/media/2026/08/SPD_Berlin_Wahlprogramm_20260521-v4-1.pdf"),
    "gruene": ("Politik ändern. Berlin bleiben. Wahlprogramm zur Abgeordnetenhauswahl 2026",
               "https://gruene.berlin/fileadmin/BE/lv_berlin/files/Wahlprogramm_2026_Online.pdf"),
    "fdp": ("Berlin geht besser. Wahlprogramm zur Abgeordnetenhauswahl 2026",
            "https://www.fdp-berlin.de/sites/default/files/2026-07/Wahlprogramm_FDP%20Berlin_Abgeordnetenhauswahl%202026_FINAL.pdf"),
    "afd": ("Berlin. Stark. Machen. Programm für die Wahlen am 20. September 2026",
            "https://lichtenberg.afd.berlin/wp-content/uploads/2026/07/AfD-WK-Berlin-Wahlprogramm-Webversion.pdf"),
    "linke": ("Berlin machen bezahlbar. Wahlprogramm zur Abgeordnetenhauswahl 2026",
              "https://dielinke.berlin/fileadmin/download/2026/Wahlprogramm_AGH_2026_Die_Linke_Berlin.pdf"),
    "bsw": ("Berlin – Mit uns endlich vernünftig und gerecht. Wahlprogramm zur AGH-Wahl 2026",
            "https://bsw.berlin/wp-content/uploads/Wahlprogramm-BSW-Berlin-AGH-Wahl-2026.pdf"),
}

# (themaId, Titel, Beschreibung, [(Fragetext, [Aussagen])])
# Aussage: (parteiId, seite, kurz, original, markierung)
# Regeln: 3-4 Aussagen je Frage, jede Partei je Thema genau einmal,
# alle Aussagen einer Frage beantworten dieselbe Unterfrage.
THEMEN = [
 ('wohnen', 'Wohnen und Mieten',
  'Mietregulierung, Neubau, landeseigene Wohnungsunternehmen.', [
  ('Wie stark soll der Staat in den Mietmarkt eingreifen?', [
   ('cdu', 30,
    'Forderungen nach Enteignungen oder einem Mietendeckel wird eine klare Absage erteilt. Solche Eingriffe seien keine Lösung, sondern verschärften die Lage am Wohnungsmarkt. Stattdessen sollen Mieterinnen und Mieter ihre Rechte einfacher geltend machen können.',
    'Populistischen Forderungen nach Enteignungen oder der Einführung eines Mietendeckels erteilen wir eine klare Absage. Solche Eingriffe sind keine Lösung für den angespannten Wohnungsmarkt, sondern verschärfen die Situation.',
    'Populistischen Forderungen nach Enteignungen oder der Einführung eines Mietendeckels erteilen wir eine klare Absage',
   ),
   ('linke', 7,
    'Für die kommunalen Wohnungen soll ein Mietendeckel durchgesetzt werden. Ein Landesamt für Mieterschutz soll Verstöße ahnden und Recht durchsetzen. Die landeseigenen Wohnungen müssen bezahlbar bleiben.',
    'Unsere kommunalen Wohnungen müssen bezahlbar bleiben. Deshalb werden wir dort einen Mietendeckel durchsetzen. Mit unserem Landesamt für Mieterschutz schaffen wir eine handlungsfähige Behörde, die Verstöße ahndet und Recht durchsetzt.',
    'Deshalb werden wir dort einen Mietendeckel durchsetzen',
   ),
   ('bsw', 2,
    'Die bestehenden Instrumente der Mietenregulierung sollen geschärft und konsequent durchgesetzt werden. Über eine Bundesratsinitiative soll zusätzlich ein Mietendeckel eingeführt werden. Berlin brauche mehr Wohnungen in öffentlicher Hand und gemeinnütziger Bewirtschaftung.',
    'Wir wollen die bestehenden Instrumente der Mietenregulierung schärfen und endlich konsequent durchsetzen und zusätzlich über eine Bundesratsinitiative einen Mietendeckel einführen. Berlin braucht mehr Wohnungen in öffentlicher Hand und in gemeinnütziger Bewirtschaftung.',
    'zusätzlich über eine Bundesratsinitiative einen Mietendeckel einführen',
   ),
  ]),
  ('Wie soll mit Milieuschutz- und Sanierungsgebieten umgegangen werden?', [
   ('spd', 20,
    'Bei An- und Ummeldungen soll über Mietpreisbremse und Mietwucher informiert und auf kostenlose Beratung verwiesen werden. Die Schutzregeln in Milieuschutzgebieten sollen erklärt werden. Milieuschutzgebiete sollen ausgeweitet werden.',
    'Bei An- und Ummeldungen informieren wir über Mietpreisbremse und Mietwucher, verweisen auf kostenlose Beratung in den Bezirken und erklären Schutzregeln in Milieuschutzgebieten. Wir setzen uns für die Ausweitung von Milieuschutzgebieten ein.',
    'Wir setzen uns für die Ausweitung von Milieuschutzgebieten ein',
   ),
   ('gruene', 16,
    'Das Land soll insbesondere in Milieuschutzgebieten ambitionierte Sanierungen fördern und Eigentümer beraten. Mieterinnen und Mieter in unsanierten Häusern dürfen den Kostensteigerungen fossiler Brennstoffe nicht ungeschützt ausgesetzt sein. In allen Bezirken soll eine starke unabhängige Beratung entstehen.',
    'Mieter*innen in unsanierten Häusern dürfen den Kostensteigerungen fossiler Brennstoffe nicht ungeschützt ausgesetzt werden. Das Land Berlin soll insbesondere in Milieuschutzgebieten ambitionierte Sanierungen fördern und Gebäudeeigentümer entsprechend beraten.',
    'Das Land Berlin soll insbesondere in Milieuschutzgebieten ambitionierte Sanierun gen fördern',
   ),
   ('fdp', 38,
    'Das öffentliche Vorkaufsrecht soll in Sanierungs- und Milieuschutzgebieten außer für öffentliche Infrastruktur nicht mehr ausgeübt werden. Die landeseigenen Wohnungsbaugesellschaften sollen Wohnraum für von Wohnungslosigkeit bedrohte Menschen bereitstellen. Reine Mieter-Neubauquartiere am Stadtrand werden abgelehnt.',
    'Die landeseigenen WBG sollen aus ihren Beständen auch Wohnraum für von Wohnungslosigkeit bedrohte Menschen zur Verfügung stellen. In Sanierungs- und Milieuschutzgebieten soll das öffentliche Vorkaufsrecht, außer für öffentliche Infrastruktur, nicht mehr ausgeübt werden.',
    'In Sanierungs- und Milieuschutzgebieten soll das öffentliche Vorkaufsrecht, außer für öffentliche Infrastruktur, nicht mehr ausgeübt werden',
   ),
   ('afd', 6,
    'Die Fehlbelegungsabgabe soll wieder eingeführt und die Untervermietung von Sozialwohnungen generell verboten werden. Die Ausweisung von Milieuschutzgebieten soll begrenzt werden. Ziel ist es, Missbrauch zu verhindern.',
    '[Wir wollen] die Fehlbelegungsabgabe wieder einführen. Um den Missbrauch zu verhindern, setzen wir uns für ein generelles Verbot der Untervermietung von Sozialwohnungen ein. Milieuschutz begrenzen: Die Ausweisung von Wohnvierteln als Milieuschutzgebiete (§ 172 BauGB) […].',
    'wir uns für ein generelles Verbot der Untervermietung von Sozialwohnungen ein',
   ),
  ]),
 ]),
 ('sicherheit', 'Innere Sicherheit',
  'Polizei, Videoüberwachung, Verbotszonen und Kontrolle.', [
  ('Wo und wie soll Videoüberwachung eingesetzt werden?', [
   ('cdu', 6,
    'An bekannten Kriminalitätsschwerpunkten sollen verstärkt Videoüberwachung sowie Waffen- und Messerverbotszonen eingesetzt werden. Als Beleg wird auf die Wache am Kottbusser Tor verwiesen. Die Polizei soll zudem mit Tasern ausgestattet werden.',
    'Genau hinschauen, was passiert, um Kriminelle dingfest zu machen: An bekannten Kriminalitätsschwerpunkten kommen nun verstärkt Videoüberwachung und Waffen- und Messerverbotszonen zum Einsatz. Mit messbarem Erfolg […].',
    'An bekannten Kriminalitätsschwerpunkten kommen nun verstärkt Videoüberwachung und Waffen- und Messerverbotszonen zum Einsatz',
   ),
   ('fdp', 67,
    'An Risikoorten wie Bahnhöfen soll neben temporärer Videoüberwachung mit baulichen Maßnahmen gearbeitet werden. Dazu zählen gute Beleuchtung, offene Sichtachsen und die Vermeidung dunkler Ecken. Security by Design soll berlinweit umgesetzt werden.',
    'Wir möchten Security by Design berlinweit implementieren. An Berliner Risikoorten wie Bahnhöfen oder Drogenumschlagplätzen wollen wir – neben der temporären Videoüberwachung – mit baulichen Maßnahmen wie guter Beleuchtung, offenen Sichtachsen, Verhinderung dunkler Ecken die Sicherheit […] [erhöhen].',
    'neben der temporären Videoüberwachung – mit baulichen Maßnahmen wie guter Beleuchtung',
   ),
   ('afd', 13,
    'Gefordert wird eine vollständige Videoüberwachung in allen Brennpunktbereichen. Mobile Polizeiwachen in Problemvierteln und ein dichteres Netz stationärer Wachen sollen eingeführt werden. Das Landesantidiskriminierungsgesetz soll sofort aufgehoben werden.',
    'Die AfD fordert: → Die sofortige Aufhebung des Landesantidiskriminierungsgesetzes und die Überarbeitung anderer sicherheitsrelevanter Gesetze. → Eine vollständige Videoüberwachung in allen Brennpunktbereichen. → Die Einführung mobiler Polizeiwachen in Problemvierteln.',
    'Eine vollständige Videoüberwachung in allen Brennpunktbereichen',
   ),
   ('bsw', 41,
    'Videoüberwachung soll an nachweislich besonders kriminalitätsbelasteten Orten eingesetzt werden. Nötig seien dafür eine parlamentarische Genehmigung und eine Echtzeit-Auswertung durch ausreichend Personal. Kriminalität und Gewalt müsse wirksam entgegengetreten werden.',
    'Kriminalität und Gewalt muss wirksam entgegengetreten werden, damit sich alle Bürger unserer Stadt sicher fühlen können. Dazu setzen wir Videoüberwachung an nachweislich besonders kriminalitätsbelasteten Orten ein – mit parlamentarischer Genehmigung und Echtzeit-Auswertung durch ausreichend Personal.',
    'Videoüberwachung an nachweislich besonders kriminalitätsbelasteten Orten ein – mit parlamentarischer Genehmigung',
   ),
  ]),
  ('Wie sollen Polizeibefugnisse und Kriminalitätsorte kontrolliert werden?', [
   ('spd', 31,
    'Die Einstufung kriminalitätsbelasteter Orte soll einer regelmäßigen parlamentarischen Kontrolle unterliegen. Software intransparenter Hersteller wie Palantir wird für Berlin abgelehnt. Die Polizei soll respektvoll handeln und die Vielfalt der Stadt widerspiegeln.',
    '[Wir unterziehen] die Einstufung kriminalitätsbelasteter Orte einer regelmäßigen parlamentarischen Kontrolle. […] Den Einsatz von Software intransparente und datenschutzrechtlich bedenklicher Hersteller wie Palantir lehnen wir für Berlin entschieden [ab].',
    'die Einstufung kriminalitätsbelasteter Orte einer regelmäßigen parlamentarischen Kontrolle',
   ),
   ('gruene', 228,
    'Die bestehenden kriminalitätsbelasteten Orte sowie Messer- und Waffenverbotszonen sollen auf ihre Sinnhaftigkeit überprüft und wo nötig wieder abgeschafft werden. Die Ergebnisse der Bodycam-Studie sollen umgesetzt werden. Ziel sind Transparenz und Nachvollziehbarkeit polizeilichen Handelns.',
    'Wir werden die bestehenden kriminalitätsbelasteten Orte und Messer- und Waffenverbotszonen auf ihre Sinnhaftigkeit überprüfen und werden sie, wo erforderlich, wieder abschaffen. Die Ergebnisse der Bodycam-Studie wollen wir umsetzen.',
    'Messer- und Waffenverbotszonen auf ihre Sinnhaftigkeit überprüfen und werden sie, wo erforderlich, wieder abschaffen',
   ),
   ('linke', 288,
    'Die Aufrüstung der Polizei soll gestoppt und die Mittel umverteilt werden. Einsätze bei Demonstrationen, anlasslose Kontrollen und Waffenverbotszonen gelten als personalintensiv und oft nicht zielführend. Geprüft werden soll, den Personalbestand auf das Niveau anderer Städte zu bringen.',
    'Aufrüstung der Polizei wollen wir stoppen und die Mittel umverteilen. Polizeieinsätze z. B. bei Demos, anlasslosen Kontrollen an KBOs und Waffenverbotszonen oder Fußballspielen sind personalintensiv und oft nicht zielführend.',
    'Aufrüstung der Polizei wollen wir stoppen und die Mittel umverteilen',
   ),
  ]),
 ]),
 ('verkehr', 'Verkehr und Mobilität',
  'Rad, Auto, Bus und Bahn im Stadtverkehr.', [
  ('Welcher Verkehrsart soll in der Stadt Vorrang eingeräumt werden?', [
   ('gruene', 81,
    'Man soll kein Auto besitzen müssen, um mobil zu sein; alle sollen sich frei und unabhängig bewegen können. Für Handwerk, Lieferverkehr und Menschen mit Mobilitätseinschränkungen soll es mehr reservierte Park- und Lieferbereiche geben. Schulzonen und sichere Schulwege sollen entstehen.',
    '[Wir schaffen] Schulzonen und sichere Schulwege von der Haustür bis zum Schuleingang und gestalten lebenswerte Kieze, in denen man entspannt zu Fuß gehen kann. […] Man muss kein Auto mehr besitzen, um mobil zu sein – alle können sich frei und unabhängig bewegen. Und für die, die auf ein Auto angewiesen sind – beispielsweise Handwerker*innen, Lieferverkehr oder Menschen mit Mobilitätseinschränkungen –, gibt es mehr reservierte Parkplätze wie Lieferbereiche und Behindertenparkplätze.',
    'Man muss kein Auto mehr besitzen, um mobil zu sein',
   ),
   ('afd', 42,
    'Der motorisierte Individualverkehr bleibt aus Sicht der Partei unverzichtbarer Bestandteil urbaner Mobilität. Gefordert werden Zugangsbeschränkungen für Personen ohne Fahrschein im Nahverkehr. Der Regionalverkehr soll besser in das Gesamtnetz eingebunden werden.',
    '→ Zugangsbeschränkungen für Personen ohne Fahrschein. → Eine bessere Einbindung des Regionalverkehrs in das Gesamtnetz. Für diskriminierungsfreien Autoverkehr: Der motorisierte Individualverkehr bleibt für uns auch in Zukunft ein unverzichtbarer Bestandteil urbaner Mobilität.',
    'Der motorisierte Individualverkehr bleibt für uns auch in Zukunft ein unverzichtbarer Bestandteil urbaner Mobilität',
   ),
   ('linke', 55,
    'Priorität hat ein überzeugendes Angebot im öffentlichen Nahverkehr. Hinzu kommen der Ausbau eines umfassenden Radwegenetzes und barrierefreier Gehwege. So soll allen eine kostengünstige Mobilität ermöglicht werden.',
    'Unsere Priorität liegt daher auf einem überzeugenden Angebot im öffentlichen Personennahverkehr (ÖPNV) sowie dem Ausbau eines umfassenden Radwegenetzes und von barrierefreien Gehwegen. So ermöglichen wir allen eine kostengünstige Mobilität.',
    'Unsere Priorität liegt daher auf einem überzeugenden Angebot im öffentlichen Personennahverkehr',
   ),
   ('bsw', 48,
    'Gefordert wird kein Gegeneinander von Auto, Fahrrad und Nahverkehr, sondern ein vernünftiges Miteinander. Sichere Fußwege, ein starker Nahverkehr, ein verlässliches Radwegenetz und gute Bedingungen für den Autoverkehr gehören zusammen. Besonders benannt werden Außenbezirke, Schichtarbeit und Handwerk.',
    '[Wir wollen kein Gegeneinander] zwischen Auto, Fahrrad und öffentlichem Nahverkehr, sondern ein vernünftiges Miteinander. Sichere Wege für Fußgänger, ein starker Nahverkehr, ein verlässliches Radwegenetz und gute Bedingungen für den motorisierten Individualverkehr gehören zusammen.',
    'ein verlässliches Radwegenetz und gute Bedingungen für den motorisierten Individualverkehr gehören zusammen',
   ),
  ]),
  ('Worin soll beim Verkehr zuerst investiert werden?', [
   ('cdu', 71,
    'Das Radwegenetz soll gezielt verbessert und bedarfsgerecht ausgebaut werden. Vorrang haben Sanierung und Ertüchtigung bestehender Wege. Sharing-Fahrzeuge sollen nur noch an fest definierten Abstellanlagen abgestellt werden dürfen.',
    'Mit dem Rad durch die Stadt: Das Berliner Radwegenetz werden wir gezielt verbessern und bedarfsgerecht ausbauen. Vorrang hat für uns die Sanierung und Ertüchtigung bestehender Wege.',
    'Das Berliner Radwegenetz werden wir gezielt verbessern und bedarfsgerecht ausbauen. Vorrang hat für uns die Sanierung',
   ),
   ('spd', 24,
    'Der Ausbau der Straßenbahn soll in allen Bezirken vorangetrieben werden. Die Elektrifizierung des Busverkehrs wird fortgesetzt und senkt zugleich den Lärm. Laufende Projekte sollen weiter finanziert werden.',
    'Die Elektrifizierung des Busverkehrs setzen wir fort und senken damit zugleich den Lärm in der Stadt. Wir treiben den Ausbau der Straßenbahn in allen Bezirken voran, finanzieren laufende Projekte […].',
    'Wir treiben den Ausbau der Straßenbahn in allen Bezirken voran',
   ),
   ('fdp', 55,
    'Bestehende Radwege sollen repariert werden, auch wenn sie nicht der Normbreite entsprechen. Man solle nicht zehn Jahre auf ein Verkehrskonzept und dessen Umsetzung warten. Eine bessere Anbindung von Außenbezirken und Umland soll den Wohnungsmarkt entlasten.',
    'Bestehende Radwege müssen repariert werden, auch wenn sie nicht der „Normbreite“ entsprechen, anstatt zehn Jahre auf ein „Verkehrskonzept“ und dessen Umsetzung zu warten.',
    'Bestehende Radwege müssen repariert werden, auch wenn sie nicht der „Normbreite“ entsprechen',
   ),
  ]),
 ]),
 ('verwaltung', 'Verwaltung und Digitalisierung',
  'Bürgerämter, Verwaltungsreform und digitale Verfahren.', [
  ('Wie weit soll die Verwaltung digitalisiert werden?', [
   ('spd', 11,
    'Der digitale Wirtschaftsservice der Berliner Verwaltung soll umgesetzt und mehr Leistungen digital angeboten werden. Digitalisierungsprojekte sollen schneller in die Umsetzung kommen. Mit digitalen Werkzeugen soll ein modernes Vergaberecht umgesetzt werden.',
    'Wir setzen den DIWI – den digitalen Wirtschaftsservice der Berliner Verwaltung – um und bieten noch mehr Leistungen digital an. Außerdem setzen wir mit digitalen Tools ein modernes Vergaberecht um.',
    'den digitalen Wirtschaftsservice der Berliner Verwaltung – um und bieten noch mehr Leistungen digital an',
   ),
   ('gruene', 71,
    'Die internen Prozesse in den Verwaltungen sollen vollständig digitalisiert werden. Dafür soll übergreifend in allen Verwaltungen die E-Akte eingeführt werden. Zudem soll die Datenkommunikation zwischen den Behörden abgesichert werden.',
    'Um das Angebot unserer Behörden verbessern zu können, müssen wir die internen Prozesse in den Verwaltungen vollständig digitalisieren. Dafür führen wir übergreifend in allen Verwaltungen die E-Akte ein.',
    'Dafür führen wir übergreifend in allen Verwaltungen die E-Akte ein',
   ),
   ('fdp', 21,
    'Bei neuen Gesetzen und Verordnungen sollen alle Verwaltungsvorgänge digitaltauglich umgesetzt werden können. Gelten sollen die Grundsätze „digital only“ und „digital once“. Daten sollen also nur noch einmal an die Verwaltung übermittelt werden.',
    'Bei neuen Gesetzen und Verordnungen oder auch bei Änderungen sorgen wir dafür, dass alle damit verbundenen Verwaltungsvorgänge digitaltauglich umgesetzt werden können. Die Grundsätze „digital only“ und „digital once“ (Übermittlung von Daten nur noch einmal an die Berliner [Verwaltung]) […].',
    'dass alle damit verbundenen Verwaltungsvorgänge digitaltauglich umgesetzt werden können',
   ),
   ('bsw', 62,
    'Verwaltung bedeute auch Dienstleistung und müsse beschleunigt werden. Dafür brauche es eine konsequentere Digitalisierung, Papierakten sollen abgelöst werden. Beförderungen für kontinuierliche Leistung sollen zum Regelfall werden.',
    'Verwaltung modernisieren: Verwaltung bedeutet auch Dienstleistung. Damit diese beschleunigt wird, braucht es eine konsequentere Digitalisierung: Papierakten soll[en] […] [abgelöst werden].',
    'Damit diese beschleunigt wird, braucht es eine konsequentere Digitalisierung',
   ),
  ]),
  ('Worauf soll es bei der Verwaltungsreform jetzt ankommen?', [
   ('cdu', 87,
    'Die Verwaltungsreform soll klare Verantwortung, starke Bezirke und ein Ende des Behörden-Pingpongs bringen. Die Verwaltung soll zuallererst den Bürgern dienen und die Stadt Schritt für Schritt wieder zum Funktionieren bringen.',
    'Mit der großen Verwaltungsreform setzen wir um, woran Vorgängersenate 25 Jahre gescheitert sind: klare Verantwortung, starke Bezirke, kein Behörden-Pingpong mehr. Wir bringen Berlin nach und nach wieder zum Funktionieren – für eine Verwaltung, die zuallererst den Bürgern dient.',
    'klare Verantwortung, starke Bezirke, kein Behörden-Pingpong mehr',
   ),
   ('afd', 96,
    'Investitionen seien insbesondere in Verwaltungsmodernisierung und die Digitalisierung kritischer Systeme erforderlich. Genannt werden zudem Infrastruktur, Sicherheits- und Rettungsdienste sowie der Substanzerhalt öffentlicher Gebäude. Der Investitionsstau der öffentlichen Hand liege bei weit über 100 Milliarden Euro.',
    'Der Investitionsstau der öffentlichen Hand beläuft sich inzwischen auf weit über 100 Mrd. Euro. Investitionen sind erforderlich, insbesondere in: Die Infrastruktur; die Verwaltungsmodernisierung; die Digitalisierung kritischer Systeme; Sicherheits- und Rettungsdienste; Substanzerhalt öffentlicher Gebäude.',
    'die Verwaltungsmodernisierung; die Digitalisierung kritischer Systeme',
   ),
   ('linke', 11,
    'Die Verwaltung soll digitaler und effizienter werden und die Verwaltungsreform mit Leben gefüllt werden. Die Ausgaben für Überwachungskameras sollen reduziert werden. Stattdessen soll in soziale Angebote investiert werden.',
    'Wir reduzieren die Ausgaben für Überwachungskameras und investieren stattdessen in soziale Angebote. Wir müssen unsere Verwaltung digitaler und effizienter machen und die Verwaltungsreform mit Leben füllen.',
    'Wir müssen unsere Verwaltung digitaler und effizienter machen und die Verwaltungsreform mit Leben füllen',
   ),
  ]),
 ]),
 ('schule', 'Schule und Bildung',
  'Schulplätze, Personal, Schulformen und Inklusion.', [
  ('Wie soll die Schule organisiert und gesteuert werden?', [
   ('cdu', 54,
    'Im Rahmen der Schulbauoffensive sind rund 62.000 neue Schulplätze, 41 neue Schulen und 76 Sporthallen entstanden. In den Schulbau soll massiv weiter investiert werden. Ein neues 11. Pflichtschuljahr soll Jugendlichen ohne Ausbildungsplatz eine Perspektive geben.',
    'Das neue 11. Pflichtschuljahr gibt Jugendlichen ohne Ausbildungsplatz eine klare Perspektive. Wir investieren massiv in Berlins Schulbau: Im Rahmen der Schulbauoffensive wurden so rund 62.000 neue Schulplätze, 41 neue Schulen, 119 Ergänzungsbauten und 76 neue Sporthallen entstanden.',
    'Wir investieren massiv in Berlins Schulbau',
   ),
   ('spd', 42,
    'Die Schulbauoffensive soll fortgesetzt werden, nachdem bereits über 50.000 Schulplätze geschaffen wurden. Die Lehrkräftebildung soll über die Schools of Education gestärkt werden. Betont wird eine praxisorientierte Professionalisierung.',
    'In diesem Sinne stärken wir die Schools of Education als zentrale Struktur der Lehrkräftebildung. Die Schulbauoffensive fortsetzen: Seit Beginn der Schulbauoffensive haben wir durch Erweiterungen und Neubauten deutlich über 50.000 Schulplätze geschaffen.',
    'Die Schulbauoffensive fortsetzen',
   ),
   ('fdp', 8,
    'Schulen sollen ihr Personal selbst auswählen und ihre Selbstverwaltung ausbauen können. Lehrkräfte und Schulleitungen sollen von Verwaltungsaufgaben entlastet werden. Schulen sollen schulspezifisch multiprofessionelle Teams bilden dürfen.',
    'Wir wollen die personelle Situation der Schulen bei der Selbstverwaltung weiter verbessern, um Lehrkräfte und die pädagogische Schulleitung von Verwaltungsaufgaben zu entlasten. Im Rahmen ihrer Personalautonomie wollen wir es Schulen außerdem ermöglichen, schulspezifisch multiprofessionelle Teams […] zu bilden.',
    'um Lehrkräfte und die pädagogische Schulleitung von Verwaltungsaufgaben zu entlasten',
   ),
   ('afd', 28,
    'Die Vergabe von 30 Prozent der Schulplätze über das Losverfahren soll abgeschafft werden. Die Aufnahme an weiterführenden Schulen soll sich an Noten, Wohnortnähe und einer Geschwisterkindregelung orientieren. An freiwilligen Aufnahmetests zum Gymnasium wird festgehalten.',
    '[Die Aufnahme an] weiterführenden Schulen muss sich konsequent an den Noten und der Wohnortnähe orientieren sowie eine Geschwisterkindregelung umfassen. Die Vergabe von 30 % der Schulplätze über das Losverfahren werden wir abschaffen.',
    'Die Vergabe von 30 % der Schulplätze über das Losverfahren werden wir abschaffen',
   ),
  ]),
  ('Worauf soll Bildung inhaltlich zielen?', [
   ('gruene', 154,
    'Exkludierende Systeme sollen vollständig abgebaut und Inklusion in allen Schulen ermöglicht werden. Multiprofessionelle Teams und Schulassistenz sollen gleiche Bildungschancen sichern. Hinzu kommen ergänzende Förderung und Betreuung in Grundschulen.',
    'Exkludierende Systeme müssen vollständig abgebaut und Inklusion in allen Schulen möglich gemacht werden. Multiprofessionelle Teams, Schulassistenz sowie ergänzende Förderung und Betreuung in Grundschulen sichern gleiche Bildungschancen.',
    'Exkludierende Systeme müssen vollständig abgebaut und Inklusion in allen Schulen möglich gemacht werden',
   ),
   ('linke', 152,
    'Schülerinnen und Schüler sollen ihren Schulalltag zunehmend selbstbestimmt mitgestalten können. Bildung soll befähigen, Gesellschaft kritisch zu verstehen. Lehrkräfte sollen bestärkt werden, emanzipatorische und partizipative Konzepte anzuwenden.',
    '[…] ihren Schulalltag zunehmend selbstbestimmt mitgestalten können. Bildung soll sie befähigen, Gesellschaft kritisch zu verstehen und solidarisch zu verändern. Lehrkräfte wollen wir bestärken, emanzipatorische und partizipative pädagogische Konzepte anzuwenden.',
    'Lehrkräfte wollen wir bestärken, emanzipatorische und partizipative pädagogische Konzepte anzuwenden',
   ),
   ('bsw', 14,
    'Angestrebt wird eine Rückbesinnung auf verbindliche Inhalte, klare Leistungsstandards und überprüfbare Ergebnisse. Schülerinnen und Schüler sollen wissen, was sie können und was von ihnen erwartet wird. Bildung soll Leistung fordern und fördern.',
    'Wir wollen eine Rückbesinnung auf verbindliche Inhalte, klare Leistungsstandards und überprüfbare Ergebnisse. Schülerinnen und Schüler sollen wissen, was sie können – und was von ihnen erwartet wird. Bildung bedeutet für uns, Leistung zu fordern und zu fördern, soziales Verhalten zu stärken und junge Menschen auf ein selbstbestimmtes, beruflich tragfähiges Leben vorzubereiten.',
    'eine Rückbesinnung auf verbindliche Inhalte, klare Leistungsstandards',
   ),
  ]),
 ]),
 ('zuwanderung', 'Zuwanderung und Integration',
  'Aufnahme, Rückführung, Einbürgerung und Arbeitsmarkt.', [
  ('Wie konsequent soll Zuwanderung begrenzt werden?', [
   ('cdu', 25,
    'Rückführungen sollen ganzjährig durchgeführt werden, auch in den Wintermonaten. Ausreisegewahrsam und Abschiebungshaft sollen stärker genutzt und die Kapazitäten des Ausreisegewahrsams deutlich erweitert werden.',
    '[Wir wollen Rückführungen] ganzjährig durchzuführen, auch in den Wintermonaten. Um Rückführungen wirksam durchzusetzen, sind die bestehenden Instrumente des Ausreisegewahrsams und der Abschiebungshaft stärker zu nutzen. Dazu wollen wir die Kapazitäten des Ausreisegewahrsams deutlich erweitern.',
    'die Kapazitäten des Ausreisegewahrsams deutlich erweitern',
   ),
   ('fdp', 95,
    'Irreguläre Migration soll unterbunden werden, wer legal komme, erhalte echte Chancen. Sprach- und Integrationskurse soll es vom ersten Tag an geben. Vermittelt werden sollen die freiheitlich-demokratische Grundordnung und der Respekt vor Gleichberechtigung.',
    'Irreguläre Migration muss unterbunden werden, wer legal kommt, erhält echte Chancen. Integration fordert alle Beteiligten: Sprach- und Integrationskurse vom ersten Tag an, die Vermittlung unserer freiheitlich-demokratischen Grundordnung, den Respekt vor Gleichberechtigung.',
    'Irreguläre Migration muss unterbunden werden, wer legal kommt, erhält echte Chancen',
   ),
   ('afd', 14,
    'Bei der Ausländerbehörde soll eine Sondereinheit eingerichtet werden. Diese soll die Ausweisung und Abschiebung ausländischer Krimineller betreiben. Die Maßnahmen richten sich zudem gegen Strukturen der organisierten Kriminalität.',
    'Die AfD fordert: → Die Einrichtung einer Sondereinheit bei der Ausländerbehörde, die die Ausweisung und Abschiebung ausländischer Krimineller [betreibt].',
    'Die Einrichtung einer Sondereinheit bei der Ausländerbehörde',
   ),
   ('bsw', 34,
    'Wer keinen Anspruch auf Asyl habe, dürfe gar nicht erst in die EU einreisen. Dann komme es auch nicht mehr zu Schwierigkeiten bei einer Abschiebung. Die notwendigen Regelungen sollen in Deutschland zügig umgesetzt werden, damit Zuwanderung regelbasiert stattfindet.',
    'Wer keinen Anspruch auf Asyl hat, darf gar nicht erst in die Europäische Union einreisen und es kann somit auch nicht mehr zu Schwierigkeiten bei einer Abschiebung kommen. Wir fordern, dass die notwendigen Regelungen in Deutschland nun zügig umzusetzen sind, damit Zuwanderung künftig regelbasiert stattfindet.',
    'Wer keinen Anspruch auf Asyl hat, darf gar nicht erst in die Europäische Union einreisen',
   ),
  ]),
  ('Wie soll die Integration derer gelingen, die hier sind?', [
   ('spd', 52,
    'Die Anstrengungen zur Integration in den Arbeitsmarkt sollen weiter gestärkt werden, damit Menschen schnell selbst ihren Lebensunterhalt verdienen. Über Einbürgerung soll Teilhabe ermöglicht werden. Alle Berlinerinnen und Berliner sollen demokratisch mitbestimmen können.',
    '[…] schnell selbst ihren Lebensunterhalt verdienen können. Deshalb stärken wir Berlins Anstrengungen zur Integration in den Arbeitsmarkt weiter. Teilhabe durch Einbürgerung: Wir wollen, dass alle Berlinerinnen und Berliner demokratisch mitbestimmen.',
    'Deshalb stärken wir Berlins Anstrengungen zur Integration in den Arbeitsmarkt weiter',
   ),
   ('gruene', 112,
    'Betroffene sollen durch Rechtsberatung und aufenthaltsrechtliche Absicherung unterstützt werden, ihre Rechte ohne Angst vor Abschiebung wahrzunehmen. Dafür brauche es ausreichend Personal. Die Kernarbeitsnormen der Internationalen Arbeitsorganisation sollen beachtet werden.',
    '[Mit] Rechtsberatung und aufenthaltsrechtlicher Absicherung unterstützen wir Betroffene dabei, ihre Rechte wahrzunehmen und Rechtsverfahren durchzustehen – ohne Angst vor Abschiebung. Dazu gehört auch eine ausreichende Zahl an Mitarbeiter*innen.',
    'ihre Rechte wahrzunehmen und Rechtsverfahren durchzustehen – ohne Angst vor Abschiebung',
   ),
   ('linke', 105,
    'Berufsbegleitende Sprachkurse und Projekte zur Arbeitsmarktintegration von Migrantinnen und Migranten sollen gestärkt werden. Der Zugang für Geflüchtete zum Arbeitsmarkt soll erleichtert werden. Behörden mit Kontakt zu migrantischen Beschäftigten sollen geschult werden.',
    'Berufsbegleitende Sprachkurse und Projekte für eine bessere Arbeitsmarktintegration von Migrant*innen müssen gestärkt werden. Der Zugang für Geflüchtete zum Arbeitsmarkt muss erleichtert werden.',
    'Der Zugang für Geflüchtete zum Arbeitsmarkt muss erleichtert werden',
   ),
  ]),
 ]),
 ('gesundheit', 'Gesundheit und Krankenhäuser',
  'Versorgung in den Bezirken, Kliniken und Pflege.', [
  ('Wie sollen die Krankenhäuser finanziert und getragen werden?', [
   ('spd', 33,
    'Angestrebt wird eine gerechte und flächendeckende Gesundheitsversorgung. Ambulante, stationäre und psychosoziale Angebote sollen enger zusammenarbeiten. Für die Krankenhäuser wird eine auskömmliche Finanzierung gefordert.',
    'Gesundheit ist ein Menschenrecht. Deshalb wollen wir eine gerechte und flächendeckende Gesundheitsversorgung. Ambulante, stationäre und psychosoziale Angebote müssen enger zusammenarbeiten. […] Die SPD Berlin setzt sich vor diesem Hintergrund für eine auskömmliche Finanzierung ein.',
    'Deshalb wollen wir eine gerechte und flächendeckende Gesundheitsversorgung',
   ),
   ('fdp', 114,
    'Wer eine Krankenhausbehandlung benötigt, soll rund um die Uhr die beste medizinische Versorgung erhalten. Angestrebt wird eine Neuordnung der Krankenhausfinanzierung am tatsächlichen Patientenbedarf. Die Trennung zwischen ambulant und stationär soll überwunden werden.',
    'Wer eine Behandlung im Krankenhaus benötigt, muss rund um die Uhr an sieben Tagen in der Woche und 365 Tagen im Jahr die beste medizinische Versorgung erhalten können. […] Wir werden uns daher für eine Neuordnung der Krankenhausfinanzierung einsetzen, die sich am tatsächlichen medizinischen Patientenbedarf orientiert.',
    'eine Neuordnung der Krankenhausfinanzierung einsetzen, die sich am tatsächlichen medizinischen Patientenbedarf orientiert',
   ),
   ('linke', 8,
    'Die Krankenhäuser sollen in kommunaler Hand bleiben. Wo private Konzerne sich aus der Verantwortung ziehen, soll rekommunalisiert werden. Gesundheit dürfe nicht dem Profitstreben von Krankenhauskonzernen zum Opfer fallen.',
    'Unser Wohlbefinden, unsere Gesundheit darf nicht dem Profitstreben von Krankenhauskonzernen zum Opfer fallen. Wir wollen, dass unsere Krankenhäuser in kommunaler Hand bleiben und dort rekommunalisiert werden, wo sich private Konzerne aus der Verantwortung ziehen.',
    'dass unsere Krankenhäuser in kommunaler Hand bleiben und dort rekommunalisiert werden',
   ),
   ('bsw', 21,
    'Das solidarische Gesundheitswesen soll gestärkt statt kaputtgespart werden. Die Zwei-Klassen-Medizin soll beendet werden. Angestrebt wird eine Bürgerversicherung als einheitliches Krankenversicherungssystem.',
    'Wir wollen das solidarische Gesundheitswesen stärken, statt es weiter kaputtzusparen. Die Zwei-Klassen-Medizin muss beendet werden. […] Deshalb strebt das BSW eine Bürgerversicherung als einheitliches Krankenversicherungssystem [an].',
    'Deshalb strebt das BSW eine Bürgerversicherung als einheitliches Krankenversicherungssystem',
   ),
  ]),
  ('Wie soll die Versorgung im Alltag erreichbar bleiben?', [
   ('cdu', 99,
    'Dokumentations- und Meldeprozesse in Pflege und Verwaltung sollen deutlich vereinfacht werden. Gute Versorgung brauche gute Ausbildung in allen Bereichen. Angehende Pflegefachkräfte sollen ausreichend Praxisplätze finden.',
    '[Wir wollen Entlastungen] in der Pflege und der Verwaltung schaffen, um Dokumentations- und Meldeprozesse deutlich zu vereinfachen. Gute Versorgung braucht gute Ausbildung in allen Bereichen der Gesundheitsversorgung. Wir setzen uns insbesondere dafür ein, dass angehende Pflegefachkräfte ausreichend Praxisplätze finden.',
    'dass angehende Pflegefachkräfte ausreichend Praxisplätze finden',
   ),
   ('gruene', 201,
    'Die Gesundheitschancen unterscheiden sich in Berlin je nach Bezirk und sozioökonomischem Status stark. Haus-, Fach- und Kinderärztinnen fehlten besonders in Stadtrandlagen. Angestrebt wird eine gleichmäßige Verteilung der Vertragsarztsitze.',
    'Noch immer unterscheiden sich die Gesundheitschancen in Berlin stark: Je nach Bezirk, Wohnviertel, Geschlecht und sozioökonomischem Status weichen Lebenserwartung und Krankheitshäufigkeiten voneinander ab. […] Wir setzen uns dafür ein, dass es eine gleichmäßige Verteilung von Vertragsärzt*innensitzen gibt.',
    'dass es eine gleichmäßige Verteilung von Vertragsärzt*innensitzen gibt',
   ),
   ('afd', 69,
    'Eine leistungsfähige und wohnortnahe Gesundheitsversorgung sowie fürsorgliche Pflege haben herausragende Bedeutung. Grundlage sind Eigenverantwortung, Prävention sowie private und staatliche Angebote der Daseinsvorsorge. Moderne Krankenhäuser sollen gesichert werden.',
    'Eine leistungsfähige und wohnortnahe Gesundheitsversorgung sowie eine fürsorgliche Pflege sind für die AfD von herausragender Bedeutung. Eigenverantwortung, Prävention, private und staatliche Angebote der Daseinsvorsorge sind die Basis für ein gesundes, langes und selbstbestimmtes Leben.',
    'Eine leistungsfähige und wohnortnahe Gesundheitsversorgung sowie eine fürsorgliche Pflege',
   ),
  ]),
 ]),
 ('wirtschaft', 'Wirtschaft und Gewerbe',
  'Gewerbeflächen, Ansiedlung und Rahmenbedingungen.', [
  ('Wodurch soll Berlin als Wirtschaftsstandort wachsen?', [
   ('spd', 6,
    'In Wirtschaftsförderung und Infrastruktur soll investiert werden. Angestrebt werden attraktive Arbeitsbedingungen mit Tarifbindung statt Lohndumping. Wachstum soll dem Wohl aller dienen.',
    'Wir investieren in Wirtschaftsförderung und Infrastruktur und wollen attraktive Arbeitsbedingungen mit Tarifbindungen statt Lohndumping.',
    'Wir investieren in Wirtschaftsförderung und Infrastruktur und wollen attraktive Arbeitsbedingungen mit Tarifbindungen statt Lohndumping',
   ),
   ('gruene', 98,
    'Technologie, Industrie, Forschung und Ausbildung sollen an einer gemeinsamen Schnittstelle zusammenwirken. Berlin soll als Standort für angewandte Innovation und klimaneutrale Industrie gestärkt werden. Geprüft wird die Einrichtung einer landeseigenen Innovationsagentur.',
    '[…] damit Technologie, Industrie, Forschung und Ausbildung an dieser wichtigen Schnittstelle zusammenwirken und Berlin als Standort für angewandte Innovation und klimaneutrale Industrie gestärkt wird. […] prüfen wir die Einrichtung einer landeseigenen Innovationsagentur.',
    'Berlin als Standort für angewandte Innovation und klimaneutrale Industrie gestärkt wird',
   ),
   ('afd', 47,
    'Berlin soll wieder industrieller Kernstandort werden. Gezielt gefördert wird die Ansiedlung in Luft- und Raumfahrt, Gesundheitswirtschaft, Halbleiter und KI. Ein öffentliches Gewerbeflächenkataster soll Flächen transparent verfügbar machen.',
    '[Der] Energiestandort Berlin muss wieder industrieller Kernstandort werden. Wir fördern gezielt die Ansiedlung von Unternehmen in den Bereichen: + Luft- und Raumfahrt; + Gesundheitswirtschaft; + Halbleiter, KI […]. Flächen für Gewerbe und Industrie – transparent und verfügbar: Ein öffentliches Gewerbeflächenkataster […].',
    'Wir fördern gezielt die Ansiedlung von Unternehmen in den Bereichen',
   ),
  ]),
  ('Wem soll die Wirtschaftspolitik vor allem dienen?', [
   ('cdu', 37,
    'Für mehr Transparenz auf dem Gewerbemarkt soll ein systematisches Leerstandsmonitoring von Büro- und Gewerbeflächen eingeführt werden. Das Leerstandsmanagement landeseigener Immobilien soll weiterentwickelt werden. Flächen sollen gezielt für Start-ups und Unternehmen genutzt werden.',
    'Für mehr Transparenz über die Entwicklungen auf dem Gewerbemarkt setzen wir uns für die Einführung eines systematischen Leerstandsmonitorings von Büro- und Gewerbeflächen ein. Wir werden das Leerstandsmanagement landeseigener Immobilien weiterentwickeln und gezielt für die Nutzung durch Start-ups und Unternehmen [öffnen].',
    'die Einführung eines systematischen Leerstandsmonitorings von Büro- und Gewerbeflächen',
   ),
   ('fdp', 18,
    'Berlin soll zu einem der freiesten Wirtschaftsstandorte Europas werden. Die Verwaltung soll sich auf ihre Kernaufgaben beschränken, Verfahren beschleunigen und unternehmerische Tätigkeit ermöglichen statt behindern. Berlin soll vom Empfänger- zum Geberland werden.',
    'Wir [wollen] Berlin zu einem der freiesten Wirtschaftsstandorte Europas machen. Unser Ziel ist eine Verwaltung, die sich auf ihre Kernaufgaben beschränkt, Verfahren beschleunigt, Rechtssicherheit gewährleistet und unternehmerische Tätigkeit nicht behindert, sondern ermöglicht. Berlin muss vom Empfänger- zum Geberland werden!',
    'eine Verwaltung, die sich auf ihre Kernaufgaben beschränkt',
   ),
   ('linke', 15,
    'Bei der Vergabe von Gewerbeflächen sollen Anwohnerinnen und Anwohner eng eingebunden werden. Eigene Bestände sollen wo möglich für Nahversorgung und soziale Angebote genutzt werden. Zwangsräumungen wegen Mietschulden werden abgelehnt.',
    'Wo immer möglich, sollen eigene Bestände für eine gute Nahversorgung für den täglichen Bedarf und soziale Angebote genutzt werden. Bei der Vergabe von Gewerbeflächen sollen Anwohner*innen und deren Vertretungen eng eingebunden werden.',
    'Bei der Vergabe von Gewerbeflächen sollen Anwohner*innen und deren Vertretungen eng eingebunden werden',
   ),
   ('bsw', 42,
    'Die Wirtschaftspolitik rückt Familienbetriebe, Selbständige und Freiberufler in den Mittelpunkt. Schwerpunkte sind der Abbau von Überregulierung, der Ausbau digitaler Verwaltungsleistungen und die Ausbildungsförderung. Zusätzlich wird ein Mutterschutz für Selbständige gefordert.',
    'Die Wirtschaftspolitik des Berliner BSW rückt Familienbetriebe, Selbständige und Freiberufler […] in den Mittelpunkt. Wir konzentrieren uns auf den Abbau von Überregulierung, den Ausbau digitaler Verwaltungsleistungen und die Ausbildungsförderung. Außerdem setzen wir uns für einen Mutterschutz für Selbständige ein.',
    'Wir konzentrieren uns auf den Abbau von Überregulierung, den Ausbau digitaler Verwaltungsleistungen',
   ),
  ]),
 ]),
 ('klima', 'Klima, Energie und Wärme',
  'Klimaziele, Wärmeversorgung und Energiekosten.', [
  ('Wie soll die Wärmeversorgung bezahlbar und klimafreundlich werden?', [
   ('fdp', 87,
    'Gesetzt wird auf einen massiven Ausbau der Geothermie, um die Wärmeversorgung klimaneutral zu gestalten. Die CO2-Emissionen der Fernwärme sollen weitgehend reduziert und die Netze ausgeweitet werden. Bevorzugt werden Technologieoffenheit und private Investitionen.',
    'Zudem setzen wir auf den massiven Ausbau der Geothermie in Berlin, um die Wärmeversorgung klimaneutral zu gestalten. Wir wollen die CO2-Emissionen der Fernwärme weitgehend reduzieren und die Fern- und Nahwärmenetze im Stadtgebiet ausweiten.',
    'den massiven Ausbau der Geothermie in Berlin, um die Wärmeversorgung klimaneutral zu gestalten',
   ),
   ('afd', 97,
    'Fernwärme und Nahverkehr sollen solide und bezahlbar gehalten werden. Die öffentliche Hand dürfe Bürger und Wirtschaft nicht über dauerhaft steigende Kosten belasten. Investitionen sollen in ein tragfähiges Finanzierungskonzept eingebettet sein.',
    '[Erforderlich ist eine Politik], die ideologische Kostensteigerungen zulasten der Berliner verhindert. Investitionen müssen in ein tragfähiges Finanzierungskonzept eingebettet sein. Fernwärme und ÖPNV solide und bezahlbar halten: Die öffentliche Hand darf Bürger und Wirtschaft nicht über dauerhaft steigende Kosten belasten.',
    'Fernwärme und ÖPNV solide und bezahlbar halten',
   ),
   ('bsw', 43,
    'Mit hoher Priorität soll für eine stabile, bezahlbare und krisenfeste Versorgung mit Strom, Wasser und Fernwärme gesorgt werden. Die Infrastruktur soll verlässlich finanziert werden. Betont wird die Bedeutung eines starken Wissenschafts- und Technologiestandorts.',
    'Gleichzeitig ist mit hoher Priorität für eine stabile, bezahlbare und krisenfeste Versorgung mit Strom, Wasser und Fernwärme zu sorgen.',
    'für eine stabile, bezahlbare und krisenfeste Versorgung mit Strom, Wasser und Fernwärme zu sorgen',
   ),
  ]),
  ('Wie verbindlich sollen die Berliner Klimaziele sein?', [
   ('cdu', 31,
    'Der Wettbewerb verschiedener Energieträger wie Gas, Fernwärme und Wärmepumpen soll erhalten bleiben. Nur so blieben Heizkosten dauerhaft bezahlbar. Einseitige staatliche Vorgaben werden abgelehnt.',
    'Den Wettbewerb verschiedener Energieträger wie Gas, Fernwärme und Wärmepumpen wollen wir erhalten, denn nur so bleiben Heizkosten dauerhaft bezahlbar. Einseitige staatliche Vorgaben lehnen wir ab.',
    'Den Wettbewerb verschiedener Energieträger wie Gas, Fernwärme und Wärmepumpen wollen wir erhalten',
   ),
   ('spd', 59,
    'Die Partei steht zu den Klimaschutzzielen und kämpft für Klimaneutralität vor dem Jahr 2045. Das Berliner Energiewendegesetz soll umgesetzt werden. Mieterinnen und Mieter sollen durch Klimaschutzmaßnahmen nicht zusätzlich belastet werden.',
    'Wir stehen zu den Klimaschutzzielen, kämpfen für Klimaneutralität vor dem Jahr 2045 und stehen zur Umsetzung des Berliner Energiewendegesetzes.',
    'kämpfen für Klimaneutralität vor dem Jahr 2045 und stehen zur Umsetzung des Berliner Energiewendegesetzes',
   ),
   ('gruene', 11,
    'Berlin solle sich an Hamburg orientieren, das bereits 2040 klimaneutral sein will. Der Fahrplan zur Klimaneutralität soll auf solide Beine gestellt und mit klaren Prioritäten hinterlegt werden, um die Ziele schnellstmöglich zu erreichen.',
    'Berlin muss sich ein Vorbild an Hamburg nehmen, das nun schon 2040 klimaneutral sein will. In Regierungsverantwortung werden wir den Fahrplan zur Klimaneutralität und -anpassung auf solide Beine stellen und Prioritäten setzen, um die Ziele schnellstmöglich zu erreichen.',
    'Berlin muss sich ein Vorbild an Hamburg nehmen',
   ),
   ('linke', 71,
    'Der Luftverkehrssektor müsse klimaneutral werden. Dafür sollen die erforderlichen Voraussetzungen geschaffen werden. Gefordert wird ein Verbot von Kurzstreckenflügen, wenn es Alternativen gibt.',
    'Klimaschutz im Luftverkehr: Der Luftverkehrssektor muss klimaneutral werden. Dafür unterstützen wir die Schaffung der erforderlichen Voraussetzungen. Wir setzen uns für ein Verbot von Kurzstreckenflügen ein.',
    'Wir setzen uns für ein Verbot von Kurzstreckenflügen ein',
   ),
  ]),
 ]),
]


# ---------------------------------------------------------------------------
# Dritte Frage je Thema (13. September 2026). Getrennt notiert, damit die
# ersten beiden Fragen unangetastet bleiben; angehaengt wird am Dateiende.
# Eine Partei kommt je Thema hoechstens einmal oefter vor als eine andere -
# dieselbe Ausgewogenheitsregel, die baue_datensatz.py prueft.
DRITTE = {
 'wohnen': ('Soll der Rand des Tempelhofer Feldes bebaut werden?', [
   ('cdu', 36,
    'Am Rand des Tempelhofer Feldes sollen mehr als 20.000 Wohnungen für rund 50.000 Menschen entstehen. Das übrige Feld soll als Ort für Sport, Freizeit und Erholung erhalten und weiterentwickelt werden.',
    'Wir bekennen uns klar zur Randbebauung des Tempelhofer Feldes. Auf den Randflächen des Feldes sollen mehr als 20.000 neue Wohnungen für etwa 50.000 Menschen entstehen. Darüber hinaus soll das Tempelhofer Feld als Ort für Sport, Freizeit, Kultur und Erholung erhalten und zugleich gezielt weiterentwickelt werden.',
    'Auf den Randflächen des Feldes sollen mehr als 20.000 neue Wohnungen',
   ),
   ('spd', 19,
    'Das Tempelhofer Feld soll in seiner heutigen Funktion erhalten und nur behutsam weiterentwickelt werden. Wohnungen am Feldrand kommen nicht infrage, solange andere Flächen in Berlin ungenutzt sind.',
    'Das Tempelhofer Feld ist ein besonderer Ort für Klima, Bewegung und soziales Miteinander. Wir erhalten es in seiner heutigen Funktion und entwickeln es behutsam weiter. […] Wohnungen am Feldrand kommen nicht in Frage, solang die bisherigen Flächen in Berlin ungenutzt sind […]',
    'Wohnungen am Feldrand kommen nicht in Frage',
   ),
   ('gruene', 22,
    'Das Tempelhofer Feld soll weiterhin geschützt bleiben. Es ist wichtig für das Stadtklima, als Kaltluftquelle, als Lebensraum für Tiere und Pflanzen und als Erholungsort.',
    'Das Tempelhofer Feld, mit seiner herausragenden Bedeutung für das Stadtklima und seiner Funktion als wichtige Kaltluftquelle, Lebensraum zahlreicher Pflanzen- und Tierarten sowie einzigartiger Erholungsort, soll weiterhin geschützt bleiben.',
    'soll weiterhin geschützt bleiben',
   ),
   ('bsw', 32,
    'Über eine Randbebauung des Tempelhofer Feldes soll nur die Bevölkerung erneut entscheiden können. Gesetze aus Volksentscheiden sollen nicht allein durch das Abgeordnetenhaus geändert werden dürfen.',
    'Gesetze, die durch einen Volksentscheid zustande gekommen sind, können nicht durch das Abgeordnetenhaus allein geändert werden, sondern müssen der Bevölkerung erneut zur Abstimmung gestellt werden (Bsp. Randbebauung Tempelhofer Feld).',
    'müssen der Bevölkerung erneut zur Abstimmung gestellt werden',
   ),
 ]),
 'verkehr': ('Soll die A 100 weitergebaut werden?', [
   ('cdu', 69,
    'Der Weiterbau der A 100 und die Tangentialverbindung Ost sollen entschlossen vorangetrieben werden. So sollen Wohngebiete vom Durchgangsverkehr entlastet und der Osten besser angebunden werden.',
    'Übergeordnete Projekte wie den Weiterbau der A 100 oder die Tangentialverbindung Ost (TVO) werden wir entschlossen vorantreiben, um Wohngebiete von Durchgangsverkehr zu entlasten und insbesondere Stadtteile im Berliner Osten besser anzubinden.',
    'werden wir entschlossen vorantreiben, um Wohngebiete von Durchgangsverkehr zu entlasten',
   ),
   ('fdp', 62,
    'Die A 100 soll zügig bis zur Storkower Straße weitergebaut werden. Auch neue Straßenverbindungen im Nordosten und Süden der Stadt haben Vorrang.',
    'Vor allem der Berliner Osten ist noch nicht in ausreichendem Umfang an das Hauptstraßennetz angeschlossen. Der zügige Weiterbau der A 100 durch den 17. Bauabschnitt bis Storkower Straße und der Fertigbau der Tangentialverbindung Ost (TVO) sowie neuer Straßenverbindungen, vor allem im Nordosten und Süden der Stadt, haben für uns daher weiterhin Priorität.',
    'Der zügige Weiterbau der A 100 durch den 17. Bauabschnitt bis Storkower Straße',
   ),
   ('linke', 69,
    'Neue Autobahnen in Berlin werden abgelehnt. Die A 100 soll am Treptower Park enden und nicht weiter ausgebaut werden, an bestehenden Autobahnen soll es Lärmschutz geben.',
    'Neue Autobahnen in Berlin lehnen wir ab. An bestehenden Autobahnen müssen Lärmschutzlösungen ermöglicht werden. Wir fordern, dass die A100 qualifiziert am Treptower Park beendet und nicht weiter ausgebaut wird.',
    'Neue Autobahnen in Berlin lehnen wir ab',
   ),
   ('spd', 26,
    'Statt die A 100 weiterzubauen, sollen Straßen und Brücken erhalten und nachhaltige Mobilität gefördert werden. Investitionsmittel des Bundes sollen stärker in die Sanierung fließen.',
    'Statt die A100 weiterzubauen, setzen wir auf den Erhalt unserer Straßen und Brücken sowie auf nachhaltige Mobilität. Wir setzen uns beim Bund dafür ein, dass Investitionsmittel stärker als bisher für die Sanierung von Straßen und Brücken […] eingesetzt werden.',
    'Statt die A100 weiterzubauen, setzen wir auf den Erhalt unserer Straßen und Brücken',
   ),
 ]),
 'schule': ('Sollen Smartphones an Schulen verboten werden?', [
   ('afd', 30,
    'Die Grundschule soll bildschirmfrei bleiben, mit einem Verbot von Smartphones. Auch an weiterführenden Schulen soll das Mitführen von Smartphones strenger geregelt werden.',
    'Die AfD will die Grundschule bildschirmfrei halten, dazu gehört auch ein Verbot der Verwendung von Smartphones. Auch an den weiterführenden Schulen werden wir das Mitführen von Smartphones restriktiver handhaben, damit die Aufmerksamkeit im Unterricht und die sozial-emotionale Entwicklung der Schüler nicht beeinträchtigt werden.',
    'Auch an den weiterführenden Schulen werden wir das Mitführen von Smartphones restriktiver handhaben',
   ),
   ('bsw', 2,
    'Smartphones und Tablets sollen aus den Klassenzimmern der Grundschulen verbannt werden. Dort sollen Lesen, Schreiben und Rechnen wieder im Vordergrund stehen.',
    '[…] dass […] in den Grundschulen wieder das Erlernen der Kernkompetenzen Lesen, Schreiben und Rechnen im Vordergrund steht. Smartphones und Tablets, die den Wissenserwerb nachweislich erschweren, wollen wir aus den Klassenzimmern der Grundschulen verbannen.',
    'wollen wir aus den Klassenzimmern der Grundschulen verbannen',
   ),
   ('fdp', 17,
    'Generelle Smartphone-Verbote für Schulen durch Land oder Bezirk werden abgelehnt. Jede Schule soll eigene Regeln für den Gebrauch festlegen können.',
    'Generelle Verbote der Nutzung von Smartphones in Schulen auf Landes- oder Bezirksebene lehnen wir ab. Im Rahmen der Schulautonomie sollen schulindividuelle Regeln für den Smartphone-Gebrauch möglich bleiben.',
    'Generelle Verbote der Nutzung von Smartphones in Schulen auf Landes- oder Bezirksebene lehnen wir ab',
   ),
   ('gruene', 190,
    'Die private Handynutzung soll dort eingeschränkt werden, wo die jeweilige Schule das für die beste Lösung hält. Anlass ist der steigende Medienkonsum von Kindern und Jugendlichen.',
    'Wir teilen die Sorgen über den steigenden Medienkonsum von Kindern und Jugendlichen. Deshalb unterstützen wir Einschränkungen der privaten Handynutzung, wo diese von der jeweiligen Schule für die beste Lösung gehalten werden.',
    'Deshalb unterstützen wir Einschränkungen der privaten Handynutzung',
   ),
 ]),
 'zuwanderung': ('Soll Berlin die Bezahlkarte für Geflüchtete nutzen?', [
   ('cdu', 25,
    'Die Bezahlkarte soll dauerhaft etabliert werden. Asylbewerber sollen bis zur Entscheidung über ihren Antrag in zentralen Einrichtungen untergebracht werden.',
    'Asylbewerber und illegal Eingereiste sollen deshalb vom ersten Tag bis zur Entscheidung über ihren Asylantrag in zentralen Einrichtungen untergebracht werden. Wir stehen zur Einführung der Bezahlkarte und wollen diese dauerhaft etablieren.',
    'Wir stehen zur Einführung der Bezahlkarte und wollen diese dauerhaft etablieren',
   ),
   ('fdp', 96,
    'Die Bezahlkarte für Geflüchtete soll in Berlin unverzüglich kommen. Sie soll für neu Ankommende und für bereits hier lebende Geflüchtete gelten.',
    'Berlin führt – als letztes Bundesland – unverzüglich die Bezahlkarte für Geflüchtete ein. Diese gilt sowohl für neu ankommende Geflüchtete als auch für Bestandsfälle.',
    'Diese gilt sowohl für neu ankommende Geflüchtete als auch für Bestandsfälle',
   ),
   ('linke', 278,
    'Die Bezahlkarte soll nicht eingeführt oder wieder abgeschafft werden. Nicht erwerbstätige EU-Bürger sollen Zugang zur Sozialhilfe erhalten.',
    'Nicht-erwerbstätige Unionsbürger*innen brauchen Zugang zur Sozialhilfe. Außerdem werden wir die diskriminierende Bezahlkarte nicht einführen bzw. wieder abschaffen.',
    'Außerdem werden wir die diskriminierende Bezahlkarte nicht einführen',
   ),
   ('spd', 53,
    'Eine Bezahlkarte für Geflüchtete wird abgelehnt, weil sie die Teilhabe stark einschränkt. Stattdessen sollen im Bund die Voraussetzungen für eine Berliner Stadtkarte geschaffen werden.',
    'Eine Bezahlkarte für Geflüchtete lehnen wir ab. Sie schränkt Teilhabe am öffentlichen Leben stark ein. Stattdessen setzen wir uns im Bund für die Voraussetzungen einer Berliner Stadtkarte (CityID).',
    'Eine Bezahlkarte für Geflüchtete lehnen wir ab',
   ),
 ]),
 'wirtschaft': ('Soll Berlin ein eigenes Vergabegesetz behalten?', [
   ('afd', 47,
    'Das Berliner Vergabegesetz soll aufgehoben werden. Ein Sonderausschuss soll Bürokratie systematisch abbauen, entbehrliche Gesetze sollen gestrichen werden.',
    'Mit einem Sonderausschuss „Bürokratieabbau“ ist eine effektive Systematik zum Abbau des Bürokratiedschungels zu entwickeln und zu begleiten. Die Verwaltung ist aufgefordert, entbehrliche Gesetze und Verordnungen zur Streichung anzumelden. Der Berliner Sonderweg eines eigenen Vergabegesetzes ist aufzugeben.',
    'Der Berliner Sonderweg eines eigenen Vergabegesetzes ist aufzugeben',
   ),
   ('fdp', 20,
    'Das Berliner Vergabegesetz soll abgeschafft werden, es soll nur noch das Vergaberecht von Bund und EU gelten. Berichtspflichten für Unternehmen sollen sinken.',
    'Das Berliner Vergabegesetz werden wir abschaffen und nur noch das Vergaberecht des Bundes (bzw. der EU) anwenden. Die unternehmerischen Berichtspflichten wollen wir reduzieren.',
    'Das Berliner Vergabegesetz werden wir abschaffen',
   ),
   ('gruene', 96,
    'Das Vergaberecht soll einfacher werden, damit kleinere und junge Berliner Firmen öfter zum Zug kommen. Tariftreue, Mindestlohn sowie soziale und ökologische Standards sollen dabei uneingeschränkt bleiben.',
    'Deshalb wollen wir das Vergaberecht reformieren – unter Beibehaltung sozialer und ökologischer Standards sowie deren wirksamer Umsetzung und Kontrolle […]. Vereinfachte Verfahren, eine Flexibilisierung der Wertgrenzen bei uneingeschränkter Tariftreue und Mindestlohnregelung, eine Innovationsklausel und vereinfachte Eignungsprüfungen sowie eine stärkere Aufteilung von Losen erleichtern dabei insbesondere KMU und Start-ups den Zugang […]',
    'Deshalb wollen wir das Vergaberecht reformieren',
   ),
   ('spd', 9,
    'Tariftreue und Vergabemindestlohn sollen strenger durchgesetzt werden, um Lohndumping zu verhindern. Öffentliche Gelder sollen so konsequent an soziale Standards gebunden werden.',
    'Berlin setzt mit dem Vergabe- und Landesmindestlohn schon jetzt Maßstäbe für faire Bezahlung im öffentlichen Auftragswesen. Wir verschärfen die Durchsetzung von Tariftreue und Vergabemindestlohn, um Lohndumping zu verhindern und öffentliche Gelder konsequent an soziale Standards zu binden. Auch Förderungen des Landes Berlin werden wir an Tarifbindung und Mitbestimmung koppeln.',
    'Wir verschärfen die Durchsetzung von Tariftreue und Vergabemindestlohn',
   ),
 ]),
}

DRITTE.update({
 'sicherheit': ('Sollen Waffen- und Messerverbotszonen bestehen bleiben?', [
   ('afd', 15,
    'Messerverbotszonen werden als Symbolpolitik abgelehnt. Stattdessen soll es härtere Strafen bei Messerdelikten und mehr anlasslose Kontrollen an kriminalitätsbelasteten Orten geben.',
    'Die Verschärfung des Strafrahmens der gefährlichen Körperverletzung bei Angriffen mit Messern, Schnellverfahren bei Messerdelikten, zügige Abschiebung ausländischer Messerstraftäter sowie die Ausweitung anlassloser Kontrollen an kriminalitätsbelasteten Orten. Messerverbotszonen lehnen wir als reine Symbolpolitik ab.',
    'Messerverbotszonen lehnen wir als reine Symbolpolitik ab',
   ),
   ('gruene', 228,
    'Kriminalitätsbelastete Orte sowie Messer- und Waffenverbotszonen sollen auf ihren Sinn überprüft werden. Wo nötig, sollen sie wieder abgeschafft werden.',
    'Wir werden die bestehenden kriminalitätsbelasteten Orte und Messer- und Waffenverbotszonen auf ihre Sinnhaftigkeit überprüfen und werden sie, wo erforderlich, wieder abschaffen.',
    'Messer- und Waffenverbotszonen auf ihre Sinnhaftigkeit überprüfen',
   ),
   ('spd', 30,
    'Waffen- und Messerverbotszonen sollen die Ausnahme bleiben. Verdachtsunabhängige Kontrollen sollen räumlich und im Anwendungsbereich auf das notwendige Minimum beschränkt werden.',
    'Verdachtsunabhängige Kontrollen wollen wir räumlich und in ihrem Anwendungsbereich auf das notwendige Minimum beschränken. Waffen- und Messerverbotszonen sollen die Ausnahme bleiben.',
    'Waffen- und Messerverbotszonen sollen die Ausnahme bleiben',
   ),
   ('linke', 288,
    'Anlasslose Kontrollen an kriminalitätsbelasteten Orten und in Waffenverbotszonen gelten als personalintensiv und oft nicht zielführend. Die Aufrüstung der Polizei soll gestoppt werden.',
    '[…] Aufrüstung der Polizei wollen wir stoppen und die Mittel umverteilen. Polizeieinsätze z. B. bei Demos, anlasslosen Kontrollen an KBOs und Waffenverbotszonen oder Fußballspielen sind personalintensiv und oft nicht zielführend.',
    'anlasslosen Kontrollen an KBOs und Waffenverbotszonen',
   ),
 ]),
 'verwaltung': ('Wie offen sollen Daten und Unterlagen der Verwaltung sein?', [
   ('linke', 257,
    'Ein Transparenzgesetz soll konkrete Veröffentlichungspflichten mit verbindlichen Fristen vorschreiben. Informationen sollen maschinenlesbar und durchsuchbar bereitgestellt werden, nicht nur als Scan.',
    'Transparenz ist Voraussetzung demokratischer Kontrolle, sie entsteht jedoch nicht allein durch politische Absichtserklärungen. Ein Transparenzgesetz für Berlin muss konkrete Veröffentlichungspflichten, verbindliche Fristen und maschinenlesbare Formate vorsehen. Informationen dürfen nicht nur als gescannte Dokumente bereitgestellt werden, sondern müssen strukturiert, durchsuchbar und technisch weiterverarbeitbar sein.',
    'Ein Transparenzgesetz für Berlin muss konkrete Veröffentlichungspflichten',
   ),
   ('spd', 62,
    'Alle nicht sensiblen Verwaltungsdaten sollen grundsätzlich öffentlich sein. Ein umfassendes Transparenzgesetz und ein zentrales Portal sollen Daten in Echtzeit abrufbar machen, Daten zur kritischen Infrastruktur bleiben geschützt.',
    'Deshalb gilt für Daten das Prinzip „Open by default“. Alle nichtsensiblen Verwaltungsdaten sollen grundsätzlich öffentlich sein. Daten zur kritischen Infrastruktur bedürfen eines besonderen Schutzes. Wir streben ein umfassendes Transparenzgesetz und ein zentrales Transparenzportal an. In einem übersichtlichen Dashboard sollen Daten in Echtzeit abrufbar sein.',
    'Wir streben ein umfassendes Transparenzgesetz und ein zentrales Transparenzportal an',
   ),
   ('cdu', 14,
    'Regeln zu Informationsfreiheit, Transparenz und offenen Daten dürfen keine Baupläne für Sabotage liefern. Offenlegungspflichten sollen überprüft und angepasst werden, um kritische Infrastruktur zu schützen.',
    'Informationsfreiheits-, Transparenz- und Open-Data-Regelungen dürfen keine Baupläne für Sabotage liefern. Sensible Informationen über Lage, Aufbau oder Schwachstellen kritischer Infrastruktur müssen wirksam geschützt werden. Offenlegungspflichten werden wir dort überprüfen und anpassen […]',
    'dürfen keine Baupläne für Sabotage liefern',
   ),
 ]),
 'gesundheit': ('Wie soll Berlin mit Drogen und Drogenkonsum umgehen?', [
   ('cdu', 11,
    'Drogenkriminalität soll mit aller Härte bekämpft, Drogennetzwerke sollen zerschlagen werden. Ein anonymes Hinweisgebersystem bei der Polizei soll Meldungen zu Drogenhandel erleichtern.',
    'Drogenkriminalität werden wir in unserer Stadt mit aller Härte bekämpfen. Clanstrukturen und Drogennetzwerke müssen konsequent zerschlagen werden. Dafür braucht die Polizei noch bessere Möglichkeiten zur Informationsgewinnung. Deshalb wollen wir ein anonymes elektronisches Hinweisgebersystem bei der Polizei Berlin einführen, über das Hinweise zu Drogenhandel und Organisierter Kriminalität sicher und vertraulich gemeldet werden können.',
    'Drogenkriminalität werden wir in unserer Stadt mit aller Härte bekämpfen',
   ),
   ('spd', 51,
    'Drogenkonsumräume sollen ausgebaut werden, mit längeren Öffnungszeiten und Landesgebäuden als Standorten. Abhängige sollen nicht vertrieben werden, Drogen aber aus Parks und von Spielplätzen verschwinden.',
    'Wir vertreiben drogenabhängige Menschen nicht von Ort zu Ort. Wir helfen dort, wo sie sind. Gleichzeitig holen wir Drogen aus dem öffentlichen Raum. Parks und Spielplätze müssen geschützt bleiben. Drogenkonsumräume bauen wir aus. Wir erleichtern ihre Einrichtung, erweitern Öffnungszeiten und stellen Landesgebäude bereit.',
    'Drogenkonsumräume bauen wir aus',
   ),
   ('bsw', 12,
    'Die Drogenprävention soll ausgeweitet werden. Wegen steigender Zahlen von Suchtkranken sollen auch geschützte Konsumräume, medizinische Betreuung und Substitutionstherapien ausgebaut werden.',
    'Wir setzen uns dafür ein, Maßnahmen zur Drogenprävention auszuweiten. Aufgrund der steigenden Zahl von Drogenkranken sollten Hilfsangebote wie geschützte Drogenkonsumräume, medizinische Betreuungseinrichtungen oder die Unterstützung bei Substitutionstherapien ausgeweitet werden.',
    'Maßnahmen zur Drogenprävention auszuweiten',
   ),
   ('fdp', 118,
    'Drug-Checking soll als Schutz vor Gesundheitsrisiken deutlich ausgebaut werden. Es soll auch mobil verfügbar und mit einem berlinweiten Frühwarnsystem für gefährliche Wirkstoffe verbunden sein.',
    'Drug-Checking ist eine zentrale Maßnahme zur Schadensminderung, die den sicheren Konsum fördert und potenzielle Gesundheitsrisiken reduziert. […] Wir wollen, dass das Berliner Drug-Checking-Projekt deutlich ausgebaut, auch mobil verfügbar und mit einem berlinweiten Frühwarnsystem für gefährliche Wirkstoffe verbunden wird.',
    'Drug-Checking-Projekt deutlich ausgebaut',
   ),
 ]),
 'klima': ('Wie sollen Böden und Regenwasser in Berlin geschützt werden?', [
   ('linke', 202,
    'Bis 2030 soll unter dem Strich keine Fläche mehr neu versiegelt werden. Wo gebaut wird, muss in Berlin gleich viel Fläche entsiegelt werden.',
    'Boden ist ein Gemeingut. Wir treten für eine Netto-Null-Versiegelung bis 2030 ein. Wo versiegelt wird, muss innerhalb Berlins in gleicher Größe entsiegelt werden. Das Entsiegelungsprogramm wird in der nächsten Wahlperiode konsequent umgesetzt.',
    'Wir treten für eine Netto-Null-Versiegelung bis 2030 ein',
   ),
   ('afd', 80,
    'Der Flächenverbrauch soll konsequent sinken. Manche ungenutzte Flächen sollen bebaut, andere entsiegelt werden, damit Regenwasser versickern kann.',
    'Wir wollen den Flächenverbrauch konsequent reduzieren und naturnahe Flächen bewahren. Sowohl ungenutzte Naturflächen als auch teilweise versiegelte Flächen müssen gezielt erfasst werden. Manche Flächen können sinnvoll bebaut werden, andere sollen durch Entsiegelung wieder naturnah hergestellt werden, damit Regenwasser versickern kann und städtische Lebensräume ökologisch aufgewertet werden.',
    'Manche Flächen können sinnvoll bebaut werden',
   ),
   ('fdp', 87,
    'Berlin soll als Schwammstadt Regenwasser nutzen und Starkregen bewältigen. Erreicht werden soll das mit privatem Kapital und Anreizen statt mit Verboten.',
    'Wir wollen eine Stadt, die Regenwasser als Ressource nutzt, deren Gewässer Badequalität haben, die als Schwammstadt Starkregen bewältigt. Aber all das erreichen wir nicht durch Verbote, sondern durch die Mobilisierung privaten Kapitals und durch marktwirtschaftliche Anreize.',
    'nicht durch Verbote, sondern durch die Mobilisierung privaten Kapitals',
   ),
 ]),
})

for _t in THEMEN:
    if _t[0] in DRITTE:
        _t[3].append(DRITTE[_t[0]])
