# -*- coding: utf-8 -*-
"""Datensatz Landtagswahl Mecklenburg-Vorpommern 2026. Alle Aussagen aus den PDFs."""

WAHL = {
    "id": "lt-mv-2026",
    "name": "Landtagswahl Mecklenburg-Vorpommern",
    "region": "Mecklenburg-Vorpommern",
    "wahltag": "2026-09-20",
    "kuerzel": "mv",
}

PROGRAMME = {
    "cdu": ("Chancenland. Wahlprogramm zur Landtagswahl 2026",
            "https://cdu-mv.de/wp-content/uploads/2026/06/Wahlprogramm-CDU-MV-2026.pdf"),
    "spd": ("Aufschwung, Zusammenhalt und Respekt. Regierungsprogramm 2026–2031",
            "https://spd-mv.de/uploads/bilderpool/2-Mecklenburg-Vorpommern/Wahlen-und-Kandidaturen/2026-Landtagswahlen/SPD_MV_Programm_2026.pdf"),
    "gruene": ("Klare Kante Zukunft. Für Mensch und Natur in MV. Wahlprogramm 2026",
               "https://schwerin.news/wp-content/uploads/2026/08/wahlprogramm-gruene.pdf"),
    "fdp": ("Freiheit, Leistung, Erfolg. Programm zur Landtagswahl 2026",
            "https://www.fdp-mv.de/sites/default/files/2026-06/Landtagswahlprogramm_2026.pdf"),
    "afd": ("Bereit für die blaue Wende. AfD-Regierungsprogramm zur Landtagswahl 2026",
            "https://afd-mv.de/wp-content/uploads/2026/06/AfD-Regierungsprogramm-Mecklenburg-Vorpommern-2026.pdf"),
    "linke": ("Sozial. Gerecht. Antifaschistisch. Programm zur Landtagswahl 2026",
              "https://www.dielinke-rostock.de/fileadmin/kreise/rostock/user/upload/Linke_MV_Landtagswahlprogramm_2026.pdf"),
    "bsw": ("Frischer Wind in MV! Landeswahlprogramm 2026",
            "https://mv.bsw-vg.de/wp-content/uploads/2026/04/Landeswahlprogramm-2026.pdf"),
}

# (themaId, Titel, Beschreibung, [(Fragetext, [Aussagen])])
# Aussage: (parteiId, seite, kurz, original, markierung)
# Regeln: 3-4 Aussagen je Frage, jede Partei je Thema genau einmal,
# alle Aussagen einer Frage beantworten dieselbe Unterfrage.
THEMEN = [
 ('sicherheit', 'Innere Sicherheit und Polizei',
  'Personal, Präsenz und Kontrolle der Polizei.', [
  ('Wie viel Polizeipräsenz braucht das Land?', [
   ('cdu', 26,
    'Ziel ist eine präsente Landespolizei mit schnellen Reaktionszeiten. Dazu kommen eine effektive Strafverfolgung und eine funktionierende Justiz. Auch Katastrophen- und Bevölkerungsschutz sollen ausgebaut werden.',
    'Unser Ziel: Der wirksame Schutz von Leben, Freiheit und Eigentum, eine präsente Landespolizei mit schnellen Reaktionszeiten, eine effektive Strafverfolgung, eine funktionierende Justiz, der Ausbau des Katastrophen- und Bevölkerungsschutzes.',
    'Landespolizei mit schnellen Reaktionszeiten, eine effektive Strafverfolgung, eine',
   ),
   ('fdp', 133,
    'Der Personalschlüssel der Landespolizei soll bedarfs- und aufgabengerecht angepasst werden. Mehr Polizeibeamte sollen wieder im operativen Dienst eingesetzt werden. Sicherheit entstehe durch Präsenz.',
    'Wir Freie Demokraten werden: den Personalschlüssel der Landespolizei bedarfs- und aufgabengerecht anpassen, und wieder mehr Polizeibeamte im operativen Dienst einsetzen. Sicherheit entsteht durch Präsenz.',
    'den Personalschlüssel der Landespolizei bedarfs- und aufgabengerecht anpassen',
   ),
   ('afd', 37,
    'Am Ziel von 6.200 Beamten der Landespolizei wird festgehalten. Die Fachhochschule Güstrow müsse fortlaufend genügend gut ausgebildete Absolventen hervorbringen. Die Polizei soll von Aufgaben entlastet und ihre Kompetenzen ausgebaut werden.',
    'Personalbestand der Polizei sichern, Kompetenzen ausbauen, Kräfte freimachen: Wir halten am Ziel von 6200 Beamten der Landespolizei fest. Die Fachhochschule Güstrow muss fortlaufend genügend gut ausgebildete und motivierte Polizeiabsolventen hervorbringen.',
    'Wir halten am Ziel von 6200 Beamten der Landespolizei fest',
   ),
   ('bsw', 67,
    'Die Polizei soll sichtbar, ansprechbar und schnell vor Ort sein, in Städten wie im ländlichen Raum. Gesetzt wird auf Präsenz vor Technik: mehr Einsatzkräfte statt Ausweitung der Videoüberwachung. Polizeireviere sollen insbesondere in ländlichen Regionen erhalten bleiben.',
    'Polizei muss sichtbar, ansprechbar und schnell vor Ort sein – in Städten wie im ländlichen Raum. […] • Präsenz vor Technik: mehr Einsatzkräfte statt Ausweitung von Videoüberwachung im öffentlichen Raum. • Erhalt von Polizeirevieren, insbesondere in ländlichen Regionen.',
    'Präsenz vor Technik: mehr Einsatzkräfte statt Ausweitung von Videoüberwachung im öffentlichen Raum',
   ),
  ]),
  ('Wie soll die Polizeiarbeit weiterentwickelt werden?', [
   ('spd', 47,
    'Die Polizeiarbeit soll durch die konsequente Fortsetzung der Digitalisierungsstrategie modernisiert und von Mehrfacharbeiten entlastet werden. Sicherheit soll nicht die Polizei allein tragen, sondern gemeinsam mit Ordnungsbehörden, Jugendhilfe, Schulen und Sozialarbeit.',
    'Dafür steht nicht die Polizei allein, sondern gemeinsam, vor allem mit ihren Kontaktbeamten, mit Ordnungsbehörden, Jugendhilfe, Schulen, Sozialarbeit, Wohnungsunternehmen, Vereinen und Trägern in Quartieren. […] Die polizeiliche Arbeit werden wir durch eine konsequente Fortsetzung der Digitalisierungsstrategie weiter modernisieren und insbesondere von Mehrfacharbeiten entlasten.',
    'durch eine konsequente Fortsetzung der Digitalisierungsstrategie weiter modernisieren',
   ),
   ('gruene', 77,
    'Gefordert werden ausreichende Neueinstellungen und eine Reform der Aus- und Fortbildung der Landespolizei. Diese soll einen höheren Anteil politischer Bildung vorsehen. Zudem soll besser auf Einsätze mit Menschen in psychischen Ausnahmezuständen vorbereitet werden.',
    'Für eine bürger*innennahe Polizei wollen wir: • ausreichende Neueinstellungen und eine Reform der Aus- und Fortbildung der Landespolizei, die einen höheren Anteil an politischer Bildung vorsieht sowie besser auf Einsatzsituationen mit Menschen in psychischen Ausnahmezuständen vorbereitet.',
    'ausreichende Neueinstellungen und eine Reform der Aus- und Fortbildung der Landespolizei',
   ),
   ('linke', 20,
    'Alle Sicherheitsbefugnisse sollen kritisch auf die Einhaltung der Bürger- und Freiheitsrechte geprüft werden. Gefordert wird eine von der Polizei unabhängige Beschwerdestelle mit ausreichendem Mandat. Zudem sollen Kontrollquittungen für Betroffene polizeilicher Maßnahmen eingeführt werden.',
    '• Alle Sicherheitsbefugnisse kritisch auf Einhaltung der Bürger:innen- und Freiheitsrechte prüfen. […] • Eine von der Polizei unabhängige Beschwerdestelle mit ausreichendem Mandat, Ressourcen und Befugnissen, um Fehlverhalten der Polizei effektiv zu verfolgen und aufzuklären.',
    'Eine von der Polizei unabhängige Beschwerdestelle mit ausreichendem Mandat',
   ),
  ]),
 ]),
 ('zuwanderung', 'Zuwanderung und Integration',
  'Aufnahme, Rückführung, Sprache und Arbeitsmarkt.', [
  ('Wie konsequent soll abgeschoben werden?', [
   ('cdu', 36,
    'Die Handyortung soll gezielt zur Durchsetzung des Rechtsstaats genutzt werden, unter anderem bei untergetauchten Ausreisepflichtigen. Damit sollen gescheiterte Abschiebungen reduziert werden. Dafür brauche es eine klare rechtliche Grundlage.',
    'Wir wollen, dass die Handyortung gezielt zur Durchsetzung des Rechtsstaats genutzt werden soll, unter anderem bei untergetauchten Ausreisepflichtigen, um gescheiterte Abschiebungen zu reduzieren und staatliche Maßnahmen effizient umzusetzen.',
    'unter anderem bei untergetauchten Ausreisepflichtigen, um',
   ),
   ('fdp', 143,
    'Abschiebungen sollen bei Vorliegen der Voraussetzungen konsequent umgesetzt werden, Vollzugsdefizite dürfe es nicht geben. Menschen ohne Bleibeperspektive sollen nicht erst auf die Kommunen verteilt werden. Verfahren sollen zügig abgeschlossen werden.',
    'Menschen ohne Bleibeperspektive sollen nicht erst auf die Kommunen verteilt werden, wenn sie ohnehin abgeschoben werden müssen. Abschiebungen müssen bei Vorliegen der Voraussetzungen konsequent umgesetzt werden. Vollzugsdefizite bei Abschiebungen darf es nicht geben.',
    'Abschiebungen müssen bei Vorliegen der Voraussetzungen konsequent umgesetzt werden',
   ),
   ('afd', 11,
    'Die illegale Einwanderung soll eingedämmt werden. Kriminelle und vollziehbar ausreisepflichtige Migranten sollen konsequent abgeschoben werden. Zugleich soll die Polizei modern ausgestattet und ihre Präsenz auf den Straßen erhöht werden.',
    '[Wir werden] unsere Polizei modern ausstatten und ihre Präsenz auf den Straßen erhöhen. Die illegale Einwanderung werden wir eindämmen, indem wir kriminelle und vollziehbar ausreisepflichtige Migranten konsequent abschieben.',
    'indem wir kriminelle und vollziehbar ausreisepflichtige Migranten konsequent abschieben',
   ),
   ('linke', 13,
    'Lebensgefährliche Abschiebungen sollen beendet werden, besonders bei unbegleiteten minderjährigen Flüchtlingen. Die UN-Kinderrechtskonvention soll uneingeschränkt angewendet werden. Integration wird als wechselseitiger Prozess verstanden.',
    'Integration ist ein wechselseitiger Prozess, der Unterstützung, Bildung und gesellschaftliche Offenheit erfordert. Wir wollen: • Lebensgefährliche Abschiebungen beenden, besonders für unbegleitete minderjährige Flüchtlinge sowie die UN-Kinderrechtskonvention uneingeschränkt anwenden.',
    'Lebensgefährliche Abschiebungen beenden, besonders für unbegleitete minderjährige Flüchtlinge',
   ),
  ]),
  ('Wie soll Zuwanderung gesteuert und Integration gestaltet werden?', [
   ('spd', 61,
    'Übergänge aus dem Asylsystem in die Erwerbsmigration sollen erleichtert werden. Die Anerkennung von Berufsabschlüssen wird beschleunigt. Insbesondere Frauen sollen beim Zugang zu Sprachkursen, Ausbildung und Beschäftigung unterstützt werden.',
    '[Wir erleichtern] Übergänge aus dem Asylsystem in die Erwerbsmigration, beschleunigen die Anerkennung von Berufsabschlüssen und unterstützen insbesondere Frauen beim Zugang zu Sprachkursen, Ausbildung und Beschäftigung.',
    'beschleunigen die Anerkennung von Berufsabschlüssen und unterstützen insbesondere Frauen beim Zugang zu Sprachkursen',
   ),
   ('gruene', 30,
    'Unternehmen sollen dabei unterstützt werden, Fachkräfte zu gewinnen und zu halten. Dazu dienen klare Anlaufstellen für Zuwanderung und Rückkehr. Hinzu kommen bessere Übergänge von Schule, Ausbildung und Studium in den Beruf.',
    'Wir unterstützen Unternehmen dabei, Fachkräfte zu gewinnen und zu halten: mit klaren Anlaufstellen für Zuwanderung und Rückkehr, besseren Übergängen von Schule, Ausbildung und Studium in den Beruf und einer engeren Zusammenarbeit zwischen Bildung und Wirtschaft.',
    'mit klaren Anlaufstellen für Zuwanderung und Rückkehr',
   ),
   ('bsw', 72,
    'Zuwanderung soll verantwortungsvoll gestaltet werden: leistbar, rechtsstaatlich und integrationsfähig. Am Grundrecht auf Asyl für politisch Verfolgte wird festgehalten. Zuwanderungspolitik brauche Augenmaß und Rechtssicherheit statt ideologischer Schnellschüsse.',
    '6.2. Zuwanderung: Zuwanderung verantwortungsvoll gestalten – leistbar, rechtsstaatlich und integrationsfähig. Das Grundrecht auf Asyl für politisch verfolgte Menschen [bleibt]. […] [Zuwanderungspolitik] braucht Augenmaß, Verantwortung und Rechtssicherheit – keine ideologischen Schnellschüsse.',
    'Zuwanderung verantwortungsvoll gestalten – leistbar, rechtsstaatlich und integrationsfähig',
   ),
  ]),
 ]),
 ('schule', 'Schule und Unterrichtsversorgung',
  'Unterrichtsausfall, Lehrkräfte und Schulqualität.', [
  ('Wie sollen Lehrkräfte entlastet und unterstützt werden?', [
   ('spd', 4,
    'Ziel ist eine flächendeckende und hochwertige Unterrichtsversorgung im Land. Lehrkräfte sollen unter anderem durch eine Reduzierung der Unterrichtsverpflichtung entlastet werden. Dies soll im Rahmen des Bildungspakts Gute Schule geschehen.',
    'Unser Ziel ist, eine flächendeckende und hochwertige Unterrichtsversorgung im Land abzusichern und sich bietende Möglichkeiten zu nutzen, um Lehrkräfte, u.a. durch eine Reduzierung der Unterrichtsverpflichtung, zu entlasten.',
    'eine flächendeckende und hochwertige Unterrichtsversorgung im Land abzusichern',
   ),
   ('gruene', 42,
    'Gesetzt wird auf multiprofessionelle Teams, in denen Fachleute wirklich zusammenarbeiten. Sie sollen nicht nur nebeneinander agieren. Lehrkräfte sollen dadurch gestärkt werden.',
    '6.2. Lehrkräfte stärken. „Wir setzen auf multiprofessionelle Teams, in denen Fachleute wirklich zusammenarbeiten und nicht nur nebeneinander agieren.“',
    'Wir setzen auf multiprofessionelle Teams,',
   ),
   ('fdp', 86,
    'Die Arbeitsbedingungen für Lehrkräfte sollen durch weniger Bürokratie verbessert werden. Dazu kommen eine bessere digitale Basisausstattung und verlässliche Zuständigkeiten für Wartung und technische Betreuung. Schulen sollen zudem über den Weg zum Abitur selbst entscheiden können.',
    '[Wir wollen] die Arbeitsbedingungen für Lehrkräfte durch weniger Bürokratie, bessere digitale Basisausstattung und verlässliche Zuständigkeiten für Wartung und technische Betreuung verbessern.',
    'die Arbeitsbedingungen für Lehrkräfte durch weniger Bürokratie, bessere digitale Basisausstattung',
   ),
   ('linke', 5,
    'Gute Bildung entstehe dort, wo ausreichend Zeit, Unterstützung und verlässliche Strukturen vorhanden sind. Lehrkräfte könnten ihren Auftrag nur erfüllen, wenn sie entlastet werden. Schule brauche multiprofessionelle Unterstützung.',
    'Gute Bildung durch mehr Personal: Gute Bildung entsteht dort, wo ausreichend Zeit, Unterstützung und verlässliche Strukturen vorhanden sind. Lehrkräfte können ihren Bildungsauftrag nur dann gut erfüllen, wenn sie entlastet werden.',
    'Lehrkräfte können ihren Bildungsauftrag nur dann gut erfüllen, wenn sie entlastet werden',
   ),
  ]),
  ('Welchen Kurs soll die Schulpolitik einschlagen?', [
   ('cdu', 46,
    'Der Unterrichtsausfall soll beendet werden. Der Anteil der Schüler ohne Schulabschluss soll drastisch verringert werden. Ziel ist, alle Schülerinnen und Schüler zu echter Ausbildungsreife zu führen.',
    'Unterrichtsausfall beenden, Grundschul-Garantie und hochqualitativer Unterricht […]. Unser Ziel: Den Unterrichtsausfall beenden, den Anteil der Schüler ohne Schulabschluss drastisch verringern und alle Schülerinnen und Schüler zu echter Ausbildungs- [reife führen].',
    'Den Unterrichtsausfall beenden, den Anteil der Schüler ohne',
   ),
   ('afd', 24,
    'Schulen sollen klare Regeln haben, in denen Lehrer ihre Aufgabe wahrnehmen können. Berufsschulen sollen handwerkliche Exzellenz fördern, Hochschulen Qualität vor Quantität stellen. Bildung sei kein Sozialprogramm.',
    'Dafür braucht es Schulen, in denen klare Regeln gelten und Lehrer ihre Aufgabe wahrnehmen können, Berufsschulen, die handwerkliche Exzellenz fördern und Hochschulen, die Qualität vor Quantität stellen. Bildung ist kein Sozialprogramm und kein Haltungsturnen.',
    'Berufsschulen, die handwerkliche Exzellenz fördern',
   ),
   ('bsw', 47,
    'Schulen sollen mehr Freiräume und eine bessere Ausstattung erhalten, um die Schulentwicklung gemeinsam vor Ort zu gestalten. Der Lehrerberuf soll durch ein praxisnäheres, duales Studium und ein Referendariat als echte Ausbildungszeit attraktiver werden.',
    'Mehr Freiräume für Schulen (auch im Sinne einer entsprechenden verbesserten Ausstattung) für eine gemeinsame Schulentwicklung vor Ort. […] Für die Lehrkräftegewinnung muss der Beruf attraktiver werden, z.B. durch ein praxisnäheres Studium (in Richtung eines Dualen Studiums), Entlastungen im Referendariat (als echte Ausbildungszeit).',
    'Mehr Freiräume für Schulen',
   ),
  ]),
 ]),
 ('kita', 'Frühkindliche Bildung und Kita',
  'Betreuungsschlüssel, Qualität und Elternbeiträge.', [
  ('Wie soll die Kita-Betreuung finanziert werden?', [
   ('cdu', 41,
    'Neubauten und Sanierungen von Schul- und Sportstätten, Kitas und Horteinrichtungen sollen auch durch Bund und Land finanziert werden. Damit sollen die Gemeinden entlastet werden. EU-Mittel sollen praxisgerechter für die Kommunen genutzt werden.',
    'Insbesondere Neubauten und Sanierungen von Schul- und Sportstätten, Kitas und Horteinrichtungen sollten auch durch Bund und Land zur Entlastung der Gemeinden finanziert werden.',
    'Neubauten und Sanierungen von Schul- und Sportstätten, Kitas und Horteinrichtungen',
   ),
   ('spd', 4,
    'Die Kita soll in Krippe, Kindergarten, Hort und Tagespflege beitragsfrei bleiben; das wird ausdrücklich garantiert. Gleichzeitig soll in Qualitätsverbesserungen in der frühkindlichen Bildung investiert werden.',
    'Für die Entlastung der Familien bleibt die Kita in Krippe, Kindergarten, Hort und Tagespflege beitragsfrei. Das garantieren wir. Gleichzeitig investieren wir in Qualitätsverbesserungen in der frühkindlichen Bildung.',
    'bleibt die Kita in Krippe, Kindergarten, Hort und Tagespflege beitragsfrei',
   ),
   ('fdp', 37,
    'Die Landesfinanzierung für die frühkindliche Betreuung in Kitas und Kindertagespflegestellen soll überprüft und an die tatsächlichen Notwendigkeiten angepasst werden. Die Trägervielfalt soll erhalten bleiben. Kommunen sollen bei Leistungen nach dem Bundesteilhabegesetz vollständig refinanziert werden.',
    '[Wir wollen] die Finanzierung des Landes für die frühkindliche Betreuung in Kitas und Kindertagespflegestellen überprüfen und an die tatsächlichen Notwendigkeiten anpassen[;] uns für den Erhalt der Trägervielfalt […] [einsetzen].',
    'die Finanzierung des Landes für die frühkindliche Betreuung in Kitas und Kindertagespflegestellen überprüfen',
   ),
   ('linke', 5,
    'Qualitätsverbesserungen sollen bei Krippe und Hort beginnen, weil die Bedarfe dort am drängendsten seien. Die Beitragsfreiheit in der Kita soll erhalten bleiben. Gute Bildung brauche zusätzlich Zeit für jedes Kind und gezielte Förderung.',
    'Doch gute Bildung braucht mehr: Zeit für jedes Kind, bessere Rahmenbedingungen und gezielte Förderung. Wir wollen: Die Beitragsfreiheit in der Kita erhalten und Qualitätsverbesserungen beginnend in Krippe und Hort, da die Bedarfe dort am drängendsten sind.',
    'Qualitätsverbesserungen beginnend in Krippe und Hort',
   ),
  ]),
  ('Was soll die Kita über die Betreuung hinaus leisten?', [
   ('gruene', 41,
    'Der Kita-Betreuungsschlüssel soll gesenkt und die Qualität verbessert werden. Zu große Gruppen und zu wenig Personal gingen zulasten von Kindern und Fachkräften. Horte liefen oft nur nebenher mit.',
    '6.1. Kita-Betreuungsschlüssel senken und Qualität verbessern […]. Zu große Gruppen, zu wenig Personal und Horte, die oft nur nebenher mitlaufen, gehen zulasten der Kinder und der Fachkräfte.',
    'Kita-Betreuungsschlüssel senken und Qualität verbessern',
   ),
   ('afd', 18,
    'Vorgesehen sind konkrete Maßnahmen von einem Baby-Begrüßungsgeld bis zu besseren Kita-Betreuungsschlüsseln. Hinzu kommt der Schutz von Kindern vor Gewalt und ideologischer Einflussnahme. Junge Eltern sollen nicht mit bürokratischen Hürden überzogen werden.',
    'Wir begegnen dieser Entwicklung mit konkreten Maßnahmen. Vom Baby-Begrüßungsgeld über bessere Kita-Betreuungsschlüssel bis hin zum Schutz von Kindern vor Gewalt und ideologischer Einflussnahme.',
    'Vom Baby-Begrüßungsgeld über bessere Kita-Betreuungsschlüssel',
   ),
   ('bsw', 45,
    'Kitas seien weit mehr als Betreuungsorte und förderten soziale, sprachliche und emotionale Kompetenzen. Frühkindliche Bildung lege den Grundstein für ein gelingendes Leben. Kitas, Schulen und Hochschulen sollen so gestaltet werden, dass Lernen Freude macht.',
    'Chancen von Anfang an: Frühkindliche Bildung und Förderung legen den Grundstein für ein gelingendes Leben. Kitas sind weit mehr als Betreuungsorte: Sie unterstützen Kinder in ihrer Entwicklung, fördern soziale, sprachliche und emotionale Kompetenzen.',
    'Kitas sind weit mehr als Betreuungsorte',
   ),
  ]),
 ]),
 ('gesundheit', 'Gesundheit und Versorgung in der Fläche',
  'Krankenhäuser, Hausärzte und Pflege im Flächenland.', [
  ('Wie soll die ärztliche Versorgung in der Fläche gesichert werden?', [
   ('cdu', 6,
    'Erweiterte Aufgaben für berufserfahrene Medizinische Fachangestellte sollen Hausärzte entlasten. Das Land soll die entsprechende Qualifizierung finanzieren. So soll die Versorgung in der Fläche gesichert werden.',
    '[Wir wollen die Qualifizierung zur Praxisassistentin] durch das Land [fördern], damit ausgebildete, berufserfahrene Medizinische Fachangestellte erweiterte medizinische Aufgaben übernehmen und so Hausärzte entlasten sowie die Versorgung in der Fläche sichern können.',
    'erweiterte medizinische Aufgaben übernehmen und so',
   ),
   ('fdp', 44,
    'Die Studienkapazitäten in den medizinischen Fächern sollen erhöht und Studienplätze bevorzugt an Bewerber vergeben werden, die sich anschließend im Land niederlassen. Das Berufsbild der Community Health Nurse soll konsequent eingeführt werden.',
    '[Wir werden] uns für eine Erhöhung der Studienkapazitäten an Hochschulen des Landes in den medizinischen Fächern einsetzen […]. Studienplätze an diejenigen vergeben, die sich nach dem Abschluss in Mecklenburg-Vorpommern niederlassen, ergänzt durch ein gezieltes Stipendiensystem für Landeskinder. […] die medizinische Versorgung im ländlichen Raum durch die konsequente Einführung des Berufsbildes der Community Health Nurse (CHN) zukunftsfest und attraktiv zu gestalten.',
    'die konsequente Einführung des Berufsbildes der Community Health Nurse',
   ),
   ('linke', 19,
    'Das „Schwester-Agnes“-Modell für arztentlastende Dienste im ländlichen Raum soll wieder aufleben. Gesundheitslotsen sollen Patientinnen und Versicherte begleiten. Die Vergütung im Praktischen Jahr soll auf ein existenzsicherndes Niveau angehoben werden.',
    '• Das „Schwester-Agnes“ Modell für arztentlastende Dienste im ländlichen Raum wieder aufleben lassen. • Darauf hinwirken, dass Gesundheitslots:innen zum Einsatz kommen, die Patient:innen und Versicherte in allen relevanten Bereichen des Gesundheitswesens begleiten.',
    'Das „Schwester-Agnes“ Modell für arztentlastende Dienste im ländlichen Raum wieder aufleben lassen',
   ),
  ]),
  ('Was braucht das Gesundheitswesen darüber hinaus?', [
   ('spd', 28,
    'Alle Krankenhäuser im Land seien erhalten worden, dieser Einsatz soll fortgesetzt werden. Eine flächendeckende stationäre Regel- und Grundversorgung soll in allen Regionen gewährleistet werden. Zugleich sollen Spezialisierungen der Krankenhäuser vorangetrieben werden.',
    'Wir haben es geschafft, dass alle Krankenhäuser im Land erhalten worden sind. […] Konkret werden wir eine flächendeckende stationäre Versorgung in der Regel- und Grundversorgung in allen Regionen unseres Landes gewährleisten und gleichzeitig Spezialisierungen der Krankenhäuser […] forcieren.',
    'eine flächendeckende stationäre Versorgung in der Regel- und Grundversorgung in allen Regionen',
   ),
   ('gruene', 58,
    'Gesundheits- und Pflegeberufe sollen aufgewertet werden. Ihre Arbeit sei von Personalmangel, hoher Belastung und zu wenig Zeit für die Versorgung geprägt. Viele verließen deshalb den Beruf.',
    '9.1. Gesundheits- und Pflegeberufe aufwerten […]. Doch ihre Arbeit ist oft von Personalmangel, hoher Belastung und zu wenig Zeit für die eigentliche Versorgung geprägt. Viele verlassen den Beruf.',
    'Gesundheits- und Pflegeberufe aufwerten',
   ),
   ('afd', 59,
    'Die Gesundheitspolitik soll Eigenverantwortung und Solidarität verbinden, den Wettbewerb fördern und den Schutz der Schwächeren sichern. Für die Beschäftigten soll die Kontrollbürokratie spürbar abgebaut werden.',
    'Das Leitbild ist eine Gesundheitspolitik, die Eigenverantwortung und Solidarität miteinander verbindet, den Wettbewerb fördert und den Schutz der Schwächeren sicherstellt. […] Das erfordert einen wirklichen Abbau der Kontrollbürokratie und des Dokumentationswahns.',
    'einen wirklichen Abbau der Kontrollbürokratie',
   ),
   ('bsw', 57,
    'Krankenhäuser und medizinische Versorgungszentren sollen als Teil der öffentlichen Daseinsvorsorge erhalten und weiterentwickelt werden. Die wohnortnahe medizinische Versorgung soll besonders in ländlichen Regionen gesichert und gestärkt werden.',
    'Unsere Ziele: Sicherung und Stärkung der wohnortnahen medizinischen Versorgung, insbesondere in ländlichen Regionen. Erhalt und Weiterentwicklung von Krankenhäusern und medizinischen Versorgungszentren als Teil der öffentlichen Daseinsvorsorge.',
    'Erhalt und Weiterentwicklung von Krankenhäusern und medizinischen Versorgungszentren',
   ),
  ]),
 ]),
 ('energie', 'Energie und Windkraft',
  'Ausbau der Erneuerbaren, Akzeptanz und Beteiligung.', [
  ('Soll die Windkraft an Land weiter ausgebaut werden?', [
   ('cdu', 93,
    'Windkraftausbau im Wald und Waldstilllegungen werden grundsätzlich abgelehnt. Stattdessen sollen Soforthilfen für Waldschäden und Waldumbau bereitgestellt werden. Die Nutzung privater Waldflächen und Holzbauprojekte wird unterstützt.',
    '[Wir wollen] Soforthilfen für Waldschäden und Waldumbau zur Klimaanpassung bereitstellen. Dabei unterstützen wir die Nutzung privater Waldflächen und Holzbauprojekte. Windkraftausbau im Wald und Waldstilllegungen lehnen wir grundsätzlich ab.',
    'Windkraftausbau im Wald und',
   ),
   ('gruene', 6,
    'Die Planungssicherheit soll erhöht werden, indem Genehmigungsbehörden als moderne und personalstarke Agenturen neu ausgerichtet werden. So sollen Windräder und Solaranlagen schneller gebaut werden. Strom soll dadurch günstiger produziert werden.',
    'Tempo für Erneuerbare: Wir erhöhen die Planungssicherheit, indem wir Genehmigungsbehörden als moderne und personalstarke Agenturen neu ausrichten und fördern. Damit Windräder und Solaranlagen schneller gebaut werden und Strom endlich günstiger produziert wird.',
    'Damit Windräder und Solaranlagen schneller gebaut werden',
   ),
   ('afd', 68,
    'Der weitere Ausbau von Windkraftanlagen wird abgelehnt. Die einzigartige Kulturlandschaft sei die Grundlage des Tourismus. Wer auf Qualitätstourismus setze, dürfe seine Landschaft nicht ruinieren.',
    'Die einzigartige Kulturlandschaft ist die Grundlage dieses Tourismus. Wir lehnen den weiteren Ausbau von Windkraftanlagen ab. Wer auf Qualitätstourismus setzt, darf seine Landschaft nicht ruinieren.',
    'Wir lehnen den weiteren Ausbau von Windkraftanlagen ab',
   ),
   ('bsw', 25,
    'Die Windenergie sei ein wichtiger Bestandteil der Energieversorgung. Ihr Ausbau dürfe jedoch nicht gegen die Interessen der Bevölkerung erfolgen. Gewinne aus der Stromerzeugung müssten auch den Gemeinden zugutekommen.',
    'Gewinne aus der Stromerzeugung müssen auch den Gemeinden zugutekommen. Windenergie mit Maß und kommunaler Verantwortung: Die Windenergie ist ein wichtiger Bestandteil der Energieversorgung. Der Ausbau darf jedoch nicht gegen die Int[eressen der Bevölkerung erfolgen].',
    'Windenergie mit Maß und kommunaler Verantwortung',
   ),
  ]),
  ('Welche Energiewirtschaft soll das Land aufbauen?', [
   ('spd', 7,
    'Der Bau von Converter-Plattformen soll die auf See erzeugte Windenergie an Land leiten. Die Energiehäfen Rostock, Sassnitz-Mukran und Lubmin sollen entwickelt werden. Damit zeige sich wirtschaftliches Potenzial über den Schiffbau hinaus.',
    'Der Bau von Converter-Plattformen, um die auf See erzeugte Windenergie an Land zu leiten, und die Entwicklung der Energiehäfen Rostock, Sassnitz-Mukran und Lubmin zeigen, dass es auch über den Schiffbau hinaus wirtschaftliche [Perspektiven gibt].',
    'die auf See erzeugte Windenergie an Land zu leiten',
   ),
   ('fdp', 63,
    'Neben Gaskraftwerken wird eine im Land ansässige Wasserstoffproduktion angestrebt. Vorhandene Überkapazitäten etwa in der Windenergie sollen zeitnah für Wasserstoff genutzt oder in Batterien gespeichert werden. Ziel ist die Nutzung bestehender Erzeugung.',
    'Neben Gaskraftwerken setzen wir uns für eine in Mecklenburg-Vorpommern ansässige Wasserstoffproduktion ein. Die bereits vorhandenen Überkapazitäten z.B. in der Windenergie müssen zeitnah für die Produktion von Wasserstoff bereitgestellt oder in Batterien gespeichert werden.',
    'Die bereits vorhandenen Überkapazitäten z.B. in der Windenergie müssen zeitnah für die Produktion von Wasserstoff bereitgestellt',
   ),
   ('linke', 10,
    'Die Offshore-Windenergie soll gestärkt werden. Zudem sollen neue Geschäftsfelder in der maritimen Industrie geprüft werden. Genannt wird etwa die Umrüstung der Binnenschifffahrtsflotte auf alternative Antriebe.',
    '• Neue Geschäftsfelder in der maritimen Industrie prüfen, etwa die Umrüstung der Binnenschifffahrtsflotte auf alternative Antriebe. • Offshore-Windenergie stärken.',
    'Offshore-Windenergie stärken',
   ),
  ]),
 ]),
 ('mobilitaet', 'Mobilität im Flächenland',
  'Bus, Bahn, Straßen und Erreichbarkeit.', [
  ('Wie soll der Nahverkehr im Flächenland zugänglich werden?', [
   ('spd', 11,
    'Gästekarten sollen neben touristischen Vergünstigungen auch die kostenlose Nutzung des ÖPNV enthalten. Diese Angebote sollen innerhalb einer Destinationsregion gelten. Auch Bewohnerinnen und Bewohner sollen sie ohne Aufpreis nutzen können.',
    '[…] Gästekarten, die neben zahlreichen Vergünstigungen für touristische Angebote vor Ort […] auch eine kostenlose Nutzung des ÖPNV beinhalten. Diese Angebote sollen innerhalb einer Destinationsregion […] auch den Bewohnerinnen und Bewohnern ohne Aufpreis zur Verf[ügung stehen].',
    'auch eine kostenlose Nutzung des ÖPNV beinhalten',
   ),
   ('gruene', 21,
    'Ein Landesverkehrsplan soll Bus und Bahn im ganzen Land zuverlässig verzahnen, damit alle auch ohne Auto bezahlbar von A nach B kommen. Bei Baumaßnahmen sollen alle Verkehrsteilnehmenden gleichberechtigt berücksichtigt werden, um den Radverkehr sicherer zu machen.',
    '[Wir setzen uns ein für die Aufstellung eines Landesverkehrsplans], der Bus und Bahn im ganzen Land zuverlässig miteinander verzahnt, damit alle auch ohne Auto bezahlbar von A nach B kommen. […] mehr Sicherheit für den Radverkehr: indem bei Baumaßnahmen alle Verkehrsteilnehmenden gleichberechtigt berücksichtigt werden.',
    'der Bus und Bahn im ganzen Land zuverlässig miteinander verzahnt',
   ),
   ('afd', 32,
    'Gemeinsam mit Landkreisen und lokalen Akteuren soll ein landesweites Verkehrsverbundsystem eingeführt werden. Dieses soll Kindern einen verlässlichen und unkomplizierten Schulweg ermöglichen. Ziel sind möglichst kurze Transportwege.',
    'Zu diesem Zweck werden wir mit den Landkreisen, kreisfreien Städten und lokalen Akteuren im öffentlichen Nahverkehr darauf hinwirken, ein landesweites Verkehrsverbundsystem einzuführen, das unseren Kindern einen verlässlichen und unkomplizierten Schulweg ermöglicht.',
    'ein landesweites Verkehrsverbundsystem einzuführen',
   ),
   ('linke', 12,
    'Für alle unter 21 Jahren soll ein kostenfreier Nahverkehr eingeführt werden. Damit sollen Mobilität und gesellschaftliche Teilhabe unabhängig vom Geldbeutel gewährleistet werden.',
    'Kostenfreien Nahverkehr für alle unter 21 Jahren einführen, um Mobilität und gesellschaftliche Teilhabe zu gewährleisten.',
    'Kostenfreien Nahverkehr für alle unter 21 Jahren einführen',
   ),
  ]),
  ('Worauf kommt es bei der Verkehrsinfrastruktur an?', [
   ('cdu', 124,
    'Landesstraßen und Brücken sollen strategisch instand gehalten werden. Bahnstrecken sollen reaktiviert und flächendeckende, sichere Rad- und Fußwege geschaffen werden. Die Flughafennutzung soll bedarfsgerecht erfolgen.',
    '[Wir wollen] flächendeckende, sichere Rad- und Fußwege, die Reaktivierung von Bahnstrecken, bedarfsgerechte Flughafennutzung sowie die strategische Instandhaltung von Landesstraßen und Brücken [– sie] erhöhen Mobilität und Sicherheit im Alltag.',
    'strategische Instandhaltung von Landesstraßen und Brücken',
   ),
   ('fdp', 60,
    'Im regionalen Schienenverkehr sollen die Züge zuverlässig und pünktlich fahren. Anzeigen an Bahnsteigen und in Apps müssten den Tatsachen entsprechen. Menschen und Güter sollen schnell, zuverlässig und ohne ideologische Bevormundung unterwegs sein.',
    '[…] frei von ideologischer Bevormundung durch unser Land und in unser Land kommen können. Im regionalen Schienenverkehr sollen nach unseren Vorstellungen die Züge zuverlässig und pünktlich fahren. Die Anzeigen an Bahnsteigen und in den Apps müssen den Tatsachen en[tsprechen].',
    'Im regionalen Schienenverkehr sollen nach unseren Vorstellungen die Züge zuverlässig und pünktlich fahren',
   ),
   ('bsw', 18,
    'Der öffentliche Nahverkehr soll gut erreichbar und barrierefrei ausgebaut werden. Bus und Bahn sollen besser vernetzt und getaktet werden, mit umstiegsarmen Verbindungen und ausreichend Haltestellen. Eine wohnortnahe Versorgung soll die Wege kurz halten.',
    '[Wir wollen die Sicherung] kurzer Wege durch eine wohnortnahe Versorgungs- und Infrastruktur im ganzen Land. Ausbau eines gut erreichbaren und barrierefrei nutzbaren öffentlichen Personennahverkehrs, insbesondere durch bessere Vernetzung und Taktung von Bus und Bahn, umstiegsarme Verbindungen, ausreichende Haltestellen.',
    'Ausbau eines gut erreichbaren und barrierefrei nutzbaren öffentlichen Personennahverkehrs',
   ),
  ]),
 ]),
 ('landwirtschaft', 'Landwirtschaft und ländlicher Raum',
  'Agrarstruktur, Bodenpreise, Ökologie und Wertschöpfung.', [
  ('Wie viel Freiheit sollen Betriebe bei der Bewirtschaftung haben?', [
   ('cdu', 86,
    'Statt Nutzungseinschränkungen und starrer Bio-Quoten sollen Betriebe Planungsperspektiven und Nutzungssicherheit erhalten. Bodenspekulationen sollen verhindert werden. Angestrebt wird eine langfristig ausgewogene Agrarstruktur.',
    'Statt Nutzungseinschränkungen und starren Bio-Quoten wollen wir Planungsperspektiven und Nutzungssicherheit für Betriebe. Bodenspekulationen sollen verhindert werden. Die Sorge vor steigenden Boden- und Pachtpreisen nehmen wir ernst und setzen auf eine langfristig ausgewogene Agrarstruktur.',
    'Statt Nutzungseinschränkungen und starren Bio-Quoten wollen wir',
   ),
   ('gruene', 16,
    'Steigende Kosten, unsichere Preise und hohe bürokratische Anforderungen erschwerten den Alltag der Betriebe. Zugleich müsse Landwirtschaft klima- und naturverträglich werden. Ziel sind Existenzsicherung und ein ermöglichter Umbau.',
    '2.4. Faire Landwirtschaft – Existenzsicherung und Umbau ermöglichen. […] Doch steigende Kosten, unsichere Preise und hohe bürokratische Anforderungen erschweren den Alltag der Betriebe.',
    'Faire Landwirtschaft - Existenzsicherung und Umbau ermöglichen',
   ),
   ('fdp', 22,
    'Angestrebt wird eine Agrarpolitik, die Landwirte nicht bevormundet, sondern Freiraum für unternehmerisches Handeln lässt. Rechtsform, Größe und Art der Bewirtschaftung sollen dabei keine Rolle spielen. Land- und Forstwirtschaft gelten als Motor des ländlichen Raums.',
    'Wir Freie Demokraten setzen uns für eine Agrarpolitik ein, die Landwirte nicht bevormundet, sondern Freiraum für unternehmerisches Handeln lässt. Die Rechtsform, die Größe oder die Art der Bewirtschaft[ung] […].',
    'eine Agrarpolitik ein, die Landwirte nicht bevormundet, sondern Freiraum für unternehmerisches Handeln lässt',
   ),
   ('afd', 73,
    'Die Landwirtschaft soll wertgeschätzt werden, geprägt von der jahrhundertealten Kulturlandschaft. Fischerei und Jagd werden als traditionsreiche Formen der Kulturlandschaftspflege begriffen, nicht als Relikte. Der ländliche Raum brauche mehr Freiheiten.',
    '[Wir wollen eine Politik, die] Fischerei wie Jagd als traditionsreiche Formen der Kulturlandschaftspflege begreift und nicht als Relikte von gestern. Der ländliche Raum braucht mehr Freiheiten. Landwirtschaft wertschätzen […].',
    'Der ländliche Raum braucht mehr Freiheiten',
   ),
  ]),
  ('Wie soll der ländliche Raum wirtschaftlich gestärkt werden?', [
   ('spd', 82,
    'Die Zukunft der ländlichen Räume liegt im Aufbau regionaler Wertschöpfungsketten. Grundlage sind Rohstoffe aus Land-, Forst- und Teichwirtschaft sowie erneuerbare Energien. Die Menschen vor Ort sollen davon profitieren.',
    'Die Zukunft der ländlichen Räume sehen wir im Aufbau regionaler Wertschöpfungsketten auf Basis der Rohstoffe aus der Land-, Forst- und Teichwirtschaft, den Erneuerbare[n] Energien und den Möglichkeiten, dass die Menschen vor Ort davon profitieren.',
    'im Aufbau regionaler Wertschöpfungsketten auf Basis der Rohstoffe aus der Land-, Forst- und Teichwirtschaft',
   ),
   ('linke', 22,
    'Die Rahmenbedingungen für die landwirtschaftliche Nutzung wiedervernässter Moore sollen verbessert werden. Gefordert wird zudem die Wiedervernässung landwirtschaftlich genutzter Moorstandorte bis 2045. Ein Strukturwandelgesetz soll betroffene Betriebe unterstützen.',
    '[Wir fordern die Wiedervernässung der] landwirtschaftlich genutzten Moorstandorte bis 2045 sowie eine umfassende Finanzierung der dafür notwendigen Maßnahmen und Strukturen. • Die Rahmenbedingungen für die landwirtschaftliche Nutzung wiedervernässter Moore (Paludikultur) verbessern.',
    'Die Rahmenbedingungen für die landwirtschaftliche Nutzung wiedervernässter Moore (Paludikultur) verbessern',
   ),
   ('bsw', 22,
    'Die Landwirtschaft präge große Teile des Landes und sei wesentlich für regionale Wertschöpfung und Beschäftigung. Ihre Potenziale würden bislang nur unzureichend im Land weiterverarbeitet. Die Verarbeitung landwirtschaftlicher Erzeugnisse soll gezielt ausgebaut werden.',
    'Eine zentrale Rolle spielt die Landwirtschaft. Sie prägt große Teile Mecklenburg-Vorpommerns und ist ein wesentlicher Faktor für regionale Wertschöpfung und Beschäftigung. Die Potenziale der landwirtschaftlichen Produktion werden bislang jedoch nur unzureichend im Land weiterverarbeitet.',
    'Die Potenziale der landwirtschaftlichen Produktion werden bislang jedoch nur unzureichend im Land weiterverarbeitet',
   ),
  ]),
 ]),
 ('wirtschaft', 'Wirtschaft und Fachkräfte',
  'Ansiedlung, Industrie und Arbeitsmarkt.', [
  ('Auf welche Branchen und Stärken soll das Land setzen?', [
   ('cdu', 9,
    'Gezielt soll moderne Industrie ins Land geholt werden, die wettbewerbsfähige Löhne zahlt. Das Land soll als verlässlicher und investorenfreundlicher Wirtschaftsstandort gestärkt werden. Dazu gehören klare Rahmenbedingungen und eine aktive Ansiedlungspolitik.',
    'Deshalb machen wir neue, attraktive Jobs zur Chefsache: Wir holen gezielt moderne Industrie nach MV, die wettbewerbsfähige Löhne zahlt. […] Unser Ziel: Wir stärken Mecklenburg-Vorpommern als attraktiven, verlässlichen und investorenfreundlichen Wirtschaftsstandort mit klaren Rahmenbedingungen und aktiver Ansiedlungspolitik.',
    'Deshalb machen wir neue, attraktive Jobs zur Chefsache: Wir holen gezielt moderne',
   ),
   ('spd', 7,
    'Bewährt habe sich die Strategie, einen Branchenmix zu stärken. Genannt werden Energiewirtschaft, maritime Industrie, Gesundheitswirtschaft, Landwirtschaft, Bioökonomie und Tourismus. Mit dem Tariftreuegesetz für öffentliche Aufträge sei gute Arbeit gestärkt worden.',
    '[…] haben sich die Strategien der SPD-geführten Landesregierungen bewährt, einen Branchenmix aus Energiewirtschaft, maritimer Industrie, Gesundheitswirtschaft, Landwirtschaft und Bioökonomie sowie Tourismus zu stärken.',
    'einen Branchenmix aus Energiewirtschaft, maritimer Industrie, Gesundheitswirtschaft',
   ),
   ('fdp', 12,
    'Große Chancen werden in Wasserstoff, Kernfusion und weiteren Zukunftstechnologien im Energiebereich gesehen. Auch in maritimer Wirtschaft, Landwirtschaft und technologiegestützten Wertschöpfungsketten könne das Land eine führende Rolle übernehmen. Die Voraussetzungen dafür seien gut.',
    'Große Chancen liegen etwa in Wasserstoff, Kernfusion und weiteren Zukunftstechnologien im Energiebereich. Auch in der maritimen Wirtschaft, in der Landwirtschaft und in technologiegestützten Wertschöpfungsketten kann Mecklenburg-Vorpommern eine führende Rolle übernehmen.',
    'Große Chancen liegen etwa in Wasserstoff, Kernfusion und weiteren Zukunftstechnologien im Energiebereich',
   ),
  ]),
  ('Was braucht die Wirtschaft neben Ansiedlung und Förderung?', [
   ('gruene', 29,
    'Für die Wirtschaft sollen die Grundlagen gesichert werden: leistungsfähige Infrastruktur, gute Bildung und verlässliche Gesundheitsversorgung. Hinzu kommt eine offene Gesellschaft, die Fachkräfte anzieht und hält. Ziel ist eine nachhaltig wachsende Wirtschaft.',
    'Gleichzeitig sorgen wir für die Grundlagen, die Wirtschaft braucht: eine leistungsfähige Infrastruktur, gute Bildung, verlässliche Gesundheitsversorgung und eine offene Gesellschaft, die Fachkräfte anzieht und hält.',
    'eine leistungsfähige Infrastruktur, gute Bildung, verlässliche Gesundheitsversorgung und eine offene Gesellschaft',
   ),
   ('afd', 30,
    'Reallabore, Unternehmen, Museen und Hochschulen sollen vor Ort vernetzt werden. Ausgerichtet wird dies auf die spezifischen Stärken des Landes. Genannt werden maritime Wirtschaft, Luft- und Raumfahrt, Landwirtschaftstechnik, Gesundheitswirtschaft und Lebensmittelindustrie.',
    '[Wir wollen] Reallabore, Unternehmen, Museen und Hochschulen vor Ort vernetzen und auf die spezifischen Stärken MVs ausgerichtet sind: maritime Wirtschaft, Luft- und Raumfahrt, Landwirtschaftstechnik, Gesundheitswirtschaft und Lebensmittelindustrie.',
    'auf die spezifischen Stärken MVs ausgerichtet sind: maritime Wirtschaft, Luft- und Raumfahrt',
   ),
   ('linke', 9,
    'Gute Arbeitsbedingungen, Mitbestimmung und tarifliche Absicherung gelten als Grundlage wirtschaftlicher Entwicklung. Das Tariftreuegesetz soll weiterentwickelt und Betriebs- und Personalräte gestärkt werden. Arbeitsschutzbehörden sollen aufgabengerecht mit Personal ausgestattet werden.',
    'Gute Arbeitsbedingungen, Mitbestimmung und tarifliche Absicherung gehören ebenso dazu wie die Förderung von Innovation und nachhaltiger Wirtschaftsentwicklung. […] Wir wollen: […] Arbeitsschutzbehörden aufgabengerecht mit Personal ausstatten. Das Tariftreuegesetz weiterentwickeln, Betriebs- und Personalräte stärken und das Personalvertretungsgesetzes evaluieren.',
    'Das Tariftreuegesetz weiterentwickeln, Betriebs- und Personalräte stärken',
   ),
   ('bsw', 7,
    'Häfen, Flughäfen und Infrastruktur sollen vorrangig zivil genutzt werden. Pläne zur Einbindung von Infrastruktur wie Krankenhäusern und Straßen in kriegsvorbereitende Maßnahmen werden abgelehnt. Zivile Arbeitsplätze und industrielle Strukturen sollen erhalten bleiben.',
    '• Häfen, Flughäfen und Infrastruktur sollen vorrangig zivil genutzt werden. Wir lehnen die Pläne zur Einbindung von Infrastruktur, wie Krankenhäuser und Straßen, in kriegsvorbereitende Maßnahmen grundsätzlich ab. • Erhalt ziviler Arbeitsplätze und industrieller Strukturen.',
    'Häfen, Flughäfen und Infrastruktur sollen vorrangig zivil genutzt werden',
   ),
  ]),
 ]),
]


# ---------------------------------------------------------------------------
# Dritte Frage je Thema (13. September 2026). Getrennt notiert, damit die
# ersten beiden Fragen unangetastet bleiben; angehaengt wird am Dateiende.
# Eine Partei kommt je Thema hoechstens einmal oefter vor als eine andere -
# dieselbe Ausgewogenheitsregel, die baue_datensatz.py prueft.
# Das CDU-Programm traegt Zeilennummern im Text: Markierungen liegen deshalb
# immer innerhalb einer Zeile, die Zitate sind ohne die Nummern gesetzt.
DRITTE = {
 'zuwanderung': ('Soll die Bezahlkarte für Geflüchtete bleiben?', [
   ('fdp', 143,
    'Das landesweit einheitliche Bezahlkartensystem soll konsequent umgesetzt und beibehalten werden. Es soll Transparenz schaffen und Missbrauch vorbeugen.',
    '[…] dass staatliche Leistungen dort ankommen, wo sie hingehören: bei den Menschen, die sie wirklich benötigen. Daher muss das landesweit einheitliches Bezahlkartensystem konsequent umgesetzt und beibehalten werden. Es schafft Transparenz und beugt Missbrauch vor.',
    'Bezahlkartensystem konsequent umgesetzt und beibehalten werden',
   ),
   ('gruene', 92,
    'Die Bezahlkarte soll abgeschafft werden, damit alle Geflüchteten einen selbstbestimmten Alltag führen können. Zugleich sollen faire Verfahren durch unabhängige Beratung gestärkt werden.',
    'Wir gestalten Asylpolitik menschlich, verlässlich und gerecht. Wir schaffen die Bezahlkarte ab und ermöglichen allen Geflüchteten einen selbstbestimmten Alltag. Gleichzeitig stärken wir faire Verfahren durch unabhängige Beratung […]',
    'Wir schaffen die Bezahlkarte ab',
   ),
   ('linke', 14,
    'Die Bezahlkarte soll in ihrer jetzigen Form abgeschafft werden. Geflüchtete sollen gleichberechtigt am Zahlungsverkehr teilnehmen, ohne Obergrenze für Bargeld und mit der Möglichkeit von Überweisungen.',
    'Die Abschaffung der Bezahlkarte in der jetzigen Form, eine gleichberechtigte Teilhabe am Finanzverkehr, die Aufhebung der Begrenzung für Bargeldabhebungen sowie die Ermöglichung von Überweisungen.',
    'Die Abschaffung der Bezahlkarte in der jetzigen Form',
   ),
   ('afd', 50,
    'Asylbewerber und Ausreisepflichtige sollen nur noch Sachleistungen nach dem Prinzip Bett, Brot, Seife erhalten. Wer die Bezahlkarte umgeht oder anderen dabei hilft, soll strafrechtlich verfolgt werden können.',
    '[…] das Sachleistungsprinzip maximal umsetzen. In den zu schaffenden Ausreiseeinrichtungen des Landes sollen zukünftig keinerlei Geldleistungen mehr ausgegeben werden. Zukünftig gilt stattdessen das „Bett-Brot-Seife-Prinzip“ für Asylbewerber und Ausreisepflichtige. […] Den Missbrauch der Bezahlkarte durch meist linksradikale Akteure werden wir konsequent beenden. Hierfür fordern wir auf Bundesebene die Ermöglichung strafrechtlicher Verfolgung […]',
    'Den Missbrauch der Bezahlkarte durch meist linksradikale Akteure werden wir konsequent beenden',
   ),
 ]),
 'schule': ('Sollen Smartphones an Schulen verboten werden?', [
   ('afd', 31,
    'Die private Handynutzung im Schulalltag soll per Verordnung bis einschließlich Klasse 7 unterbunden werden. Ausnahmen soll es nur in Notfällen oder nach Rücksprache mit der Lehrkraft geben.',
    'Die private Handynutzung im Schulalltag werden wir auf dem Verordnungswege bis einschließlich der 7. Klasse konsequent unterbinden, allenfalls bei Notfällen oder nach Rücksprache mit dem Lehrer soll das Handy genutzt werden dürfen.',
    'bis einschließlich der 7. Klasse konsequent unterbinden',
   ),
   ('bsw', 47,
    'Handys und Tablets sollen aus den Klassenzimmern der Grundschulen verbannt werden. Digitale Geräte sollen nicht in den Mittelpunkt des Unterrichts rücken, sie gelten als bloße Werkzeuge.',
    'Handys und Tablets wollen wir aus den Klassenzimmern der Grundschulen verbannen. Digitale Geräte wie Smartphones und Tablets dürfen nicht in den Mittelpunkt des Unterrichts gerückt werden. Sie sind nicht die Lösung der Bildungsprobleme, sondern lediglich Werkzeuge […]',
    'Handys und Tablets wollen wir aus den Klassenzimmern der Grundschulen verbannen',
   ),
   ('cdu', 53,
    'Die private Smartphone-Nutzung soll landeseinheitlich bis Klasse 10 im Unterricht und auf dem ganzen Schulgelände verboten werden. Ab Klasse 7 dürfen Smartphones nur auf Anweisung der Lehrkraft genutzt werden.',
    'Für die private Smartphone-Nutzung werden wir eine landeseinheitliche Regelung einführen, nach der die private Nutzung von Smartphones im Unterricht und auf dem gesamten Schulgelände bis Klasse zehn untersagt ist. Von Klasse sieben bis zehn darf der Einsatz von Smartphones ausschließlich auf Anweisung des Lehrers erfolgen.',
    'dem gesamten Schulgelände bis Klasse zehn untersagt ist',
   ),
 ]),
 'kita': ('Wie viele Kinder soll eine Fachkraft in der Kita betreuen?', [
   ('afd', 20,
    'Der Betreuungsschlüssel soll deutlich verbessert werden, auf 1:4 in der Krippe, 1:10 im Kindergarten und 1:17 im Hort. Dafür sollen Erzieher gut bezahlt werden.',
    '[…] die deutliche Verbesserung der Betreuungsquote auf 1:4 in der Krippe, 1:10 im Kindergarten und 1:17 im Hort durchsetzen. Damit dies gelingt, brauchen wir gut bezahlte Erzieher.',
    'Betreuungsquote auf 1:4 in der Krippe, 1:10 im Kindergarten und 1:17 im Hort',
   ),
   ('cdu', 45,
    'Personal, das durch sinkende Kinderzahlen frei wird, soll weitgehend für bessere Betreuungsschlüssel eingesetzt werden. Ein Perspektivplan soll die Relation in Richtung der empfohlenen 1:3 in der Krippe und 1:7,5 im Kindergarten verbessern.',
    'Deshalb werden freiwerdende Ressourcen weitgehend für eine Verbesserung der Betreuungsschlüssel und spezifische Fördermaßnahmen eingesetzt. Die Bertelsmann-Stiftung empfiehlt in ihrem Fachkräfteradar eine Erzieher-Kind-Relation von 1:3 in der Krippe und 1:7,5 in der KiTa […]. Mit den gesellschaftlich relevanten Akteuren werden wir einen Perspektivplan für die Verbesserung der Erzieher-Kind-Relation entwickeln.',
    'Relation von 1:3 in der Krippe und 1:7,5 in der KiTa',
   ),
   ('spd', 4,
    'Der beschlossene Zukunftsplan Kita soll Schritt für Schritt umgesetzt werden: in der Krippe ab 2027 fünf statt sechs Kinder je Fachkraft, im Kindergarten ab 2028 dreizehn. Im Hort soll die Zahl bis 2029 auf zwanzig sinken.',
    'Wir setzen den beschlossenen Zukunftsplan Kita konsequent um: In der Krippe verkleinern wir die Gruppengröße zum 1. Januar 2027 von 6 auf 5 Kinder je Fachkraft und im Hort zum 1. August 2027 von 22 auf 21 Kinder je Fachkraft. Ab dem 1. Januar 2028 soll die Gruppengröße im Kindergarten auf 13 Kinder je Fachkraft und im Hort ab dem 1. Januar 2029 auf 20 Kinder je Fachkraft gesenkt werden.',
    'In der Krippe verkleinern wir die Gruppengröße zum 1. Januar 2027 von 6 auf 5 Kinder je Fachkraft',
   ),
 ]),
 'gesundheit': ('Wie sollen die Eigenanteile in Pflegeheimen sinken?', [
   ('bsw', 66,
    'Das Land soll die Investitionskosten der Pflegeheime übernehmen, damit die Eigenanteile der Bewohner sinken. Grundlage soll die Landespflegeplanung sein.',
    'Senkung der Eigenanteile pflegebedürftiger Personen in stationären Pflegeeinrichtungen durch Übernahme der Investitionskosten der Einrichtungen durch das Land auf Grundlage der Landespflegeplanung.',
    'durch Übernahme der Investitionskosten der Einrichtungen durch das Land',
   ),
   ('cdu', 78,
    'Das Land soll sich an den Investitionskosten und an der Ausbildungsumlage der Pflege beteiligen. So sollen die Eigenanteile sinken und Pflege bezahlbarer werden.',
    'Wir entlasten Pflegebedürftige und ihre Angehörigen finanziell. Indem wir durch eine Landesbeteiligung an den Investitionskosten und der Ausbildungsumlage die Eigenanteile reduzieren, machen wir Pflege bezahlbarer.',
    'Landesbeteiligung an den Investitionskosten und der Ausbildungsumlage',
   ),
   ('linke', 12,
    'Ein Investitionsprogramm soll notwendige Sanierungen von Pflegeheimen unterstützen. So sollen die Wohnkosten die Eigenanteile nicht noch schneller steigen lassen.',
    'Die notwendigen Sanierungen von vollstationären Einrichtungen durch ein Investitionsprogramm unterstützen, damit die Eigenanteile durch die Kosten des Wohnens nicht schneller in die Höhe getrieben werden.',
    'durch ein Investitionsprogramm unterstützen',
   ),
 ]),
 'mobilitaet': ('Wie soll das Deutschlandticket weiterentwickelt werden?', [
   ('cdu', 124,
    'Das Deutschlandticket soll durch zusätzliche Busangebote auf dem Land ergänzt werden. Für junge Menschen bis 27 Jahre soll es nach dem Vorbild des Seniorentickets vergünstigt werden.',
    'Wir sehen das Deutschland-Ticket als Chance, ergänzt durch ein zusätzliches Busangebot im ländlichen Raum, um Mobilität flächendeckend zu sichern. Gleichzeitig wollen wir ein vergünstigtes Deutschlandticket für junge Menschen bis 27 Jahren nach dem Vorbild des Seniorentickets umsetzen.',
    'vergünstigtes Deutschlandticket für junge Menschen bis',
   ),
   ('fdp', 61,
    'Das Deutschlandticket soll mit einem zukunftsfesten Finanzierungskonzept erhalten bleiben. Das Land soll die notwendigen eigenen Zuschüsse leisten.',
    '[…] uns für den Erhalt eines Deutschlandtickets mit einem zukunftsfesten Finanzierungskonzept einsetzen und die notwendigen landesseitigen Zuschüsse leisten.',
    'Erhalt eines Deutschlandtickets mit einem zukunftsfesten Finanzierungskonzept',
   ),
   ('gruene', 4,
    'Alle Kinder und Jugendlichen sollen Busse und Bahnen kostenfrei nutzen können, mit einem U27-Deutschlandticket. So sollen sie auch ohne Führerschein zu Sportverein, Freunden und Familie kommen.',
    'Wir werden allen Kindern und Jugendlichen die Möglichkeit geben, kostenfrei den öffentlichen Nahverkehr zu nutzen, indem wir ein U27-Deutschlandticket für sie einführen. Damit sie nicht nur zur Schule, sondern auch zum Sportverein, den Freunden und der Familie kommen.',
    'indem wir ein U27-Deutschlandticket für sie einführen',
   ),
 ]),
 'landwirtschaft': ('Wie soll mit dem Wolf umgegangen werden?', [
   ('fdp', 23,
    'Für Wolf, Biber, Wildgänse und Kormoran soll es ein sachgerechtes Bestandsmanagement geben. Beim Wolf sollen klare Bestandsziele gelten und Problemwölfe rechtssicher entnommen werden können.',
    '[…] ein sachgerechtes Bestandsmanagement für Biber, Wildgänse, Kormoran und Wolf unterstützen. Beim Wolf setzen wir uns für ein wirksames Management mit klaren Bestandszielen und rechtssicheren Entnahmen bei Problemwölfen ein.',
    'wirksames Management mit klaren Bestandszielen',
   ),
   ('bsw', 81,
    'Schäden durch Wolf und Biber sollen vollständig entschädigt, der Herdenschutz umfassend gefördert werden. Auffällige Wölfe sollen schnell entnommen werden, dazu soll es wolfsfreie Zonen geben.',
    'Vollständige Entschädigung bei Schäden durch streng geschützte Tiere wie Wolf, Biber und Co. sowie umfassende Förderung des Herdenschutzes. Praxistaugliches Wolfsmanagement mit schneller Entnahme auffälliger Tiere und wolfsfreien Zonen.',
    'Praxistaugliches Wolfsmanagement mit schneller Entnahme auffälliger Tiere',
   ),
   ('linke', 22,
    'Für geschützte Arten wie Wolf und Biber sollen Managementpläne und ein Monitoring vorangebracht werden. Dazu sollen Biotope besser vernetzt und Gewässer renaturiert werden.',
    'Biotopvernetzung stärken und vorrangig wassergebundene Ökosysteme renaturieren. Managementpläne und Monitoring für geschützte Arten, insbesondere für Wolf und Biber, voranbringen.',
    'Managementpläne und Monitoring für geschützte Arten',
   ),
   ('afd', 77,
    'Zurückkehrende Arten wie Wolf, Wisent und Elch sollen nach Möglichkeit Platz bekommen. Eine ungehinderte Ausbreitung in die genutzte Kulturlandschaft wird aber abgelehnt.',
    'Zurückkehrenden Arten wie Wolf, Wisent und Elch muss nach Möglichkeit Platz geboten werden. Eine ungehinderte Ausbreitung in die vom Menschen geschaffene und genutzte Kulturlandschaft lehnen wir jedoch ab.',
    'Eine ungehinderte Ausbreitung in die vom Menschen geschaffene und genutzte Kulturlandschaft lehnen wir jedoch ab',
   ),
 ]),
}

DRITTE.update({
 'sicherheit': ('Soll die Videoüberwachung im öffentlichen Raum ausgeweitet werden?', [
   ('cdu', 6,
    'Angsträume sollen unter anderem durch mehr Videoüberwachung verhindert werden. Dazu kommen je 50 zusätzliche Stellen bei Staatsanwaltschaften und Gerichten sowie bei der Kriminalpolizei.',
    'Schaffung von 50 zusätzlichen Stellen bei den Staatsanwaltschaften und Gerichten sowie von 50 zusätzlichen spezialisierten Stellen bei der Kriminalpolizei, insbesondere zur wirksamen Bekämpfung von Kinderpornografie und Cyberkriminalität; Verhinderung von Angsträumen, unter anderem durch eine Ausweitung der Videoüberwachung.',
    'anderem durch eine Ausweitung der Videoüberwachung',
   ),
   ('bsw', 67,
    'Bürgernähe soll vor allem durch mehr Personal im Streifen- und Ermittlungsdienst entstehen. Einen unverhältnismäßigen Ausbau der Videoüberwachung im öffentlichen Raum soll es nicht geben.',
    'Bürgernähe entsteht vor allem durch ausreichend Personal im Streifen- und Ermittlungsdienst und durch erreichbare Strukturen, nicht durch den unverhältnismäßigen Ausbau von Videoüberwachung im öffentlichen Raum.',
    'nicht durch den unverhältnismäßigen Ausbau von Videoüberwachung im öffentlichen Raum',
   ),
   ('fdp', 133,
    'Flächendeckende Videoüberwachung und automatisierte Gesichtserkennung werden klar abgelehnt. Freiheit soll nicht permanenter Beobachtung weichen.',
    '[…] eine flächendeckende Videoüberwachung und automatisierte Gesichtserkennung klar und deutlich ablehnen. Freiheit darf nicht permanenter Beobachtung weichen.',
    'eine flächendeckende Videoüberwachung und automatisierte Gesichtserkennung klar und deutlich ablehnen',
   ),
   ('linke', 19,
    'Staatstrojaner, Vorratsdatenspeicherung und automatisierte Gesichtserkennung sollen nicht eingesetzt werden. Palantir und allgegenwärtige Videoüberwachung werden ausdrücklich abgelehnt.',
    'Das Recht auf informationelle Selbstbestimmung sicherstellen: kein Einsatz von Staatstrojanern, Vorratsdatenspeicherung oder automatisierter Gesichtserkennung. Insbesondere stellen wir uns gegen eine Nutzung von Palantir oder allgegenwärtiger Videoüberwachung.',
    'Insbesondere stellen wir uns gegen eine Nutzung von Palantir oder allgegenwärtiger Videoüberwachung',
   ),
 ]),
 'energie': ('Wie soll Strom für die Menschen im Land bezahlbarer werden?', [
   ('bsw', 27,
    'Die Netzentgelte sollen bundesweit angeglichen und gesenkt werden, weil Erzeugerregionen bisher benachteiligt sind. Neue regionale Marktmodelle sollen die Wertschöpfung im Land halten.',
    'Eine zentrale Stellschraube für bezahlbare Energie ist die Reform der Netzentgelte. Wir setzen uns für eine bundesweite Angleichung und Senkung der Netzentgelte ein. Die derzeitige Kostenverteilung benachteiligt insbesondere energieerzeugende Regionen wie Mecklenburg-Vorpommern. Darüber hinaus braucht es neue regionale Marktmodelle, um Wertschöpfung im Land zu halten.',
    'Wir setzen uns für eine bundesweite Angleichung und Senkung der Netzentgelte ein',
   ),
   ('gruene', 9,
    'Haushalte im Umkreis von Windrädern und Solarparks sollen vollständig von den Netzentgelten befreit werden. Wer die Energiewende trägt, soll günstigeren Strom erhalten.',
    'Wer die Energiewende trägt, soll auch günstigeren Strom erhalten. […] Haushalte im unmittelbaren Umfeld von Windenergieanlagen (2 km Radius) sowie von Freiflächen-Photovoltaikanlagen (500 m Radius) befreien wir vollständig von den Netzentgelten auf ihren Stromverbrauch.',
    'befreien wir vollständig von den Netzentgelten',
   ),
   ('cdu', 119,
    'Menschen in Regionen mit Windkraftanlagen sollen direkte Stromgutschriften erhalten, dazu soll es einen Landesbonus geben. So sollen sie fair an der Energieerzeugung vor Ort beteiligt werden.',
    'Neben der Einführung eines „MV-Bonus“ setzen wir auf direkte Stromgutschriften für Menschen in Regionen mit Windkraftanlagen, um die Akzeptanz der Energiewende zu stärken und eine faire finanzielle Teilhabe an der regionalen Energieerzeugung zu ermöglichen.',
    'setzen wir auf direkte Stromgutschriften',
   ),
   ('afd', 17,
    'Grundlastfähige Gaskraftwerke sollen ins Land geholt werden, verbunden mit einer Wiedereröffnung von Nord Stream. Als Option soll auch ein Wiedereinstieg in die Kernenergie offenstehen.',
    '[…] bezahlbare Stromversorgung. Wir werden deshalb daran arbeiten, grundlastfähige Gaskraftwerke nach Mecklenburg-Vorpommern zu holen, die insbesondere in Verbindung mit einer Wiedereröffnung von Nord Stream unschlagbare Argumente für Investitionen in MV liefern können. Zusätzlich mit der Option eines Wiedereinstiegs in die Kernenergie könnte so zum Beispiel im Bereich Lubmin […] ein modernes Industrie-Cluster entstehen […]',
    'grundlastfähige Gaskraftwerke nach Mecklenburg-Vorpommern zu holen',
   ),
 ]),
 'wirtschaft': ('Soll das Tariftreue- und Vergabegesetz bleiben?', [
   ('afd', 13,
    'Lohnpolitische Kriterien sollen aus dem Vergaberecht gestrichen werden. Aufträge sollen nach Qualität, Zuverlässigkeit und Wirtschaftlichkeit vergeben werden.',
    'Das geltende Tariftreue- und Vergabegesetz Mecklenburg-Vorpommerns ist ein Bürokratiemonster, das kleine Unternehmen und Einzelunternehmer systematisch benachteiligt. […] Wir werden das Gesetz grundlegend überarbeiten und lohnpolitische Kriterien aus dem Vergaberecht streichen. Öffentliche Aufträge müssen nach Qualität, Zuverlässigkeit und Wirtschaftlichkeit vergeben werden […]',
    'lohnpolitische Kriterien aus dem Vergaberecht streichen',
   ),
   ('spd', 3,
    'Unternehmen sollen auch künftig nur dann öffentliche Aufträge erhalten, wenn sie Tariflöhne oder tarifgleiche Löhne zahlen. Das soll Beschäftigte und tariftreue Betriebe schützen.',
    'Mit dem Tariftreue- und Vergabegesetz MV erhalten Unternehmen auch in Zukunft nur dann öffentliche Aufträge, wenn sie Tariflöhne oder tarifgleiche Löhne zahlen. Das ist gerecht für die Beschäftigten, macht Arbeiten in MV attraktiver und schützt Unternehmen, die heute […]',
    'erhalten Unternehmen auch in Zukunft nur dann öffentliche Aufträge',
   ),
   ('bsw', 19,
    'Öffentliche Aufträge und Fördermittel sollen an gute Arbeit gekoppelt werden. Tariftreue, faire Arbeitsbedingungen und klare Standards sollen Voraussetzung sein.',
    'Öffentliche Aufträge und Fördermittel an gute Arbeit koppeln: Tariftreue, faire Arbeitsbedingungen und klare Standards müssen Voraussetzung sein.',
    'Tariftreue, faire Arbeitsbedingungen und klare Standards müssen Voraussetzung sein',
   ),
   ('fdp', 11,
    'Das Vergaberecht soll radikal modernisiert und von allen vergabefremden Kriterien befreit werden. Ausgeschrieben werden soll erst ab den EU-Schwellenwerten.',
    'Die 16 Bundesländer haben 16 verschiedene Vergabegesetze. Wir Freie Demokraten fordern daher eine radikale Modernisierung des Vergaberechtes unter Herauslösung aller vergabefremden Kriterien. Aufträge sollen nach unseren Plänen erst ab einem Auftragswert in Höhe der EU-Schwellenwerte von 216.000 € für Dienstleistungen und ab 5.404.000 € für Bauleistungen ausgeschrieben werden müssen und dem Vergaberecht unterliegen.',
    'radikale Modernisierung des Vergaberechtes unter Herauslösung aller vergabefremden Kriterien',
   ),
 ]),
})

for _t in THEMEN:
    if _t[0] in DRITTE:
        _t[3].append(DRITTE[_t[0]])


# Vierte Fragen (gezielt, September 2026): nur Parteien, die im Thema bisher
# einmal auftreten - haelt die Ausgewogenheit und hebt seltene Paarungen.
VIERTE = {
 'landwirtschaft': ('Wie sollen die Moore im Land geschützt werden?', [
   ('cdu', 88,
    'Moorschutz soll über kooperative Modelle und Vertragsnaturschutz mit wirtschaftlichen Anreizen gelingen. Landwirtschaft soll auch in Schutzgebieten möglich bleiben, pauschale Verbote werden ausgeschlossen.',
    'Natur-, Arten- und Moorschutz kooperativ gestalten[:] Landwirtschaft, wirtschaftliche Tragfähigkeit und Naturschutz werden wir vereinen. Dazu setzen wir auf kooperative Modelle und Vertragsnaturschutz mit wirtschaftlichen Anreizen. Landwirtschaft wird damit auch in Schutzgebieten grundsätzlich möglich bleiben. Pauschale Verbote schließen wir aus.',
    'Pauschale Verbote schließen wir aus',
   ),
   ('spd', 83,
    'Auf Moorflächen sollen Photovoltaikanlagen Strom erzeugen. Das soll Landwirten Einkommen sichern und zugleich die Wiedervernässung der Moore voranbringen.',
    'Wir wollen die Nutzung von Mooren zur Photovoltaik-Stromerzeugung erreichen, um Einkommen bei den Landwirten zu ermöglichen und die Wiedervernässung von Mooren voranzutreiben.',
    'Nutzung von Mooren zur Photovoltaik-Stromerzeugung erreichen',
   ),
   ('gruene', 11,
    'Die Wiedervernässung der Moore soll als CO2-Speicher im Landeswassergesetz verankert werden. Zugleich soll die landwirtschaftliche Nutzung der nassen Flächen gefördert werden.',
    'Um das klimaschädliche CO2 besser zu speichern und uns vor Extremwetterereignissen besser zu schützen, werden wir: • die Wiedervernässung der Moore als natürliche CO2-Speicher im Landeswassergesetz fest verankern und zugleich deren landwirtschaftliche Nutzung fördern.',
    'Wiedervernässung der Moore als natürliche CO2-Speicher im Landeswassergesetz fest verankern',
   ),
 ]),
}

for _t in THEMEN:
    if _t[0] in VIERTE:
        _t[3].append(VIERTE[_t[0]])
