# -*- coding: utf-8 -*-
"""Datensatz Landtagswahl Mecklenburg-Vorpommern 2026. Alle Aussagen aus den PDFs."""

WAHL = {
    "id": "lt-mv-2026",
    "name": "Landtagswahl Mecklenburg-Vorpommern",
    "region": "Mecklenburg-Vorpommern",
    "wahltag": "2026-09-20",
    "kuerzel": "mv",
}

PROGRAMME = {
    "cdu": ("Chancenland. Wahlprogramm zur Landtagswahl 2026",
            "https://cdu-mv.de/wp-content/uploads/2026/06/Wahlprogramm-CDU-MV-2026.pdf"),
    "spd": ("Aufschwung, Zusammenhalt und Respekt. Regierungsprogramm 2026–2031",
            "https://spd-mv.de/uploads/bilderpool/2-Mecklenburg-Vorpommern/Wahlen-und-Kandidaturen/2026-Landtagswahlen/SPD_MV_Programm_2026.pdf"),
    "gruene": ("Klare Kante Zukunft. Für Mensch und Natur in MV. Wahlprogramm 2026",
               "https://schwerin.news/wp-content/uploads/2026/08/wahlprogramm-gruene.pdf"),
    "fdp": ("Freiheit, Leistung, Erfolg. Programm zur Landtagswahl 2026",
            "https://www.fdp-mv.de/sites/default/files/2026-06/Landtagswahlprogramm_2026.pdf"),
    "afd": ("Bereit für die blaue Wende. AfD-Regierungsprogramm zur Landtagswahl 2026",
            "https://afd-mv.de/wp-content/uploads/2026/06/AfD-Regierungsprogramm-Mecklenburg-Vorpommern-2026.pdf"),
    "linke": ("Sozial. Gerecht. Antifaschistisch. Programm zur Landtagswahl 2026",
              "https://www.dielinke-rostock.de/fileadmin/kreise/rostock/user/upload/Linke_MV_Landtagswahlprogramm_2026.pdf"),
    "bsw": ("Frischer Wind in MV! Landeswahlprogramm 2026",
            "https://mv.bsw-vg.de/wp-content/uploads/2026/04/Landeswahlprogramm-2026.pdf"),
}

THEMEN = [
 ("sicherheit", "Innere Sicherheit und Polizei",
  "Personal, Präsenz und Kontrolle der Polizei.", [
  ("cdu", 26,
   "Ziel ist eine präsente Landespolizei mit schnellen Reaktionszeiten. Dazu kommen eine effektive Strafverfolgung und eine funktionierende Justiz. Auch Katastrophen- und Bevölkerungsschutz sollen ausgebaut werden.",
   "Unser Ziel: Der wirksame Schutz von Leben, Freiheit und Eigentum, eine präsente Landespolizei mit schnellen Reaktionszeiten, eine effektive Strafverfolgung, eine funktionierende Justiz, der Ausbau des Katastrophen- und Bevölkerungsschutzes.",
   "Landespolizei mit schnellen Reaktionszeiten, eine effektive Strafverfolgung, eine"),
  ("spd", 45,
   "Die Landespolizei wurde in den vergangenen Jahren personell, technisch und organisatorisch modernisiert. Dazu zählen zusätzliche Ausbildungskapazitäten und eine bessere Ausstattung. Die öffentliche Sicherheit sei damit weiter gefestigt worden.",
   "In den vergangenen Jahren haben wir die öffentliche Sicherheit in Mecklenburg-Vorpommern weiter gefestigt. Die Landespolizei wurde personell, technisch und organisatorisch modernisiert – mit zusätzlichen Ausbildungskapazitäten, besserer Ausstattung sowie neuen Angeboten.",
   "Die Landespolizei wurde personell, technisch und organisatorisch modernisiert"),
  ("gruene", 77,
   "Gefordert werden ausreichende Neueinstellungen und eine Reform der Aus- und Fortbildung der Landespolizei. Diese soll einen höheren Anteil politischer Bildung vorsehen. Zudem soll besser auf Einsätze mit Menschen in psychischen Ausnahmezuständen vorbereitet werden.",
   "Für eine bürger*innennahe Polizei wollen wir: • ausreichende Neueinstellungen und eine Reform der Aus- und Fortbildung der Landespolizei, die einen höheren Anteil an politischer Bildung vorsieht sowie besser auf Einsatzsituationen mit Menschen in psychischen Ausnahmezuständen vorbereitet.",
   "ausreichende Neueinstellungen und eine Reform der Aus- und Fortbildung der Landespolizei"),
  ("fdp", 133,
   "Der Personalschlüssel der Landespolizei soll bedarfs- und aufgabengerecht angepasst werden. Mehr Polizeibeamte sollen wieder im operativen Dienst eingesetzt werden. Sicherheit entstehe durch Präsenz.",
   "Wir Freie Demokraten werden: den Personalschlüssel der Landespolizei bedarfs- und aufgabengerecht anpassen, und wieder mehr Polizeibeamte im operativen Dienst einsetzen. Sicherheit entsteht durch Präsenz.",
   "den Personalschlüssel der Landespolizei bedarfs- und aufgabengerecht anpassen"),
  ("afd", 37,
   "Am Ziel von 6.200 Beamten der Landespolizei wird festgehalten. Die Fachhochschule Güstrow müsse fortlaufend genügend gut ausgebildete Absolventen hervorbringen. Die Polizei soll von Aufgaben entlastet und ihre Kompetenzen ausgebaut werden.",
   "Personalbestand der Polizei sichern, Kompetenzen ausbauen, Kräfte freimachen: Wir halten am Ziel von 6200 Beamten der Landespolizei fest. Die Fachhochschule Güstrow muss fortlaufend genügend gut ausgebildete und motivierte Polizeiabsolventen hervorbringen.",
   "Wir halten am Ziel von 6200 Beamten der Landespolizei fest"),
  ("linke", 20,
   "Alle Sicherheitsbefugnisse sollen kritisch auf die Einhaltung der Bürger- und Freiheitsrechte geprüft werden. Gefordert wird eine von der Polizei unabhängige Beschwerdestelle mit ausreichendem Mandat. Zudem sollen Kontrollquittungen für Betroffene polizeilicher Maßnahmen eingeführt werden.",
   "• Alle Sicherheitsbefugnisse kritisch auf Einhaltung der Bürger:innen- und Freiheitsrechte prüfen. […] • Eine von der Polizei unabhängige Beschwerdestelle mit ausreichendem Mandat, Ressourcen und Befugnissen, um Fehlverhalten der Polizei effektiv zu verfolgen und aufzuklären.",
   "Eine von der Polizei unabhängige Beschwerdestelle mit ausreichendem Mandat"),
  ("bsw", 67,
   "Die Polizei soll sichtbar, ansprechbar und schnell vor Ort sein, in Städten wie im ländlichen Raum. Gesetzt wird auf Präsenz vor Technik: mehr Einsatzkräfte statt Ausweitung der Videoüberwachung. Polizeireviere sollen insbesondere in ländlichen Regionen erhalten bleiben.",
   "Polizei muss sichtbar, ansprechbar und schnell vor Ort sein – in Städten wie im ländlichen Raum. […] • Präsenz vor Technik: mehr Einsatzkräfte statt Ausweitung von Videoüberwachung im öffentlichen Raum. • Erhalt von Polizeirevieren, insbesondere in ländlichen Regionen.",
   "Präsenz vor Technik: mehr Einsatzkräfte statt Ausweitung von Videoüberwachung im öffentlichen Raum"),
  ]),

 ("zuwanderung", "Zuwanderung und Integration",
  "Aufnahme, Rückführung, Sprache und Arbeitsmarkt.", [
  ("cdu", 36,
   "Die Handyortung soll gezielt zur Durchsetzung des Rechtsstaats genutzt werden, unter anderem bei untergetauchten Ausreisepflichtigen. Damit sollen gescheiterte Abschiebungen reduziert werden. Dafür brauche es eine klare rechtliche Grundlage.",
   "Wir wollen, dass die Handyortung gezielt zur Durchsetzung des Rechtsstaats genutzt werden soll, unter anderem bei untergetauchten Ausreisepflichtigen, um gescheiterte Abschiebungen zu reduzieren und staatliche Maßnahmen effizient umzusetzen.",
   "unter anderem bei untergetauchten Ausreisepflichtigen, um"),
  ("spd", 61,
   "Übergänge aus dem Asylsystem in die Erwerbsmigration sollen erleichtert werden. Die Anerkennung von Berufsabschlüssen wird beschleunigt. Insbesondere Frauen sollen beim Zugang zu Sprachkursen, Ausbildung und Beschäftigung unterstützt werden.",
   "[Wir erleichtern] Übergänge aus dem Asylsystem in die Erwerbsmigration, beschleunigen die Anerkennung von Berufsabschlüssen und unterstützen insbesondere Frauen beim Zugang zu Sprachkursen, Ausbildung und Beschäftigung.",
   "beschleunigen die Anerkennung von Berufsabschlüssen und unterstützen insbesondere Frauen beim Zugang zu Sprachkursen"),
  ("gruene", 30,
   "Unternehmen sollen dabei unterstützt werden, Fachkräfte zu gewinnen und zu halten. Dazu dienen klare Anlaufstellen für Zuwanderung und Rückkehr. Hinzu kommen bessere Übergänge von Schule, Ausbildung und Studium in den Beruf.",
   "Wir unterstützen Unternehmen dabei, Fachkräfte zu gewinnen und zu halten: mit klaren Anlaufstellen für Zuwanderung und Rückkehr, besseren Übergängen von Schule, Ausbildung und Studium in den Beruf und einer engeren Zusammenarbeit zwischen Bildung und Wirtschaft.",
   "mit klaren Anlaufstellen für Zuwanderung und Rückkehr"),
  ("fdp", 143,
   "Abschiebungen sollen bei Vorliegen der Voraussetzungen konsequent umgesetzt werden, Vollzugsdefizite dürfe es nicht geben. Menschen ohne Bleibeperspektive sollen nicht erst auf die Kommunen verteilt werden. Verfahren sollen zügig abgeschlossen werden.",
   "Menschen ohne Bleibeperspektive sollen nicht erst auf die Kommunen verteilt werden, wenn sie ohnehin abgeschoben werden müssen. Abschiebungen müssen bei Vorliegen der Voraussetzungen konsequent umgesetzt werden. Vollzugsdefizite bei Abschiebungen darf es nicht geben.",
   "Abschiebungen müssen bei Vorliegen der Voraussetzungen konsequent umgesetzt werden"),
  ("afd", 11,
   "Die illegale Einwanderung soll eingedämmt werden. Kriminelle und vollziehbar ausreisepflichtige Migranten sollen konsequent abgeschoben werden. Zugleich soll die Polizei modern ausgestattet und ihre Präsenz auf den Straßen erhöht werden.",
   "[Wir werden] unsere Polizei modern ausstatten und ihre Präsenz auf den Straßen erhöhen. Die illegale Einwanderung werden wir eindämmen, indem wir kriminelle und vollziehbar ausreisepflichtige Migranten konsequent abschieben.",
   "indem wir kriminelle und vollziehbar ausreisepflichtige Migranten konsequent abschieben"),
  ("linke", 13,
   "Lebensgefährliche Abschiebungen sollen beendet werden, besonders bei unbegleiteten minderjährigen Flüchtlingen. Die UN-Kinderrechtskonvention soll uneingeschränkt angewendet werden. Integration wird als wechselseitiger Prozess verstanden.",
   "Integration ist ein wechselseitiger Prozess, der Unterstützung, Bildung und gesellschaftliche Offenheit erfordert. Wir wollen: • Lebensgefährliche Abschiebungen beenden, besonders für unbegleitete minderjährige Flüchtlinge sowie die UN-Kinderrechtskonvention uneingeschränkt anwenden.",
   "Lebensgefährliche Abschiebungen beenden, besonders für unbegleitete minderjährige Flüchtlinge"),
  ("bsw", 72,
   "Zuwanderung soll verantwortungsvoll gestaltet werden: leistbar, rechtsstaatlich und integrationsfähig. Am Grundrecht auf Asyl für politisch Verfolgte wird festgehalten. Zuwanderungspolitik brauche Augenmaß und Rechtssicherheit statt ideologischer Schnellschüsse.",
   "6.2. Zuwanderung: Zuwanderung verantwortungsvoll gestalten – leistbar, rechtsstaatlich und integrationsfähig. Das Grundrecht auf Asyl für politisch verfolgte Menschen [bleibt]. […] [Zuwanderungspolitik] braucht Augenmaß, Verantwortung und Rechtssicherheit – keine ideologischen Schnellschüsse.",
   "Zuwanderung verantwortungsvoll gestalten – leistbar, rechtsstaatlich und integrationsfähig"),
  ]),

 ("schule", "Schule und Unterrichtsversorgung",
  "Unterrichtsausfall, Lehrkräfte und Schulqualität.", [
  ("cdu", 46,
   "Der Unterrichtsausfall soll beendet werden. Der Anteil der Schüler ohne Schulabschluss soll drastisch verringert werden. Ziel ist, alle Schülerinnen und Schüler zu echter Ausbildungsreife zu führen.",
   "Unterrichtsausfall beenden, Grundschul-Garantie und hochqualitativer Unterricht […]. Unser Ziel: Den Unterrichtsausfall beenden, den Anteil der Schüler ohne Schulabschluss drastisch verringern und alle Schülerinnen und Schüler zu echter Ausbildungs- [reife führen].",
   "Den Unterrichtsausfall beenden, den Anteil der Schüler ohne"),
  ("spd", 4,
   "Ziel ist eine flächendeckende und hochwertige Unterrichtsversorgung im Land. Lehrkräfte sollen unter anderem durch eine Reduzierung der Unterrichtsverpflichtung entlastet werden. Dies soll im Rahmen des Bildungspakts Gute Schule geschehen.",
   "Unser Ziel ist, eine flächendeckende und hochwertige Unterrichtsversorgung im Land abzusichern und sich bietende Möglichkeiten zu nutzen, um Lehrkräfte, u.a. durch eine Reduzierung der Unterrichtsverpflichtung, zu entlasten.",
   "eine flächendeckende und hochwertige Unterrichtsversorgung im Land abzusichern"),
  ("gruene", 42,
   "Gesetzt wird auf multiprofessionelle Teams, in denen Fachleute wirklich zusammenarbeiten. Sie sollen nicht nur nebeneinander agieren. Lehrkräfte sollen dadurch gestärkt werden.",
   "6.2. Lehrkräfte stärken. „Wir setzen auf multiprofessionelle Teams, in denen Fachleute wirklich zusammenarbeiten und nicht nur nebeneinander agieren.“",
   "Wir setzen auf multiprofessionelle Teams,"),
  ("fdp", 86,
   "Die Arbeitsbedingungen für Lehrkräfte sollen durch weniger Bürokratie verbessert werden. Dazu kommen eine bessere digitale Basisausstattung und verlässliche Zuständigkeiten für Wartung und technische Betreuung. Schulen sollen zudem über den Weg zum Abitur selbst entscheiden können.",
   "[Wir wollen] die Arbeitsbedingungen für Lehrkräfte durch weniger Bürokratie, bessere digitale Basisausstattung und verlässliche Zuständigkeiten für Wartung und technische Betreuung verbessern.",
   "die Arbeitsbedingungen für Lehrkräfte durch weniger Bürokratie, bessere digitale Basisausstattung"),
  ("afd", 23,
   "Eine jahrzehntelange Politik des kleinsten gemeinsamen Nenners habe sichtbare Schäden hinterlassen. Genannt werden ideologische Experimente, Unterrichtsausfall und überforderte Lehrkräfte. Schulabgänger seien weder ausbildungs- noch studierfähig.",
   "Mecklenburg-Vorpommern hat eine jahrzehntelange Politik des kleinsten gemeinsamen Nenners, geprägt von ideologischen Experimenten, vernachlässigten pädagogischen Grundlagen, Unterrichtsausfall, sinkenden Leistungen, überforderten Lehrkräften und Schulabgängern, die weder ausbildungs- noch studierfähig sind, sichtbare Schäden hinterl[assen].",
   "vernachlässigten pädagogischen Grundlagen, Unterrichtsausfall, sinkenden Leistungen"),
  ("linke", 5,
   "Gute Bildung entstehe dort, wo ausreichend Zeit, Unterstützung und verlässliche Strukturen vorhanden sind. Lehrkräfte könnten ihren Auftrag nur erfüllen, wenn sie entlastet werden. Schule brauche multiprofessionelle Unterstützung.",
   "Gute Bildung durch mehr Personal: Gute Bildung entsteht dort, wo ausreichend Zeit, Unterstützung und verlässliche Strukturen vorhanden sind. Lehrkräfte können ihren Bildungsauftrag nur dann gut erfüllen, wenn sie entlastet werden.",
   "Lehrkräfte können ihren Bildungsauftrag nur dann gut erfüllen, wenn sie entlastet werden"),
  ("bsw", 46,
   "Schulen brauchen Zeit, verlässliche Rahmenbedingungen und ausreichend Unterstützung. Überschaubare Klassen und engagierte Lehrkräfte machten Lernen wirksam und gerecht. Hinzu kommen ein verlässliches Unterstützungsnetzwerk und vielfältige Bildungsangebote.",
   "Schulen brauchen Zeit, verlässliche Rahmenbedingungen und ausreichend Unterstützung. Überschaubare Klassen, engagierte Lehrkräfte, ein verlässliches Unterstützungsnetzwerk und vielfältige Bildungsangebote machen Lernen wirksam, gerecht und spannend.",
   "Überschaubare Klassen, engagierte Lehrkräfte, ein verlässliches Unterstützungsnetzwerk"),
  ]),

 ("kita", "Frühkindliche Bildung und Kita",
  "Betreuungsschlüssel, Qualität und Elternbeiträge.", [
  ("cdu", 41,
   "Neubauten und Sanierungen von Schul- und Sportstätten, Kitas und Horteinrichtungen sollen auch durch Bund und Land finanziert werden. Damit sollen die Gemeinden entlastet werden. EU-Mittel sollen praxisgerechter für die Kommunen genutzt werden.",
   "Insbesondere Neubauten und Sanierungen von Schul- und Sportstätten, Kitas und Horteinrichtungen sollten auch durch Bund und Land zur Entlastung der Gemeinden finanziert werden.",
   "Neubauten und Sanierungen von Schul- und Sportstätten, Kitas und Horteinrichtungen"),
  ("spd", 2,
   "Mit beitragsfreien Kitas und besseren Bildungsangeboten sei das Land sozial gerechter geworden. Hinzu kamen gezielte Investitionen in Infrastruktur. Dieser Kurs steht für einen Aufschwung, von dem alle profitieren sollen.",
   "Mit beitragsfreien Kitas, besseren Bildungsangeboten, gezielten Investitionen in Infrastruktur und einem starken Einsatz für gute Arbeit haben wir gezeigt: Aufschwu[ng ist möglich].",
   "Mit beitragsfreien Kitas, besseren Bildungsangeboten, gezielten Investitionen in Infrastruktur"),
  ("gruene", 41,
   "Der Kita-Betreuungsschlüssel soll gesenkt und die Qualität verbessert werden. Zu große Gruppen und zu wenig Personal gingen zulasten von Kindern und Fachkräften. Horte liefen oft nur nebenher mit.",
   "6.1. Kita-Betreuungsschlüssel senken und Qualität verbessern […]. Zu große Gruppen, zu wenig Personal und Horte, die oft nur nebenher mitlaufen, gehen zulasten der Kinder und der Fachkräfte.",
   "Kita-Betreuungsschlüssel senken und Qualität verbessern"),
  ("fdp", 37,
   "Die Landesfinanzierung für die frühkindliche Betreuung in Kitas und Kindertagespflegestellen soll überprüft und an die tatsächlichen Notwendigkeiten angepasst werden. Die Trägervielfalt soll erhalten bleiben. Kommunen sollen bei Leistungen nach dem Bundesteilhabegesetz vollständig refinanziert werden.",
   "[Wir wollen] die Finanzierung des Landes für die frühkindliche Betreuung in Kitas und Kindertagespflegestellen überprüfen und an die tatsächlichen Notwendigkeiten anpassen[;] uns für den Erhalt der Trägervielfalt […] [einsetzen].",
   "die Finanzierung des Landes für die frühkindliche Betreuung in Kitas und Kindertagespflegestellen überprüfen"),
  ("afd", 18,
   "Vorgesehen sind konkrete Maßnahmen von einem Baby-Begrüßungsgeld bis zu besseren Kita-Betreuungsschlüsseln. Hinzu kommt der Schutz von Kindern vor Gewalt und ideologischer Einflussnahme. Junge Eltern sollen nicht mit bürokratischen Hürden überzogen werden.",
   "Wir begegnen dieser Entwicklung mit konkreten Maßnahmen. Vom Baby-Begrüßungsgeld über bessere Kita-Betreuungsschlüssel bis hin zum Schutz von Kindern vor Gewalt und ideologischer Einflussnahme.",
   "Vom Baby-Begrüßungsgeld über bessere Kita-Betreuungsschlüssel"),
  ("linke", 5,
   "Frühkindliche Bildung entscheide maßgeblich über den weiteren Bildungsweg und sei Schlüssel für Chancengerechtigkeit. Mit dem Erhalt der Beitragsfreiheit seien wichtige Voraussetzungen geschaffen. Nötig seien zusätzlich Zeit für jedes Kind und bessere Rahmenbedingungen.",
   "Frühkindliche Bildung entscheidet maßgeblich über den weiteren Bildungsweg und ist der Schlüssel für echte Chancengerechtigkeit. Mit dem Erhalt der Beitragsfreiheit haben wir wichtige Voraussetzungen geschaffen. Doch gute Bildung braucht mehr: Zeit für jedes Kind, bessere Rahmenbedingungen und gezielte Förd[erung].",
   "Mit dem Erhalt der Beitragsfreiheit haben wir wichtige Voraussetzungen geschaffen"),
  ("bsw", 45,
   "Kitas seien weit mehr als Betreuungsorte und förderten soziale, sprachliche und emotionale Kompetenzen. Frühkindliche Bildung lege den Grundstein für ein gelingendes Leben. Kitas, Schulen und Hochschulen sollen so gestaltet werden, dass Lernen Freude macht.",
   "Chancen von Anfang an: Frühkindliche Bildung und Förderung legen den Grundstein für ein gelingendes Leben. Kitas sind weit mehr als Betreuungsorte: Sie unterstützen Kinder in ihrer Entwicklung, fördern soziale, sprachliche und emotionale Kompetenzen.",
   "Kitas sind weit mehr als Betreuungsorte"),
  ]),

 ("gesundheit", "Gesundheit und Versorgung in der Fläche",
  "Krankenhäuser, Hausärzte und Pflege im Flächenland.", [
  ("cdu", 6,
   "Erweiterte Aufgaben für berufserfahrene Medizinische Fachangestellte sollen Hausärzte entlasten. Das Land soll die entsprechende Qualifizierung finanzieren. So soll die Versorgung in der Fläche gesichert werden.",
   "[Wir wollen die Qualifizierung zur Praxisassistentin] durch das Land [fördern], damit ausgebildete, berufserfahrene Medizinische Fachangestellte erweiterte medizinische Aufgaben übernehmen und so Hausärzte entlasten sowie die Versorgung in der Fläche sichern können.",
   "erweiterte medizinische Aufgaben übernehmen und so"),
  ("spd", 28,
   "Alle Krankenhäuser im Land seien erhalten worden, dieser Einsatz soll fortgesetzt werden. Eine flächendeckende stationäre Regel- und Grundversorgung soll in allen Regionen gewährleistet werden. Zugleich sollen Spezialisierungen der Krankenhäuser vorangetrieben werden.",
   "Wir haben es geschafft, dass alle Krankenhäuser im Land erhalten worden sind. […] Konkret werden wir eine flächendeckende stationäre Versorgung in der Regel- und Grundversorgung in allen Regionen unseres Landes gewährleisten und gleichzeitig Spezialisierungen der Krankenhäuser […] forcieren.",
   "eine flächendeckende stationäre Versorgung in der Regel- und Grundversorgung in allen Regionen"),
  ("gruene", 58,
   "Gesundheits- und Pflegeberufe sollen aufgewertet werden. Ihre Arbeit sei von Personalmangel, hoher Belastung und zu wenig Zeit für die Versorgung geprägt. Viele verließen deshalb den Beruf.",
   "9.1. Gesundheits- und Pflegeberufe aufwerten […]. Doch ihre Arbeit ist oft von Personalmangel, hoher Belastung und zu wenig Zeit für die eigentliche Versorgung geprägt. Viele verlassen den Beruf.",
   "Gesundheits- und Pflegeberufe aufwerten"),
  ("fdp", 43,
   "Die Gesundheitsversorgung im ländlichen Raum soll gesichert werden. Der Bedarf an medizinischer Versorgung steige durch die demografische Entwicklung. Die bisherigen Strukturen stießen dabei an ihre Grenzen.",
   "Gesundheitsversorgung im ländlichen Raum sichern: Mecklenburg-Vorpommern steht vor einer doppelten Herausforderung: Während der Bedarf an medizinischer Versorgung durch die demografische Entwicklung steigt, stoßen die bisherigen Strukturen an ihre Grenzen.",
   "Gesundheitsversorgung im ländlichen Raum sichern"),
  ("afd", 58,
   "Der Ärztemangel im ländlichen Raum sei real, auch wenn Statistiken ihn kleinrechneten. Krankenhäuser würden geschlossen, Kinder- und Geburtsstationen verschwänden aus der Fläche. Pflegekräfte arbeiteten am Limit.",
   "Der Ärztemangel im ländlichen Raum ist real, auch wenn offizielle Statistiken ihn kleinrechnen. Krankenhäuser werden geschlossen, Kinder- und Geburtsstationen verschwinden aus der Fläche. Pflegekräfte arbeiten am Limit.",
   "Krankenhäuser werden geschlossen, Kinder- und Geburtsstationen verschwinden aus der Fläche"),
  ("linke", 19,
   "Das „Schwester-Agnes“-Modell für arztentlastende Dienste im ländlichen Raum soll wieder aufleben. Gesundheitslotsen sollen Patientinnen und Versicherte begleiten. Die Vergütung im Praktischen Jahr soll auf ein existenzsicherndes Niveau angehoben werden.",
   "• Das „Schwester-Agnes“ Modell für arztentlastende Dienste im ländlichen Raum wieder aufleben lassen. • Darauf hinwirken, dass Gesundheitslots:innen zum Einsatz kommen, die Patient:innen und Versicherte in allen relevanten Bereichen des Gesundheitswesens begleiten.",
   "Das „Schwester-Agnes“ Modell für arztentlastende Dienste im ländlichen Raum wieder aufleben lassen"),
  ("bsw", 57,
   "Gesundheit sei keine Ware, sondern ein Grundrecht. Die Gesundheitsversorgung soll bezahlbar und wohnortnah gesichert werden. Sie müsse gut und erreichbar sein.",
   "5.1. Gesundheitsversorgung: Gesundheitsversorgung bezahlbar und wohnortnah sichern. Gesundheit ist keine Ware, sondern ein Grundrecht. Eine gute, erreichbare und bezahlbare Gesundheitsverso[rgung …].",
   "Gesundheitsversorgung bezahlbar und wohnortnah sichern"),
  ]),

 ("energie", "Energie und Windkraft",
  "Ausbau der Erneuerbaren, Akzeptanz und Beteiligung.", [
  ("cdu", 93,
   "Windkraftausbau im Wald und Waldstilllegungen werden grundsätzlich abgelehnt. Stattdessen sollen Soforthilfen für Waldschäden und Waldumbau bereitgestellt werden. Die Nutzung privater Waldflächen und Holzbauprojekte wird unterstützt.",
   "[Wir wollen] Soforthilfen für Waldschäden und Waldumbau zur Klimaanpassung bereitstellen. Dabei unterstützen wir die Nutzung privater Waldflächen und Holzbauprojekte. Windkraftausbau im Wald und Waldstilllegungen lehnen wir grundsätzlich ab.",
   "Windkraftausbau im Wald und"),
  ("spd", 7,
   "Der Bau von Converter-Plattformen soll die auf See erzeugte Windenergie an Land leiten. Die Energiehäfen Rostock, Sassnitz-Mukran und Lubmin sollen entwickelt werden. Damit zeige sich wirtschaftliches Potenzial über den Schiffbau hinaus.",
   "Der Bau von Converter-Plattformen, um die auf See erzeugte Windenergie an Land zu leiten, und die Entwicklung der Energiehäfen Rostock, Sassnitz-Mukran und Lubmin zeigen, dass es auch über den Schiffbau hinaus wirtschaftliche [Perspektiven gibt].",
   "die auf See erzeugte Windenergie an Land zu leiten"),
  ("gruene", 6,
   "Die Planungssicherheit soll erhöht werden, indem Genehmigungsbehörden als moderne und personalstarke Agenturen neu ausgerichtet werden. So sollen Windräder und Solaranlagen schneller gebaut werden. Strom soll dadurch günstiger produziert werden.",
   "Tempo für Erneuerbare: Wir erhöhen die Planungssicherheit, indem wir Genehmigungsbehörden als moderne und personalstarke Agenturen neu ausrichten und fördern. Damit Windräder und Solaranlagen schneller gebaut werden und Strom endlich günstiger produziert wird.",
   "Damit Windräder und Solaranlagen schneller gebaut werden"),
  ("fdp", 63,
   "Neben Gaskraftwerken wird eine im Land ansässige Wasserstoffproduktion angestrebt. Vorhandene Überkapazitäten etwa in der Windenergie sollen zeitnah für Wasserstoff genutzt oder in Batterien gespeichert werden. Ziel ist die Nutzung bestehender Erzeugung.",
   "Neben Gaskraftwerken setzen wir uns für eine in Mecklenburg-Vorpommern ansässige Wasserstoffproduktion ein. Die bereits vorhandenen Überkapazitäten z.B. in der Windenergie müssen zeitnah für die Produktion von Wasserstoff bereitgestellt oder in Batterien gespeichert werden.",
   "Die bereits vorhandenen Überkapazitäten z.B. in der Windenergie müssen zeitnah für die Produktion von Wasserstoff bereitgestellt"),
  ("afd", 68,
   "Der weitere Ausbau von Windkraftanlagen wird abgelehnt. Die einzigartige Kulturlandschaft sei die Grundlage des Tourismus. Wer auf Qualitätstourismus setze, dürfe seine Landschaft nicht ruinieren.",
   "Die einzigartige Kulturlandschaft ist die Grundlage dieses Tourismus. Wir lehnen den weiteren Ausbau von Windkraftanlagen ab. Wer auf Qualitätstourismus setzt, darf seine Landschaft nicht ruinieren.",
   "Wir lehnen den weiteren Ausbau von Windkraftanlagen ab"),
  ("linke", 10,
   "Die Offshore-Windenergie soll gestärkt werden. Zudem sollen neue Geschäftsfelder in der maritimen Industrie geprüft werden. Genannt wird etwa die Umrüstung der Binnenschifffahrtsflotte auf alternative Antriebe.",
   "• Neue Geschäftsfelder in der maritimen Industrie prüfen, etwa die Umrüstung der Binnenschifffahrtsflotte auf alternative Antriebe. • Offshore-Windenergie stärken.",
   "Offshore-Windenergie stärken"),
  ("bsw", 25,
   "Die Windenergie sei ein wichtiger Bestandteil der Energieversorgung. Ihr Ausbau dürfe jedoch nicht gegen die Interessen der Bevölkerung erfolgen. Gewinne aus der Stromerzeugung müssten auch den Gemeinden zugutekommen.",
   "Gewinne aus der Stromerzeugung müssen auch den Gemeinden zugutekommen. Windenergie mit Maß und kommunaler Verantwortung: Die Windenergie ist ein wichtiger Bestandteil der Energieversorgung. Der Ausbau darf jedoch nicht gegen die Int[eressen der Bevölkerung erfolgen].",
   "Windenergie mit Maß und kommunaler Verantwortung"),
  ]),

 ("mobilitaet", "Mobilität im Flächenland",
  "Bus, Bahn, Straßen und Erreichbarkeit.", [
  ("cdu", 22,
   "Die Verkehrsinfrastruktur soll effizienter geplant werden. Synergien zwischen Straßen-, Schienen- und Nahverkehr sollen besser genutzt werden. Grundlage ist eine Strategie mit klarer politischer Steuerung.",
   "[Wir wollen eine Strategie entwickeln], die eine klare politische Steuerung vorsieht. Wir wollen die Verkehrsinfrastruktur effizienter planen und Synergien zwischen Straßen-, Schienen- und Nahverkehr besser nutzen.",
   "Wir wollen die Verkehrsinfrastruktur effizienter planen"),
  ("spd", 11,
   "Gästekarten sollen neben touristischen Vergünstigungen auch die kostenlose Nutzung des ÖPNV enthalten. Diese Angebote sollen innerhalb einer Destinationsregion gelten. Auch Bewohnerinnen und Bewohner sollen sie ohne Aufpreis nutzen können.",
   "[…] Gästekarten, die neben zahlreichen Vergünstigungen für touristische Angebote vor Ort […] auch eine kostenlose Nutzung des ÖPNV beinhalten. Diese Angebote sollen innerhalb einer Destinationsregion […] auch den Bewohnerinnen und Bewohnern ohne Aufpreis zur Verf[ügung stehen].",
   "auch eine kostenlose Nutzung des ÖPNV beinhalten"),
  ("gruene", 21,
   "Mobilität wird vom Alltag der Menschen her gedacht. Angestrebt wird eine klimafreundliche Verbindung von attraktivem ÖPNV und individueller Mobilität, ob mit Rad, zu Fuß oder im Auto. Erreichbarkeit soll unabhängig vom Wohnort bestehen.",
   "Wir denken Mobilität in Mecklenburg-Vorpommern vom Alltag der Menschen her: Wir stehen für eine klimafreundliche Verbindung von attraktivem ÖPNV und individueller Mobilität, ob mit dem Rad, zu Fuß oder im (E-)Auto.",
   "eine klimafreundliche Verbindung von attraktivem ÖPNV und individueller Mobilität"),
  ("fdp", 60,
   "Im regionalen Schienenverkehr sollen die Züge zuverlässig und pünktlich fahren. Anzeigen an Bahnsteigen und in Apps müssten den Tatsachen entsprechen. Menschen und Güter sollen schnell, zuverlässig und ohne ideologische Bevormundung unterwegs sein.",
   "[…] frei von ideologischer Bevormundung durch unser Land und in unser Land kommen können. Im regionalen Schienenverkehr sollen nach unseren Vorstellungen die Züge zuverlässig und pünktlich fahren. Die Anzeigen an Bahnsteigen und in den Apps müssen den Tatsachen en[tsprechen].",
   "Im regionalen Schienenverkehr sollen nach unseren Vorstellungen die Züge zuverlässig und pünktlich fahren"),
  ("afd", 32,
   "Gemeinsam mit Landkreisen und lokalen Akteuren soll ein landesweites Verkehrsverbundsystem eingeführt werden. Dieses soll Kindern einen verlässlichen und unkomplizierten Schulweg ermöglichen. Ziel sind möglichst kurze Transportwege.",
   "Zu diesem Zweck werden wir mit den Landkreisen, kreisfreien Städten und lokalen Akteuren im öffentlichen Nahverkehr darauf hinwirken, ein landesweites Verkehrsverbundsystem einzuführen, das unseren Kindern einen verlässlichen und unkomplizierten Schulweg ermöglicht.",
   "ein landesweites Verkehrsverbundsystem einzuführen"),
  ("linke", 12,
   "Für alle unter 21 Jahren soll ein kostenfreier Nahverkehr eingeführt werden. Damit sollen Mobilität und gesellschaftliche Teilhabe gewährleistet werden. Zudem wird auf Bundesebene eine solidarische Gesundheits- und Pflegeversicherung angestrebt.",
   "• Kostenfreien Nahverkehr für alle unter 21 Jahren einführen, um Mobilität und gesellschaftliche Teilhabe zu gewährleisten.",
   "Kostenfreien Nahverkehr für alle unter 21 Jahren einführen"),
  ("bsw", 1,
   "Erwartet werden eine verlässliche Infrastruktur, gute Straßen und Brücken sowie gepflegte Bahnhöfe. Bus und Bahn sollen erreichbar und pünktlich sein. Genannt werden ebenso lebenswerte Städte und Dörfer und Sicherheit im Alltag.",
   "Lebenswerte Städte und Dörfer, Sicherheit im Alltag, verlässliche Infrastruktur – gute Straßen und Brücken, gepflegte Bahnhöfe, Bus und Bahn, die erreichbar und pünktlich sind.",
   "gute Straßen und Brücken, gepflegte Bahnhöfe, Bus und Bahn, die erreichbar und pünktlich sind"),
  ]),

 ("landwirtschaft", "Landwirtschaft und ländlicher Raum",
  "Agrarstruktur, Bodenpreise, Ökologie und Wertschöpfung.", [
  ("cdu", 86,
   "Statt Nutzungseinschränkungen und starrer Bio-Quoten sollen Betriebe Planungsperspektiven und Nutzungssicherheit erhalten. Bodenspekulationen sollen verhindert werden. Angestrebt wird eine langfristig ausgewogene Agrarstruktur.",
   "Statt Nutzungseinschränkungen und starren Bio-Quoten wollen wir Planungsperspektiven und Nutzungssicherheit für Betriebe. Bodenspekulationen sollen verhindert werden. Die Sorge vor steigenden Boden- und Pachtpreisen nehmen wir ernst und setzen auf eine langfristig ausgewogene Agrarstruktur.",
   "Statt Nutzungseinschränkungen und starren Bio-Quoten wollen wir"),
  ("spd", 82,
   "Die Zukunft der ländlichen Räume liegt im Aufbau regionaler Wertschöpfungsketten. Grundlage sind Rohstoffe aus Land-, Forst- und Teichwirtschaft sowie erneuerbare Energien. Die Menschen vor Ort sollen davon profitieren.",
   "Die Zukunft der ländlichen Räume sehen wir im Aufbau regionaler Wertschöpfungsketten auf Basis der Rohstoffe aus der Land-, Forst- und Teichwirtschaft, den Erneuerbare[n] Energien und den Möglichkeiten, dass die Menschen vor Ort davon profitieren.",
   "im Aufbau regionaler Wertschöpfungsketten auf Basis der Rohstoffe aus der Land-, Forst- und Teichwirtschaft"),
  ("gruene", 16,
   "Steigende Kosten, unsichere Preise und hohe bürokratische Anforderungen erschwerten den Alltag der Betriebe. Zugleich müsse Landwirtschaft klima- und naturverträglich werden. Ziel sind Existenzsicherung und ein ermöglichter Umbau.",
   "2.4. Faire Landwirtschaft – Existenzsicherung und Umbau ermöglichen. […] Doch steigende Kosten, unsichere Preise und hohe bürokratische Anforderungen erschweren den Alltag der Betriebe.",
   "Faire Landwirtschaft - Existenzsicherung und Umbau ermöglichen"),
  ("fdp", 22,
   "Angestrebt wird eine Agrarpolitik, die Landwirte nicht bevormundet, sondern Freiraum für unternehmerisches Handeln lässt. Rechtsform, Größe und Art der Bewirtschaftung sollen dabei keine Rolle spielen. Land- und Forstwirtschaft gelten als Motor des ländlichen Raums.",
   "Wir Freie Demokraten setzen uns für eine Agrarpolitik ein, die Landwirte nicht bevormundet, sondern Freiraum für unternehmerisches Handeln lässt. Die Rechtsform, die Größe oder die Art der Bewirtschaft[ung] […].",
   "eine Agrarpolitik ein, die Landwirte nicht bevormundet, sondern Freiraum für unternehmerisches Handeln lässt"),
  ("afd", 73,
   "Die Landwirtschaft soll wertgeschätzt werden, geprägt von der jahrhundertealten Kulturlandschaft. Fischerei und Jagd werden als traditionsreiche Formen der Kulturlandschaftspflege begriffen, nicht als Relikte. Der ländliche Raum brauche mehr Freiheiten.",
   "[Wir wollen eine Politik, die] Fischerei wie Jagd als traditionsreiche Formen der Kulturlandschaftspflege begreift und nicht als Relikte von gestern. Der ländliche Raum braucht mehr Freiheiten. Landwirtschaft wertschätzen […].",
   "Der ländliche Raum braucht mehr Freiheiten"),
  ("linke", 22,
   "Die Rahmenbedingungen für die landwirtschaftliche Nutzung wiedervernässter Moore sollen verbessert werden. Gefordert wird zudem die Wiedervernässung landwirtschaftlich genutzter Moorstandorte bis 2045. Ein Strukturwandelgesetz soll betroffene Betriebe unterstützen.",
   "[Wir fordern die Wiedervernässung der] landwirtschaftlich genutzten Moorstandorte bis 2045 sowie eine umfassende Finanzierung der dafür notwendigen Maßnahmen und Strukturen. • Die Rahmenbedingungen für die landwirtschaftliche Nutzung wiedervernässter Moore (Paludikultur) verbessern.",
   "Die Rahmenbedingungen für die landwirtschaftliche Nutzung wiedervernässter Moore (Paludikultur) verbessern"),
  ("bsw", 22,
   "Die Landwirtschaft präge große Teile des Landes und sei wesentlich für regionale Wertschöpfung und Beschäftigung. Ihre Potenziale würden bislang nur unzureichend im Land weiterverarbeitet. Die Verarbeitung landwirtschaftlicher Erzeugnisse soll gezielt ausgebaut werden.",
   "Eine zentrale Rolle spielt die Landwirtschaft. Sie prägt große Teile Mecklenburg-Vorpommerns und ist ein wesentlicher Faktor für regionale Wertschöpfung und Beschäftigung. Die Potenziale der landwirtschaftlichen Produktion werden bislang jedoch nur unzureichend im Land weiterverarbeitet.",
   "Die Potenziale der landwirtschaftlichen Produktion werden bislang jedoch nur unzureichend im Land weiterverarbeitet"),
  ]),

 ("wirtschaft", "Wirtschaft und Fachkräfte",
  "Ansiedlung, Industrie und Arbeitsmarkt.", [
  ("cdu", 9,
   "Gezielt soll moderne Industrie ins Land geholt werden, die wettbewerbsfähige Löhne zahlt. Das Land soll als verlässlicher und investorenfreundlicher Wirtschaftsstandort gestärkt werden. Dazu gehören klare Rahmenbedingungen und eine aktive Ansiedlungspolitik.",
   "Deshalb machen wir neue, attraktive Jobs zur Chefsache: Wir holen gezielt moderne Industrie nach MV, die wettbewerbsfähige Löhne zahlt. […] Unser Ziel: Wir stärken Mecklenburg-Vorpommern als attraktiven, verlässlichen und investorenfreundlichen Wirtschaftsstandort mit klaren Rahmenbedingungen und aktiver Ansiedlungspolitik.",
   "Deshalb machen wir neue, attraktive Jobs zur Chefsache: Wir holen gezielt moderne"),
  ("spd", 7,
   "Bewährt habe sich die Strategie, einen Branchenmix zu stärken. Genannt werden Energiewirtschaft, maritime Industrie, Gesundheitswirtschaft, Landwirtschaft, Bioökonomie und Tourismus. Mit dem Tariftreuegesetz für öffentliche Aufträge sei gute Arbeit gestärkt worden.",
   "[…] haben sich die Strategien der SPD-geführten Landesregierungen bewährt, einen Branchenmix aus Energiewirtschaft, maritimer Industrie, Gesundheitswirtschaft, Landwirtschaft und Bioökonomie sowie Tourismus zu stärken.",
   "einen Branchenmix aus Energiewirtschaft, maritimer Industrie, Gesundheitswirtschaft"),
  ("gruene", 29,
   "Für die Wirtschaft sollen die Grundlagen gesichert werden: leistungsfähige Infrastruktur, gute Bildung und verlässliche Gesundheitsversorgung. Hinzu kommt eine offene Gesellschaft, die Fachkräfte anzieht und hält. Ziel ist eine nachhaltig wachsende Wirtschaft.",
   "Gleichzeitig sorgen wir für die Grundlagen, die Wirtschaft braucht: eine leistungsfähige Infrastruktur, gute Bildung, verlässliche Gesundheitsversorgung und eine offene Gesellschaft, die Fachkräfte anzieht und hält.",
   "eine leistungsfähige Infrastruktur, gute Bildung, verlässliche Gesundheitsversorgung und eine offene Gesellschaft"),
  ("fdp", 12,
   "Große Chancen werden in Wasserstoff, Kernfusion und weiteren Zukunftstechnologien im Energiebereich gesehen. Auch in maritimer Wirtschaft, Landwirtschaft und technologiegestützten Wertschöpfungsketten könne das Land eine führende Rolle übernehmen. Die Voraussetzungen dafür seien gut.",
   "Große Chancen liegen etwa in Wasserstoff, Kernfusion und weiteren Zukunftstechnologien im Energiebereich. Auch in der maritimen Wirtschaft, in der Landwirtschaft und in technologiegestützten Wertschöpfungsketten kann Mecklenburg-Vorpommern eine führende Rolle übernehmen.",
   "Große Chancen liegen etwa in Wasserstoff, Kernfusion und weiteren Zukunftstechnologien im Energiebereich"),
  ("afd", 30,
   "Reallabore, Unternehmen, Museen und Hochschulen sollen vor Ort vernetzt werden. Ausgerichtet wird dies auf die spezifischen Stärken des Landes. Genannt werden maritime Wirtschaft, Luft- und Raumfahrt, Landwirtschaftstechnik, Gesundheitswirtschaft und Lebensmittelindustrie.",
   "[Wir wollen] Reallabore, Unternehmen, Museen und Hochschulen vor Ort vernetzen und auf die spezifischen Stärken MVs ausgerichtet sind: maritime Wirtschaft, Luft- und Raumfahrt, Landwirtschaftstechnik, Gesundheitswirtschaft und Lebensmittelindustrie.",
   "auf die spezifischen Stärken MVs ausgerichtet sind: maritime Wirtschaft, Luft- und Raumfahrt"),
  ("linke", 10,
   "Neue Geschäftsfelder in der maritimen Industrie sollen geprüft werden. Qualifizierte Fachkräfte gelten als Grundlage für den Erhalt der wirtschaftlichen Leistungsfähigkeit. Genannt wird etwa die Umrüstung der Binnenschifffahrtsflotte.",
   "Fachkräftesicherung: Qualifizierte Fachkräfte sind die Grundlage für den Erhalt der wirtschaftlichen Leistungsfähigkeit.",
   "Qualifizierte Fachkräfte sind die Grundlage für den Erhalt der wirtschaftlichen Leistungsfähigkeit"),
  ("bsw", 7,
   "Häfen, Flughäfen und Infrastruktur sollen vorrangig zivil genutzt werden. Pläne zur Einbindung von Infrastruktur wie Krankenhäusern und Straßen in kriegsvorbereitende Maßnahmen werden abgelehnt. Zivile Arbeitsplätze und industrielle Strukturen sollen erhalten bleiben.",
   "• Häfen, Flughäfen und Infrastruktur sollen vorrangig zivil genutzt werden. Wir lehnen die Pläne zur Einbindung von Infrastruktur, wie Krankenhäuser und Straßen, in kriegsvorbereitende Maßnahmen grundsätzlich ab. • Erhalt ziviler Arbeitsplätze und industrieller Strukturen.",
   "Häfen, Flughäfen und Infrastruktur sollen vorrangig zivil genutzt werden"),
  ]),
]
