# -*- coding: utf-8 -*-
"""Datensatz Landtagswahl Sachsen-Anhalt 2026. Alle Aussagen aus den PDFs."""

WAHL = {
    "id": "lt-st-2026",
    "name": "Landtagswahl Sachsen-Anhalt",
    "region": "Sachsen-Anhalt",
    "wahltag": "2026-09-06",
    "kuerzel": "st",
}

PROGRAMME = {
    "cdu": ("Regierungsprogramm zur Landtagswahl am 6. September 2026",
            "https://www.cdulsa.de/sites/www.cdulsa.de/files/downloads/regierungsprogramm_ltw_web.pdf"),
    "spd": ("Mit Herz, Haltung und Zuversicht. Wahlprogramm 2026",
            "https://spdsachsenanhalt.de/wp-content/uploads/sites/63/2026/03/SPD-Wahlprogramm-2026.pdf"),
    "gruene": ("Nur mit Grün wird Zukunft draus. Programm zur Landtagswahl 2026",
               "https://www.gruene-lsa.de/wp-content/uploads/2026/05/Programm-zur-Landtagswahl-2026.pdf"),
    "fdp": ("Freiheit hat nur eine Heimat. Wahlprogramm zur Landtagswahl 2026",
            "https://www.fdp-lsa.de/sites/default/files/2026-07/fdpwahlprogrammltw2026.pdf"),
    "afd": ("Kurz und gut. Kurzprogramm zur Landtagswahl 2026",
            "https://afd-lsa.de/wp-content/uploads/2026/08/LSA26_KURZPROGRAMM_A6_Final.pdf"),
    "linke": ("Wir sind der Pol der Hoffnung. Wahlprogramm zur Landtagswahl 2026",
              "https://www.dielinke-sachsen-anhalt.de/fileadmin/aaa_download_lsa/Parteitage/10._LPT_2._Tagung_VV_LTW_2026/Beschluesse/2026-03-19_Landtagswahlprogramm__final_.pdf"),
    "bsw": ("Sachsen-Anhalt bleibt anders. Wahlprogramm zur Landtagswahl 2026",
            "https://st.bsw-vg.de/wp-content/uploads/2026/04/BSW_Landtagswahlprogramm_SachsenAnhalt.pdf"),
}

# (themaId, Titel, Beschreibung, [(Fragetext, [Aussagen])])
# Aussage: (parteiId, seite, kurz, original, markierung)
# Regeln: 3-4 Aussagen je Frage, jede Partei je Thema genau einmal,
# alle Aussagen einer Frage beantworten dieselbe Unterfrage.
THEMEN = [
 ('sicherheit', 'Innere Sicherheit und Polizei',
  'Personal und Befugnisse der Polizei, Kontrolle und Prävention.', [
  ('Wie soll die Polizei personell und materiell ausgestattet werden?', [
   ('cdu', 6,
    'Die Landespolizei soll personell deutlich wachsen, auf weit mehr als 8.100 Bedienstete. Zugleich sollen ihre Kompetenzen und Befugnisse erweitert werden. Ziel ist eine sichtbare und handlungsfähige Polizei.',
    'Spürbare Sicherheit: Sicherheit gewährleisten durch eine sichtbare und handlungsfähige Polizei, hierzu erweitern wir ihre Kompetenzen und Befugnisse. Wir wollen einen personellen Aufwuchs innerhalb der Landespolizei auf weit mehr als 8.100 Bedienstete.',
    'personellen Aufwuchs innerhalb der Landespolizei auf weit mehr als 8.100 Bedienstete',
   ),
   ('gruene', 41,
    'Der Personalausbau im Polizeivollzug soll bis zur Zielgröße von 7.000 Stellen fortgesetzt werden. Zusätzlich soll die Polizeiverwaltung substanziell gestärkt werden. Polizeireviere sollen eigenständige Budgets erhalten.',
    'Der Personalausbau bei den Vollzugsbeamt*innen soll konsequent bis zur Zielgröße von 7.000 Stellen fortgesetzt werden. Gleichzeitig ist eine substanzielle Stärkung der Polizeiverwaltung erforderlich. […] Zudem sollen eigenständige und verlässliche Budgets für die Polizeireviere umgesetzt werden.',
    'Der Personalausbau bei den Vollzugsbeamt*innen soll konsequent bis zur Zielgröße von 7.000 Stellen fortgesetzt werden',
   ),
   ('fdp', 47,
    'Mehr sichtbare Polizei in Stadt und Land soll durch eine klare Aufgabentrennung nach Qualifikation entstehen. Dafür wird eine Laufbahn als Polizeiverwaltungsassistent geschaffen. So wird der Vollzugsdienst entlastet.',
    'Wir sorgen für sichtbar mehr Polizei in Stadt und Land durch eine klare Aufgabentrennung nach Qualifikation. […] Wir setzen uns für die Schaffung einer Laufbahn als Polizeiverwaltungsassistenten ein. So wird der Vollzugsdienst konsequent entlastet.',
    'Wir sorgen für sichtbar mehr Polizei in Stadt und Land durch eine klare Aufgabentrennung nach Qualifikation',
   ),
   ('bsw', 67,
    'Polizei und Ermittlungsbehörden sollen so ausgestattet werden, dass sie kriminellen Netzwerken auf Augenhöhe begegnen können. Der Schwerpunkt liegt auf der Bekämpfung organisierter Kriminalität. Eine Privatisierung von Sicherheitsaufgaben wird abgelehnt.',
    'Wir wollen Polizei und Ermittlungsbehörden in Sachsen-Anhalt so ausstatten, dass sie auf Augenhöhe mit kriminellen Netzwerken und der Organisierten Kriminalität agieren können. […] Polizei als staatliche Kernaufgabe stärken, Privatisierung ablehnen.',
    'Polizei und Ermittlungsbehörden in Sachsen-Anhalt so ausstatten, dass sie auf Augenhöhe mit kriminellen Netzwerken',
   ),
  ]),
  ('Was braucht die Polizei über mehr Personal hinaus?', [
   ('spd', 29,
    'Polizistinnen und Polizisten sollen von bürokratischen Aufgaben entlastet werden, um sich auf ihre Kernaufgaben zu konzentrieren. Das Beförderungsbudget wird deutlich verbessert, um den Beförderungsstau abzubauen. Dienststellen sollen baulich auf modernen Stand gebracht werden.',
    'Bürokratische Belastungen werden reduziert, damit Polizistinnen und Polizisten sich auf ihre Kernaufgaben konzentrieren können. […] Deshalb wird das Beförderungsbudget deutlich verbessert, um den Stau abzubauen und verlässliche Perspektiven zu schaffen.',
    'Bürokratische Belastungen werden reduziert, damit Polizistinnen und Polizisten sich auf ihre Kernaufgaben konzentrieren können',
   ),
   ('afd', 11,
    'Es sollen mehr Polizisten eingestellt und der Polizeivollzug von Verwaltungstätigkeiten entlastet werden. Der Taser soll als Zwangsmittel unterhalb der Schusswaffe eingeführt werden. Eine freiwillige Bürgerwacht soll die Polizei bei Kleinkriminalität entlasten.',
    '[Wir werden] mehr Polizisten einstellen und den Polizeivollzug von Verwaltungstätigkeiten entlasten; den Taser als Zwangsmittel unterhalb der Schusswaffe […] einführen; eine freiwillige Bürgerwacht zur Bekämpfung von Kleinkriminalität und Entlastung der Polizei einführen.',
    'mehr Polizisten einstellen und den Polizeivollzug von Verwaltungstätigkeiten entlasten',
   ),
   ('linke', 128,
    'Sicherheitspolitik soll öffentlich beraten werden, mit Anhörungen zu Sicherheitsgesetzen und Bürgerforen zur Polizeiarbeit. Eine unabhängige Polizeibeschwerdestelle mit eigenen Ermittlungsbefugnissen soll eingerichtet werden. Polizeistatistiken sollen offengelegt werden.',
    'Wir schaffen echte Bürger:innenbeteiligung bei sicherheitspolitischen Fragen: Öffentliche Anhörungen zu neuen Sicherheitsgesetzen, Bürger:innenforen zur Polizeiarbeit vor Ort […]. Ihre Rechte werden gestärkt durch eine unabhängige Polizeibeschwerdestelle mit eigenen Ermittlungsbefugnissen.',
    'eine unabhängige Polizeibeschwerdestelle mit eigenen Ermittlungsbefugnissen',
   ),
  ]),
 ]),
 ('migration', 'Migration und Integration',
  'Aufnahme, Rückführung, Sprachförderung und Zugang zum Arbeitsmarkt.', [
  ('Wie soll mit Menschen ohne Bleiberecht umgegangen werden?', [
   ('cdu', 6,
    'Migration soll geordnet, begrenzt und gesteuert werden: Schutz für Berechtigte, konsequente Rückführung für alle ohne Bleiberecht. Die irreguläre Migration soll auf null zurückgeführt werden. Integration soll verlässlich geregelt sein.',
    'Migration ordnen, begrenzen, steuern: Klare Regeln: Schutz für Berechtigte, konsequente Rückführung für alle ohne Bleiberecht, Missbrauch verhindern, Integration mit Verlässlichkeit. Wir wollen die irreguläre Migration auf null zurückführen.',
    'konsequente Rückführung für alle ohne Bleiberecht',
   ),
   ('fdp', 10,
    'Der irregulären Migration soll mit aller Kraft entgegengewirkt werden, Ausreisepflichtige sollen das Land zügig verlassen. Aufenthaltstitel zur Beschäftigung sollen binnen vier Wochen erteilt werden. Sprachkurse sollen vorrangig Selbstzahlern angeboten werden.',
    'Der irregulären Migration werden wir mit aller Kraft entgegenwirken. Ausreisepflichtige Ausländer müssen zügig das Land verlassen. […] Ziel ist es, dass Aufenthaltstitel, die zur Aufnahme einer Beschäftigung berechtigen, innerhalb von vier Wochen erteilt werden.',
    'Der irregulären Migration werden wir mit aller Kraft entgegenwirken. Ausreisepflichtige Ausländer müssen zügig das Land verlassen',
   ),
   ('afd', 7,
    'Ausreisepflichtige sollen konsequent ausgewiesen und eine Abschiebeoffensive eingeleitet werden. Das Kirchenasyl soll unterbunden werden. Die Willkommenskultur soll durch eine Verabschiedungskultur ersetzt werden.',
    '[Wir werden] die Willkommenskultur durch eine Verabschiedungskultur ersetzen; Ausreisepflichtige konsequent ausweisen und eine Abschiebeoffensive einleiten, das Kirchenasyl unterbinden und Personen, die Abschiebungen vereiteln, zur Rechenschaft ziehen.',
    'Ausreisepflichtige konsequent ausweisen und eine Abschiebeoffensive einleiten',
   ),
   ('bsw', 62,
    'Wer keinen Anspruch auf Asyl hat, bei Asylmissbrauch oder bei Straffälligkeit soll konsequent abgeschoben werden. Die einheimische Bevölkerung soll vor Überlastungstendenzen geschützt werden. Die Handlungsfähigkeit des Staates soll sichtbar sein.',
    'Die einheimische Bevölkerung ist vor Überlastungstendenzen zu schützen. Die Handlungsfähigkeit des Staates muss glaubhaft und sichtbar sein. Dazu gehört auch die konsequente Abschiebung, wenn kein Anspruch auf Asyl besteht, Asylmissbrauch vorliegt oder Migranten straffällig werden.',
    'die konsequente Abschiebung, wenn kein Anspruch auf Asyl besteht',
   ),
  ]),
  ('Was soll denen geboten werden, die bleiben?', [
   ('spd', 33,
    'Wer arbeitet, lernt oder eine Ausbildung absolviert, soll eine Bleibeperspektive erhalten. Freiwillige Rückkehr wird unterstützt, Abschiebungen bleiben letztes Mittel. Ordnung und Humanität sollen sich nicht ausschließen.',
    'Menschen, die arbeiten, lernen oder eine Ausbildung absolvieren, sollen eine Bleibeperspektive haben. Freiwillige Rückkehr wird unterstützt. Abschiebungen bleiben die ultima ratio. Ordnung und Humanität schließen sich nicht aus.',
    'sollen eine Bleibeperspektive haben. Freiwillige Rückkehr wird unterstützt. Abschiebungen bleiben die ultima ratio',
   ),
   ('gruene', 78,
    'Sprachkurse sollen ab dem ersten Tag zugänglich sein, nicht erst nach Anerkennung oder Verwaltungsverfahren. Dazu gehören flexible und berufsbegleitende Kursmodelle. Sprache gilt als Schlüssel zu Arbeit, Bildung und Alltag.',
    'Sprache ist der Schlüssel zu allem: Arbeit, Bildung, Alltag, Begegnung. Deshalb sollen Sprachkurse ab dem ersten Tag zugänglich sein, nicht erst nach Anerkennung oder nach Verwaltungsverfahren. Dazu gehören flexible Kursmodelle, berufsbegleitende […] Angebote.',
    'Sprachkurse ab dem ersten Tag zugänglich sein, nicht erst nach Anerkennung',
   ),
   ('linke', 97,
    'Sprachkurse sollen flächendeckend angeboten werden, auch im ländlichen Raum. Ausländische Qualifikationen sollen anerkannt, Familiennachzug ermöglicht werden. Ziel sind klare Regelungen und verlässliche Zusagen.',
    'Das erreichen wir über klare Regelungen [und] verlässliche Zusagen, was flächendeckende Angebote an Sprachkursen, auch im ländlichen Raum, die Anerkennung von Qualifikationen und die Möglichkeit des Familiennachzuges angeht.',
    'flächendeckende Angebote an Sprachkursen, auch im ländlichen Raum, die Anerkennung von Qualifikationen',
   ),
  ]),
 ]),
 ('schule', 'Schule und Unterrichtsversorgung',
  'Lehrkräfte, Unterrichtsausfall, Schulformen und Ganztag.', [
  ('Wie soll dem Lehrkräftemangel und dem Unterrichtsausfall begegnet werden?', [
   ('cdu', 24,
    'Um die Unterrichtsversorgung im ländlichen Raum zu sichern, sollen Lehrkräfte im Vorbereitungsdienst eine ergänzende Zulage erhalten. Leistungsorientierung wird mit Chancengleichheit verbunden. Schulentwicklung soll datengestützt erfolgen.',
    'Personalentwicklung gestalten: Um die Unterrichtsversorgung im ländlichen Raum zu sichern, sollen Lehrkräfte im Vorbereitungsdienst eine ergänzende Zulage zu ihren Anwärterbezügen erhalten […]. Wir verbinden Leistungsorientierung mit Chancengleichheit.',
    'Um die Unterrichtsversorgung im ländlichen Raum zu sichern, sollen Lehrkräfte im Vorbereitungsdienst eine ergänzende Zulage',
   ),
   ('spd', 18,
    'Verlässliche Unterrichtsversorgung gilt als Voraussetzung für Lernerfolg und Chancengerechtigkeit, Unterrichtsausfall darf nicht zur Normalität werden. Schulen brauchen Planungssicherheit und ausreichende Personalausstattung. Dazu kommen pädagogische Spielräume.',
    'Verlässliche Unterrichtsversorgung ist Voraussetzung für Lernerfolg und Chancengerechtigkeit. Unterrichtsausfall darf nicht zur Normalität werden. Schulen brauchen Planungssicherheit, ausreichende Personalausstattung und pädagogische Spielräume.',
    'Unterrichtsausfall darf nicht zur Normalität werden. Schulen brauchen Planungssicherheit',
   ),
   ('linke', 33,
    'Der Mangel an ausgebildeten Lehrkräften soll mit einem Zehn-Punkte-Plan für eine gute Unterrichtsversorgung behoben werden. Schulen sollen möglichst große Teile ihres Schulhaushalts selbst bewirtschaften. Ursache ist aus Sicht der Partei eine Fehleinschätzung des Ausbildungsbedarfs.',
    'Wir wollen den Schulen möglichst große Teile ihres Schulhaushalts als Budget zur eigenen Bewirtschaftung zur Verfügung stellen. Ressourcen sichern: 10 Punkte für eine gute Unterrichtsversorgung. Der extreme Mangel an ausgebildeten Lehrkräften […].',
    'Ressourcen sichern: 10 Punkte für eine gute Unterrichtsversorgung',
   ),
  ]),
  ('Welcher Umbau der Schule hat darüber hinaus Vorrang?', [
   ('gruene', 59,
    'Alle allgemeinbildenden Schulen sollen zu Schulen mit Ganztagsangebot weiterentwickelt werden. Volkshochschulen, Musikschulen, Sportvereine und Ehrenamt sollen in den Ganztag eingebunden werden. Der Zugang soll möglichst kostenfrei sein.',
    'Deshalb wollen wir alle allgemeinbildenden Schulen in Sachsen-Anhalt zu Schulen mit Ganztagsangebot weiterentwickeln und den Ausbau der Ganztagsangebote konsequent vorantreiben. Dabei sollen an allen Schulen Angebote von Volkshochschulen, Musikschulen, Sportvereinen sowie aus dem Ehrenamt in den Ganztag eingebunden werden.',
    'alle allgemeinbildenden Schulen in Sachsen-Anhalt zu Schulen mit Ganztagsangebot weiterentwickeln',
   ),
   ('fdp', 23,
    'Alle Schulen sollen eine moderne digitale Infrastruktur mit passenden Geräten erhalten. Damit soll zeitgemäßes Lernen ermöglicht und Unterrichtsausfall gerade im ländlichen Raum vermieden werden. Zusätzlich wird in nachhaltige und barrierefreie Schulgebäude investiert.',
    'Eine moderne digitale Infrastruktur soll nun durch eine entsprechende Struktur und Geräte in allen Schulen ergänzt werden, um zeitgemäßes Lernen zu ermöglichen und Unterrichtsausfall – gerade im ländlichen Raum – möglichst zu vermeiden.',
    'um zeitgemäßes Lernen zu ermöglichen und Unterrichtsausfall',
   ),
   ('afd', 9,
    'Ein leistungsdifferenziertes Schulsystem mit starken Gymnasien, Realschulen, Hauptschulen und Förderschulen soll eingeführt werden. Der Leistungsgedanke soll im Mittelpunkt stehen und die Bewertungsschlüssel angehoben werden. Schule soll wieder Bildungsanstalt sein.',
    'Wir werden die Schule wieder zur Bildungsanstalt machen, indem wir den Leistungsgedanken statt Kuschelpädagogik in den Mittelpunkt stellen und die Bewertungsschlüssel wieder anheben; ein leistungsdifferenziertes Schulsystem mit starken Gymnasien, Realschulen, Hauptschulen und Förderschulen einführen.',
    'ein leistungsdifferenziertes Schulsystem mit starken Gymnasien, Realschulen, Hauptschulen und Förderschulen einführen',
   ),
   ('bsw', 44,
    'Der Lehrkräftemangel gilt als eines der gravierendsten Probleme und führt zu Unterrichtsausfall und fachfremdem Einsatz. Lehrerausbildung und Lehrkräftegewinnung sollen deshalb umgebaut werden. Die Arbeitsbelastung soll sichtbar gemacht und begrenzt werden.',
    'Der Lehrkräftemangel ist eines der gravierendsten Probleme im Bildungssystem des Landes und führt zu Unterrichtsausfall, fachfremdem Einsatz sowie zum Wegfall ganzer Fächer, insbesondere in den Bereichen Musik, Kunst und Technik.',
    'Der Lehrkräftemangel ist eines der gravierendsten Probleme im Bildungssystem des Landes',
   ),
  ]),
 ]),
 ('kita', 'Frühkindliche Bildung und Kita',
  'Personalschlüssel, Betreuungsplätze und Elternbeiträge.', [
  ('Wie soll der Personalschlüssel in den Kitas verbessert werden?', [
   ('spd', 28,
    'Der tatsächliche Personalschlüssel in der Arbeit mit den Kindern soll schrittweise verbessert werden. Kitas mit besonderen sozialen Herausforderungen erhalten zusätzliche Unterstützung. Beitragsfreiheit bleibt das erklärte Ziel.',
    'Der tatsächliche Personalschlüssel in der Arbeit mit den Kindern wird schrittweise verbessert. Kitas mit besonderen sozialen Herausforderungen erhalten zusätzliche Unterstützung. […] Beitragsfreiheit bleibt unser Ziel.',
    'Der tatsächliche Personalschlüssel in der Arbeit mit den Kindern wird schrittweise verbessert',
   ),
   ('gruene', 57,
    'Der Mindestpersonalschlüssel in den Kitas soll angehoben werden. Die Sonderförderung für Kitas mit besonderen Bedarfen wird ausgebaut und die Kitasozialarbeit gefördert. Aus der mittelfristigen Lösung soll eine strukturelle Verbesserung werden.',
    'Dafür wollen wir den Mindestpersonalschlüssel anheben, die zielgenaue Sonderförderung für Kitas mit besonderen Bedarfen ausbauen und insbesondere die Kitasozialarbeit fördern.',
    'wollen wir den Mindestpersonalschlüssel anheben',
   ),
   ('fdp', 25,
    'Der Betreuungsschlüssel soll weiter angepasst werden, unter Einbezug der individuellen Kinderförderung. Auch Zeit für Vor- und Nachbereitung soll berücksichtigt werden. Kindertagesstätte, Hort und Grundschule sollen enger verzahnt werden.',
    'Zudem fordern wir eine weitere Anpassung des Betreuungsschlüssels unter Einbezug der Erfordernisse der individuellen Kinderförderung sowie der notwendigen zeitlichen Kontingente für die Vor- und Nachbereitung.',
    'eine weitere Anpassung des Betreuungsschlüssels unter Einbezug der Erfordernisse der individuellen Kinderförderung',
   ),
   ('bsw', 42,
    'In den Kitas fehlen aus Sicht der Partei Fachkräfte, Plätze und Zeit für pädagogische Arbeit. Schlechte Personalschlüssel machten frühkindliche Bildung zur bloßen Betreuung. Stattdessen sollen Grundlagen für Sprache, Mathematik und soziale Entwicklung gelegt werden.',
    'In Kitas fehlen Fachkräfte, Plätze und Zeit für pädagogische Arbeit. Schlechte Personalschlüssel machen frühkindliche Bildung oft zur bloßen Betreuung, statt Grundlagen für Sprache, Mathematik und soziale Entwicklung zu legen.',
    'Schlechte Personalschlüssel machen frühkindliche Bildung oft zur bloßen Betreuung',
   ),
  ]),
  ('Wie soll die frühkindliche Betreuung finanziert und ausgebaut werden?', [
   ('cdu', 49,
    'Ein belastbares Konzept soll den tatsächlichen Betreuungsbedarf erfassen und eine stabile Finanzierung sichern. Gleichzeitig soll der Personalschlüssel verbessert werden. Ziel sind Verlässlichkeit, Qualität und individuelle Förderung.',
    'Wir werden ein belastbares Konzept vorlegen, das den tatsächlichen Bedarf realistisch erfasst, eine stabile Finanzierung gewährleistet und gleichzeitig den Personalschlüssel verbessert. Damit sichern wir Verlässlichkeit, Qualität, individuelle Förderung.',
    'eine stabile Finanzierung gewährleistet und gleichzeitig den Personalschlüssel verbessert',
   ),
   ('afd', 6,
    'Kitaplätze und Schulessen sollen kostenfrei werden. Zusätzlich sind ein Kinderwillkommensgeld und ein monatliches Landeskindergeld vorgesehen. Ziel sind starke Familien mit möglichst vielen Kindern.',
    '[Wir werden] ein Kinderwillkommensgeld i. H. v. 2000 Euro für die ersten beiden Kinder […] sowie ein monatliches Landeskindergeld […] einführen […]; für kostenfreie Kitaplätze und kostenfreies Schulessen sorgen.',
    'für kostenfreie Kitaplätze und kostenfreies Schulessen sorgen',
   ),
   ('linke', 27,
    'In Schulen, Kitas, Schulsozialarbeit und Jugendhilfe soll dauerhaft und ausreichend investiert werden. Gefordert wird eine Abkehr von der Sparpolitik bei den Jüngsten. Bildungspolitik soll soziale Unterschiede aktiv ausgleichen.',
    'Wir stehen für eine Abkehr von der „Rotstiftpolitik bei den Kleinen“: Wer von Zukunft redet, muss in Schulen, Kitas, Schulsozialarbeit, Jugendhilfe, Weiterbildung und digitale Infrastruktur dauerhaft und ausreichend investieren.',
    'muss in Schulen, Kitas, Schulsozialarbeit, Jugendhilfe, Weiterbildung und digitale Infrastruktur dauerhaft und ausreichend investieren',
   ),
  ]),
 ]),
 ('wirtschaft', 'Wirtschaft und Bürokratie',
  'Standort, Ansiedlung, Entlastung von Unternehmen.', [
  ('Wie soll die Bürokratie für Betriebe verringert werden?', [
   ('spd', 4,
    'Handwerk, Gewerbe und Mittelstand sollen nicht durch Bürokratie ausgebremst werden. Gesetze werden auf ihre Wirkung hin geprüft. Mitbestimmung in den Betrieben wird als Bestandteil einer fairen Wirtschaftsordnung gestärkt.',
    'Mittelstand, Handwerk und Bürokratieabbau: Handwerk, Gewerbe und Mittelstand sichern Arbeitsplätze im ganzen Land. Bürokratie darf sie nicht ausbremsen. […] Mitbestimmung in den Betrieben ist ein zentraler Bestandteil einer fairen Wirtschaftsordnung und wird gestärkt.',
    'Handwerk, Gewerbe und Mittelstand sichern Arbeitsplätze im ganzen Land. Bürokratie darf sie nicht ausbremsen',
   ),
   ('gruene', 89,
    'Dokumentations- und Berichtspflichten sollen reduziert und Verfahren durch klare Zuständigkeiten beschleunigt werden. Prozesse sollen digital und medienbruchfrei ablaufen. Im Bundesrat wird für ein reformiertes Vergaberecht mit regionalen Kriterien geworben.',
    'Wir setzen uns außerdem im Bundesrat für ein reformiertes Bundesvergaberecht ein, das mehr regionale Kriterien berücksichtigt und Bürokratie abbaut. […] Wir wollen Bürokratie abbauen, Dokumentations- und Berichtspflichten sollen reduziert und Verfahren durch klare Zuständigkeiten sowie digitale, medienbruchfreie Prozesse […].',
    'Dokumentations- und Berichtspflichten sollen reduziert und Verfahren durch klare Zuständigkeiten',
   ),
   ('fdp', 7,
    'Die Bürokratielast soll spürbar gesenkt werden, damit Investitionen nicht in Verfahren stecken bleiben. Unternehmen sollen ihre Zeit in die Entwicklung ihrer Produkte statt in Zuständigkeiten investieren. Ziel ist ein Staat, der Leistung ermöglicht statt behindert.',
    'Bürokratieabbau heißt am Ende: weniger Stillstand, mehr Tempo und ein Staat, der Leistung ermöglicht, statt sie behindert. Deshalb werden wir die Bürokratielast [senken].',
    'ein Staat, der Leistung ermöglicht, statt sie behindert',
   ),
  ]),
  ('Wodurch soll das Land die heimische Wirtschaft darüber hinaus stärken?', [
   ('cdu', 13,
    'Produktionsvorhaben für wichtige Medikamente sollen als strategische Projekte anerkannt werden. Dadurch sollen Genehmigungsverfahren beschleunigt und Fördermöglichkeiten verbessert werden. Ziel sind attraktive Rahmenbedingungen für Ansiedlungen.',
    'Ziel ist es, Produktionsvorhaben für wichtige Medikamente als „strategische Projekte“ anerkennen zu lassen. Dadurch können Genehmigungsverfahren beschleunigt, Fördermöglichkeiten verbessert und beihilferechtliche Spielräume erweitert werden.',
    'Dadurch können Genehmigungsverfahren beschleunigt, Fördermöglichkeiten verbessert',
   ),
   ('afd', 14,
    'Die Förderung soll sich auf heimische Unternehmen konzentrieren, statt ausländische Großkonzerne in Millionenhöhe zu subventionieren. Zugleich soll die Wirtschaft radikal entbürokratisiert und von vielen sinnlosen Regelungen befreit werden.',
    '[Wir werden] radikal entbürokratisieren und die Wirtschaft von vielen sinnlosen Regelungen befreien; […] uns auf die Förderung heimischer Unternehmen fokussieren, statt ausländische Großkonzerne in Millionenhöhe zu subventionieren.',
    'uns auf die Förderung heimischer Unternehmen fokussieren',
   ),
   ('linke', 86,
    'Die Tarifbindung soll wieder zur Regel werden, weil immer weniger Betriebe nach Tarif zahlen. Gefordert werden ein Vergabemindestlohn von 16,50 Euro je Stunde und ein konsequentes Vergabegesetz. Zudem soll die Allgemeinverbindlichkeit von Tarifverträgen erleichtert werden.',
    'Wo Tarif gilt, geht es den Menschen besser. Doch immer weniger Betriebe zahlen ihn noch – das drückt Löhne und mindert Lebensqualität. Wir wollen die Tarifbindung wieder zur Regel machen. Dafür fordern wir: einen Vergabemindestlohn von 16,50 Euro pro Stunde […], die Einführung eines konsequenten Vergabegesetzes […], die Allgemeinverbindlichkeit von Tarifverträgen zu erleichtern.',
    'Wir wollen die Tarifbindung wieder zur Regel machen',
   ),
   ('bsw', 18,
    'Für heimische und regional agierende Betriebe ist aus Sicht der Partei nicht der Kostendruck, sondern die schwache Binnennachfrage das Hauptproblem. Bürokratieabbau und Entlastungen seien wichtig, schafften aber keine Aufträge. Entscheidend sei, dass Geld in der Region zirkuliert.',
    'Für die heimischen und regional agierenden Betriebe ist nicht der internationale Kostendruck das Hauptproblem, sondern die anhaltende Schwäche der Binnennachfrage. Echter Bürokratieabbau und Entlastungen sind wichtig, schaffen jedoch keine neuen Aufträge.',
    'Echter Bürokratieabbau und Entlastungen sind wichtig, schaffen jedoch keine neuen Aufträge',
   ),
  ]),
 ]),
 ('energie', 'Energie und Windkraft',
  'Ausbau erneuerbarer Energien, Netze und Akzeptanz vor Ort.', [
  ('Wer soll darüber entscheiden, wo Windräder gebaut werden?', [
   ('gruene', 23,
    'Am Flächenziel für den Ausbau erneuerbarer Energien wird konsequent festgehalten. Eignungsgebiete sollen über die Regionalplanung ausgewiesen werden, NATURA-2000-Gebiete bleiben ausgeschlossen. Der Windausbau gilt als Voraussetzung für lokalen grünen Wasserstoff.',
    'Wir halten konsequent am Flächenziel für den Ausbau erneuerbarer Energien fest, um die Energiewende voranzutreiben. […] Der Ausbau der Windenergie ist die wichtige Voraussetzung zur Herstellung von lokalem Grünem Wasserstoff mit regionalen Elektrolyseuren.',
    'Wir halten konsequent am Flächenziel für den Ausbau erneuerbarer Energien fest',
   ),
   ('fdp', 14,
    'Die Länder sollen einen deutlich größeren Entscheidungsspielraum beim Ausbau erneuerbarer Energien erhalten. Erfüllt ein Land bis 2027 sein Sektorenziel bei Windenergie an Land, soll die Flächenzielpflicht bis 2032 entfallen. Eigene Energiequellen sollen genutzt werden.',
    '[Wir wollen den Bundesländern] einen deutlich größeren Entscheidungsspielraum beim Ausbau erneuerbarer Energien [geben]. Erfüllen Bundesländer bis 2027 das Sektorenziel in erzeugter Energiemenge durch Windenergieanlagen an Land, entfällt die Pflicht zur Erfüllung des für sie derzeit festgelegten Flächenziels bis 2032.',
    'entfällt die Pflicht zur Erfüllung des für sie derzeit festgelegten Flächenziels bis 2032',
   ),
   ('afd', 15,
    'Das sogenannte Akzeptanzgesetz, das Kommunen zur Hinnahme von Wind- und Solarparks anhalte, soll abgeschafft werden. Ziel ist eine nachhaltige, günstige und krisensichere Energieversorgung.',
    'Unsere Energiepolitik stellt das Ziel einer nachhaltigen, günstigen und krisensicheren Energieversorgung in den Mittelpunkt. Deshalb werden wir […] das sog. „Akzeptanzgesetz“, das die Kommunen nötigt, Wind- und Solarparks zu akzeptieren, abschaffen.',
    'das die Kommunen nötigt, Wind- und Solarparks zu akzeptieren, abschaffen',
   ),
   ('bsw', 24,
    'Windkraftanlagen leisten aus Sicht der Partei einen wichtigen Beitrag zur Stromversorgung. Ihr Ausbau müsse jedoch regional ausgewogen erfolgen und die Belange der Bevölkerung berücksichtigen. Durch Repowering bestehender Anlagen soll die Leistung gesteigert werden.',
    'Windkraftanlagen leisten ebenfalls einen wichtigen Beitrag zur Stromversorgung. Ihr Ausbau muss jedoch regional ausgewogen erfolgen und die Belange der Bevölkerung berücksichtigen. Durch Repowering bestehender Windkraftanlagen kann ihre Leistung erheblich gesteigert werden.',
    'Ihr Ausbau muss jedoch regional ausgewogen erfolgen und die Belange der Bevölkerung berücksichtigen',
   ),
  ]),
  ('Wie sollen Kommunen und Anwohner am Ausbau beteiligt werden?', [
   ('cdu', 45,
    'Erneuerbare Energien sollen technologieoffen genutzt und die Bürgerakzeptanz bei der Windkraft gesichert werden. Windenergieanlagen im Wald werden kritisch gesehen. Alle Anlagen sollen die Zustimmung der kommunalen Ebene brauchen.',
    'Erneuerbare Energien technologieoffen nutzen und Bürgerakzeptanz bei der Windkraftnutzung sicherstellen […]. Wir stehen dem Errichten von Windenergieanlagen im Wald aufgrund seiner Multifunktionalität kritisch gegenüber. Alle Windenergieanlagen müssen stets die Zustimmung der kommunalen Ebene […].',
    'Erneuerbare Energien technologieoffen nutzen und Bürgerakzeptanz bei der Windkraftnutzung sicherstellen',
   ),
   ('spd', 5,
    'Das Land soll als Standort für Zukunftsindustrien gestärkt werden, von Windkraft über Wasserstoff bis zu Batterietechnologien. Dazu dienen Investitionen in Infrastruktur, Forschung und beschleunigte Verfahren. Für die Wärmewende wird auf Bürgerbeteiligung gesetzt.',
    'Investitionen in Infrastruktur, Forschung und beschleunigte Verfahren stärken Sachsen-Anhalt als Standort für Zukunftsindustrien – von erneuerbaren Energien wie Windkraft über Wasserstoff und Batterietechnologien bis zur digitalen Wirtschaft.',
    'von erneuerbaren Energien wie Windkraft über Wasserstoff und Batterietechnologien',
   ),
   ('linke', 107,
    'Der Ausbau erneuerbarer Energien braucht aus Sicht der Partei klare Leitplanken: Naturverträglichkeit, Transparenz und echte Beteiligung vor Ort. Kommunen sollen von Wind-, Solar- und Agri-PV-Projekten profitieren. Ökologische Standards sollen gesichert sein.',
    'Doch der Ausbau der erneuerbaren Energien braucht klare Leitplanken: Naturverträglichkeit, Transparenz und echte Beteiligung der Menschen vor Ort. Wenn Windräder, Solaranlagen und Agri-PV-Projekte Landschaften prägen, müssen Kommunen davon profitieren und ökologische Standards gesichert sein.',
    'Naturverträglichkeit, Transparenz und echte Beteiligung der Menschen vor Ort',
   ),
  ]),
 ]),
 ('gesundheit', 'Gesundheit und Krankenhäuser',
  'Wohnortnahe Versorgung, Krankenhausstandorte, Pflege.', [
  ('Wie sollen die Krankenhäuser im Land gesichert werden?', [
   ('cdu', 27,
    'Angestrebt wird eine wohnortnahe, digital unterstützte und sektorenübergreifend vernetzte Versorgung. Krankenhäuser sollen klare Profile erhalten und eng mit ambulanten Strukturen zusammenarbeiten. Gesundheitsberufe sollen attraktive Arbeitsbedingungen vorfinden.',
    'Eine wohnortnahe, hochwertige medizinische und pflegerische Versorgung – digital unterstützt, sektorenübergreifend vernetzt und konsequent am Menschen ausgerichtet. […] Krankenhäuser mit klaren Profilen, die eng mit ambulanten Strukturen zusammenarbeiten.',
    'Eine wohnortnahe, hochwertige medizinische und pflegerische Versorgung',
   ),
   ('gruene', 79,
    'Die Krankenhäuser im Land sollen als Orte der Gesundheits- und Notfallversorgung erhalten bleiben. Alle Berufsgruppen im Gesundheits- und Pflegebereich sollen eigenverantwortlich mitarbeiten. Kommunen, Land und Selbstverwaltung sollen optimal zusammenwirken.',
    'Krankenhausstandorte erhalten, Versorgungssicherheit gewährleisten: Die Krankenhäuser im Land müssen als Orte der Gesundheits- und Notfallversorgung erhalten werden. […] eigenverantwortliche Mitarbeit aller Professionen des Gesundheits- und Pflegebereichs.',
    'Die Krankenhäuser im Land müssen als Orte der Gesundheits- und Notfallversorgung erhalten',
   ),
   ('linke', 48,
    'Krankenhäuser sollen nach Bedarf und Qualität finanziert werden statt nach Fallpauschalen. Gefordert werden integrierte Versorgungszentren in kommunaler Trägerschaft. Diese sollen ambulante, stationäre und Notfallleistungen aus einer Hand anbieten.',
    'Wir wollen: eine Entökonomisierung: Krankenhäuser sollen nach Bedarf und Qualität finanziert und organisiert werden, nicht nach Fallpauschalen, Profit oder Kostendruck[;] integrierte Versorgungszentren in kommunaler Trägerschaft, die ambulante, stationäre und Notfallleistungen aus einer Hand anbieten.',
    'Krankenhäuser sollen nach Bedarf und Qualität finanziert und organisiert werden, nicht nach Fallpauschalen',
   ),
  ]),
  ('Wie soll die Versorgung in der Fläche erreichbar bleiben?', [
   ('spd', 12,
    'Alternde Bevölkerung, fehlende Fachkräfte und lange Wege stellen die Versorgung besonders im ländlichen Raum vor Herausforderungen. Diese Entwicklungen sollen nicht verwaltet, sondern politisch gestaltet werden. Die Anforderungen an Versorgung und Pflege steigen.',
    'Die Bevölkerung wird älter, Fachkräfte fehlen, Wege sind lang – besonders im ländlichen Raum. Gleichzeitig steigen die Anforderungen an medizinische Versorgung, Pflege und soziale Dienste. Diese Entwicklungen lassen sich nicht verwalten, sie müssen politisch gestaltet werden.',
    'Diese Entwicklungen lassen sich nicht verwalten, sie müssen politisch gestaltet werden',
   ),
   ('fdp', 56,
    'Menschen sollen sich darauf verlassen können, dass medizinische Versorgung, Bildung, digitale Netze und wirtschaftliche Chancen erreichbar sind. In der Praxis sei das oft anders, gerade bei der Gesundheitsversorgung. Gleichwertige Lebensverhältnisse gelten als Anspruch für Stadt und Land.',
    'Ob in unseren Städten oder im ländlichen Raum – Menschen sollen sich darauf verlassen können, dass sie gut erreichbar sind, dass medizinische Versorgung, Bildung, digitale Netze und wirtschaftliche Chancen verfügbar sind. In der Praxis ist das oft noch anders.',
    'dass medizinische Versorgung, Bildung, digitale Netze und wirtschaftliche Chancen verfügbar sind',
   ),
   ('afd', 22,
    'Krankenhäuser sollen nicht weiter privatisiert und mehr regionale Gesundheitszentren geschaffen werden. Notaufnahmen sollen erhalten bleiben. Zusätzlich sind mehr Medizinstudienplätze und ein Landarztstipendienprogramm vorgesehen.',
    '[Wir werden] mehr Medizinstudienplätze schaffen und ein spezielles Landarztstipendienprogramm auflegen; Krankenhäuser nicht mehr privatisieren und mehr regionale Gesundheitszentren schaffen; Notaufnahmen erhalten.',
    'Krankenhäuser nicht mehr privatisieren und mehr regionale Gesundheitszentren schaffen',
   ),
   ('bsw', 58,
    'Krankenhäuser sollen erhalten und Personal sowie Ausbildungsplätze ausgebaut werden. Die Gesundheitsversorgung soll als Daseinsvorsorge flächendeckend gesichert werden. Ein verbindliches Tariftreuegesetz soll die Bezahlung in Gesundheitsberufen stärken.',
    'Gesundheitsversorgung als Daseinsvorsorge flächendeckend sichern • Pflege- und Gesundheitsberufe mit fairer Bezahlung durch die Einführung eines für alle Mitarbeiter von Krankenhäusern verbindlichen Tariftreuegesetzes stärken • Krankenhäuser erhalten und Personal sowie Ausbildungsplätze ausbauen',
    'Krankenhäuser erhalten und Personal sowie Ausbildungsplätze ausbauen',
   ),
  ]),
 ]),
 ('mobilitaet', 'Mobilität und Nahverkehr',
  'Busse, Bahnen, Straßen und Anbindung der Fläche.', [
  ('Wie soll das Nahverkehrsangebot ausgebaut werden?', [
   ('cdu', 61,
    'Straßen und Schienennetz sollen ausgebaut und modernisiert werden. Das Deutschlandticket soll erhalten und das ÖPNV-Angebot im ländlichen Raum ausgebaut werden. Auch der Radverkehr soll gestärkt werden.',
    'Bezahlbare Mobilität in Stadt und Land: Ausbau und Modernisierung von Straßen und Schienennetz – Deutschlandticket erhalten – ÖPNV-Angebot im ländlichen Raum ausbauen – Radverkehr stärken und Alltagsradeln fördern.',
    'Deutschlandticket erhalten - ÖPNV-Angebot im ländlichen Raum ausbauen',
   ),
   ('spd', 26,
    'Ein Deutschlandticket für alle Schülerinnen und Schüler soll die Mobilität im Alltag verbessern. Jugendliche sollen in die ÖPNV-Planung eingebunden werden, damit Taktung und Verbindungen passen. Ergänzend werden Ruf- und Nachtbussysteme ausgebaut.',
    'Ein Deutschlandticket für alle Schülerinnen und Schüler verbessert die Mobilität im Alltag. Jugendliche sollen in die Planung des ÖPNV eingebunden werden, damit Taktung und Verbindungen ihren Lebensrealitäten entsprechen. Ergänzend werden moderne Ruf- und Nachtbussysteme ausgebaut.',
    'Ein Deutschlandticket für alle Schülerinnen und Schüler verbessert die Mobilität im Alltag',
   ),
   ('gruene', 27,
    'Der öffentliche Nahverkehr soll umfassend ausgebaut werden. Busse und Bahnen sollen im ganzen Land durch Barrierefreiheit und niedrigere Kosten attraktiver werden. Ziel sind nachhaltige Mobilitätslösungen für alle.',
    'Wir setzen uns für einen umfassenden Ausbau des öffentlichen Nahverkehrs ein und wollen Busse und Bahnen im ganzen Land durch Barrierefreiheit und Kostenreduzierungen attraktiver machen.',
    'Wir setzen uns für einen umfassenden Ausbau des öffentlichen Nahverkehrs ein',
   ),
   ('afd', 17,
    'Nahverkehrslinien im ländlichen Raum sollen ausgebaut statt gestrichen werden. Kommunen sollen besser finanziert werden und in der Verwaltung mehr Spielraum erhalten.',
    '[Wir bekennen uns zum ländlichen Raum als Lebensraum, indem wir] Kommunen besser finanzieren und zugleich der Kommunalverwaltung mehr Spielraum lassen; Nahverkehrslinien im ländlichen Raum ausbauen statt streichen […].',
    'Nahverkehrslinien im ländlichen Raum ausbauen statt streichen',
   ),
  ]),
  ('Worauf kommt es beim Nahverkehr über das Angebot hinaus an?', [
   ('fdp', 57,
    'Die Pünktlichkeit im Schienenpersonennahverkehr soll gegenüber 2025 um 20 Prozent steigen. Die Zugausfälle sollen um 30 Prozent sinken. Zugleich sollen die Straßen gut ausgebaut sein.',
    'Die Pünktlichkeit im Schienenpersonennahverkehr (SPNV) soll gegenüber dem Basisjahr 2025 um 20 Prozent steigen, die Zugausfälle sollen um 30 Prozent sinken. Die Straßen sollen gut ausgebaut sein.',
    'Die Pünktlichkeit im Schienenpersonennahverkehr (SPNV) soll gegenüber dem Basisjahr 2025 um 20 Prozent steigen',
   ),
   ('linke', 66,
    'Gefordert wird ein verbindliches Ausbauprogramm für alle ÖPNV-Haltestellen. Dazu gehören taktile Leitsysteme, Blindenschrift an Fahrplanaushängen, akustische Ansagen und stufenloser Einstieg. Öffentlicher Nahverkehr soll für alle nutzbar sein.',
    'Öffentlicher Nahverkehr für alle, das bedeutet ein verbindliches Ausbauprogramm für alle Haltestellen des ÖPNV mit taktilen Leitsystemen, Blindenschrift an Fahrplanaushängen, akustischen Ansagen und stufenlosem Einstieg.',
    'ein verbindliches Ausbauprogramm für alle Haltestellen des ÖPNV',
   ),
   ('bsw', 32,
    'Weitere Zerschlagungen der Mobilitätsinfrastruktur werden abgelehnt. Zentrale Mobilitätsinfrastruktur soll in die öffentliche Hand zurückgeführt werden. Nötig sei eine langfristige, transparente und realistisch finanzierte Verkehrsplanung.',
    'Das BSW Sachsen-Anhalt lehnt weitere Zerschlagungen ab und setzt sich für eine Rückführung zentraler Mobilitätsinfrastruktur in die öffentliche Hand ein. Eine nachhaltige Landesentwicklung braucht eine langfristige, transparente und realistisch finanzierte Verkehrsplanung.',
    'setzt sich für eine Rückführung zentraler Mobilitätsinfrastruktur in die öffentliche Hand ein',
   ),
  ]),
 ]),
 ('landwirtschaft', 'Landwirtschaft und Boden',
  'Agrarförderung, Bodenmarkt, Ökolandbau, ländlicher Raum.', [
  ('Welche Art von Landwirtschaft soll das Land fördern?', [
   ('cdu', 39,
    'Der Landwirtschaft soll Vorrang eingeräumt, Betriebe gesichert und regionale Produktion gezielt unterstützt werden. Grüne Berufe sollen attraktiver werden. Im ländlichen Raum sollen gleichwertige Lebensverhältnisse herrschen.',
    'Eigentum schützen, ländlichen Raum stärken: Vorrang für Landwirtschaft, Betriebe sichern und regionale Produktion gezielt unterstützen. „Grüne Berufe“ attraktiver machen.',
    'Vorrang für Landwirtschaft, Betriebe sichern und regionale Produktion gezielt unterstützen',
   ),
   ('gruene', 15,
    'Der Ökolandbau soll besser unterstützt und sein Flächenanteil deutlich erhöht werden. Dazu dienen verlässliche Ökoprämien und ein stärkerer Fokus in Ausbildung, Fachschule und Beratung. Auch die Lehr- und Versuchseinrichtungen des Landes sollen einbezogen werden.',
    '[Der Ökolandbau] soll besser unterstützt und sein Flächenanteil soll deutlich erhöht werden – insbesondere durch verlässliche Ökoprämien und einen stärkeren Fokus auf den Ökolandbau in der Ausbildung, in der Fachschule, bei der Umstellung, bei der Beratung.',
    'sein Flächenanteil soll deutlich erhöht werden – insbesondere durch verlässliche Ökoprämien',
   ),
   ('afd', 16,
    'Jede Form der Landwirtschaft soll gefördert werden, nicht nur Biobetriebe. EU-Vorgaben sollen zurückgedrängt und die Agrarpolitik renationalisiert werden. Auch die Regelungen zur Nutztierhaltung sollen geändert werden.',
    '[Wir werden] jede Form der Landwirtschaft fördern, nicht nur Biobetriebe; so weit wie möglich die EU mit ihren rigiden Vorgaben zurückdrängen und die Agrarpolitik renationalisieren.',
    'jede Form der Landwirtschaft fördern, nicht nur Biobetriebe',
   ),
   ('bsw', 19,
    'Zur Sicherung der einheimischen Landwirtschaft werden Abnahmegarantien für regional erzeugte Produkte gefordert. Öffentliche Einrichtungen sollen vorrangig regionale Erzeugnisse beziehen. Landwirtschaftliche Belange sollen wieder ins gesellschaftliche Bewusstsein rücken.',
    'Zur Sicherung der einheimischen Landwirtschaft setzt sich das BSW für Abnahmegarantien für landwirtschaftliche Produkte aus regionaler Erzeugung ein. Öffentliche Einrichtungen sollen vorrangig [regionale Produkte beziehen].',
    'setzt sich das BSW für Abnahmegarantien für landwirtschaftliche Produkte aus regionaler Erzeugung ein',
   ),
  ]),
  ('Wodurch sollen landwirtschaftliche Betriebe wirtschaftlich abgesichert werden?', [
   ('spd', 46,
    'Die Förderhöhe in der Agrarpolitik soll beibehalten und die Mittel regional verteilt werden. Gemeinwohlleistungen der Landwirtschaft sollen honoriert werden. Entscheidungen über Flächen sollen ortsnah und fachlich fundiert fallen.',
    'Öffentliche Agrarförderung gerecht ausgestalten, Gemeinwohl stärken: […] Die Beibehaltung der Förderhöhe ist unabdingbar, ebenso wie die Verteilung der Mittel auf regionaler Ebene. Gemeinwohlleistungen der Landwirtschaft – etwa für Umwelt [und] Klima […].',
    'Die Beibehaltung der Förderhöhe ist unabdingbar, ebenso wie die Verteilung der Mittel auf regionaler Ebene',
   ),
   ('fdp', 15,
    'Landwirte sollen beim Grunderwerb nicht doppelt besteuert werden, Share Deals sollen verursachergerecht erfasst werden. Der Boden gilt als wichtigstes Produktionsmittel. Angestrebt wird eine nachhaltige Produktivitätssteigerung.',
    'Fairness beim Grunderwerb: doppelte Besteuerung beenden, Share Deals verursachergerecht erfassen. Landwirte beim Grunderwerb doppelt zu besteuern, finden wir nicht fair. Das wichtigste Produktionsmittel für Landwirte ist der Boden.',
    'Fairness beim Grunderwerb: doppelte Besteuerung beenden, Share Deals verursachergerecht erfassen',
   ),
   ('linke', 111,
    'Ein Agrarstrukturgesetz soll Bodenpreise begrenzen und Landkonzentration verhindern. Share Deals beim Erwerb landwirtschaftlicher Betriebe sollen landesweit verboten werden. Die Privatisierung der BVVG-Flächen soll dauerhaft enden.',
    'Wir wollen: ein Agrarstrukturgesetz für Sachsen-Anhalt, das Bodenpreise begrenzt und Landkonzentration verhindert, ein landesweites Verbot von Share Deals beim Erwerb landwirtschaftlicher Betriebe, die Privatisierung der BVVG-Flächen dauerhaft beenden.',
    'ein Agrarstrukturgesetz für Sachsen-Anhalt, das Bodenpreise begrenzt und Landkonzentration verhindert',
   ),
  ]),
 ]),
 ('verwaltung', 'Verwaltung und Digitalisierung',
  'Behördenleistungen, Personal und digitale Verfahren.', [
  ('Wie soll die Verwaltung digitalisiert werden?', [
   ('cdu', 52,
    'Erfolgreiche Modellprojekte für digitalisierte Verwaltungsprozesse sollen zentral finanziert und standardisiert werden. So sollen erprobte Lösungen in die Fläche kommen. Kritische IT-Systeme sollen auf Open-Source-Software umgestellt werden.',
    'Digitale Verwaltung ausbauen: Erfolgreiche Modellprojekte für digitalisierte Verwaltungsprozesse werden zentral finanziert und standardisiert, um erprobte Lösungen [zu verbreiten]. […] Die Umstellung kritischer IT-Systeme auf Open-Source Software sichert eine langfristige Arbeitsfähigkeit.',
    'Erfolgreiche Modellprojekte für digitalisierte Verwaltungsprozesse werden zentral finanziert und standardisiert',
   ),
   ('spd', 50,
    'Digitale Lösungen sollen zentral entwickelt und bereitgestellt werden, um Kommunen zu entlasten. Bewährte Lösungen aus anderen Bundesländern sollen übernommen werden. Ziel sind besserer Service, schnellere Verfahren und mehr Transparenz.',
    '[Lösungen sollen] zentral entwickelt und bereitgestellt werden, um Kommunen bei der Umsetzung zu entlasten. Digital etablierte Lösungen sind aus anderen Bundesländern zu übernehmen. Digitale Verwaltung dient nicht der Technik um ihrer selbst willen, sondern besserem Service, schnelleren Verfahren und mehr Transparenz.',
    'Digital etablierte Lösungen sind aus anderen Bundesländern zu übernehmen',
   ),
   ('gruene', 89,
    'Die digitale Verwaltung soll aus Sicht der Nutzenden gedacht und gestaltet werden. Alle Verwaltungsdienstleistungen sollen über einen zentralen Zugang erreichbar sein. Verfahren sollen medienbruchfrei ablaufen.',
    'Die digitale Verwaltung muss aus Sicht der Nutzenden gedacht und gestaltet werden. Alle Verwaltungsdienstleistungen sollen über einen zentralen Zugang erreichbar sein.',
    'Alle Verwaltungsdienstleistungen sollen über einen zentralen Zugang erreichbar se',
   ),
   ('bsw', 74,
    'Digitale Behördengänge sollen für Bürger und Unternehmen einfacher, schneller und nachvollziehbarer werden. Digitale Serviceangebote sollen weiter ausgebaut werden. Digitalisierung soll dabei ein Angebot bleiben und kein Zwang werden.',
    'Digitalisierung muss ein Angebot sein, kein Zwang. Digitale Behördengänge sollen für Bürger sowie Unternehmen einfacher, schneller und nachvollziehbarer werden. Wir wollen den weiteren Ausbau digitaler Serviceangebote […].',
    'Digitalisierung muss ein Angebot sein, kein Zwang',
   ),
  ]),
  ('Wie soll der Staat schlanker und einfacher werden?', [
   ('fdp', 44,
    'Digitalisierung soll bessere Services, weniger Wege und schnellere Entscheidungen bringen. Der Abbau von Bürokratie soll gemessen und über die Zeit sichtbar gemacht werden. Entbürokratisierung wird damit zum politischen Gradmesser.',
    'So wird Entbürokratisierung zum politischen Gradmesser: Jede Regierung muss daran erkennbar liefern. Digitale Verwaltung ohne Umwege: Digitalisierung ist dann gut, wenn sie Freiheit schafft: bessere Services, weniger Wege, weniger Papier, schnellere Entscheidungen.',
    'Digitalisierung ist dann gut, wenn sie Freiheit schafft: bessere Services, weniger Wege',
   ),
   ('afd', 18,
    'Ausgaben in Verwaltung und Ministerien sollen gekürzt und die Zahl der Ministerien reduziert werden. Unnötige Landesgesellschaften sollen aufgelöst und das Landesverwaltungsamt abgeschafft werden. Überflüssige Gesetze sollen gestrichen werden.',
    '[Wir werden] Ausgaben in Verwaltung und Ministerien kürzen und die Zahl der Ministerien reduzieren; unnötige Landesgesellschaften auflösen und das Landesverwaltungsamt abschaffen; überflüssige Gesetze streichen.',
    'Ausgaben in Verwaltung und Ministerien kürzen und die Zahl der Ministerien reduzieren',
   ),
   ('linke', 98,
    'Statt Behörden-Dschungel sollen One-Stop-Shops mit klaren Zuständigkeiten geschaffen werden. Verwaltungen sollen gemeinsam die besten Verfahren erarbeiten. Damit sollen Abläufe für alle einfacher werden.',
    'Statt Behörden-Dschungel und unklaren Verantwortlichkeiten, können „OneStop-Shops“ und damit klare Zuständigkeiten geschaffen werden.',
    '„OneStop-Shops“ und damit klare Zuständigkeiten',
   ),
  ]),
 ]),
]
