# -*- coding: utf-8 -*-
"""Datensatz Landtagswahl Sachsen-Anhalt 2026. Alle Aussagen aus den PDFs."""

WAHL = {
    "id": "lt-st-2026",
    "name": "Landtagswahl Sachsen-Anhalt",
    "region": "Sachsen-Anhalt",
    "wahltag": "2026-09-06",
    "kuerzel": "st",
}

PROGRAMME = {
    "cdu": ("Regierungsprogramm zur Landtagswahl am 6. September 2026",
            "https://www.cdulsa.de/sites/www.cdulsa.de/files/downloads/regierungsprogramm_ltw_web.pdf"),
    "spd": ("Mit Herz, Haltung und Zuversicht. Wahlprogramm 2026",
            "https://spdsachsenanhalt.de/wp-content/uploads/sites/63/2026/03/SPD-Wahlprogramm-2026.pdf"),
    "gruene": ("Nur mit Grün wird Zukunft draus. Programm zur Landtagswahl 2026",
               "https://www.gruene-lsa.de/wp-content/uploads/2026/05/Programm-zur-Landtagswahl-2026.pdf"),
    "fdp": ("Freiheit hat nur eine Heimat. Wahlprogramm zur Landtagswahl 2026",
            "https://www.fdp-lsa.de/sites/default/files/2026-07/fdpwahlprogrammltw2026.pdf"),
    "afd": ("Das Land zuerst. Regierungsprogramm zur Landtagswahl 2026",
            "https://afd-lsa.de/wp-content/uploads/2026/07/AfD_Sachsen-Anhalt_Regierungsprogramm_2026_230726-web.pdf"),
    "linke": ("Wir sind der Pol der Hoffnung. Wahlprogramm zur Landtagswahl 2026",
              "https://www.dielinke-sachsen-anhalt.de/fileadmin/aaa_download_lsa/Parteitage/10._LPT_2._Tagung_VV_LTW_2026/Beschluesse/2026-03-19_Landtagswahlprogramm__final_.pdf"),
    "bsw": ("Sachsen-Anhalt bleibt anders. Wahlprogramm zur Landtagswahl 2026",
            "https://st.bsw-vg.de/wp-content/uploads/2026/04/BSW_Landtagswahlprogramm_SachsenAnhalt.pdf"),
}

# (themaId, Titel, Beschreibung, [(Fragetext, [Aussagen])])
# Aussage: (parteiId, seite, kurz, original, markierung)
# Regeln: 3-4 Aussagen je Frage, jede Partei je Thema genau einmal,
# alle Aussagen einer Frage beantworten dieselbe Unterfrage.
THEMEN = [
 ('sicherheit', 'Innere Sicherheit und Polizei',
  'Personal und Befugnisse der Polizei, Kontrolle und Prävention.', [
  ('Wie soll die Polizei personell und materiell ausgestattet werden?', [
   ('cdu', 6,
    'Die Landespolizei soll personell deutlich wachsen, auf weit mehr als 8.100 Bedienstete. Zugleich sollen ihre Kompetenzen und Befugnisse erweitert werden. Ziel ist eine sichtbare und handlungsfähige Polizei.',
    'Spürbare Sicherheit: Sicherheit gewährleisten durch eine sichtbare und handlungsfähige Polizei, hierzu erweitern wir ihre Kompetenzen und Befugnisse. Wir wollen einen personellen Aufwuchs innerhalb der Landespolizei auf weit mehr als 8.100 Bedienstete.',
    'personellen Aufwuchs innerhalb der Landespolizei auf weit mehr als 8.100 Bedienstete',
   ),
   ('gruene', 41,
    'Der Personalausbau im Polizeivollzug soll bis zur Zielgröße von 7.000 Stellen fortgesetzt werden. Zusätzlich soll die Polizeiverwaltung substanziell gestärkt werden. Polizeireviere sollen eigenständige Budgets erhalten.',
    'Der Personalausbau bei den Vollzugsbeamt*innen soll konsequent bis zur Zielgröße von 7.000 Stellen fortgesetzt werden. Gleichzeitig ist eine substanzielle Stärkung der Polizeiverwaltung erforderlich. […] Zudem sollen eigenständige und verlässliche Budgets für die Polizeireviere umgesetzt werden.',
    'Der Personalausbau bei den Vollzugsbeamt*innen soll konsequent bis zur Zielgröße von 7.000 Stellen fortgesetzt werden',
   ),
   ('fdp', 47,
    'Mehr sichtbare Polizei in Stadt und Land soll durch eine klare Aufgabentrennung nach Qualifikation entstehen. Dafür wird eine Laufbahn als Polizeiverwaltungsassistent geschaffen. So wird der Vollzugsdienst entlastet.',
    'Wir sorgen für sichtbar mehr Polizei in Stadt und Land durch eine klare Aufgabentrennung nach Qualifikation. […] Wir setzen uns für die Schaffung einer Laufbahn als Polizeiverwaltungsassistenten ein. So wird der Vollzugsdienst konsequent entlastet.',
    'Wir sorgen für sichtbar mehr Polizei in Stadt und Land durch eine klare Aufgabentrennung nach Qualifikation',
   ),
   ('bsw', 67,
    'Polizei und Ermittlungsbehörden sollen so ausgestattet werden, dass sie kriminellen Netzwerken auf Augenhöhe begegnen können. Der Schwerpunkt liegt auf der Bekämpfung organisierter Kriminalität. Eine Privatisierung von Sicherheitsaufgaben wird abgelehnt.',
    'Wir wollen Polizei und Ermittlungsbehörden in Sachsen-Anhalt so ausstatten, dass sie auf Augenhöhe mit kriminellen Netzwerken und der Organisierten Kriminalität agieren können. […] Polizei als staatliche Kernaufgabe stärken, Privatisierung ablehnen.',
    'Polizei und Ermittlungsbehörden in Sachsen-Anhalt so ausstatten, dass sie auf Augenhöhe mit kriminellen Netzwerken',
   ),
  ]),
  ('Was braucht die Polizei über mehr Personal hinaus?', [
   ('spd', 29,
    'Polizistinnen und Polizisten sollen von bürokratischen Aufgaben entlastet werden, um sich auf ihre Kernaufgaben zu konzentrieren. Das Beförderungsbudget wird deutlich verbessert, um den Beförderungsstau abzubauen. Dienststellen sollen baulich auf modernen Stand gebracht werden.',
    'Bürokratische Belastungen werden reduziert, damit Polizistinnen und Polizisten sich auf ihre Kernaufgaben konzentrieren können. […] Deshalb wird das Beförderungsbudget deutlich verbessert, um den Stau abzubauen und verlässliche Perspektiven zu schaffen.',
    'Bürokratische Belastungen werden reduziert, damit Polizistinnen und Polizisten sich auf ihre Kernaufgaben konzentrieren können',
   ),
   ('afd', 106,
    'Die Polizei soll mit Distanz-Elektro-Impulsgeräten ausgestattet werden. In vielen Lagen sei der Schusswaffengebrauch unverhältnismäßig, mildere Mittel wie Pfefferspray oder Schlagstock aber unzureichend.',
    'In vielen Fällen der polizeilichen Praxis wäre der Schusswaffengebrauch unverhältnismäßig, mildere Mittel wie Pfefferspray oder Schlagstock aber unzureichend. Oft wäre dann ein Distanz-Elektro-Impulsgerät, landläufig auch „Elektroschocker“ oder „Taser“ genannt, das Mittel der Wahl.',
    'mildere Mittel wie Pfefferspray oder Schlagstock aber unzureichend',
   ),
   ('linke', 128,
    'Sicherheitspolitik soll öffentlich beraten werden, mit Anhörungen zu Sicherheitsgesetzen und Bürgerforen zur Polizeiarbeit. Eine unabhängige Polizeibeschwerdestelle mit eigenen Ermittlungsbefugnissen soll eingerichtet werden. Polizeistatistiken sollen offengelegt werden.',
    'Wir schaffen echte Bürger:innenbeteiligung bei sicherheitspolitischen Fragen: Öffentliche Anhörungen zu neuen Sicherheitsgesetzen, Bürger:innenforen zur Polizeiarbeit vor Ort […]. Ihre Rechte werden gestärkt durch eine unabhängige Polizeibeschwerdestelle mit eigenen Ermittlungsbefugnissen.',
    'eine unabhängige Polizeibeschwerdestelle mit eigenen Ermittlungsbefugnissen',
   ),
  ]),
 ]),
 ('migration', 'Migration und Integration',
  'Aufnahme, Rückführung, Sprachförderung und Zugang zum Arbeitsmarkt.', [
  ('Wie soll mit Menschen ohne Bleiberecht umgegangen werden?', [
   ('cdu', 6,
    'Migration soll geordnet, begrenzt und gesteuert werden: Schutz für Berechtigte, konsequente Rückführung für alle ohne Bleiberecht. Die irreguläre Migration soll auf null zurückgeführt werden. Integration soll verlässlich geregelt sein.',
    'Migration ordnen, begrenzen, steuern: Klare Regeln: Schutz für Berechtigte, konsequente Rückführung für alle ohne Bleiberecht, Missbrauch verhindern, Integration mit Verlässlichkeit. Wir wollen die irreguläre Migration auf null zurückführen.',
    'konsequente Rückführung für alle ohne Bleiberecht',
   ),
   ('fdp', 10,
    'Der irregulären Migration soll mit aller Kraft entgegengewirkt werden, Ausreisepflichtige sollen das Land zügig verlassen. Aufenthaltstitel zur Beschäftigung sollen binnen vier Wochen erteilt werden. Sprachkurse sollen vorrangig Selbstzahlern angeboten werden.',
    'Der irregulären Migration werden wir mit aller Kraft entgegenwirken. Ausreisepflichtige Ausländer müssen zügig das Land verlassen. […] Ziel ist es, dass Aufenthaltstitel, die zur Aufnahme einer Beschäftigung berechtigen, innerhalb von vier Wochen erteilt werden.',
    'Der irregulären Migration werden wir mit aller Kraft entgegenwirken. Ausreisepflichtige Ausländer müssen zügig das Land verlassen',
   ),
   ('afd', 43,
    'Ausreisepflichtige sollen konsequent abgeschoben und eine Abschiebeoffensive eingeleitet werden. Abschiebung sei Ländersache: 2024 seien 654 Personen abgeschoben worden, während 1.252 Abschiebungen scheiterten. Dafür sind 100 Millionen Euro vorgesehen.',
    'Ausreisepflichtige konsequent abschieben – Abschiebeoffensive einleiten! Abschiebung ist Ländersache. Im Jahre 2024 wurden von der CDU-geführten Landesregierung lediglich 654 ausreisepflichtige Personen abgeschoben, während 1.252 Abschiebungen scheiterten. […] einen Betrag in Höhe von 100 Millionen Euro zur Einleitung einer Abschiebeoffensive für ausreisepflichtige Ausländer.',
    'Ausreisepflichtige konsequent abschieben',
   ),
   ('bsw', 62,
    'Wer keinen Anspruch auf Asyl hat, bei Asylmissbrauch oder bei Straffälligkeit soll konsequent abgeschoben werden. Die einheimische Bevölkerung soll vor Überlastungstendenzen geschützt werden. Die Handlungsfähigkeit des Staates soll sichtbar sein.',
    'Die einheimische Bevölkerung ist vor Überlastungstendenzen zu schützen. Die Handlungsfähigkeit des Staates muss glaubhaft und sichtbar sein. Dazu gehört auch die konsequente Abschiebung, wenn kein Anspruch auf Asyl besteht, Asylmissbrauch vorliegt oder Migranten straffällig werden.',
    'die konsequente Abschiebung, wenn kein Anspruch auf Asyl besteht',
   ),
  ]),
  ('Was soll denen geboten werden, die bleiben?', [
   ('spd', 33,
    'Wer arbeitet, lernt oder eine Ausbildung absolviert, soll eine Bleibeperspektive erhalten. Freiwillige Rückkehr wird unterstützt, Abschiebungen bleiben letztes Mittel. Ordnung und Humanität sollen sich nicht ausschließen.',
    'Menschen, die arbeiten, lernen oder eine Ausbildung absolvieren, sollen eine Bleibeperspektive haben. Freiwillige Rückkehr wird unterstützt. Abschiebungen bleiben die ultima ratio. Ordnung und Humanität schließen sich nicht aus.',
    'sollen eine Bleibeperspektive haben. Freiwillige Rückkehr wird unterstützt. Abschiebungen bleiben die ultima ratio',
   ),
   ('gruene', 78,
    'Sprachkurse sollen ab dem ersten Tag zugänglich sein, nicht erst nach Anerkennung oder Verwaltungsverfahren. Dazu gehören flexible und berufsbegleitende Kursmodelle. Sprache gilt als Schlüssel zu Arbeit, Bildung und Alltag.',
    'Sprache ist der Schlüssel zu allem: Arbeit, Bildung, Alltag, Begegnung. Deshalb sollen Sprachkurse ab dem ersten Tag zugänglich sein, nicht erst nach Anerkennung oder nach Verwaltungsverfahren. Dazu gehören flexible Kursmodelle, berufsbegleitende […] Angebote.',
    'Sprachkurse ab dem ersten Tag zugänglich sein, nicht erst nach Anerkennung',
   ),
   ('linke', 97,
    'Sprachkurse sollen flächendeckend angeboten werden, auch im ländlichen Raum. Ausländische Qualifikationen sollen anerkannt, Familiennachzug ermöglicht werden. Ziel sind klare Regelungen und verlässliche Zusagen.',
    'Das erreichen wir über klare Regelungen [und] verlässliche Zusagen, was flächendeckende Angebote an Sprachkursen, auch im ländlichen Raum, die Anerkennung von Qualifikationen und die Möglichkeit des Familiennachzuges angeht.',
    'flächendeckende Angebote an Sprachkursen, auch im ländlichen Raum, die Anerkennung von Qualifikationen',
   ),
  ]),
 ]),
 ('schule', 'Schule und Unterrichtsversorgung',
  'Lehrkräfte, Unterrichtsausfall, Schulformen und Ganztag.', [
  ('Wie soll dem Lehrkräftemangel und dem Unterrichtsausfall begegnet werden?', [
   ('cdu', 24,
    'Um die Unterrichtsversorgung im ländlichen Raum zu sichern, sollen Lehrkräfte im Vorbereitungsdienst eine ergänzende Zulage erhalten. Leistungsorientierung wird mit Chancengleichheit verbunden. Schulentwicklung soll datengestützt erfolgen.',
    'Personalentwicklung gestalten: Um die Unterrichtsversorgung im ländlichen Raum zu sichern, sollen Lehrkräfte im Vorbereitungsdienst eine ergänzende Zulage zu ihren Anwärterbezügen erhalten […]. Wir verbinden Leistungsorientierung mit Chancengleichheit.',
    'Um die Unterrichtsversorgung im ländlichen Raum zu sichern, sollen Lehrkräfte im Vorbereitungsdienst eine ergänzende Zulage',
   ),
   ('spd', 18,
    'Ein umfassendes Programm soll die Unterrichtsversorgung absichern. Schulstandorte im ländlichen Raum sollen erhalten und weiterentwickelt werden. Flexible, schulbezogene Modelle sollen Bildung auch dort ermöglichen, wo die Schülerzahlen sinken.',
    'Deshalb braucht es ein umfassendes Programm zur Absicherung der Unterrichtsversorgung. […] Schulstandorte im ländlichen Raum werden erhalten und weiterentwickelt. Flexible Modelle und schulbezogene Lösungen ermöglichen Bildung auch dort, wo Schülerzahlen sinken.',
    'ein umfassendes Programm zur Absicherung der Unterrichtsversorgung',
   ),
   ('linke', 33,
    'Der Mangel an ausgebildeten Lehrkräften soll mit einem Zehn-Punkte-Plan für eine gute Unterrichtsversorgung behoben werden. Schulen sollen möglichst große Teile ihres Schulhaushalts selbst bewirtschaften. Ursache ist aus Sicht der Partei eine Fehleinschätzung des Ausbildungsbedarfs.',
    'Wir wollen den Schulen möglichst große Teile ihres Schulhaushalts als Budget zur eigenen Bewirtschaftung zur Verfügung stellen. Ressourcen sichern: 10 Punkte für eine gute Unterrichtsversorgung. Der extreme Mangel an ausgebildeten Lehrkräften […].',
    'Ressourcen sichern: 10 Punkte für eine gute Unterrichtsversorgung',
   ),
  ]),
  ('Welcher Umbau der Schule hat darüber hinaus Vorrang?', [
   ('gruene', 59,
    'Alle allgemeinbildenden Schulen sollen zu Schulen mit Ganztagsangebot weiterentwickelt werden. Volkshochschulen, Musikschulen, Sportvereine und Ehrenamt sollen in den Ganztag eingebunden werden. Der Zugang soll möglichst kostenfrei sein.',
    'Deshalb wollen wir alle allgemeinbildenden Schulen in Sachsen-Anhalt zu Schulen mit Ganztagsangebot weiterentwickeln und den Ausbau der Ganztagsangebote konsequent vorantreiben. Dabei sollen an allen Schulen Angebote von Volkshochschulen, Musikschulen, Sportvereinen sowie aus dem Ehrenamt in den Ganztag eingebunden werden.',
    'alle allgemeinbildenden Schulen in Sachsen-Anhalt zu Schulen mit Ganztagsangebot weiterentwickeln',
   ),
   ('fdp', 23,
    'Alle Schulen sollen eine moderne digitale Infrastruktur mit passenden Geräten erhalten. Damit soll zeitgemäßes Lernen ermöglicht und Unterrichtsausfall gerade im ländlichen Raum vermieden werden. Zusätzlich wird in nachhaltige und barrierefreie Schulgebäude investiert.',
    'Eine moderne digitale Infrastruktur soll nun durch eine entsprechende Struktur und Geräte in allen Schulen ergänzt werden, um zeitgemäßes Lernen zu ermöglichen und Unterrichtsausfall – gerade im ländlichen Raum – möglichst zu vermeiden.',
    'um zeitgemäßes Lernen zu ermöglichen und Unterrichtsausfall',
   ),
   ('afd', 72,
    'Angestrebt wird ein leistungsdifferenziertes, mehrgliedriges Schulsystem. Das Gymnasium soll gestärkt werden und wieder die Schulform sein, die höchstens 25 Prozent eines Jahrgangs besuchen. Die Wiedereinführung von Hauptschule und Realschule soll geprüft werden.',
    '[Wir treten] für ein leistungsdifferenziertes, mehrgliedriges Schulsystem ein. Wir werden das Gymnasium stärken und wieder zu dem machen, was es war: Die Schulform, die zur Universität führt und von nicht mehr als 25 Prozent eines Jahrgangs besucht werden muss. Weiterhin werden wir die Wiedereinführung von Hauptschule und Realschule prüfen.',
    'für ein leistungsdifferenziertes, mehrgliedriges Schulsystem ein',
   ),
   ('bsw', 45,
    'Das gegliederte Schulsystem habe sich überlebt. Angestrebt wird längeres gemeinsames Lernen bis zur 8. Klasse. Die frühe Auswahl in der 4. Klasse benachteilige Kinder aus sozial schwächeren Haushalten.',
    'Die frühzeitige Selektion in der 4. Klasse für den zukünftigen Schulweg steht dem entgegen und benachteiligt zudem Kinder aus sozial schwächeren Haushalten. […] Das gegliederte Schulsystem hat sich überlebt. […] Längeres gemeinsames Lernen bleibt ein wichtiges Ziel.',
    'Das gegliederte Schulsystem hat sich überlebt',
   ),
  ]),
 ]),
 ('kita', 'Frühkindliche Bildung und Kita',
  'Personalschlüssel, Betreuungsplätze und Elternbeiträge.', [
  ('Wie soll der Personalschlüssel in den Kitas verbessert werden?', [
   ('spd', 28,
    'Der tatsächliche Personalschlüssel in der Arbeit mit den Kindern soll schrittweise verbessert werden. Kitas mit besonderen sozialen Herausforderungen erhalten zusätzliche Unterstützung. Beitragsfreiheit bleibt das erklärte Ziel.',
    'Der tatsächliche Personalschlüssel in der Arbeit mit den Kindern wird schrittweise verbessert. Kitas mit besonderen sozialen Herausforderungen erhalten zusätzliche Unterstützung. […] Beitragsfreiheit bleibt unser Ziel.',
    'Der tatsächliche Personalschlüssel in der Arbeit mit den Kindern wird schrittweise verbessert',
   ),
   ('gruene', 57,
    'Der Mindestpersonalschlüssel in den Kitas soll angehoben werden. Die Sonderförderung für Kitas mit besonderen Bedarfen wird ausgebaut und die Kitasozialarbeit gefördert. Aus der mittelfristigen Lösung soll eine strukturelle Verbesserung werden.',
    'Dafür wollen wir den Mindestpersonalschlüssel anheben, die zielgenaue Sonderförderung für Kitas mit besonderen Bedarfen ausbauen und insbesondere die Kitasozialarbeit fördern.',
    'wollen wir den Mindestpersonalschlüssel anheben',
   ),
   ('fdp', 25,
    'Der Betreuungsschlüssel soll weiter angepasst werden, unter Einbezug der individuellen Kinderförderung. Auch Zeit für Vor- und Nachbereitung soll berücksichtigt werden. Kindertagesstätte, Hort und Grundschule sollen enger verzahnt werden.',
    'Zudem fordern wir eine weitere Anpassung des Betreuungsschlüssels unter Einbezug der Erfordernisse der individuellen Kinderförderung sowie der notwendigen zeitlichen Kontingente für die Vor- und Nachbereitung.',
    'eine weitere Anpassung des Betreuungsschlüssels unter Einbezug der Erfordernisse der individuellen Kinderförderung',
   ),
   ('bsw', 42,
    'In den Kitas fehlen aus Sicht der Partei Fachkräfte, Plätze und Zeit für pädagogische Arbeit. Schlechte Personalschlüssel machten frühkindliche Bildung zur bloßen Betreuung. Stattdessen sollen Grundlagen für Sprache, Mathematik und soziale Entwicklung gelegt werden.',
    'In Kitas fehlen Fachkräfte, Plätze und Zeit für pädagogische Arbeit. Schlechte Personalschlüssel machen frühkindliche Bildung oft zur bloßen Betreuung, statt Grundlagen für Sprache, Mathematik und soziale Entwicklung zu legen.',
    'Schlechte Personalschlüssel machen frühkindliche Bildung oft zur bloßen Betreuung',
   ),
  ]),
  ('Wie soll die frühkindliche Betreuung finanziert und ausgebaut werden?', [
   ('cdu', 49,
    'Das letzte Kita-Jahr soll gezielt als Vorschuljahr ausgestaltet werden. Ein belastbares Konzept soll den tatsächlichen Bedarf erfassen, die Finanzierung stabilisieren und den Personalschlüssel verbessern. Ein Runder Tisch soll Vorschläge zu Finanzierung und Personalgewinnung erarbeiten.',
    'Das letzte Kita-Jahr zum Vorschuljahr ausbauen: Wir werden das letzte Kita-Jahr gezielt als Vorschuljahr ausgestalten. […] Wir werden ein belastbares Konzept vorlegen, das den tatsächlichen Bedarf realistisch erfasst, eine stabile Finanzierung gewährleistet und gleichzeitig den Personalschlüssel verbessert. […] Dazu werden wir einen Runden Tisch mit allen Beteiligten einrichten.',
    'Wir werden das letzte Kita-Jahr gezielt als Vorschuljahr ausgestalten',
   ),
   ('afd', 18,
    'Krippen und Kindergärten sollen ab dem ersten Kind kostenlos werden, mit einer dauerhaft auf Landesebene gesicherten Finanzierung. Auch die Mittagsverpflegung soll für alle Kinder kostenfrei und von hoher Qualität sein.',
    'Wir werden Krippen und Kindergärten mit einer dauerhaft auf Landesebene gesicherten Finanzierung ab dem ersten Kind kostenlos machen. Die Mittagsverpflegung muss für alle Kinder, von der Krippe bis zur Schule, ebenfalls kostenfrei und von hoher Qualität vorzuhalten sein.',
    'Krippen und Kindergärten mit einer dauerhaft auf Landesebene',
   ),
   ('linke', 27,
    'In Schulen, Kitas, Schulsozialarbeit und Jugendhilfe soll dauerhaft und ausreichend investiert werden. Gefordert wird eine Abkehr von der Sparpolitik bei den Jüngsten. Bildungspolitik soll soziale Unterschiede aktiv ausgleichen.',
    'Wir stehen für eine Abkehr von der „Rotstiftpolitik bei den Kleinen“: Wer von Zukunft redet, muss in Schulen, Kitas, Schulsozialarbeit, Jugendhilfe, Weiterbildung und digitale Infrastruktur dauerhaft und ausreichend investieren.',
    'muss in Schulen, Kitas, Schulsozialarbeit, Jugendhilfe, Weiterbildung und digitale Infrastruktur dauerhaft und ausreichend investieren',
   ),
  ]),
 ]),
 ('wirtschaft', 'Wirtschaft und Bürokratie',
  'Standort, Ansiedlung, Entlastung von Unternehmen.', [
  ('Wie soll die Bürokratie für Betriebe verringert werden?', [
   ('spd', 4,
    'Handwerk, Gewerbe und Mittelstand sollen nicht durch Bürokratie ausgebremst werden. Gesetze werden auf ihre Wirkung hin geprüft. Mitbestimmung in den Betrieben wird als Bestandteil einer fairen Wirtschaftsordnung gestärkt.',
    'Mittelstand, Handwerk und Bürokratieabbau: Handwerk, Gewerbe und Mittelstand sichern Arbeitsplätze im ganzen Land. Bürokratie darf sie nicht ausbremsen. […] Mitbestimmung in den Betrieben ist ein zentraler Bestandteil einer fairen Wirtschaftsordnung und wird gestärkt.',
    'Handwerk, Gewerbe und Mittelstand sichern Arbeitsplätze im ganzen Land. Bürokratie darf sie nicht ausbremsen',
   ),
   ('gruene', 89,
    'Dokumentations- und Berichtspflichten sollen reduziert und Verfahren durch klare Zuständigkeiten beschleunigt werden. Prozesse sollen digital und medienbruchfrei ablaufen. Im Bundesrat wird für ein reformiertes Vergaberecht mit regionalen Kriterien geworben.',
    'Wir setzen uns außerdem im Bundesrat für ein reformiertes Bundesvergaberecht ein, das mehr regionale Kriterien berücksichtigt und Bürokratie abbaut. […] Wir wollen Bürokratie abbauen, Dokumentations- und Berichtspflichten sollen reduziert und Verfahren durch klare Zuständigkeiten sowie digitale, medienbruchfreie Prozesse […].',
    'Dokumentations- und Berichtspflichten sollen reduziert und Verfahren durch klare Zuständigkeiten',
   ),
   ('fdp', 7,
    'Die Bürokratielast soll spürbar gesenkt werden, damit Investitionen nicht in Verfahren stecken bleiben. Unternehmen sollen ihre Zeit in die Entwicklung ihrer Produkte statt in Zuständigkeiten investieren. Ziel ist ein Staat, der Leistung ermöglicht statt behindert.',
    'Bürokratieabbau heißt am Ende: weniger Stillstand, mehr Tempo und ein Staat, der Leistung ermöglicht, statt sie behindert. Deshalb werden wir die Bürokratielast [senken].',
    'ein Staat, der Leistung ermöglicht, statt sie behindert',
   ),
  ]),
  ('Wodurch soll das Land die heimische Wirtschaft darüber hinaus stärken?', [
   ('cdu', 13,
    'Produktionsvorhaben für wichtige Medikamente sollen als strategische Projekte anerkannt werden. Dadurch sollen Genehmigungsverfahren beschleunigt und Fördermöglichkeiten verbessert werden. Ziel sind attraktive Rahmenbedingungen für Ansiedlungen.',
    'Ziel ist es, Produktionsvorhaben für wichtige Medikamente als „strategische Projekte“ anerkennen zu lassen. Dadurch können Genehmigungsverfahren beschleunigt, Fördermöglichkeiten verbessert und beihilferechtliche Spielräume erweitert werden.',
    'Dadurch können Genehmigungsverfahren beschleunigt, Fördermöglichkeiten verbessert',
   ),
   ('afd', 143,
    'Die Förderung soll sich auf kleine und mittelständische heimische Unternehmen richten statt auf die Ansiedlung und Subventionierung ausländischer Großkonzerne. Als Beispiel wird die geplante Intel-Ansiedlung genannt, für die zehn Milliarden Euro Subventionen vorgesehen waren.',
    'Förderung des Mittelstands statt Subventionierung globalistischer Großkonzerne! […] Statt sich auf die Unterstützung heimischer Unternehmen zu fokussieren, konzentriert sie sich auf die Ansiedlung und Subventionierung ausländischer Großkonzerne. Nach den Plänen der Landesregierung […] sollten für die Intel-Ansiedlung Subventionen in Höhe von zehn Milliarden Euro fließen.',
    'Statt sich auf die Unterstützung heimischer Unternehmen zu fokussieren',
   ),
   ('linke', 86,
    'Die Tarifbindung soll wieder zur Regel werden, weil immer weniger Betriebe nach Tarif zahlen. Gefordert werden ein Vergabemindestlohn von 16,50 Euro je Stunde und ein konsequentes Vergabegesetz. Zudem soll die Allgemeinverbindlichkeit von Tarifverträgen erleichtert werden.',
    'Wo Tarif gilt, geht es den Menschen besser. Doch immer weniger Betriebe zahlen ihn noch – das drückt Löhne und mindert Lebensqualität. Wir wollen die Tarifbindung wieder zur Regel machen. Dafür fordern wir: einen Vergabemindestlohn von 16,50 Euro pro Stunde […], die Einführung eines konsequenten Vergabegesetzes […], die Allgemeinverbindlichkeit von Tarifverträgen zu erleichtern.',
    'Wir wollen die Tarifbindung wieder zur Regel machen',
   ),
   ('bsw', 18,
    'Für heimische und regional agierende Betriebe ist aus Sicht der Partei nicht der Kostendruck, sondern die schwache Binnennachfrage das Hauptproblem. Bürokratieabbau und Entlastungen seien wichtig, schafften aber keine Aufträge. Entscheidend sei, dass Geld in der Region zirkuliert.',
    'Für die heimischen und regional agierenden Betriebe ist nicht der internationale Kostendruck das Hauptproblem, sondern die anhaltende Schwäche der Binnennachfrage. Echter Bürokratieabbau und Entlastungen sind wichtig, schaffen jedoch keine neuen Aufträge.',
    'Echter Bürokratieabbau und Entlastungen sind wichtig, schaffen jedoch keine neuen Aufträge',
   ),
  ]),
 ]),
 ('energie', 'Energie und Windkraft',
  'Ausbau erneuerbarer Energien, Netze und Akzeptanz vor Ort.', [
  ('Wer soll darüber entscheiden, wo Windräder gebaut werden?', [
   ('gruene', 23,
    'Am Flächenziel für den Ausbau erneuerbarer Energien wird konsequent festgehalten. Eignungsgebiete sollen über die Regionalplanung ausgewiesen werden, NATURA-2000-Gebiete bleiben ausgeschlossen. Der Windausbau gilt als Voraussetzung für lokalen grünen Wasserstoff.',
    'Wir halten konsequent am Flächenziel für den Ausbau erneuerbarer Energien fest, um die Energiewende voranzutreiben. […] Der Ausbau der Windenergie ist die wichtige Voraussetzung zur Herstellung von lokalem Grünem Wasserstoff mit regionalen Elektrolyseuren.',
    'Wir halten konsequent am Flächenziel für den Ausbau erneuerbarer Energien fest',
   ),
   ('fdp', 14,
    'Die Länder sollen einen deutlich größeren Entscheidungsspielraum beim Ausbau erneuerbarer Energien erhalten. Erfüllt ein Land bis 2027 sein Sektorenziel bei Windenergie an Land, soll die Flächenzielpflicht bis 2032 entfallen. Eigene Energiequellen sollen genutzt werden.',
    '[Wir wollen den Bundesländern] einen deutlich größeren Entscheidungsspielraum beim Ausbau erneuerbarer Energien [geben]. Erfüllen Bundesländer bis 2027 das Sektorenziel in erzeugter Energiemenge durch Windenergieanlagen an Land, entfällt die Pflicht zur Erfüllung des für sie derzeit festgelegten Flächenziels bis 2032.',
    'entfällt die Pflicht zur Erfüllung des für sie derzeit festgelegten Flächenziels bis 2032',
   ),
   ('afd', 157,
    'Das Gesetz zur Akzeptanzsteigerung beim Ausbau erneuerbarer Energien soll abgeschafft werden. Seine finanziellen Anreize seien geeignet, klamme Kommunen zur Zustimmung zu Windrädern und Solarparks zu nötigen. Bürgerinitiativen dagegen sollen unterstützt werden.',
    'Akzeptanzgesetz abschaffen! In Sachsen-Anhalt leisten zahlreiche Bürgerinitiativen Widerstand gegen den Bau von Windrädern, Solarparks und Kabeltrassen. […] Die in dem Gesetz verankerten finanziellen Anreize sind geeignet, widerspenstige Kommunen zu erpressen. […] Nun sollen die klammen Kommunen durch monetäre Anreize dazu genötigt werden, dem Bau von Windrädern oder Solarparks zuzustimmen.',
    'Nun sollen die klammen Kommunen durch monetäre Anreize dazu genötigt werden',
   ),
   ('bsw', 24,
    'Windkraftanlagen leisten aus Sicht der Partei einen wichtigen Beitrag zur Stromversorgung. Ihr Ausbau müsse jedoch regional ausgewogen erfolgen und die Belange der Bevölkerung berücksichtigen. Durch Repowering bestehender Anlagen soll die Leistung gesteigert werden.',
    'Windkraftanlagen leisten ebenfalls einen wichtigen Beitrag zur Stromversorgung. Ihr Ausbau muss jedoch regional ausgewogen erfolgen und die Belange der Bevölkerung berücksichtigen. Durch Repowering bestehender Windkraftanlagen kann ihre Leistung erheblich gesteigert werden.',
    'Ihr Ausbau muss jedoch regional ausgewogen erfolgen und die Belange der Bevölkerung berücksichtigen',
   ),
  ]),
  ('Wie sollen Kommunen und Anwohner am Ausbau beteiligt werden?', [
   ('cdu', 45,
    'Erneuerbare Energien sollen technologieoffen genutzt und die Bürgerakzeptanz bei der Windkraft gesichert werden. Windenergieanlagen im Wald werden kritisch gesehen. Alle Anlagen sollen die Zustimmung der kommunalen Ebene brauchen.',
    'Erneuerbare Energien technologieoffen nutzen und Bürgerakzeptanz bei der Windkraftnutzung sicherstellen […]. Wir stehen dem Errichten von Windenergieanlagen im Wald aufgrund seiner Multifunktionalität kritisch gegenüber. Alle Windenergieanlagen müssen stets die Zustimmung der kommunalen Ebene […].',
    'Erneuerbare Energien technologieoffen nutzen und Bürgerakzeptanz bei der Windkraftnutzung sicherstellen',
   ),
   ('spd', 5,
    'Für die Wärmewende soll auf Bürgerbeteiligung gesetzt werden. Energiegenossenschaften, Bürgerstrom und Energie-Sharing sollen gefördert werden. Das Land soll zugleich Standort für Windkraft, Wasserstoff und Batterietechnologien werden.',
    '[Wir stärken das Land als Standort für Zukunftsindustrien] von erneuerbaren Energien wie Windkraft über Wasserstoff und Batterietechnologien bis zur digitalen Wirtschaft. Für eine erfolgreiche Wärmewende setzen wir auf Bürgerbeteiligung, Förderung von Energiegenossenschaften, Bürgerstrom und Energie-Sharing.',
    'setzen wir auf Bürgerbeteiligung, Förderung von Energiegenossenschaften',
   ),
   ('linke', 107,
    'Der Ausbau erneuerbarer Energien braucht aus Sicht der Partei klare Leitplanken: Naturverträglichkeit, Transparenz und echte Beteiligung vor Ort. Kommunen sollen von Wind-, Solar- und Agri-PV-Projekten profitieren. Ökologische Standards sollen gesichert sein.',
    'Doch der Ausbau der erneuerbaren Energien braucht klare Leitplanken: Naturverträglichkeit, Transparenz und echte Beteiligung der Menschen vor Ort. Wenn Windräder, Solaranlagen und Agri-PV-Projekte Landschaften prägen, müssen Kommunen davon profitieren und ökologische Standards gesichert sein.',
    'Naturverträglichkeit, Transparenz und echte Beteiligung der Menschen vor Ort',
   ),
  ]),
 ]),
 ('gesundheit', 'Gesundheit und Krankenhäuser',
  'Wohnortnahe Versorgung, Krankenhausstandorte, Pflege.', [
  ('Wie sollen die Krankenhäuser im Land gesichert werden?', [
   ('cdu', 27,
    'Krankenhäuser sollen klare Profile und Spezialisierungen erhalten und als Knotenpunkte in regionalen Versorgungsnetzwerken eng mit ambulanten Strukturen zusammenarbeiten. Die flächendeckende medizinische Versorgung soll als Kern der Daseinsvorsorge gesichert werden.',
    'Krankenhäuser mit klaren Profilen, die eng mit ambulanten Strukturen zusammenarbeiten und als starke Knotenpunkte und Spezialisierung in regionalen Versorgungsnetzwerken verankert sind. […] Versorgung sichern – überall im Land: Wir sichern eine flächendeckende medizinische Versorgung als Kern der Daseinsvorsorge.',
    'Krankenhäuser mit klaren Profilen, die eng mit ambulanten Strukturen',
   ),
   ('gruene', 79,
    'Die Krankenhäuser im Land sollen als Orte der Gesundheits- und Notfallversorgung erhalten bleiben. Alle Berufsgruppen im Gesundheits- und Pflegebereich sollen eigenverantwortlich mitarbeiten. Kommunen, Land und Selbstverwaltung sollen optimal zusammenwirken.',
    'Krankenhausstandorte erhalten, Versorgungssicherheit gewährleisten: Die Krankenhäuser im Land müssen als Orte der Gesundheits- und Notfallversorgung erhalten werden. […] eigenverantwortliche Mitarbeit aller Professionen des Gesundheits- und Pflegebereichs.',
    'Die Krankenhäuser im Land müssen als Orte der Gesundheits- und Notfallversorgung erhalten',
   ),
   ('linke', 48,
    'Krankenhäuser sollen nach Bedarf und Qualität finanziert werden statt nach Fallpauschalen. Gefordert werden integrierte Versorgungszentren in kommunaler Trägerschaft. Diese sollen ambulante, stationäre und Notfallleistungen aus einer Hand anbieten.',
    'Wir wollen: eine Entökonomisierung: Krankenhäuser sollen nach Bedarf und Qualität finanziert und organisiert werden, nicht nach Fallpauschalen, Profit oder Kostendruck[;] integrierte Versorgungszentren in kommunaler Trägerschaft, die ambulante, stationäre und Notfallleistungen aus einer Hand anbieten.',
    'Krankenhäuser sollen nach Bedarf und Qualität finanziert und organisiert werden, nicht nach Fallpauschalen',
   ),
  ]),
  ('Wie soll die Versorgung in der Fläche erreichbar bleiben?', [
   ('spd', 12,
    'An der Schulgeldfreiheit in den Gesundheitsberufen und an Ausbildungsvergütungen soll festgehalten werden. Gesundheitsberufe sollen mehr Verantwortung übernehmen, auch durch Aufgabenverlagerung zur Entlastung von Ärztinnen und Ärzten.',
    'Deshalb setzen wir weiterhin auf die Schulgeldfreiheit in den Gesundheitsberufen und die Zahlung von Ausbildungsvergütungen. Wir unterstützen, dass Gesundheitsberufe künftig mehr Verantwortung u.a. durch Aufgabenverlagerung in der medizinischen Versorgung übernehmen – auch zur Entlastung von Ärztinnen und Ärzten.',
    'setzen wir weiterhin auf die Schulgeldfreiheit in den Gesundheitsberufen',
   ),
   ('fdp', 59,
    'Über ein landesweites Förderprogramm sollen rollende Arztpraxen und spezialisierte Facharzt-Busse in infrastrukturell schwierigen Regionen eingeführt werden. Vor allem in der Kinder- und Jugendmedizin sowie der psychiatrischen Versorgung soll das lange Anfahrtswege ersparen.',
    'Gesundheit vor Ort – Die mobile Versorgungsoffensive: Wir bringen die medizinische Versorgung zu den Menschen, die sie benötigen. Durch ein landesweites Förderprogramm etablieren wir „rollende Arztpraxen“ und spezialisierte Facharzt-Busse in infrastrukturell herausfordernden Regionen. Besonders in der Kinder- und Jugendmedizin sowie der psychiatrischen Versorgung schaffen wir so eine schnelle, wohnortnahe Behandlung ohne lange Anfahrtswege.',
    'etablieren wir „rollende Arztpraxen“ und spezialisierte Facharzt-Busse',
   ),
   ('afd', 243,
    'Die Kapazitäten für Medizinstudenten an den Universitäten des Landes sollen um mindestens 20 Prozent ausgebaut werden. Universitäten sollen mehr Bewerber unabhängig vom Numerus clausus direkt annehmen. Zusätzlich ist ein Landarztstipendienprogramm vorgesehen.',
    'In einem ersten Schritt werden wir die Kapazitäten für Medizinstudenten an den Universitäten des Landes ausbauen. Der Aufwuchs an Studienplätzen soll mindestens 20 Prozent betragen. Wir werden auch dafür Sorge tragen, dass unsere Universitäten unabhängig von dem bürokratischen […] Numerus-clausus-System mehr engagierte Studienbewerber direkt annehmen.',
    'Der Aufwuchs an Studienplätzen soll mindestens 20 Prozent betragen',
   ),
   ('bsw', 58,
    'Krankenhäuser sollen erhalten und Personal sowie Ausbildungsplätze ausgebaut werden. Die Gesundheitsversorgung soll als Daseinsvorsorge flächendeckend gesichert werden. Ein verbindliches Tariftreuegesetz soll die Bezahlung in Gesundheitsberufen stärken.',
    'Gesundheitsversorgung als Daseinsvorsorge flächendeckend sichern • Pflege- und Gesundheitsberufe mit fairer Bezahlung durch die Einführung eines für alle Mitarbeiter von Krankenhäusern verbindlichen Tariftreuegesetzes stärken • Krankenhäuser erhalten und Personal sowie Ausbildungsplätze ausbauen',
    'Krankenhäuser erhalten und Personal sowie Ausbildungsplätze ausbauen',
   ),
  ]),
 ]),
 ('mobilitaet', 'Mobilität und Nahverkehr',
  'Busse, Bahnen, Straßen und Anbindung der Fläche.', [
  ('Wie soll das Nahverkehrsangebot ausgebaut werden?', [
   ('cdu', 61,
    'Straßen und Schienennetz sollen ausgebaut und modernisiert werden. Das Deutschlandticket soll erhalten und das ÖPNV-Angebot im ländlichen Raum ausgebaut werden. Auch der Radverkehr soll gestärkt werden.',
    'Bezahlbare Mobilität in Stadt und Land: Ausbau und Modernisierung von Straßen und Schienennetz – Deutschlandticket erhalten – ÖPNV-Angebot im ländlichen Raum ausbauen – Radverkehr stärken und Alltagsradeln fördern.',
    'Deutschlandticket erhalten - ÖPNV-Angebot im ländlichen Raum ausbauen',
   ),
   ('spd', 26,
    'Ein Deutschlandticket für alle Schülerinnen und Schüler soll die Mobilität im Alltag verbessern. Jugendliche sollen in die ÖPNV-Planung eingebunden werden, damit Taktung und Verbindungen passen. Ergänzend werden Ruf- und Nachtbussysteme ausgebaut.',
    'Ein Deutschlandticket für alle Schülerinnen und Schüler verbessert die Mobilität im Alltag. Jugendliche sollen in die Planung des ÖPNV eingebunden werden, damit Taktung und Verbindungen ihren Lebensrealitäten entsprechen. Ergänzend werden moderne Ruf- und Nachtbussysteme ausgebaut.',
    'Ein Deutschlandticket für alle Schülerinnen und Schüler verbessert die Mobilität im Alltag',
   ),
   ('gruene', 27,
    'Der öffentliche Nahverkehr soll umfassend ausgebaut werden. Busse und Bahnen sollen im ganzen Land durch Barrierefreiheit und niedrigere Kosten attraktiver werden. Ziel sind nachhaltige Mobilitätslösungen für alle.',
    'Wir setzen uns für einen umfassenden Ausbau des öffentlichen Nahverkehrs ein und wollen Busse und Bahnen im ganzen Land durch Barrierefreiheit und Kostenreduzierungen attraktiver machen.',
    'Wir setzen uns für einen umfassenden Ausbau des öffentlichen Nahverkehrs ein',
   ),
   ('afd', 200,
    'Der öffentliche Personennahverkehr soll als Ergänzung zum privaten Pkw weiter ausgebaut werden, nicht als dessen Ersatz. Fährverbindungen im ländlichen Raum sollen erhalten und ihre Finanzierung dem Land übertragen werden.',
    'Gleichwohl werden wir, nicht als Ersatz, aber als sinnvolle Ergänzung zum privaten PKW, den öffentlichen Personen-Nahverkehr weiter ausbauen. […] Um die Fährverbindungen im Land langfristig zu erhalten, werden wir die Finanzierung insbesondere im ländlichen Raum durch Gesetzesänderungen dem Land übertragen.',
    'als sinnvolle Ergänzung zum privaten PKW',
   ),
  ]),
  ('Worauf kommt es beim Nahverkehr über das Angebot hinaus an?', [
   ('fdp', 57,
    'Die Pünktlichkeit im Schienenpersonennahverkehr soll gegenüber 2025 um 20 Prozent steigen. Die Zugausfälle sollen um 30 Prozent sinken. Zugleich sollen die Straßen gut ausgebaut sein.',
    'Die Pünktlichkeit im Schienenpersonennahverkehr (SPNV) soll gegenüber dem Basisjahr 2025 um 20 Prozent steigen, die Zugausfälle sollen um 30 Prozent sinken. Die Straßen sollen gut ausgebaut sein.',
    'Die Pünktlichkeit im Schienenpersonennahverkehr (SPNV) soll gegenüber dem Basisjahr 2025 um 20 Prozent steigen',
   ),
   ('linke', 66,
    'Gefordert wird ein verbindliches Ausbauprogramm für alle ÖPNV-Haltestellen. Dazu gehören taktile Leitsysteme, Blindenschrift an Fahrplanaushängen, akustische Ansagen und stufenloser Einstieg. Öffentlicher Nahverkehr soll für alle nutzbar sein.',
    'Öffentlicher Nahverkehr für alle, das bedeutet ein verbindliches Ausbauprogramm für alle Haltestellen des ÖPNV mit taktilen Leitsystemen, Blindenschrift an Fahrplanaushängen, akustischen Ansagen und stufenlosem Einstieg.',
    'ein verbindliches Ausbauprogramm für alle Haltestellen des ÖPNV',
   ),
   ('bsw', 32,
    'Weitere Zerschlagungen der Mobilitätsinfrastruktur werden abgelehnt. Zentrale Mobilitätsinfrastruktur soll in die öffentliche Hand zurückgeführt werden. Nötig sei eine langfristige, transparente und realistisch finanzierte Verkehrsplanung.',
    'Das BSW Sachsen-Anhalt lehnt weitere Zerschlagungen ab und setzt sich für eine Rückführung zentraler Mobilitätsinfrastruktur in die öffentliche Hand ein. Eine nachhaltige Landesentwicklung braucht eine langfristige, transparente und realistisch finanzierte Verkehrsplanung.',
    'setzt sich für eine Rückführung zentraler Mobilitätsinfrastruktur in die öffentliche Hand ein',
   ),
  ]),
 ]),
 ('landwirtschaft', 'Landwirtschaft und Boden',
  'Agrarförderung, Bodenmarkt, Ökolandbau, ländlicher Raum.', [
  ('Welche Art von Landwirtschaft soll das Land fördern?', [
   ('gruene', 15,
    'Der Ökolandbau soll besser unterstützt und sein Flächenanteil deutlich erhöht werden. Dazu dienen verlässliche Ökoprämien und ein stärkerer Fokus in Ausbildung, Fachschule und Beratung. Auch die Lehr- und Versuchseinrichtungen des Landes sollen einbezogen werden.',
    '[Der Ökolandbau] soll besser unterstützt und sein Flächenanteil soll deutlich erhöht werden – insbesondere durch verlässliche Ökoprämien und einen stärkeren Fokus auf den Ökolandbau in der Ausbildung, in der Fachschule, bei der Umstellung, bei der Beratung.',
    'sein Flächenanteil soll deutlich erhöht werden – insbesondere durch verlässliche Ökoprämien',
   ),
   ('afd', 177,
    'Zwischen Bio-, Öko- und konventionellen Betrieben soll nicht unterschieden werden; alle sollen gerecht und ausgewogen unterstützt werden. Eine einseitige Bevorzugung bestimmter Betriebsformen wird abgelehnt. Lokale Erzeuger- und Vermarktungsstrukturen sollen einen erheblichen Anteil der Wirtschaftsförderung ausmachen.',
    'Jede Form der Landwirtschaft fördern! Wir unterscheiden nicht zwischen Bio-, Öko- oder konventionellen Betrieben. Alle Landwirte leisten ihren Beitrag und sind daher gerecht und ausgewogen zu unterstützen. […] eine einseitige, ungerechtfertigte Bevorzugung bestimmter Betriebsformen, die den Wettbewerb verzerrt, lehnen wir ab. Die Förderung lokaler Erzeuger- und Vermarktungsstrukturen […] muss ein erheblicher Anteil der Wirtschaftsförderung werden.',
    'Wir unterscheiden nicht zwischen Bio-, Öko- oder konventionellen Betrieben',
   ),
   ('bsw', 19,
    'Zur Sicherung der einheimischen Landwirtschaft werden Abnahmegarantien für regional erzeugte Produkte gefordert. Öffentliche Einrichtungen sollen vorrangig regionale Erzeugnisse beziehen. Landwirtschaftliche Belange sollen wieder ins gesellschaftliche Bewusstsein rücken.',
    'Zur Sicherung der einheimischen Landwirtschaft setzt sich das BSW für Abnahmegarantien für landwirtschaftliche Produkte aus regionaler Erzeugung ein. Öffentliche Einrichtungen sollen vorrangig [regionale Produkte beziehen].',
    'setzt sich das BSW für Abnahmegarantien für landwirtschaftliche Produkte aus regionaler Erzeugung ein',
   ),
   ('spd', 46,
    'Die Förderhöhe in der Agrarpolitik soll beibehalten und die Mittel regional verteilt werden. Gemeinwohlleistungen der Landwirtschaft sollen honoriert werden. Entscheidungen über Flächen sollen ortsnah und fachlich fundiert fallen.',
    'Öffentliche Agrarförderung gerecht ausgestalten, Gemeinwohl stärken: […] Die Beibehaltung der Förderhöhe ist unabdingbar, ebenso wie die Verteilung der Mittel auf regionaler Ebene. Gemeinwohlleistungen der Landwirtschaft – etwa für Umwelt [und] Klima […].',
    'Die Beibehaltung der Förderhöhe ist unabdingbar, ebenso wie die Verteilung der Mittel auf regionaler Ebene',
   ),
  ]),
  ('Wodurch sollen landwirtschaftliche Betriebe wirtschaftlich abgesichert werden?', [
   ('fdp', 15,
    'Landwirte sollen beim Grunderwerb nicht doppelt besteuert werden, Share Deals sollen verursachergerecht erfasst werden. Der Boden gilt als wichtigstes Produktionsmittel. Angestrebt wird eine nachhaltige Produktivitätssteigerung.',
    'Fairness beim Grunderwerb: doppelte Besteuerung beenden, Share Deals verursachergerecht erfassen. Landwirte beim Grunderwerb doppelt zu besteuern, finden wir nicht fair. Das wichtigste Produktionsmittel für Landwirte ist der Boden.',
    'Fairness beim Grunderwerb: doppelte Besteuerung beenden, Share Deals verursachergerecht erfassen',
   ),
   ('linke', 111,
    'Ein Agrarstrukturgesetz soll Bodenpreise begrenzen und Landkonzentration verhindern. Share Deals beim Erwerb landwirtschaftlicher Betriebe sollen landesweit verboten werden. Die Privatisierung der BVVG-Flächen soll dauerhaft enden.',
    'Wir wollen: ein Agrarstrukturgesetz für Sachsen-Anhalt, das Bodenpreise begrenzt und Landkonzentration verhindert, ein landesweites Verbot von Share Deals beim Erwerb landwirtschaftlicher Betriebe, die Privatisierung der BVVG-Flächen dauerhaft beenden.',
    'ein Agrarstrukturgesetz für Sachsen-Anhalt, das Bodenpreise begrenzt und Landkonzentration verhindert',
   ),
   ('cdu', 39,
    'Die Inanspruchnahme landwirtschaftlicher Nutzflächen für Versiegelung, Industrieansiedlungen auf der grünen Wiese oder Zersiedelung soll deutlich begrenzt werden. Die Bodenmarktreserve des Landes von 20.000 Hektar soll erhalten bleiben.',
    'Landwirtschaftliche Nutzflächen wirksam schützen: Die Inanspruchnahme landwirtschaftlicher Nutzflächen für andere Zwecke – etwa Versiegelung, Industrieansiedlungen auf der „grünen Wiese“, Zersiedelung oder Ausgleichsmaßnahmen – wollen wir deutlich begrenzen. […] Die Bodenmarktreserve des Landes von 20.000 ha werden wir erhalten.',
    'Die Bodenmarktreserve des Landes von 20.000 ha werden wir erhalten',
   ),
  ]),
 ]),
 ('verwaltung', 'Verwaltung und Digitalisierung',
  'Behördenleistungen, Personal und digitale Verfahren.', [
  ('Wie soll die Verwaltung digitalisiert werden?', [
   ('cdu', 52,
    'Erfolgreiche Modellprojekte für digitalisierte Verwaltungsprozesse sollen zentral finanziert und standardisiert werden. So sollen erprobte Lösungen in die Fläche kommen. Kritische IT-Systeme sollen auf Open-Source-Software umgestellt werden.',
    'Digitale Verwaltung ausbauen: Erfolgreiche Modellprojekte für digitalisierte Verwaltungsprozesse werden zentral finanziert und standardisiert, um erprobte Lösungen [zu verbreiten]. […] Die Umstellung kritischer IT-Systeme auf Open-Source Software sichert eine langfristige Arbeitsfähigkeit.',
    'Erfolgreiche Modellprojekte für digitalisierte Verwaltungsprozesse werden zentral finanziert und standardisiert',
   ),
   ('spd', 50,
    'Digitale Lösungen sollen zentral entwickelt und bereitgestellt werden, um Kommunen zu entlasten. Bewährte Lösungen aus anderen Bundesländern sollen übernommen werden. Ziel sind besserer Service, schnellere Verfahren und mehr Transparenz.',
    '[Lösungen sollen] zentral entwickelt und bereitgestellt werden, um Kommunen bei der Umsetzung zu entlasten. Digital etablierte Lösungen sind aus anderen Bundesländern zu übernehmen. Digitale Verwaltung dient nicht der Technik um ihrer selbst willen, sondern besserem Service, schnelleren Verfahren und mehr Transparenz.',
    'Digital etablierte Lösungen sind aus anderen Bundesländern zu übernehmen',
   ),
   ('gruene', 89,
    'Die digitale Verwaltung soll aus Sicht der Nutzenden gedacht und gestaltet werden. Alle Verwaltungsdienstleistungen sollen über einen zentralen Zugang erreichbar sein. Verfahren sollen medienbruchfrei ablaufen.',
    'Die digitale Verwaltung muss aus Sicht der Nutzenden gedacht und gestaltet werden. Alle Verwaltungsdienstleistungen sollen über einen zentralen Zugang erreichbar sein.',
    'Alle Verwaltungsdienstleistungen sollen über einen zentralen Zugang erreichbar se',
   ),
   ('bsw', 74,
    'Digitale Behördengänge sollen für Bürger und Unternehmen einfacher, schneller und nachvollziehbarer werden. Digitale Serviceangebote sollen weiter ausgebaut werden. Digitalisierung soll dabei ein Angebot bleiben und kein Zwang werden.',
    'Digitalisierung muss ein Angebot sein, kein Zwang. Digitale Behördengänge sollen für Bürger sowie Unternehmen einfacher, schneller und nachvollziehbarer werden. Wir wollen den weiteren Ausbau digitaler Serviceangebote […].',
    'Digitalisierung muss ein Angebot sein, kein Zwang',
   ),
  ]),
  ('Wie soll der Staat schlanker und einfacher werden?', [
   ('fdp', 44,
    'Digitalisierung soll bessere Services, weniger Wege und schnellere Entscheidungen bringen. Der Abbau von Bürokratie soll gemessen und über die Zeit sichtbar gemacht werden. Entbürokratisierung wird damit zum politischen Gradmesser.',
    'So wird Entbürokratisierung zum politischen Gradmesser: Jede Regierung muss daran erkennbar liefern. Digitale Verwaltung ohne Umwege: Digitalisierung ist dann gut, wenn sie Freiheit schafft: bessere Services, weniger Wege, weniger Papier, schnellere Entscheidungen.',
    'Digitalisierung ist dann gut, wenn sie Freiheit schafft: bessere Services, weniger Wege',
   ),
   ('afd', 211,
    'Die Ausgaben in Ministerien und Verwaltung sollen pauschal um mindestens zehn Prozent gekürzt werden; die Bürokratiekosten seien in zehn Jahren um über 60 Prozent gestiegen. Kommunalverwaltungen sollen gesetzlich auf die örtliche Daseinsvorsorge beschränkt werden.',
    'Die Kommunalverwaltungen im Land sind gesetzlich auf die örtliche Daseinsvorsorge zu beschränken. […] Ausgaben in Ministerien und Verwaltung kürzen! Die Kosten für die Bürokratie sind in den letzten zehn Jahren um über 60 Prozent explodiert […]. Deshalb fordern wir eine pauschale Ausgabenkürzung von mindestens 10 Prozent.',
    'Die Kosten für die Bürokratie sind in den letzten zehn Jahren um über 60 Prozent explodiert',
   ),
   ('linke', 98,
    'Statt Behörden-Dschungel sollen One-Stop-Shops mit klaren Zuständigkeiten geschaffen werden. Verwaltungen sollen gemeinsam die besten Verfahren erarbeiten. Damit sollen Abläufe für alle einfacher werden.',
    'Statt Behörden-Dschungel und unklaren Verantwortlichkeiten, können „OneStop-Shops“ und damit klare Zuständigkeiten geschaffen werden.',
    '„OneStop-Shops“ und damit klare Zuständigkeiten',
   ),
  ]),
 ]),
]


# ---------------------------------------------------------------------------
# Dritte Frage je Thema (13. September 2026). Getrennt notiert, damit die
# ersten beiden Fragen unangetastet bleiben; angehaengt wird am Dateiende.
# Eine Partei kommt je Thema hoechstens einmal oefter vor als eine andere -
# dieselbe Ausgewogenheitsregel, die baue_datensatz.py prueft.
DRITTE = {
 'sicherheit': ('Wie sollen Taser und Bodycams bei der Polizei eingesetzt werden?', [
   ('cdu', 6,
    'Die Polizei soll mit Tasern ausgestattet werden, Bodycams sollen konsequent zum Einsatz kommen. Dazu soll landesweit KI-gestützter Videoschutz möglich werden. Ziel ist ein starker Schutz der Einsatzkräfte.',
    'Moderne Einsatzkräfte und starken Schutz: Sicherheit für jene, die für unsere Sicherheit sorgen. Beste Ausstattung für Polizei, Feuerwehren und Rettungsdienste, in Stadt und Land. Ausstattung unserer Polizei mit Tasern, konsequenter Einsatz von Bodycams. Technologie für Ihre Sicherheit: KI-gestützten intelligenten Videoschutz landesweit ermöglichen […]',
    'Ausstattung unserer Polizei mit Tasern, konsequenter Einsatz von Bodycams',
   ),
   ('gruene', 42,
    'Taser sollen nur eine der letzten Möglichkeiten zur Deeskalation sein. Vorrang hat eine bessere Zusammenarbeit von Gefahrenabwehr und psychosozialer Unterstützung. Das gilt besonders bei Menschen in psychischen Ausnahmesituationen.',
    'Es braucht eine eindeutige Definition des polizeilichen Aufgabenfeldes, insbesondere im Umgang mit Menschen in psychischen Ausnahmesituationen, bei denen ein ganzheitliches Konzept erforderlich ist. Der Einsatz von Tasern kann dabei lediglich eine der letzten Möglichkeiten der Deeskalation sein. Notwendig ist vielmehr eine bessere Verzahnung der beteiligten Akteur*innen zwischen Gefahrenabwehr, psychosozialer Unterstützung und dem Schutz vor Eigengefährdung.',
    'Der Einsatz von Tasern kann dabei lediglich eine der letzten Möglichkeiten der Deeskalation sein',
   ),
   ('linke', 129,
    'Polizeikräfte sollen individuell gekennzeichnet werden. Bodycams sollen sich beim Schusswaffengebrauch und beim Einsatz von Tasern automatisch einschalten. Das soll Bürger und Polizei vor falschen Anschuldigungen schützen.',
    'Eine demokratische Polizei hat nichts zu verbergen. Die individuelle Kennzeichnungspflicht und der automatische Einsatz von Bodycams beim Schusswaffengebrauch oder beim Einsatz von Tasern schützen Bürger:innen ebenso wie Polizeikräfte vor falschen Anschuldigungen.',
    'Die individuelle Kennzeichnungspflicht und der automatische Einsatz von Bodycams',
   ),
 ]),
 'migration': ('Sollen Geflüchtete ihre Leistungen per Bezahlkarte statt als Geld erhalten?', [
   ('cdu', 8,
    'Die Bezahlkarte soll dauerhaft abgesichert und weiterentwickelt werden. Dazu gehören leistungsfähige Ausländerbehörden und beschleunigte Verfahren.',
    'Leistungsfähige Ausländerbehörden, beschleunigte Verfahren, eine zentrale Erstaufnahme und wirksame Instrumente wie die Bezahlkarte sichern wir dauerhaft ab und entwickeln sie gezielt weiter.',
    'wirksame Instrumente wie die Bezahlkarte sichern wir dauerhaft ab',
   ),
   ('gruene', 79,
    'Die Bezahlkarte soll abgeschafft werden. Sozialleistungen sollen ohne Unterschied als Geld ausgezahlt werden, damit alle frei über ihre Mittel verfügen können.',
    'Wir fordern die Abschaffung der Bezahlkarte und wollen diese diskriminierende Praxis endgültig beenden. Sozialleistungen müssen unterschiedslos als Geldleistungen ausgezahlt werden, damit alle Menschen frei über ihre Mittel verfügen können.',
    'Wir fordern die Abschaffung der Bezahlkarte',
   ),
   ('linke', 98,
    'Die Bezahlkarte soll durch ein verpflichtendes Basiskonto ersetzt werden. Geflüchtete sollen ihr Konto selbstständig führen können.',
    'Selbständige Kontoführung: Die diskriminierende Bezahlkarte wird durch ein verpflichtendes Basiskonto ersetzt.',
    'Die diskriminierende Bezahlkarte wird durch ein verpflichtendes Basiskonto ersetzt',
   ),
   ('afd', 35,
    'Asylbewerber sollen konsequent Sachleistungen statt Geld erhalten. Über die Bezahlkarte hinaus sollen Wege geprüft werden, Zahlungen ins Ausland zu unterbinden.',
    'Eine AfD-geführte Landesregierung wird das Sachleistungsprinzip im Einklang mit dem Asylbewerberleistungsgesetz konsequent anwenden, um finanzielle Fehlanreize für illegale Zuwanderer zu unterbinden. Außerdem werden – sofern nötig und möglich – über die Bezahlkarte hinaus Möglichkeiten geprüft werden, um Auslandszahlungen von „Flüchtlingen“ bzw. Asylanten zu unterbinden.',
    'Sachleistungsprinzip im Einklang mit dem Asylbewerberleistungsgesetz konsequent anwenden',
   ),
 ]),
 'schule': ('Sollen Smartphones an Schulen verboten werden?', [
   ('afd', 79,
    'Die Nutzung von Smartphones soll bis einschließlich Klasse 10 untersagt werden. Digitale Medien sollen erst an weiterführenden Schulen und nur gezielt eingesetzt werden. Buch, Heft und Tafel bleiben die Hauptmedien.',
    'Wir werden dafür Sorge tragen, dass digitale Medien im Unterricht nicht schon an der Grundschule, sondern erst an weiterführenden Schulen und dort nicht flächendeckend, sondern nur selektiv eingesetzt werden. Außerdem werden wir entsprechend den Empfehlungen der Leopoldina die Nutzung von Smartphones bis einschließlich Klasse 10 untersagen. Das Buch, das Hausaufgabenheft und die Schultafel müssen die Hauptmedien des Unterrichts bleiben.',
    'die Nutzung von Smartphones bis einschließlich Klasse 10 untersagen',
   ),
   ('bsw', 45,
    'Im Schulalltag soll ein verbindliches Smartphone-Verbot gelten, um Ablenkung und digitale Abhängigkeit zu verringern. In der Grundschule sollen digitale Geräte gar nicht eingesetzt werden.',
    'Digitale Geräte sind Werkzeuge, keine pädagogische Lösung. In der Grundschule lehnen wir ihren Einsatz ab, da sie den Erwerb grundlegender Fähigkeiten beeinträchtigen. Außerdem setzen wir uns für ein verbindliches Smartphone-Verbot im Schulalltag ein, um Ablenkung, Leistungsabfall, soziale Konflikte und digitale Abhängigkeiten zu reduzieren.',
    'verbindliches Smartphone-Verbot im Schulalltag',
   ),
   ('fdp', 26,
    'Ob Handys auf dem Schulgelände erlaubt sind, soll jede Schule vor Ort entscheiden. Statt Verboten soll es gute Unterstützungsangebote geben, auch für Eltern.',
    'Der Umgang mit digitalen Medien an Schulen kann und muss vor Ort entschieden werden: Das gilt für den Einsatz digitaler Medien im Unterricht wie für die Handynutzung auf dem Schulgelände. Wer Kinder und Jugendliche auf die digitale Welt vorbereiten will, braucht keine Verbote, sondern gute Unterstützungsangebote auch für Eltern.',
    'Der Umgang mit digitalen Medien an Schulen kann und muss vor Ort entschieden werden',
   ),
 ]),
 'kita': ('Sollen Eltern für die Kita weiter Beiträge zahlen?', [
   ('fdp', 25,
    'Die Kita-Beiträge sollen überprüft werden, damit gute frühkindliche Bildung nicht an finanziellen Hürden scheitert. Fehlanreize in der Geschwisterkindregelung sollen beseitigt werden, ohne die Regelung abzuschaffen.',
    'Hohe Qualität in der frühkindlichen Bildung darf nicht an finanziellen Hürden scheitern – deshalb nehmen wir auch die Beitragsgestaltung in den Blick. Wir wollen Fehlanreize in der Geschwisterkindregelung auflösen, ohne diese abzuschaffen.',
    'Fehlanreize in der Geschwisterkindregelung auflösen, ohne diese abzuschaffen',
   ),
   ('gruene', 57,
    'Die Beitragsermäßigung für Familien mit mehreren Kindern soll dauerhaft gesichert werden. Das Land soll außerdem ein Modell erarbeiten, nach dem Kita-Beiträge sozial gestaffelt werden.',
    'Wir sichern die Beitragsermäßigung für Mehrkinderfamilien dauerhaft ab, um Familien finanziell zu entlasten und allen Kindern gleiche Zugänge zu frühkindlicher Bildung zu ermöglichen. Das Land soll ein Modell zur sozialen Staffelung von Kitabeiträgen erarbeiten.',
    'Modell zur sozialen Staffelung von Kitabeiträgen',
   ),
   ('linke', 29,
    'Die Kita soll für alle Eltern beitragsfrei werden. Die bisherigen Elternbeiträge und die Kosten besserer Personalschlüssel soll vollständig das Land übernehmen.',
    '[…] die Bildung in Kindertageseinrichtungen für alle Eltern beitragsfrei wird, […] die bisherigen Elternbeiträge sowie die höheren Kosten durch bessere Personalschlüssel werden dabei vollständig durch das Land finanziert […]',
    'die Bildung in Kindertageseinrichtungen für alle Eltern beitragsfrei wird',
   ),
 ]),
 'wirtschaft': ('Soll das Tariftreue- und Vergabegesetz bleiben?', [
   ('fdp', 7,
    'Das Tariftreue- und Vergabegesetz soll so schnell wie möglich abgeschafft werden. Der Staat soll Arbeit erleichtern und Wachstum beschleunigen, statt Kosten an die Betriebe durchzureichen.',
    'Deshalb braucht Sachsen-Anhalt eine Politik, die die Kosten des Staates nicht nach unten durchreicht, sondern den Staat so organisiert, dass er Arbeit erleichtert und Wachstum beschleunigt. […] In den kommenden Jahren gilt es, das Tariftreue- und Vergabegesetz schnellstmöglich abzuschaffen.',
    'das Tariftreue- und Vergabegesetz schnellstmöglich abzuschaffen',
   ),
   ('spd', 8,
    'Das Tariftreue- und Vergabegesetz soll die Tarifbindung im Land stärken. Eine Abschaffung oder weitere Einschränkungen des Gesetzes werden ausgeschlossen.',
    'Tarifbindung und betriebliche Mitbestimmung sind entscheidend für gute Arbeitsbedingungen und höhere Einkommen. Mit dem Tariftreue- und Vergabegesetz stärken wir die Tarifbindung im Land. Eine Ausweitung der bestehenden Einschränkungen oder eine Abschaffung dieses Gesetzes wird es mit uns nicht geben.',
    'Eine Ausweitung der bestehenden Einschränkungen oder eine Abschaffung dieses Gesetzes',
   ),
   ('gruene', 76,
    'Das bestehende Tariftreue- und Vergabegesetz soll die Tarifbindung weiter stärken. Öffentliche Aufträge sollen nur an Unternehmen mit fairen Löhnen gehen, auch in der Privatwirtschaft soll die Tarifbindung wachsen.',
    'Deshalb soll die Tarifbindung in Sachsen-Anhalt durch das bestehende Tariftreue- und Vergabegesetz weiter gestärkt werden. Öffentliche Aufträge sollen nur an Unternehmen mit fairen Löhnen vergeben werden. Auch in der Privatwirtschaft sollen Tarifbindung und Mitbestimmung ausgebaut werden.',
    'Öffentliche Aufträge sollen nur an Unternehmen mit fairen Löhnen vergeben werden',
   ),
   ('bsw', 35,
    'Wer Fördermittel des Landes erhält oder öffentliche Aufträge ausführt, soll mindestens nach Tarif bezahlen. Tariftreue soll Voraussetzung für jede öffentliche Förderung sein.',
    'Unternehmen, die Fördermittel des Landes erhalten oder öffentliche Aufträge ausführen, müssen mindestens nach Tarif bezahlen. Tariftreue ist Voraussetzung für öffentliche Förderung.',
    'müssen mindestens nach Tarif bezahlen',
   ),
 ]),
 'energie': ('Wie sollen die Netzentgelte für Stromkunden sinken?', [
   ('cdu', 45,
    'Die Netzentgelte sollen bundesweit vereinheitlicht werden. Regionen mit vielen Wind- und Solaranlagen sollen die Kosten des Netzausbaus nicht allein tragen.',
    'Die bundesweite Vereinheitlichung von Netzentgelten kann beispielsweise die Bürger in Regionen mit überproportional vielen regenerativen Energieerzeugungsanlagen wie Sachsen-Anhalt spürbar entlasten. So müssen die durch die notwendigen Netzausbaumaßnahmen stark steigenden Netzentgelte, die die Bürger vor Ort über ihre Stromrechnung bezahlen müssen, gedämpft werden.',
    'Die bundesweite Vereinheitlichung von Netzentgelten',
   ),
   ('fdp', 13,
    'Die Netzentgelte sollen zwischen den Regionen fairer verteilt und im Land spürbar gesenkt werden. Umlagen und Abgaben sollen zusammengeführt werden, um Kosten und Aufwand zu verringern.',
    'Sachsen-Anhalt trägt als starker Windstrom-Erzeuger zugleich eine besondere Netzkostenlast, obwohl andere Regionen vom exportierten Strom profitieren. […] Netzentgelte müssen daher zwischen den Regionen fairer verteilt und für die Menschen in Sachsen-Anhalt spürbar gesenkt werden. Umlagen und Abgaben sollten zusammengeführt werden, um Komplexität und Verwaltungskosten zu reduzieren.',
    'Netzentgelte müssen daher zwischen den Regionen fairer verteilt',
   ),
   ('linke', 107,
    'Die Netzentgelte sollen deutlich sinken, Strompreiszonen sollen geprüft werden. Die Stromsteuer soll auf 0,1 Cent je Kilowattstunde fallen, die Energienetze sollen in öffentliche Hand.',
    'die Netzentgelte deutlich senken und damit die regionale Ungerechtigkeit abbauen, dass wir in Sachsen-Anhalt mehr bezahlen als in anderen Bundesländern, die Einführung von Strompreiszonen prüfen, damit Länder mit viel erneuerbarer Energie profitieren, die Stromsteuer auf 0,1 ct/kWh senken, Energienetze in öffentliche Hand überführen […]',
    'die Netzentgelte deutlich senken und damit die regionale Ungerechtigkeit abbauen',
   ),
   ('spd', 5,
    'Die Netzentgelte sollen weitgehend gedeckelt und die Stromsteuer soll gesenkt werden. Dazu sollen die Netze konsequent digitalisiert werden.',
    'Wir stehen für eine konsequente Energiewende bei bezahlbaren Energiepreisen für Unternehmen und private Haushalte. Deshalb setzen wir uns für eine weitgehende Deckelung der Netzentgelte, eine konsequente Digitalisierung der Netze sowie für eine Reduzierung der Stromsteuer ein.',
    'weitgehende Deckelung der Netzentgelte',
   ),
 ]),
 'mobilitaet': ('Wie soll es mit dem Deutschlandticket weitergehen?', [
   ('fdp', 67,
    'Das Deutschlandticket soll Teil des Angebots bleiben. Es darf aber nicht zulasten von Qualität und Stabilität des Nahverkehrs gehen.',
    'Das Deutschlandticket bleibt Teil des Angebots, darf jedoch nicht zu Lasten von Qualität und Stabilität der Verkehre gehen.',
    'Das Deutschlandticket bleibt Teil des Angebots, darf jedoch nicht zu Lasten von Qualität und Stabilität der Verkehre gehen',
   ),
   ('bsw', 33,
    'Das Deutschlandticket soll erhalten bleiben und mit der Zeit günstiger werden. Der Tarifdschungel soll kleiner werden, Tickets sollen digital und analog erhältlich sein.',
    'Das Deutschlandticket hat sich bewährt, muss erhalten bleiben und perspektivisch günstiger werden. Der Tarifdschungel ist zu reduzieren, digitale und analoge Ticketangebote müssen gleichermaßen verfügbar sein.',
    'muss erhalten bleiben und perspektivisch günstiger werden',
   ),
   ('spd', 26,
    'Alle Schülerinnen und Schüler sollen ein Deutschlandticket erhalten. Jugendliche sollen in die Planung von Takt und Verbindungen eingebunden werden.',
    'Kinder und Jugendliche müssen selbstständig, sicher, barrierefrei und bezahlbar unterwegs sein können. Ein Deutschlandticket für alle Schülerinnen und Schüler verbessert die Mobilität im Alltag. Jugendliche sollen in die Planung des ÖPNV eingebunden werden, damit Taktung und Verbindungen ihren Lebensrealitäten entsprechen.',
    'Ein Deutschlandticket für alle Schülerinnen und Schüler verbessert die Mobilität im Alltag',
   ),
   ('linke', 103,
    'Auf stark genutzten Nahverkehrsstrecken soll das Deutschlandticket auch in Intercity-Zügen gelten. Das Land soll dafür eigene Mittel einsetzen.',
    'Landesmittel einsetzen, um auf stark frequentierten Nahverkehrs-verbindungen auch im IC-Netz das Deutschlandticket nutzbar zu machen […]',
    'auch im IC-Netz das Deutschlandticket nutzbar zu machen',
   ),
 ]),
 'landwirtschaft': ('Wie soll mit dem Wolf umgegangen werden?', [
   ('afd', 181,
    'Die Wolfspopulation soll gezielt reguliert werden. Das Wolfskompetenzzentrum des Landes soll abgeschafft werden, weil Risse und Schutzauflagen die Tierhaltung belasten.',
    'Die vom Wolf verursachten Kosten laufen aus dem Ruder. Erstattungen von Rissen, Förderung von Schutzmaßnahmen und das Wolfskompetenzzentrum (WZI) behindern die Tierhaltung. […] Daher werden wir das umstrittene Wolfskompetenzzentrum abschaffen und die Population gezielt regulieren.',
    'das umstrittene Wolfskompetenzzentrum abschaffen und die Population gezielt regulieren',
   ),
   ('gruene', 7,
    'Der Wolf soll wieder aus dem Jagdrecht gestrichen und unter Naturschutzrecht gestellt werden. Abschüsse sollen nur in eng begrenzten Ausnahmefällen erlaubt sein.',
    'Zum Erhalt des Schutzstatus von Wölfen setzen wir uns auf Bundes- und Landesebene dafür ein, die Eintragung ins Jagdrecht rückgängig zu machen und seinen Schutz wieder im Bundesnaturschutzrecht zu verankern. Jagdrechtliche Regelungen in Sachsen-Anhalt sollen auf einem unabhängigen, wissenschaftlich fundierten Wolfsmanagement basieren, wobei Abschüsse nur in eng begrenzten Ausnahmefällen zulässig sind.',
    'wobei Abschüsse nur in eng begrenzten Ausnahmefällen zulässig sind',
   ),
   ('linke', 112,
    'Der Herdenschutz soll staatlich getragen und verlässlich finanziert werden, die Akzeptanz des Wolfs soll wachsen. Für notwendige gezielte Entnahmen von Wölfen sollen klare Bedingungen gelten.',
    'Wir wollen eine sachliche, faktenbasierte Wolfspolitik, die Weidetierhaltung stärkt und die Akzeptanz des Wolfs fördert. Gleichzeitig braucht es aber auch klare Bedingungen für gegebenenfalls notwendige gezielte Entnahmen von Wölfen. Wir wollen: einen starken, staatlich getragenen Herdenschutz mit verlässlicher Finanzierung […]',
    'klare Bedingungen für gegebenenfalls notwendige gezielte Entnahmen von Wölfen',
   ),
   ('fdp', 20,
    'Der Wolf soll wie andere inzwischen stabile Arten aktiv gemanagt werden. Dafür soll das Jagdrecht weiter modernisiert werden, damit Artenschutz und Nutztierschutz zusammenpassen.',
    'Das Jagdrecht wollen wir weiter spürbar modernisieren. […] Auch andere Tierarten, die aufgrund des erfolgreichen Artenschutzes inzwischen stabile Populationen gebildet haben, müssen in Zukunft gemanagt werden, wie etwa die Saatkrähen oder der Wolf.',
    'müssen in Zukunft gemanagt werden, wie etwa die Saatkrähen oder der Wolf',
   ),
 ]),
}

DRITTE.update({
 'gesundheit': ('Wie sollen die Eigenanteile in der Pflege begrenzt werden?', [
   ('cdu', 29,
    'Die Pflegeversicherung soll grundlegend reformiert werden, mit gedeckelten Eigenanteilen. Dazu gehören eine faire Finanzierung und der Schutz des selbst genutzten Wohneigentums.',
    '[…] grundlegende Reform der Pflegeversicherung ein, mit gedeckelten Eigenanteilen, fairer Finanzierung und Schutz des selbstgenutzten Wohneigentums.',
    'Reform der Pflegeversicherung ein, mit gedeckelten Eigenanteilen',
   ),
   ('afd', 245,
    'Die Kosten der Heimpflege sollen wirksam begrenzt werden. Pflegende Familienangehörige sollen mehr Geld, steuerliche Entlastungen und ein Landespflegegeld erhalten.',
    'Die steigenden Eigenanteile in der stationären Pflege sind für viele Menschen in Sachsen-Anhalt eine untragbare Belastung. Wir stehen für eine wirksame Begrenzung dieser Kosten und mehr Unterstützung für Familien. Angesichts der hohen Kosten, die ein Pflegeplatz im Heim erzeugt, sind die Vergütungen für pflegende Familienangehörige noch zu niedrig. Wir brauchen steuerliche Entlastungen und ein Landespflegegeld.',
    'Wir stehen für eine wirksame Begrenzung dieser Kosten und mehr Unterstützung für Familien',
   ),
   ('bsw', 58,
    'Es soll eine Pflegevollversicherung geben, die überwiegend aus Steuermitteln bezahlt wird. Würdige Pflege im Alter soll keine Frage des Geldes sein.',
    'Das BSW fordert eine Pflegevollversicherung, die überwiegend aus Steuermitteln finanziert wird. Eine würdige Pflege im Alter darf keine Frage des Geldes sein.',
    'Pflegevollversicherung, die überwiegend aus Steuermitteln finanziert wird',
   ),
   ('linke', 56,
    'Eine solidarische Pflegevollversicherung soll die Eigenanteile abschaffen. Die Beitragsbemessungsgrenze soll fallen und Kapitalerträge sollen einbezogen werden.',
    'Wir wollen: eine solidarische Pflegevollversicherung auf Bundesebene, damit pflegebedingte Eigenanteile abgeschafft werden. die Abschaffung der Beitragsbemessungsgrenze und die Einbeziehung von Kapitalerträgen in die Beitragsbemessung, damit starke Schultern mehr tragen.',
    'damit pflegebedingte Eigenanteile abgeschafft werden',
   ),
 ]),
 'verwaltung': ('Soll in der Landesverwaltung Personal abgebaut werden?', [
   ('afd', 214,
    'Frei werdende Stellen sollen nur noch im Ausnahmefall nachbesetzt werden, damit das Personal schrittweise sinkt. Alle Behörden sollen auf überflüssige Tätigkeiten und Doppelzuständigkeiten geprüft werden.',
    'Wir werden alle Behörden einer Soll-Ist-Überprüfung unterziehen, eine strenge Aufgabenkritik üben und überflüssige Tätigkeiten sowie Doppelzuständigkeiten ersatzlos streichen. […] Freiwerdende Stellen werden nur noch im Ausnahmefall nachbesetzt, sodass der Personalbestand durch natürliche Fluktuation schrittweise sinkt.',
    'Freiwerdende Stellen werden nur noch im Ausnahmefall nachbesetzt',
   ),
   ('gruene', 49,
    'Die Verwaltung soll auf eine Zielgröße von 18,7 Vollzeitstellen je 1.000 Einwohner kommen. Dazu soll es einen landesweiten Personalentwicklungsplan bis 2035 und eine ständige Aufgabenkritik geben.',
    'Die Effizienzsteigerung in Verwaltungen soll fortgesetzt werden, mit einer Zielgröße von 18,7 Vollzeitäquivalenten pro 1.000 Einwohner*innen und einem landesweiten Personalentwicklungsplan 2035. Kontinuierliche Aufgaben- und Effizienzkritik soll eingeführt und über einen Open-Data-Haushalt öffentlich nachvollziehbar gemacht werden.',
    'mit einer Zielgröße von 18,7 Vollzeitäquivalenten',
   ),
   ('linke', 19,
    'Einen Personalabbau im öffentlichen Dienst soll es nicht geben, ebenso wenig einen Abbau öffentlicher Infrastruktur. Eine kurzfristig höhere Verschuldung wird dafür in Kauf genommen.',
    'Eine kurzfristige höhere Verschuldung wird durch unsere steuerpolitischen Änderungen und die Förderung der Binnenwirtschaft langfristig kompensiert. Kürzungen in den Bereichen Soziales und Umwelt wird es mit uns nicht geben, ebenso wenig den Abbau öffentlicher Infrastruktur oder Personalabbau im öffentlichen Dienst.',
    'ebenso wenig den Abbau öffentlicher Infrastruktur oder Personalabbau im öffentlichen Dienst',
   ),
   ('spd', 57,
    'Das Personal soll den Aufgaben folgen und leichter zwischen den Verwaltungsebenen wechseln können. Ein Abbau darf nicht zu längeren Verfahren oder höheren Sachkosten führen.',
    'Personaldurchlässigkeit zwischen den Ebenen wird gestärkt, damit Beschäftigte dort eingesetzt werden können, wo sie gebraucht werden. Starre Zuständigkeitsgrenzen werden überprüft. Personalkennzahlen sind kein Selbstzweck. Personalabbau darf nicht zu längeren Verfahrensdauern führen oder durch steigende Sachkosten kompensiert werden.',
    'Personalabbau darf nicht zu längeren Verfahrensdauern führen',
   ),
 ]),
})

for _t in THEMEN:
    if _t[0] in DRITTE:
        _t[3].append(DRITTE[_t[0]])
